### ISSUE TITLE
Table 5 confusion if Length is optional when F key is present

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#10]
In ISO 32000-2:2020, "Table 5 — Entries common to all stream dictionaries" states that Length is a required key.

The **F** key is then described as "(_Optional; PDF 1.2_) The file containing the stream data. If this entry is present, the bytes between **stream** and **endstream** shall be ignored. However, the **Length** entry should still specify the number of those bytes (usually, there are no bytes and **Length** is 0). The filters that are applied to the file data shall be specified by **FFilter** and the filter parameters shall be specified by **FDecodeParms**."

In this text it says Length "should still specify..." but if Length is really mandatory then it "shall specify...".
Or Length is optional when F is present. 

I personally think **/Length** is always required so the correct fix is "should" to "shall" in the description of **F**.

**Comment by lrosenthol** [comment]
Agreed. `Length` is always required and should->shall

**Comment by petervwyatt** [comment]
Proposed solution: reword second sentence as "However, the **Length** entry shall still specify the number of those bytes (usually, there are no bytes and Length is 0)."
