### ISSUE TITLE
Is it invalid for a PDF/A-4e file to use undocumented (non ISO 21757-1:2020) ECMAscript?

### ISSUE THREAD

**Issue by crlf0710** [pdf-association/pdf-issues#100]
It turns out that implementing ISO 21757-1 specified ECMAScript APIs is not enough to get a large portion of existing PDFs working. Existing software like Acrobat are creating PDF-form documents that relies on undocument APIs to react properly for features like form auto-calculations and so on (many are still 1.x PDF files though).

I wonder if it makes sense to expand the API surface a little to cover the existing usages, for ISO 21757 and PDF 2.0 to be more useful. I don't know the exact minimal set, but it seems many documents are using identifiers starting with `AF`, `RE_` or `IDS_`. (Not sure if i missed something)

Following https://gist.github.com/keeganbrown/5405c1d959a04cbc3866 , i created an initial list for consideration:
```text
AFAMRegExp
AFBuildRegExps
AFDate_Format
AFDate_FormatEx
AFDate_Keystroke
AFDate_KeystrokeEx
AFDateFromYMD
AFDateHorizon
AFDigitsRegExp
AFExactMatch
AFExtractNums
AFExtractRegExp
AFExtractTime
AFGetJapaneseYear
AFGetMonthIndex
AFGetMonthString
AFMakeArrayFromList
AFMakeNumber
AFMatchMonth
AFMergeChange
AFMonthsRegExp
AFNumber_Format
AFNumber_Keystroke
AFNumberCommaSepCommitRegExp
AFNumberCommaSepEntryRegExp
AFNumberDotSepCommitRegExp
AFNumberDotSepEntryRegExp
AFParseDate
AFParseDateEx
AFParseDateOrder
AFParseDateWithPDF
AFParseDateYCount
AFParseGMTDateString
AFParseJapaneseEraDateEx
AFParseTime
AFPercent_Format
AFPercent_Keystroke
AFPhoneCommitRegExp
AFPhoneEntryRegExp
AFPMRegExp
AFRange_Validate
AFSignature_Format
AFSignatureLock
AFSimple
AFSimple_Calculate
AFSimpleInit
AFSpecial_Format
AFSpecial_Keystroke
AFSpecial_KeystrokeEx
AFSSNCommitRegExp
AFSSNEntryRegExp
AFStringReplace
AFTime_Format
AFTime_FormatEx
AFTime_Keystroke
AFTimeGarbageRegExp
AFTimeLongRegExp
AFTimeShortRegExp
AFValidateEmailSyntax
AFZip4CommitRegExp
AFZip4EntryRegExp
AFZipCommitRegExp
AFZipEntryRegExp

IDS_AM
IDS_GREATER_THAN
IDS_GT_AND_LT
IDS_HEISEI_ABBREV
IDS_HEISEI_ABBREV_LONG
IDS_INVALID_DATE
IDS_INVALID_DATE2
IDS_INVALID_MONTH
IDS_INVALID_VALUE
IDS_LESS_THAN
IDS_MEIJI_ABBREV
IDS_MEIJI_ABBREV_LONG
IDS_MONTH_INFO
IDS_PM
IDS_REIWA_ABBREV
IDS_REIWA_ABBREV_LONG
IDS_SHOWA_ABBREV
IDS_SHOWA_ABBREV_LONG
IDS_STARTUP_CONSOLE_MSG
IDS_TAISHO_ABBREV
IDS_TAISHO_ABBREV_LONG

RE_NUMBER_COMMIT_COMMA_SEP
RE_NUMBER_COMMIT_DOT_SEP
RE_NUMBER_ENTRY_COMMA_SEP
RE_NUMBER_ENTRY_DOT_SEP
RE_PHONE_COMMIT
RE_PHONE_ENTRY
RE_SSN_COMMIT
RE_SSN_ENTRY
RE_ZIP_COMMIT
RE_ZIP_ENTRY
RE_ZIP4_COMMIT
RE_ZIP4_ENTRY

```

**Comment by petervwyatt** [comment]
That is a very significant list! I would also have expected that a majority of legacy PDF 1.7 forms (especially of the simpler kind) would Just Work (tm) with the ISO 21757-1:2020 subset of the full Acrobat-JS. I also cannot comment on the "undocumented" aspect except to say that ISO 21757-1:2020 began with the Acrobat JS and 3D JS reference documents, so there was never any acknowledgement of undocumented but necessary JS APIs...

I'm not sure how you arrived at your list, but maybe looking at "c:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Javascripts\JSByteCodeWin.bin" and extracting the strings might reveal more...

**Comment by lrosenthol** [comment]
The list of methods there are *NOT* JavaScript APIs, but are undefined/private methods included with Adobe's Acrobat family of products.  Adobe has chosen to not document these methods for standardization.

I will also note publicly that extracting the strings from any part of the Adobe Acrobat software is a clear violation of our EULA and therefore illegal and *not recommended*.

**Comment by MatthiasValvekens** [comment]
If these private Acrobat functions/classes/methods/... were omitted intentionally, then I guess this isn't really an erratum, is it?

Additionally, given the long-term direction we're taking in the PDFa to move away from ECMAScript for PDF forms (to the extent possible), I'm personally not too keen on expanding the ECMAScript API in this area.

**Comment by lrosenthol** [comment]
I propose we close this issue as "Not Fix"

**Comment by petervwyatt** [comment]
@lrosenthol : Adobe Acrobat does not create PDF 2.0 with Acrobat Forms containing this information. It only does this in a 1.x context.

PDF TWG agree to closing as "No Fix" - please join the PDFa Forms TWG to continue discussions!

**Comment by crlf0710** [comment]
Thanks for this clarification! And also great to know that Adobe Acrobat does not create PDF 2.0 with Acrobat Forms containing this information.

One last question:
Can we also conclude that a file that depends on any of these "non-API"s are not PDF/A-4e conforming? ("A conforming file is not obligated to use any PDF feature other than those explicitly required by ISO 32000-2:— or this document." from ISO 19005-4)

**Comment by petervwyatt** [comment]
@crlf0710  Great question. Re-opening issue so you can get a clear answer in regards to PDF/A-4e (PDF/A-4 label also added).

My opinion (for what it is worth) is that you are 100% correct for the precise reason you state - it is invalid for any PDF/A-4e file to depend on non-standardized JS features (i.e. JS features not described by ISO 21757-1:2020).

@bdoubrov, @lrosenthol - would you care to comment?

**Comment by lrosenthol** [comment]
@petervwyatt @crlf0710 

PDF/A (all versions) as well as all versions of all PDF subsets **fully support** the use of private keys.  This is no different.

**Comment by crlf0710** [comment]
@lrosenthol I feel this is quite different from private keys. Private keys carry information that **does not affect** the standardized behavior of pdf files, while this does. Instead, this is actually "external dependencies that complicate preservation efforts", which is exactly what PDF/A is set out to avoid at the first place.

Imagine people creating PDF/4e files and PDF/A validators say ok, these files are conforming, and these files get archived. But after fifty years, when personal computers and current software become no longer a thing. When people tries to access the archived files, and only found out it depends on some "undefined/private methods included with Adobe's Acrobat family of products" that are never covered by ISO 21757 and no complete descriptions elsewhere. I must say, that would be a disaster.

**Comment by lrosenthol** [comment]
>@lrosenthol I feel this is quite different from private keys. 

You are welcome to feel that way...but it's not correct.

>Private keys carry information that does not affect the standardized behavior of pdf files, while this does. 

I don't understand that.  Private keys, by definition are *OUT OF SCOPE* of any standard.  They can be (and are!) used for many purposes both in public and private workflows.  

>Instead, this is actually "external dependencies that complicate preservation efforts", which is exactly what PDF/A is set out to avoid at the first place.

I don't see any more complication here since execution of JavaScript in a PDF/A file can only be performed in a PDF/A-4e file *and only then* is optional for interactive processors by explicit actions of the user.

>Imagine people creating PDF/4e files and PDF/A validators say ok, these files are conforming, and these files get archived. 

Good, because they are fully conforming.

>But after fifty years, when personal computers and current software become no longer a thing. When people tries to access the archived files, 

If they access the files, the values of the fields will be correctly displayed since a processor has to use the AP dictionary - and I suspect that is the only reason someone is viewing such an old file.  The only possible issue would be if someone built a new interactive processor which included executing JavaScript actions.

>and only found out it depends on some "undefined/private methods included with Adobe's Acrobat family of products" that are never covered by ISO 21757 and no complete descriptions elsewhere. I must say, that would be a disaster.

Again, this is *no different* than a PDF with private keys being processed by a processor that doesn't understand those keys and ending up with a different result than a process that does.

**Comment by crlf0710** [comment]
@lrosenthol Let me verify if i correctly understand your position. Let's say i have a pdf file that i intend to convert to PDF/4e and get archived, and it's using a JavaScript action to update its annot AP appearance, using a implicitly defined function called `AFSimple_Calculate`(outside the scope of ISO 21757) in the script.

You believe that:
The standardized behavior using ISO 32000-2 and ISO 21757-1, the action triggering effect should be "JavaScript action script execution error" (in the real world, this is usually a silent error), since `AFSimple_Calculate` is outside the scope of any standard.

At the same time, when opening the file, using Adobe Acrobat and a few other commerical products and open source software([1](https://github.com/mozilla/pdf.js/blob/3da9f077be33d8689129d5ddb7915d7bf1f2a5fa/src/scripting_api/aform.js#L395), [2](https://github.com/ArtifexSoftware/mupdf/blob/8f62d6bd2f2e8c260c9f1dfcb9315904516f94ed/source/pdf/js/util.js#L735)), the action triggering effect would be "script executed successfully, updating annot AP appearance".

So basically you believe that these products exhibit their own workflow (whether public or not), not the standardized behavior following ISO 32000-2 and ISO 21757-1.  The PDF/A validators will all say this file is conforming. It's me, the person's fault that **i didn't find out a reference implementation interactive processor that implemented the standard without a customized workflow to examine these files' interactive behavior**. 

And this fault will not discovered until maybe fifty years later, when people are using maybe "Executable ISO Standard" devices following ISO standards in a machine-readable form. Only then these files will exhibit exactly the standardized behavior, then people can realize that this archived file should not actually work if it's used in a "standardized workflow" in the past years.

----
While this outcome is understandable from a technical perspective, it basically put the burden on the people outside the PDF industry. It actually does more harm than good to the general fame of PDF technology. I feel it's important to make archived pdf files **"vendor-neutrally and workflow-neutrally usable"**. I'm eager to see pdf association and the TWGs help with this situation.

**Comment by lrosenthol** [comment]
> Let's say i have a pdf file that i intend to convert to PDF/4e

The process by which a "regular" PDF is converted to PDF/A (or any subset) is **implementation dependent**.   The only thing that the PDF/A standard defines is what the resultant PDF/A file should consist of - in this case, an AP for the field - and then how a PDF/A processor should use it.

>At the same time, when opening the file, using Adobe Acrobat and a few other commerical products and open source software(1, 2), the action triggering effect would be "script executed successfully, updating annot AP appearance".

Given a PDF/A-4 **compliant processor**, the script would **never** be executed upon open!  The processor would simply render the AP.

As defined in PDF/A-4 (ISO 19005-4, 6.6.2), should a PDF/A-4 **compliant interactive processor** choose to allow for users to change the value of fields in a PDF/A-4 file, then that processor would indeed need to execute the script to regenerate any impacted APs.  I will note that Adobe Acrobat does **NOT** allow a user to modify a PDF/A file in any way - but that is our business choice.

>i didn't find out a reference implementation interactive processor that implemented the standard 

Correct.  Processing a PDF/A file - any version of PDF/A including PDF/A-1 - using a non-PDF/A compliant processor is **OUT OF SCOPE** since the rules for processing a PDF/A file properly are included as part of the PDF/A standard.  NOTE: this is the same as any PDF standard, whether it be 32K or all of the subsets.

>I feel it's important to make archived pdf files "vendor-neutrally and workflow-neutrally usable". 

I hear what you are saying, but the PDF/A committee made a decision almost 20 years ago(!!) back with PDF/A-1 that private keys are allowed and we have maintained that position to this day with the current specification.

If you believe that the committee is wrong - and it sounds like you do - then I strongly recommend that you join the committee either directly through your ISO national body or through membership in the PDF Association and its liaison status.

**Comment by petervwyatt** [comment]
A reminder that JS exists in PDF beyond just "JS Actions" - for example, 3D annot **OnInstantiate** streams.

**Comment by lrosenthol** [comment]
@petervwyatt That is true.  However, as mentioned in ISO 19005-4, B.3.2, an interactive conforming processor may ignore the OnInstantiate key, but even if it does process it, then it shall do so only when the user explicitly initiates an action.

So my comments are still all relevant.

**Comment by petervwyatt** [comment]
Assigning to @bdoubrov to record the results of any discussions in the PDF/A TWG as this relates to PDF/A-4e
