### ISSUE TITLE
Table 15 *Prev* entry change from 2017 to 2020 misleading

### ISSUE THREAD

**Issue by mkl-public** [pdf-association/pdf-issues#101]
Table 15 describes the _Entries in the file trailer dictionary_; as there is no trailer dictionary in a PDF using pure cross reference streams, this table clearly refers to PDFs using cross reference tables.

The *Prev* entry in that table in ISO 32000-2:2017 was

> The byte offset in the decoded stream from the beginning of the file to the beginning of the previous cross-reference section.

but in ISO 32000-2:2020 it has been changed to

>The byte offset from the beginning of the PDF file to the beginning of the previous cross-reference stream.

This change is clearly wrong, *Prev* in a _file trailer dictionary_ does not refer to a cross reference stream but to a cross reference section..

Thus, this part of the change should be undone.

I have no idea whether the other changes in the wording make sense or not.

**Comment by MatthiasValvekens** [comment]
I agree w.r.t. the stream vs. section issue. I assume that was mistakenly copied over from a change in Table 17, and that part of the change should be reverted.

As for the distinction between "file" and "PDF file": I believe there was some discussion somewhere in the review process about potential ambiguity between "PDF file" (as in "the bytes that make up a well-formed PDF document") vs. the notion of a "file" in the colloquial sense. I wasn't around for that discussion, but I would guess that that's where this change originated.

**Comment by petervwyatt** [comment]
Clause 7.5.2 File Header opens with:

> The PDF file begins with the 5 characters “%PDF–” and byte offsets shall be calculated from the PERCENT SIGN (25h).
NOTE 1 This provision allows for arbitrary bytes preceding the %PDF- without impacting the viability of the PDF file and its byte offsets.

The ISO subsets then further require that the "%" is at file offset 0, which is all precise and clear.

And, yes, this was likely a cut & paste error from fixing all mentions of the **Prev** key (Table 15, 7.5.6, Table 17). Thanks.

**Comment by MPBailey** [comment]
So what is the proposed solution, given that both 2017 and 2020 appear to be wrong?

"The byte offset from the beginning of the PDF file to the beginning of the previous cross-reference section"?

**Comment by petervwyatt** [comment]
Proposed solution: "The byte offset from the beginning of the PDF file to the beginning of the previous cross-reference section"

PDF TWG agrees.

**Comment by vasekp** [comment]
More text has been added in errata to 7.5.5 which says "or the beginning of the previous cross-reference stream (see 7.5.8, "Cross-reference streams")", linking this issue. However, that addition is not discussed here, and is also manifestly wrong because it it's a trailer, it links to a traditional cross-reference section and *not* to a cross-reference stream. The link to #101 is unjustified. Why was that added?

**Comment by petervwyatt** [comment]
PDF TWG discussions are not recorded here in GitHub. This is what the PDF TWG agreed. There is nothing in ISO 32000 stating that a conventional cross-reference section and trailer cannot occur in an incremental after a cross-reference stream is used - there exist such PDFs.

**Comment by mkl-public** [comment]
IIRC @lrosenthol once explained that you can *not* freely switch between xref streams and xref tables in the incremental updates of a document, either you use pure xref streams or you use xref tables / hybrid xrefs.
This indeed has not been backed by the spec. 
Should I assume that explanation merely described an implementation limitation of that time?

**Comment by vasekp** [comment]
This is not even about mixing the two formats. It's a statement about the meaning of the offset in the PDF file indicated by `startxref`. In the context we're discussing, the `startxref` follows a `trailer`, which in turn follows an `xref`. If it pointed to a cross-reference stream, there wouldn't be `trailer`. This text appears in the section about File Trailer and while sure, `startxref` could also point to a stream, that this is to be preceded by a trailer dictionary is in the very next sentence, which contradicts that possibility.

W.r.t. TWG discussions not being recorded in GitHub – that's fine, but if you hover over the text in the errata, it points to this discussion, and that feels like a mistake if it's not discussed here. I understood that "GitHub Issue numbers and ISO status (where relevant) will appear"... and it's not 'relevant' in this case.

**Comment by mkl-public** [comment]
Yes, the additional change ('or the beginning of the previous cross-reference stream (see 7.5.8, "Cross-reference streams")' in the first paragraph of 7.5.5, not in the table which was the actual topic here) actually is inappropriate in my opinion, too. As is, this section is about the old xref table structure, so either one makes a big re-write or one should leave it with that focus.
The differences in case of xref streams are described in 7.5.8.1 after all.
