### ISSUE TITLE
Incorrect description of rendering result for B operator in Table 59

### ISSUE THREAD

**Issue by t-merz** [pdf-association/pdf-issues#103]
[I posted this in 2018 on pdfa-cc-tech which resulted in "Not accepted. Already clearly explained in clause
11." in ISO-TC171-SC2-WG8_N0827_2019-01-08-32000-2-errata-notes. I'll bring it up here again since the "explained elsewhere" part is correct, but the wrong sentence still hasn't been addressed.]

The "B" operator is described as follows in ISO 32000-2:2020, Table 59:

"Fill and then stroke the path, using the non-zero winding number rule to determine the region to fill. This operator shall produce the same result as constructing two identical path objects, painting the first with f and the second with S."

However, the second sentence is true only in the absence of transparency. If transparencyis involved, the filled area interacts with the area produced by stroking when separate fill and stroke operators are used, while there is no such interaction when "B" is used.

The existing note mentions
"The filling and stroking portions of the operation consult different values of several graphics state parameters, such as the current colour."

While fill and stroke colors are processed independently from each other, fill or stroke opacity results in interaction between the filled and stroked paths; both painting operations cannot be separated. The "same result" claim is not true in general.

Suggestion: amend the second sentence of the "B" description as follows:

"If fill and stroke opacity are both 1, this operator shall produce the same result as constructing two identical path objects, painting the first with f and the second with S."

Since the description of "B" is referenced by B*, b and b* the suggested improvement indirectly applies to these as well.

The current description of "B" is already present since PDF 1.3 where it was correct since transparency wasn't supported. It just didn't get updated with the introduction of transparency.

**Comment by petervwyatt** [comment]
Proposed solution as per OP.

Alternatively can simplify to start 2nd sentence with "In the opaque imaging model, ..." which is phrasing we use elsewhere.

**Comment by petervwyatt** [comment]
PDF TWG agree
