### ISSUE TITLE
Table 29 Lang key and invalid values

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#105]
Table 29 (Catalog) **Lang** key states: "(_Optional; PDF 1.4_) A language identifier that shall specify the natural language for all text in the document except where overridden by language specifications for structure elements or marked-content (see 14.9.2, "Natural language specification"). If this entry is absent, the language shall be considered unknown."

I have a PDF file where the **Lang** key is a name object: `/Lang /en`
Clearly this is syntactically incorrect (should be text string), but the final sentence in Table 29 doesn't allow me to consider this as "unknown language" (which I believe is the correct result) as the key IS present in the PDF. And I cannot see any other wording in PDF which gives me an "out" to officially treat this as "unknown language" since duplicate dict key names are also not allowed.

Change last sentence to "If this entry is absent or invalid, the language shall be considered unknown."

**Comment by lrosenthol** [comment]
The problem with your recommendation is that we don't have a definition of "invalid"...

**Comment by MatthiasValvekens** [comment]
Maybe this is a cop-out, but wouldn't something like that fall under the general umbrella of "invalid behaviour is undefined by default"? IIRC there are a couple of places where the standard defines an entry as required, while simultaneously also prescribing fallback behaviour in case the entry is absent, but I don't know of any instances where ISO 32k tells people how to recover from "type errors" like the one you described---happy to be corrected if that's not the case. For better or worse, isn't error recovery essentially always implementation-dependent by default?

**Comment by petervwyatt** [comment]
I think that depends on how you interpret "If this entry is absent, the language shall be considered unknown.". If you take it as written, then the situation when a key is present but wrong is not covered by this statement. If we want to be unambiguous we need to be clearer.

A clearer statement would be "If this entry is absent or invalid (see 14.9.2, "Natural language specification"), the language shall be considered unknown."

**Comment by petervwyatt** [comment]
@MatthiasValvekens You indirectly made a better suggestion... 😁

Rather than this single point solution, it would be better to clarify that when ISO 32000 states any requirement regarding a "key" or "entry" being "absent" then this is inclusive of the case where the same key name is used but the key value is not according to ISO 32000. There are 70 instances of the word absent in 32000 and use a mixture of language!

I would add such a general clarification statement to the end of clause 7.3.7 Dictionary objects - done INFORMATIVELY!!:

NOTE When this document states any requirements regarding a key or entry being "absent", then those requirements also apply when the dictionary has a key of the correct name, but the key value is not a permitted type according to this document.

**Comment by MPBailey** [comment]
Agree in principle, but shouldn't the end be adjusted for cases where it's the right type, but valid values are a (closed) enumeration and it doesn't match anything in the permitted list?

**Comment by petervwyatt** [comment]
I'd argue then such a key is not "absent", but clearly "present". And other wording and/or context would apply. 

Either that or we have to look at all 70 occurrences of the word "absent" :-(

**Comment by petervwyatt** [comment]
PDF TWG agree to this specific point fix for the Lang key:

"If this entry is absent or invalid (see 14.9.2, "Natural language specification"), the language shall be considered unknown"

A new Issue will be created to track the other 79 uses of the word 'absent'.
