### ISSUE TITLE
Mandated indirect reference requirements not followed and not enforced - are they really requirements?

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#106]
There are several places where the PDF spec requires something to be an indirect reference ("shall ...") when it is not absolutely technically necessary (i.e. when something is not a stream, not a "back pointer" to a page, not Kids, etc). Yet when you begin to analyze extant PDF files, many writers do not obey these nuanced rules and all(?) PDF processors seem to silently ignore all but the absolutely required indirect-ness requirements. Common examples where indirect requirements are often not written AND are widely silently supported include Catalog/Dests, trailer/Info, FontDescriptor, ... 

Maybe it is time to recognize this reality and loosen some more of the "_shall be indirect interference_" to "_should be an indirect reference_" or "_indirect reference preferred_"?
Discuss.

PS. The **ID** key in Table 31 and Table 87, and **Widths** in Table 109 all currently state "_indirect reference preferred_". Widths in Table 110 says "_should be an indirect reference_". Is there any semantic difference between these 2 statements? I assume not.

**Comment by lrosenthol** [comment]
>Maybe it is time to recognize this reality and loosen some more of the "shall be indirect interference" to "should be an indirect reference" or "indirect reference preferred"?

If you can come up with the full list of these that we can evaluate on a case by case, that would seem like the right thing to do.   And of the choices, I prefer the former ("should be...")

**Comment by MatthiasValvekens** [comment]
I think we should be careful with objects that can appear in backreferences elsewhere. For example, the **Data** key in a signature reference dictionary often (always?) points to the document catalog. Softening the "shalls" to "shoulds" would then potentially complicate things for processors that both consume & write PDFs.

Other than that, no objections :)

**Comment by petervwyatt** [comment]
@MatthiasValvekens - absolutely agree. This is for limited cases where the target object is only referred to once (i.e. there is no technical need for it to be a direct object). But if PDF writers desire then they can make (almost) any object be an indirect reference.

@lrosenthol - I also agree that "should" is a better statement than "preferred".

Three common fails I have encountered so far which are specified as "shall be indirect": Catalog/Dests, trailer/Info, FontDescriptor. I will keep an eye out for others.

**Comment by prashantbarca** [comment]
We have found some files with /Catalog/Outlines as well. Would be good to add that to the list!

**Comment by petervwyatt** [comment]
Here is a concrete list of common objects that DO occur as inline (not indirect as stated in the spec) in the wild AND that multiple implementations happily handle without error or warning. Proposed solution is to delete the "shall be indirect object" in all cases:
* Table 15. trailer/Info
* Table 29. Catalog/Dests
* Table 29. Catalog/Outlines
* Table 29. Catalog/Threads
* Table 31. Page/ID says "indirect reference preferred" - strike that
* Table 109. Type 1 font/FontDescriptor
* Table 110. Type 3 font/FontDescriptor
* Table 115. CIDFont/FontDescriptor

**Comment by MPBailey** [comment]
As info is (usually) deprecated now, I'd suggest not changing it at this stage.
Requiring FontDescriptor to be indirect makes it easier to fall into the habit of generating multiple subsets of the same font, which is usually a bad thing. Allowing them to be direct isn't much of a lever in the opposite direction, but I'll take what I can get!
I also see ID in Table 87. Image/ID

**Comment by petervwyatt** [comment]
Yes to Table 87. Image/ID which currently says "_indirect reference preferred_" which is neither a "shall" or a "should" :-)

Although Info is deprecated, the PDF 2.0 spec is still relevant to processors needing to apply incremental updates (such as version upgrade increments) to a legacy PDF and thus assessing whether they should consider this an error or not.

**Comment by lrosenthol** [comment]
As @MPBailey points out there, most of these exist to prevent PDF writers from doing things that will complicate downstream processing (like the FontDescriptor examples).   Some are there to make it easier to transition a file to linearized (like Dests, Outlines and Threads).

A well know implementation will simply fix these sorts of things up when it is modifying a "bad" (as currently spec'd) file, so from our perspective I would be fine changing the language to "should" instead of "shall"

**Comment by MPBailey** [comment]
FWIW, I'm trying to figure out whether it's safe to allow Trailer/Prev to be indirect, as is currently the case. I think I might just put the lid back on that can of worms and step back quickly!

**Comment by MatthiasValvekens** [comment]
> FWIW, I'm trying to figure out whether it's safe to allow Trailer/Prev to be indirect, as is currently the case.

Huh, I never bothered to try that, but you're right that the text doesn't appear to exclude **Prev** being an indirect reference. That sounds dangerous because **Prev** (obviously) affects how indirect references are supposed to be processed in the first place... Do viewers actually accept indirect references for **Prev** in practice?

**Comment by lrosenthol** [comment]
I haven't seen it either and agree that it is confusing...

However, a "well known implementation" does not check if it is direct or indirect...

Anybody want to try to make a sample PDF to try this out on various processors??

**Comment by petervwyatt** [comment]
Table 15 specifically requires Trailer/**Prev** to always be a direct object so that is fine.

And 7.5.8.2 Cross reference stream dictionary also has an explicit requirement for **Prev** entries there: "_The values of all entries shown in "Table 17 — Additional entries specific to a cross-reference stream dictionary" shall be direct objects; indirect references shall not be permitted._"

**Comment by MatthiasValvekens** [comment]
Well, that's a relief. I must've been looking at the *Prev* entry in Table 17 (not Table 15), and somehow missed that part of the text preceding the table. Thanks for the double-check!

**Comment by petervwyatt** [comment]
PDF agree to the following not being mandated as indirect references:
    Table 15. trailer/Info
    Table 29. Catalog/Dests
    Table 29. Catalog/Outlines
    Table 29. Catalog/Threads
    Table 31. Page/ID says "indirect reference preferred" - strike that

Will defer discussion on the following until @MPBailey is able to attend PDF TWG:
    Table 109. Type 1 font/FontDescriptor
    Table 110. Type 3 font/FontDescriptor
    Table 115. CIDFont/FontDescriptor

**Comment by MPBailey** [comment]
If there were a requirement that every Font object for a specific font used the same FontDescriptor then the requirement for an indirect reference to the FontDescriptor would make sense. But there isn't, so no objections to allowing direct resources in any of those remaining three instances.

**Comment by petervwyatt** [comment]
PDF TWG the additional 3 edits after discussion with Martin
