### ISSUE TITLE
Resource Properties needs to be used for all object reference in content streams

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#107]
Indirect references are not allowed in content streams at all, as so stated in 7.8.2 Content streams which explicitly says: “Indirect objects and object references shall not be permitted at all”. 

However the Resources Properties description in Table 34 is written so that it specifically only applies to marked content operators and nothing else, which is incorrect. It is the general method that needs to be used to map all resource names to objects, regardless of how they are specified in a content stream. While marked content operators might be the only formally defined use in ISO 32000, there are other syntactically valid places in content streams where indirect references might occur (e.g. private keys in inline image dictionaries and in compatibility sections bounded by BX/EX). 

Current Table 34 **Properties** value description:

> (_Optional; PDF 1.2_) A dictionary that maps resource names to property list dictionaries for marked-content (see 14.6.2, "Property lists").

Proposed solution:

> (_Optional; PDF 1.2_) A dictionary that maps resource names used in content streams to PDF objects, including property list dictionaries for marked-content (see 14.6.2, "Property lists").

**Comment by MPBailey** [comment]
14.6.2 only talks about the DP and BDC operators in the context of using named property list resources in a contents stream. Surely you would need to add at least a note there to raise the potential for the other uses that you’re suggesting?

**Comment by lrosenthol** [comment]
Properties are **just for marked content**, so this change is incorrect.  Leave as is.

**Comment by petervwyatt** [comment]
No fix. Correct solution is to add a new sub-dict to Resources appropriate to the operator or private data in question.
