### ISSUE TITLE
incorrect table mentioned for BMC operator in Table A.1 

### ISSUE THREAD

**Issue by pmundkur** [pdf-association/pdf-issues#108]
The listing in Table A.1 has incorrect information in the table column for BMC.
The BMC operator is described in Table 352 for marked-content operators, not Table 351.

**Comment by petervwyatt** [comment]
Thanks @pmundkur. Proposed solution as per OP.

**Comment by pmundkur** [comment]
I noticed the same problem for marked-content operators in Table 50: the location column should refer to Table 352 instead of 351.  Perhaps I can add Table 50 to the title of this bug.  Or should I open a new issue?

**Comment by petervwyatt** [comment]
We can use this same issue as these fixes are not controversal. Thanks again!

**Comment by petervwyatt** [comment]
PDF TWG agree

**Comment by pmundkur** [comment]
BTW, another issue in Table 50 is "Sh" as shading operator, whereas Table 76 and Figure 9 call it "sh".  I'm guessing it should be "sh"?

**Comment by petervwyatt** [comment]
@pmundkur Thanks - this was previously identified and fixed as Issue #80

**Comment by petervwyatt** [comment]
Table 50 was previously fixed via Issue #85
