### ISSUE TITLE
More misc formatting issues (please add to this Issue for formatting-only issues)

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#109]
Additional formatting-only issues:

* Table 260: PDF versions in parentheses represent the version things were introduced and should be fully italic.
 
* Clause 7.5.4 Cross reference table, Example 2 - appears that there are 2 spaces between "0" and "6" for the xref subsection line, yet the spec requires precisely 1 space.

* Clause 7.5.4 Cross reference table, Example 3 - appears that there are 2 spaces between "0" and "1" for the first xref subsection line, yet the spec requires precisely 1 space. There might also be a non-fixed width font issue for the xref lines in this example as they don't appear the same as the first xref entry.

* Clause 13.1 Multimedia feature, General - short clause has extraneous bullet points in some clause titles. Quite messed up.

**Comment by MPBailey** [comment]
On the first bullet (Table 260, PDF versions in italic), that matches many uses in the current text, but is not as described in the last para of section 5.

Clause 7.5.4 Cross reference table, Example 3 - it looks as if there's a double space before 65535 as well.

**Comment by MatthiasValvekens** [comment]
Clause 7.12.2, Table 48: "shall be a direct objectif present" -> "shall be a direct object if present"

**Comment by petervwyatt** [comment]
PDF TWG agree to all formatting and typo fixes. Will not update clause 5 as this is not consistently done throughout 32K.
