### ISSUE TITLE
Catalog should be added to the list of objects that must be excluded from ObjStm

### ISSUE THREAD

**Issue by faceless2** [pdf-association/pdf-issues#110]
Based on recent (20210805) discussions on the pdf-twg mailing list:

There are technical reasons why the Catalog must not be stored in an ObjStm:
* it would potentially hide the version number of the PDF
* it would hide the /Metadata for the PDF if the PDF was encrypted.

I'm pretty sure no-one does this, as Acrobat can't load the resulting file. So can I request adding the Catalog to the list of objects excluded from Object Streams in section 7.5.7

**Comment by MatthiasValvekens** [comment]
As noted on the mailing list (repeating here for the record): this is only really a problem with encrypted files, since it would prevent a processor from deducing the correct version & applicable PDF extensions prior to decryption. Perhaps we can add a note in 7.5.7 to that effect.

**Comment by petervwyatt** [comment]
@faceless2 - could you please attach an example PDF?

We should allow everyone to test their implementations to reach a full industry agreement, so we can consider more than a single vendor. I'm currently more in favour of @MatthiasValvekens proposal to only require this for encrypted PDFs. I also note that the 5th bullet in 7.5.7 already excludes Catalog for Linearized PDFs.

**Comment by MatthiasValvekens** [comment]
I personally don't have a strong opinion on which way to resolve this, to be honest. My intention was simply to restate the point of the mailing list discussion here.

Two further observations that I believe would apply regardless of whether we limit the scope of the change to encrypted files:

 - This is (at least on paper) a backwards-incompatible normative change---not that I have a problem with that.
 - I think a note explaining the rationale (i.e. problems with pre-decryption processing of encrypted files) would be valuable in either case.

**Comment by faceless2** [comment]
* [catalog-in-objstm.pdf](https://github.com/pdf-association/pdf-issues/files/6944327/catalog-in-objstm.pdf) - unencrypted
* [catalog-in-objstm-aes.pdf](https://github.com/pdf-association/pdf-issues/files/6944329/catalog-in-objstm-aes.pdf) - encrypted

Acrobat only seems to have issues with the encrypted one, so my assertion in the original post was partly wrong and I'd agree this really only needs considering for encrypted files. Whether that's by a rule, or a note in the spec to the effect of "for maximum compatibility, don't do this for encrypted files" probably doesn't matter, but it's a bit of a "trap for young players" so worth noting somehow.

**Comment by petervwyatt** [comment]
Maybe just a note so that the normative language is unchanged...

**Comment by MatthiasValvekens** [comment]
Proposed solution:

> NOTE: Including the document catalog in an object stream has interoperability implications, particularly for encrypted documents. If the catalog dictionary is part of an object stream, a PDF processor reading the document must first process that object stream before it can access potentially relevant document metadata, including the declared PDF version, developer extensions and XMP metadata.

IIRC "must" is informational in ISO-ese, and I don't think this sounds normative, but feel free to wordsmith as appropriate.

As to why I wrote "process" instead of "decrypt" in the second sentence: encryption is the only case where any of that currently matters (hence why it's called out explicitly), but this wording would also cover potential future extension TSes that define new compression algorithms, for example. Not that that's particularly likely to happen, but it doesn't hurt IMO.

**Comment by smuehlst** [comment]
> There are technical reasons why the Catalog must not be stored in an ObjStm:

I'm not sure that these are actually technical reasons but rather reasons caused by a certain policy.

> * it would potentially hide the version number of the PDF

There's no reason why someone needs to know the version number of an encrypted PDF file unless the file can be decrypted by the user.

> * it would hide the /Metadata for the PDF if the PDF was encrypted.

Same argument as above: Why should someone get access to the Metadata of an encrypted PDF file unless the file can be decrypted by the user. Compare that to a Document Information dictionary: The entries in a Document Information dictionary are encrypted if the file is encrypted.

Please correct me if I'm wrong, but according to my understanding the /Encrypt dictionary is self-contained, and it isn't necessary to know the concrete PDF version for being able to determine the key to decrypt a file. If that is correct, then a PDF processor can first determine the decryption key, then decrypt the catalog to determine the PDF version, and then act appropriately depending on the PDF version.

**Comment by MatthiasValvekens** [comment]
Yes, that's true, and in fact it's exactly what our library (iText) does. But I can see why you might want to access information about developer extensions & version info prior to attempting authentication & decryption in an interactive viewer. For example, ISO 32003 defines a new security handler with an encryption algorithm that is incompatible with any of the existing ones. A viewer that doesn't support ISO 32003 wouldn't be able to infer that it was missing a developer extension; all it would see is crypt filter definitions that it doesn't recognise.

As for XMP metadata: there's an option to leave metadata unencrypted for indexation purposes. In such cases, you presumably want to make sure that a PDF processor can still reliably locate the metadata stream without requiring authentication. That doesn't apply universally, obviously, but it's still an edge case worthy of consideration IMO.

That said, I think you have a point in that this is probably a matter of policy, and better left up to the implementation to decide. I think adding a note calling out the potential interoperability issue would still be valuable, though.

**Comment by smuehlst** [comment]
> As for XMP metadata: there's an option to leave metadata unencrypted for indexation purposes. In such cases, you presumably want to make sure that a PDF processor can still reliably locate the metadata stream without requiring authentication. That doesn't apply universally, obviously, but it's still an edge case worthy of consideration IMO.

You are right, I forgot about the /EncryptMetadata entry in the encryption dictionary. If "/EncryptMetadata false" is present, it should be possible to locate the XMP metadata stream of the document without having to decrypt the catalog.

**Comment by lrosenthol** [comment]
>You are right, I forgot about the /EncryptMetadata entry in the encryption dictionary. If "/EncryptMetadata false" is present, it should be possible to locate the XMP metadata stream of the document without having to decrypt the catalog.

That would be true *only if* the XMP hasn't been updated in any update tables - which is usually *not* the case (since you want/need to update the mod dates in each update).

**Comment by petervwyatt** [comment]
PDF TWG accepts proposed note from 6 Aug comment by Matthias.
