### ISSUE TITLE
Confusion from "graphics operators" vs "graphics object" for Type 3 CharProcs

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#111]
I have been asked a question if there are any limitations on which graphics operators can occur in Type 3 CharProcs. The reasoning is as follows:

Clause 9.6.4 paragraph 1: "In Type 3 fonts, glyphs shall be defined by streams of PDF graphics operators". 

Then clause 8.2 states: "... PDF content stream is not a program to be interpreted; rather, it is a static description of a sequence of _graphics objects_" where the italics is in ISO 32000-2:2020 and represent a term-of-art. Table 50 also has no Operator Category for "graphics operators" and neither does Figure 9. So the root of the misunderstanding is that the terminology in 9.6.4 uses "graphics operators" and clause 8.2 uses "graphics objects".

I think the best solution is to alter 9.6.4 to use matching terminology from clause 8.2:

"In Type 3 fonts, glyphs shall be defined by streams of PDF graphics objects."

and then also add a factual informative note that all operator categories as per Table 50/Figure 9 are permitted in Type 3 CharProcs (and reusing terminology from 8.2 as necessary):

NOTE: Type 3 glyphs can use any PDF operator from any operator category (see Table 50 and Figure 9).

**Comment by petervwyatt** [comment]
Table 50 has a dedicated row for `d0`/`d1` under the category "Type 3 fonts", but admittedly Figure 9 does not "Type 3 fonts" anywhere (I'm not sure how it could???).

Clause 9.6.4 and Table 111 clearly define everything to do with `d0`/`d1` so I'm not seeing any issue. And if the text in 9.6.4 is modified to say "... _any operator from Table 50_" then that also includes `d0`/`d1` so there is no contradiction.  

Back in clause 8.2, we could add a forward referencing statement along the lines of "The Type 3 font operators d0 and d1 are described in clause 9.6.4 "Type 3 fonts"" as NOTE 3 below Table 50.

The issue is where the set of PDF operators allowed in Type3 CharProcs is defined and if there are any restrictions on operators (besides `d0`/`d1`). Currently nothing is explicitly stated either wat that I can see so therefore I beleive the full set of PDF operators (including obviously `d0`/`d1`) is permitted.

**Comment by petervwyatt** [comment]
Summarising proposed solution:

* change 2nd sentence, 1st para in clause 9.6.4 (using matching terminology from clause 8.2): "_In Type 3 fonts, glyphs shall be defined by streams of PDF graphics objects._"

* add in clause 9.6.4 below para 1 a factual informative note that all operator categories as per Table 50/Figure 9 are permitted in Type 3 CharProcs (and reusing terminology from 8.2 as necessary): "NOTE: Type 3 glyphs can use any PDF operator from any operator category (see Table 50 and Figure 9)."

* in clause 8.2, add a forward referencing statement along the lines of "The Type 3 font operators d0 and d1 are described in clause 9.6.4 "Type 3 fonts"" as NOTE 3 below Table 50.

**Comment by t-merz** [comment]
>     * add in clause 9.6.4 below para 1 a factual informative note that all operator categories as per Table 50/Figure 9 are permitted in Type 3 CharProcs (and reusing terminology from 8.2 as necessary): "NOTE: Type 3 glyphs can use any PDF operator from any operator category (see Table 50 and Figure 9)."

The "any operator" phrase looks a bit misleading to me in the light of uncolorized fonts; Table 111 says in the entry for "d1"

"A glyph description that begins with the d1 operator should not execute any operators that set the colour..."

Granted, it says "should not", but the unsuspecting reader of the proposed "can use any" is lead in the wrong direction. The restriction should at least be mentioned in the note.

**Comment by petervwyatt** [comment]
But Table 111 goes on to say "... any use of such operators shall be ignored and the glyph stream continues to be processed without error". 

So any PDF operator is permitted to exist in `d1` content streams - it's just that some of them will be no-ops. So, from a syntax validator PoV, the presence of those operators in a `d1` stream is not technically an error (more a warning).

**Comment by t-merz** [comment]
> But Table 111 goes on to say "... any use of such operators shall be ignored and the glyph stream continues to be processed without error".
> 
> So any PDF operator is permitted to exist in `d1` content streams - it's just that some of them will be no-ops. So, from a syntax validator PoV, the presence of those operators in a `d1` stream is not technically an error (more a warning).

Yes, but there's still the "should not" clause in Table 111, so I find it appropriate to at least mention this restriction.

**Comment by lrosenthol** [comment]
Although it's not operator specific, it's probably worth a note (at least) somewhere concerning the ability to create a potential infinite recursion by having a T3 charproc refer to itself (or even a more complex loop through multiple charprocs).

**Comment by crlf0710** [comment]
If we could turn back the clock, personally i'd say just create d0 d1 equivalents as form dictionary keys. It's obvious that these doesn't fit in the "graphics object" model well. 

But since we have to bite the bullet, with "... PDF content stream ... is a static description of a sequence of graphics objects", it follows that either `d0` `d1` information is a special kind of a graphic object, or this sentence should be changed to something like "a static description ... graphics object plus optional Type3 CharProc information" or something (with appropriate wording), or just change "is a" to "contains"(this seems indeed easier)...

By the way, i see marked-content (points and sequences) in a very similar position.

**Comment by lrosenthol** [comment]
>If we could turn back the clock, personally i'd say just create d0 d1 equivalents as form dictionary keys. It's obvious that these doesn't fit in the "graphics object" model well.

For those interested in the history - these were done as operators for consistency with (and easy conversion to) Postscript. `d0` maps to `setcharwidth` and `d1` maps to `setcachedevice`. (and there is no equivalent to setcachedevice2).

**Comment by petervwyatt** [comment]
PDF TWG agree.
