### ISSUE TITLE
Object stream dictionary key values all need to be direct 

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#114]
Object stream dictionaries are defined by "Table 16 — Additional entries specific to an object stream dictionary" as well as the usual set of keys from "Table 5 — Entries common to all stream dictionaries". Clause 7.5.7 "Object streams" has a list of objects that "... _shall not be stored in an object stream_" which includes "_An object representing the value of the **Length** entry in an object stream dictionary_". 

Clause 7.3.10 Indirect objects also states: "_Except where documented to the contrary, any object value may be a direct or an indirect reference; the semantics are equivalent_". Thus any key value can be referred to by an indirect so there are also other key values, besides just **Length**, that also must not be inside an object stream that needs them, or things are not processable. Catch 22! For example, values for **Filter**, **DecodeParams** from Table 5, the value of the **Type**, **N** and **First** keys from Table 16 all can't be in the object stream they are defining.

Although technically these key values could be in a different object stream and then things should work so long as there are no circularities between object streams, I think this is an unnecessarily confusing roundabout we don't want to be on. The other confusing part here is that Table 16 **Extends** key does need to be an indirect reference to "another stream object" - but it should be directly to that other stream object, and not indirectly via a chain of indirect references. 

So I suggest we make a blanket statement in PDF 2.0 that:

> Except for **Extends**, all key values in object stream dictionaries (from both Table 5 and Table 16) shall be direct objects.

and update the **Extends** description:

> A direct reference to another object stream, of which the current object stream is an extension (chains of indirect references are not permitted).

PS. Note that ISO 32000-2:2020 PDF 2.0 already added the statement to 7.3.7 Dictionary objects "_All keys shall be direct objects._" so we don't need to worry about the keys themselves - just the key values.

**Comment by petervwyatt** [comment]
We can also add "(_Required; shall be direct_)" to the description for **Type**, **N**, and **First** in Table 16.

**Comment by MatthiasValvekens** [comment]
I can think of one case where this change might affect existing implementations. There is at least one widely used graphics toolkit (`cairo`) that insists on making the **Length** key in a stream dictionary indirect. Presumably this is a hack to make sure the stream content can be compressed & written in one pass, since it allows the value of the **Length** key to be written _after_ the encoded stream content. I'm not sure whether `cairo` makes use of object streams, though, so perhaps the point is moot. I also don't think the `cairo` project has any ambitions to output PDF 2.0 files (or whatever version of PDF that this change would apply to).

I'm not particularly fond of this practice; I just wanted to record that it's something people do (for better or worse).

**Comment by petervwyatt** [comment]
But that is fine, since object streams cannot contain other streams, as per the 1st bullet in clause 7.5.7.

However if they also do this for the **Length** of the object stream itself then that would be clearly incorrect since Adobe PDF 1.6 and every later PDF spec/standard states: "_Any PDF object can appear in an object stream, with the following exceptions: ... An object representing the value of the **Length** entry in an object stream dictionary_".

Remember this is ONLY object streams, not all streams :-)

**Comment by zauguin** [comment]
> However if they also do this for the **Length** of the object stream itself then that would be clearly incorrect since Adobe PDF 1.6 and every later PDF spec/standard states: "_Any PDF object can appear in an object stream, with the following exceptions: ... An object representing the value of the **Length** entry in an object stream dictionary_".

I don't see how this is relevant here. Sure, `cairo` can't store the Length in an object stream, but if they want to write the file in one pass they might still store the Length in a separate indirect object just after the object stream.

I don't see any technical reason to require these values to be direct objects, IMO it would be enough to just require them not to be part of an object stream. So basically change the list entry

> An object representing the value of the Length entry in an object stream dictionary

to

> An object representing the value of an entry of an object stream dictionary.

**Comment by petervwyatt** [comment]
@zauguin  ... except for the **Extends** entry which always has to be indirect. 

I'm not sure of the historic reasoning of why Adobe specified it the way they did back in 2004, but they did nonetheless. And it's been unchanged ever since. But you are technically correct: so long as all object stream dictionary key values (or the chain of indirect references that lead to such a key value) are never in _any_ object stream then there cannot be the possibility of a Catch22 stalemate where 2 or more object streams circularly depend on each other for resolving key values. Excepting **Extends** which must be an indirect reference to an object stream by its very definition.

It is a good discussion point for the next PDF TWG meeting, as changing a requirement that is more than 17 years old may have big ramifications on existing implementations and validators.

**Comment by MatthiasValvekens** [comment]
I think I agree with @zauguin. Again, I'm not sure whether `cairo` and friends use object streams, but if they did, they'd probably take issue with a general prohibition on indirect references in object stream dictionaries. IMO restricting object stream dictionary values to indirect references _that don't live in an object stream_ (with the exception of **Extends**) is less likely to cause issues.

**Comment by zauguin** [comment]
> ... except for the **Extends** entry which always has to be indirect.

I would argue that `Extends` is not actually an exception since the list lists things which should not be "stored in an object stream" and while `Extends` *is* a (reference to a) object stream, it's not stored *in* one (since object streams can't contain streams).

**Comment by MatthiasValvekens** [comment]
> I would argue that Extends is not actually an exception since the list lists things which should not be "stored in an object stream" and while Extends is a (reference to a) object stream, it's not stored in one (since object streams can't contain streams).

Oh, good point! That makes it even cleaner :)

**Comment by MPBailey** [comment]
FWIW, it's not just Cairo that uses indirect references for Length in Stream objects; it's pretty common so that the length can be calculated as the stream is written. Not sure I've ever seen that for object streams, but the same logic would apply, I think.

**Comment by petervwyatt** [comment]
This might be one for our resident historian @lrosenthol as to why things were spec'd the way they were...

I think we can all agree so long as all object stream key values are not in _any_ object stream (i.e. are always ordinary objects) then there is no technical issue if they are direct or indirect.

**Comment by lrosenthol** [comment]
I am confused what is being proposed here...

If the only proposed change is to make the three keys on the ObjStm dict (`/Type`, `/N` and `/First) required as direct - I have no objections to that.

**Comment by petervwyatt** [comment]
Any entry's value in an ObjStm dictionary shall be either a direct object or an indirect uncompressed object.

PDF TWG Agree for above sentence.

**Comment by vasekp** [comment]
Oh, how stupid of me, I read that note in the errata but did not connect the dots. Even your former Issue sounds familiar – I remember seeing the "Catch 22!" My apologies for putting an unnecessary issue, brain fog.

In this case, however, the bullet point "An object representing the value of the Length entry in an object stream dictionary" should probably be removed given that placing the Length there is already precluded by other means.
