### ISSUE TITLE
What is meant by Table 255 "Entries in a signature dictionary" when the Filter key states "inheritable"?

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#121]
What is meant in Table 255 "Entries in a signature dictionary", when the **Filter** key states "(_Required; inheritable_)"? 

The **Filter** is a property of the _value_ of a signature field, not the field itself so I don't understand the "inheritable" statement. It is clearly not related to the inheritance statements related to page attributes in clause 7.7.3.4 "Inheritance of page attributes"...  and AFAICT there is no description of any other kind of inheritance that seems related.

@MatthiasValvekens suggested that it might refer to the fact that **Filter** and **SubFilter** can be prescribed by the field's seed value dictionary, but that's probably also wrong: the "(_Required; inheritable_)" qualifier for **Filter** has been in place since PDF 1.3, all the way back to when digital signatures were first introduced. Meanwhile, seed values are a PDF 1.5 feature.

So can someone please explain what "inheritable" means for Table 255 **Filter** key? Inheritable from what? What are the inheritance rules?

@lrosenthol are you able to shed any light? TIA

**Comment by MatthiasValvekens** [comment]
As @petervwyatt already mentioned, we had a short exchange over e-mail about this issue. The main points have been summarised by Peter already, but I'll paste the relevant part of my reply below for some additional context:

> _(snip)_
> 
> As for the Filter entry in a signature dictionary: my knee-jerk reflex
> was to say that it'd have to be inherited from a form field higher up
> in the AcroForm hierarchy, but that doesn't apply, since Filter is a
> property of the _value_ of a signature field, not the field itself.
> 
> 
> My next thought was that it might refer to the fact that Filter and
> SubFilter can be prescribed by the field's seed value dictionary, but
> that's probably also wrong: the "(Required; inheritable)" qualifier for
> Filter has been in place since PDF 1.3, all the way back to when
> digital signatures were first introduced. Meanwhile, seed values are a
> PDF 1.5 feature.
> 
> 
> In the "real world", I've only ever seen deeply nested form field
> hierarchies in XFA forms, and I'm not going to pretend I understand how
> those work...  Complicating matters further, a Usage Rights signature
> can live outside the document's form structure, where things are even
> more murky.
> Fortunately those are deprecated and I don't think anyone other than
> Adobe ever produced them systematically.

Bottom line: I personally don't have any qualms about turning _(Required; inheritable)_ into _(Required)_ in a future PDF version and/or dated revision, but I'll wait for more information :).

**Comment by mkl-public** [comment]
While being at it, nowadays the **Filter** information is not needed at all anymore as long as one of the interoperable **SubFilter** values is used. Many signing products use one of the example values given in the spec, essentially rendering the value meaningless.

Thus, _(Required; inheritable)_ could even be turned into a _(Optional)_ or at least _(Required when **SubFilter** is not among the values mentioned in the **SubFilter** definition)_.

**Comment by lrosenthol** [comment]
A well known implementation does *not* treat this value as inherited from anywhere - it only looks on the dictionary itself for a value.

FWIW: the original DigSig proposal at Adobe had it labled this way as well. I can only conclude it was a copy/paste error that no one caught till now...

**Comment by petervwyatt** [comment]
PDF TWG agrees to strike "inheritable" for this entry.
