### ISSUE TITLE
What is meant by Table 239 "Additional entries specific to a submit-form action" when Flags and CharSet state "inheritable"?

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#122]
What is meant by Table 239 "Additional entries specific to a submit-form action" when **Flags** and **CharSet** both state "_inheritable_"?

There are arrays of actions but they are executed in sequential order not hierarchically so where is there any inheritance?
And **Flags** can't be referring to Annotation flags from fields or widgets as the bits are all different (cf. Table 240 vs Table 167).

Is it trying to say what paras below Table 240 state regarding **Fields** array and/or **Ff** (in which case this is not "inheritance" per-se as we define elsewhere in ISO 32000)?

Help please.

**Comment by lrosenthol** [comment]
A well known implementation does not treat this value as inherited from anywhere.

FWIW: The public version of PDF 1.3 has the field marked as inherited *however* the Adobe internal version of PDF 1.3 does **not** it marked accordingly.

**Comment by petervwyatt** [comment]
PDF TWG agree to strike inheritable for these entries

**Comment by bdoubrov** [comment]
As per PDF/A TWG resolution, PDF/A-4 should indeed reference Annex Q as an algorithm to determine the transparency on the page.
