### ISSUE TITLE
Question: is "pdfa:conformance"  property of the Table 2 — PDF/A identification schema valid (ISO 19005-4:2020 ch: 6.7.3 Version identification ) ?

### ISSUE THREAD

**Issue by RahamanMdEkhlasur** [pdf-association/pdf-issues#123]
In the 6.7.3 "Version identification" chapter there is the following paragraph:

**The PDF/A identification schema defined in Table 2 uses the namespace URI https:// www .aiim .org/ pdfa/ ns/ id/ . The required schema namespace prefix is pdfaid.**

The second sentence describes the required schema namespace prefix which is pdfaid but at the same time prefix of the last property "pdfa:conformance" of the "Table 2 — PDF/A identification schema" uses pdfa instead of pdfaid. Is it valid?

And also want to know that the namespace URI scheme used in the first sentence is https. Is it https instead of http?

**Comment by petervwyatt** [comment]
Assign to @bdoubrov for PDF/A TWG to consider

**Comment by bdoubrov** [comment]
I believe the correct prefix is `pdfaid:conformance` , as it was in previous parts of ISO 19005. There was certainly no intention to change this. Are you looking at the specification draft or at the published version of ISO 19005-4?

The URI starts with `http`, not `https`. Note that this is not supposed to be a working URL. Merely a URI used to identify the namespace.

**Comment by RahamanMdEkhlasur** [comment]
@bdoubrov Thank you for the clarification. I am looking at the following published version:
**ISO 19005-4:2020
Document management — Electronic document file format for long-term preservation — Part 4: Use of ISO 32000-2 (PDF/A-4)**

**Comment by petervwyatt** [comment]
This is what I see in my copy of ISO 19005-4:2020:
![image](https://user-images.githubusercontent.com/26521615/135877724-e1a7a51e-4b31-4e39-8516-9305f971fe5a.png)

**Comment by bdoubrov** [comment]
Indeed, this is an unfortunate misprint, both in this table and in the following paragraph. The correct is `pdfaid:conformance`.

**Comment by petervwyatt** [comment]
And http://

**Comment by petervwyatt** [comment]
PDF TWG agree both these errors need require fixing. 
Should include a NOTE that there was an error in the first version and implementations may choose to accept "https" in addition to "HTTP"
