### ISSUE TITLE
Incorrect array indices used for rectangle entries of annotation /Rect dictionary entry

### ISSUE THREAD

**Issue by smuehlst** [pdf-association/pdf-issues#124]
Type `rectangle` is defined in "3 Terms and definitions", "3.57 rectangle" as a "specific _array object_ (3.2)" and as "an array of four numbers".

Type `array` is defined in "3 Terms and definitions", "3.2 array object": 
"one-dimensional collection of objects (3.44) arranged sequentially and implicitly numbered starting at 0"

In "12.5.2 Annotation dictionaries", "Table 166 — Entries common to all annotation dictionaries" the `Rect` key has type `rectangle`.

In the same table the description of the `AP` key contains the following clause:

"Annotations where the value of the Rect key consists of an array where the value at index 1 is equal to the value at index 3 and the value at index 2 is equal to the value at index 4."

As arrays are 0-based according to the definition in "3.2 array object" the 1-based indices in this clause are incorrect.

Proposed correction:

"Annotations where the value of the Rect key consists of an array where the value at index 0 is equal to the value at index 2 and the value at index 1 is equal to the value at index 3."

**Comment by petervwyatt** [comment]
Proposed solution as per OP (index values in sentence are -1)

**Comment by lrosenthol** [comment]
I agree with the issue and the proposed resolution.

I will note, however, that this text originally comes from PDF/A and PDF/X, so that there may need to be errata added there as well.

**Comment by petervwyatt** [comment]
PDF TWG agrees with an informative note indicating no change in behavior for any subset.
