### ISSUE TITLE
RichMediaContent Views and RichMediaActivation's View entry point to incorrect portion of the specification.

### ISSUE THREAD

**Issue by datalogics-pgallot** [pdf-association/pdf-issues#127]
In 13.7.2.3.5 A View dictionary is defined in the first paragraph of 13.7.2.3.5 as containing 'a superset of the information present in a 3D view (3DV) dictionary as specified in "Table 315 — Entries in a 3D view dictionary".'

Table 341 (Entries in a RichMediaContent dictionary) the Views entry specifies its values as being Table 315 3D view dictionaries rather than referencing section 13.7.2.3.5 (View dictionary).

Likewise, Table 335's (Entries in a RichMediaActivation dictionary) View entry explicitly calls out its value as being a Table 315 3D view dictionary rather than referencing section 13.7.2.3.5, though the last sentence of the entry does mention Table 344 from section 13.7.2.3.5.

Rather than referencing Table 315 directly, the respective entries in Table 335 and Table 341 should reference section 13.7.2.3.5

**Comment by petervwyatt** [comment]
PDF TWG agree
