### ISSUE TITLE
Join Soft-mask image dictionary key limitations between Table 143 and Table 87

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#13]
Clause 11.6.5.2, "Table 143 — Restrictions on the entries in a soft-mask image dictionary" defines a number of image XObjects keys as being "Ignored" yet this information to ignore for soft-masks is not mentioned or cross-referenced from "Table 87 — Additional entries specific to an image dictionary". 

Specifically for Table 87 keys: Intent, Alternates, Name, ID, StructParent.

Table 143 also says SMask key shall be absent, but Table 87 doesn't mention this.

Various simple, not overly wordy solutions and that don't duplicate technical requirements include:

- add a reference to 11.6.5.2 Soft-mask images to the NOTE above Table 87

- adding "Additional limitations also apply to this key when used in soft-mask image dictionaries - see clause 11.6.5.2 Soft-mask images." to each of the above keys in Table 87.

**Comment by lrosenthol** [comment]
I'd tend to favor the second suggestion since it's normative and makes it more clear which keys are impacted.

**Comment by petervwyatt** [comment]
Proposed solution: add the sentence "Additional limitations also apply to this key when used in soft-mask image dictionaries - see clause 11.6.5.2 Soft-mask images." to the description for each of the Table 87 keys: Intent, Alternates, Name, ID, StructParent, and SMask.
