### ISSUE TITLE
Requirements for Link elements are incorrect (section 14.8.4.7.2)

### ISSUE THREAD

**Issue by mrbhardy** [pdf-association/pdf-issues#133]
Section 14.8.4.7.2 defines the **Link** structure element type.  Table 368 provides the primary guidance on how to use the element, but in the paragraphs below Table 368 are additional restrictions and requirements for the children of **Link** structure elements.  These are fundamentally wrong, not only contradicting early specifications, but requiring setting requirements that make no sense in the context (and are impossible).

The specification provides the following text:

> The following items may be children of a link element:
> - One or more content items or other ILSEs (except other links) if **A**, **Dest** and **PA** keys of all of them have identical values
> - One object reference (see 14.7.5.3, "PDF objects as content items") to one link annotation associated with the content

Neither of the bullets describe correct requirements for the children of **Link** structure elements.

Addressing the issues for the first bullet:

> - One or more content items or other ILSEs (except other links) if **A**, **Dest** and **PA** keys of all of them have identical values

The **A**, **Dest** and **PA** are related to Link annotations, so cannot exist for content items or child ILSEs.  The equivalent from ISO 32000-1 stops at the end of the parenthetical, correctly having no opinion on these non-existent entries.

**Recommendation:** strike the text after the parenthetical, leaving the text to match ISO 32000-1:2008:
> One or more content items or other ILSEs (except other links)

Addressing the issues for the second bullet:
> - One object reference (see 14.7.5.3, "PDF objects as content items") to one link annotation associated with the content

If a link spans a page, the only mechanism to connect that spanning link is a parent **Link** structure element enclosing the content from both pages and both link annotations.  This has always been permissible and was part of the PDF standards ever since the introduction of links in structure.

** Recommendation:** Restore the original text from ISO 32000-1 and PDF 1.7:
> - Object references (see 14.7.5.3, “PDF Objects as Content Items”) to one or more link annotations associated with the content

Additionally, a lot of text was removed from ISO 32000-1 and PDF 1.7.  We would recommend the inclusion of that.

**Comment by petervwyatt** [comment]
@mrbhardy could you please label this issue as "proposed solution" or "question" (meaning still seeking opinions)?
I'm also not sure who "we would recommend..." is coming from? PDF/UA TWG? WTPDF TWG? Specific vendor?
Thanks!

**Comment by petervwyatt** [comment]
PDF TWG agrees to the specific recommendations above. The additional text from 32K-1 needs to be reviewed first.

**Comment by mrbhardy** [comment]
I would recommend moving all text after Table 368 to a new section 14.8.7.4.3, "Link elements".  Then dd directly at the end of that text:

When a Link structure element describes a span of text to be associated with a link annotation and that span wraps from the end of one line to the beginning of another, the Link structure element shall include a single object reference that associates the span with the associated link annotation. Further, the link annotation shall use the QuadPoint entry to denote the active areas on the page.

EXAMPLE 1 The Link structure element references a link annotation that includes a QuadPoint entry that boxes the strings “with a” and “link”. That is, the QuadPoint entry contains 16 numbers: the first 8 numbers describe a quadrilateral for “with a”, and the next 8 describe a quadrilateral for “link.”

         Here is some text with a link inside.

NOTE 2 Beginning with PDF 1.7, use of the Link structure element to enclose multiple link annotations is deprecated for annotations on the same page.

EXAMPLE 2 Consider the following fragment of HTML code, which produces a line of text containing a hypertext link:

```
<html>
    <body>
         <p>
             Here is some text <a href=http://www.adobe.com>with a link</a> inside.
    </body>
</html>
```

This code sample shows an equivalent fragment of PDF using a link element, whose text it displays in blue and underlined.

```
/P << /MCID 0 >>% Marked-content sequence 0 (paragraph)
BDC% Begin marked-content sequence
BT% Begin text object
/T1_0 1 Tf% Set text font and size
14 0 0 14 10.000 753.976 Tm% Set text matrix
0.0 0.0 0.0 rg% Set nonstroking colour to black
(Here is some text ) Tj% Show text preceding link
ET% End text object
EMC% End marked-content sequence
/Link << /MCID 1 >>% Marked-content sequence 1 (link)
BDC% Begin marked-content sequence
0.7 w% Set line width
[ ] 0 d % Solid dash pattern
111.094 751.8587 m% Move to beginning of underline
174.486 751.8587 l% Draw underline
0.0 0.0 1.0 RG % Set stroking colour to blue
S % Stroke underline
BT% Begin text object
14 0 0 14 111.094 753.976 Tm% Set text matrix
0.0 0.0 1.0 rg% Set nonstroking colour to blue
(with a link) Tj% Show text of link
ET% End text object
EMC% End marked-content sequence
/P << /MCID 2 >>% Marked-content sequence 2 (paragraph)
BDC% Begin marked-content sequence
BT% Begin text object
14 0 0 14 174.486 753.976 Tm% Set text matrix
0.0 0.0 0.0 rg% Set nonstroking colour to black
( inside.) Tj% Show text following link
ET% End text object
EMC% End marked-content sequence
```

EXAMPLE 3 This example shows an excerpt from the associated logical structure hierarchy.

```
501 0 obj% Structure element for paragraph
<< /Type /StructElem
/S /P
. . .
/K [ 0% Three children: marked-content sequence 0
502 0 R% Link
2% Marked-content sequence 2
]
>>
endobj
502 0 obj% Structure element for link
<< /Type /StructElem
/S /Link
. . .
/K [ 1% Two children: marked-content sequence 1
503 0 R% Object reference to link annotation
]
>>
endobj
503 0 obj% Object reference to link annotation
<< /Type /OBJR
/Obj 600 0 R% Link annotation (not shown)
>>
endobj
```

**Comment by petervwyatt** [comment]
PDF TWG also agree to restore heading and text as above.

**Comment by faceless2** [comment]
This is marked as completed but Matthew's suggestion in https://github.com/pdf-association/pdf-issues/issues/133#issuecomment-1012528360 does not appear to have been applied.

**Comment by petervwyatt** [comment]
@faceless2 Is it not here https://pdf-issues.pdfa.org/32000-2-2020/clause14.html#H14.8.4.7.3? 

Amd1 is currently cancelled due to ISO rules not supporting what PDF and industry require. There are plans to try and restart a far smaller Amd1 (since ISO rules require Amendments to be "small") supporting only the very small subset of errata determined to be necessary/required by PDF/UA-2, ISO/TS 32005 and the dated revisions of PDF/A-4 and PDF/X-6. That will next be discussed in May 2024.
