### ISSUE TITLE
Inconsistent description of /Lang entry in the catalog

### ISSUE THREAD

**Issue by t-merz** [pdf-association/pdf-issues#135]
ISO 32000-2, 14.9.2.1 describes the /Lang entry in the document catalog as "the document’s default language" which "applies to both content within content streams and any text string".

The main entry for /Lang in ISO 32000-2, Table 29 describes /Lang as "natural language for all text in the document except where overridden by language specifications for structure elements or marked-content. If this entry is absent, the language shall be considered unknown". This contradicts 14.9.2.1 on two accounts:

- In the absence of /Lang the language isn't necessarily unknown, it's just that no document-wide default is available.
- The exemption is too strict as it covers only structure elements and marked content, but not text strings, e.g. in bookmarks.

### Suggestion
Align the /Lang description in Table 29 to 14.9.2.1 by avoiding the incomplete "except..." repetition and the "unknown" clause:

> Lang
> (Optional; PDF 1.4) A language identifier that shall specify the default value of the natural language for all text in the document except where overridden by language specifications in any of several possible locations (see 14.9.2, "Natural language specification").

**Comment by petervwyatt** [comment]
Historic note: Table 29 Lang description is unchanged since it was first introduced in Adobe PDF 1.4.

**Comment by lrosenthol** [comment]
I'm confused.  Are we update the `Lang` entry in the Catalog or the `Lang` entry in structure elements?
