### ISSUE TITLE
Are Outline Item (Table 151) Prev/Next optional or prohibited when not required?

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#139]
"Table 151 — Entries in an outline item dictionary" states:

* for **Prev**: (_Required for all but the first item at each level_; ...
* for **Next**: (_Required for all but the last item at each level_; ...

It is arguably ambiguous if **Prev**/**Next** are prohibited or just optional for the first/last item at each level respectively. Here are some trivial test PDFs:

[OutlinesGood.pdf](https://github.com/pdf-association/pdf-issues/files/7798402/OutlinesGood.pdf)  - no **Prev**/**Next** key for first/last outline items. Works everywhere AFAICT.

[OutlinesBad.pdf](https://github.com/pdf-association/pdf-issues/files/7798404/OutlinesBad.pdf)  - "optional" **Prev**/**Next** keys for first/last outline items. Causes various popular implementations to lock-up/hang(!!) or display "Outline A" twice.

I would interpret the current wording as implying the keys are optional for the inverse of the required statement, as there is no explicit prohibition, but experimenting with various popular implementations causes them to lock up and hang, hence this is a question. I could also see nothing helpful in the prose of clause 12.3.3 Document outlines.

Wording can be improved by the addition of "_optional otherwise_" to the parenthetical.

**Comment by lrosenthol** [comment]
Prev/Next **shall not** be present on the first item of each level

**Comment by petervwyatt** [comment]
OK:

* for **Prev**: (_Required for all but the first item at each level; shall not be present on the first item at each level;_ ...
* for **Next**: (_Required for all but the last item at each level; shall not be present on the last item at each level;_...

**Comment by petervwyatt** [comment]
On reflection - and since there are PDFs in the wild with this case, maybe it should be "_shall be ignored on first/last_".

Realistically implementations will need to code against infinite cycles here and in lots of other places.

**Comment by petervwyatt** [comment]
PDF TWG would like this to be a file format requirement rather than a processor requirement.
Change to "shall not be present..."
PDF TWG agree to this.
