### ISSUE TITLE
Incorrect use of Bold

### ISSUE THREAD

**Issue by lrosenthol** [pdf-association/pdf-issues#14]
In 14.13.5, paragraph 3 it emboldens the phrase "Property List", which is not a formal key and therefore should not be bold.  

The simplest change is to make it italic and all lower case, which matches other uses of that phrase.

**Comment by petervwyatt** [comment]
Agreed.

Other formatting issues: 

- Table 147 Viewer Preferences, ViewArea, ViewClip, PrintArea and PrintClip keys - CropBox shouldn't be bold as it is not the key name, but a name value. They should be italic. I also note that for these cases there is not a definitive list of all the permitted CamelCase values - the references describe what they are, but don't enumerate the name values. Easiest solution is to to describe the list of values as matching the key names in Table 396 — Entries in a box colour information dictionary - or we can list them out fully in Table 147 for each key.

- Table 87 Image Dictionary, ImageMask description: the Mask key name in "... the Mask and ColorSpace shall not..." needs to be bold

**Comment by petervwyatt** [comment]
Proposed solution: all of the above
