### ISSUE TITLE
Not clear if D entry in GoTo actions can define a structure destination

### ISSUE THREAD

**Issue by bdoubrov** [pdf-association/pdf-issues#140]
Currently Table 202 in 12.6.4.2 Go-To actions defines **D** entry as:  

> The destination to jump to (see 12.3.2, "Destinations").

Section 12.3.2 specifies three ways to define destinations: 
- 12.3.2.2 Explicit destinations
- 12.3.2.3 Structure destinations
- 12.3.2.4 Named destinations

So, as it is written now, one may use a Structure destination as a value of **D** entry.

It looks like the original intention was to keep the definition of **D** entry fully compatible with PDF 1.7 and allow Structure destinations only as values of the newly introduced **SD** entry.  

One additional issue is that according to the same Table 202 the value of **SD** can only be of _array_ type, which does not permit the use of Named destinations here, which have type _name_ or _byte string_.  On the other hand, section 12.3.2.4 on Named destinations does provide the text on how to use Structure destinations via Named destinations. So, again, the current text permits **D** entry of the GoTo action to have Named destination wrapping a Structure element as its value. Was this really intended?

**Comment by bdoubrov** [comment]
I think the easiest fix would be to clarify that the value of the D entry in the Tables 202 and 203 shall be either an explicit destination (as described under 12.3.2.2 "Explicit destinations") or a named destinations (as described under 12.3.2.4 "Named destinations").

There is still a potential conflict if the named destination under /D entry defined a structure destination and at the same time (another) structure destination is defined by the SD entry. We may either prohibit this case or require that both structure destinations are identical in such situation. In fast, the current text says that the value of the SD entry should take precedence over D entry, if present. But this is "should", not "shall".

**Comment by petervwyatt** [comment]
Are you suggesting the "Should" should really be a "shall"?
I cannot see an issue for that...

**Comment by petervwyatt** [comment]
PDF TWG agree that the existing "should" is correct as there the statement that SD is strongly preferred by PDF processors which is intended. MH to draft an informative note to help implementers understand.

**Comment by mrbhardy** [comment]
I suggest the following fix.  In Table 202, row with entry "D", it reads:

> The destination to jump to (see 12.3.2, "Destinations").

It could be updated to read:

> The explicit destination or named destination to jump to (see 12.3.2, "Destinations").

**Comment by petervwyatt** [comment]
PDF TWG agree with Matthew's suggestion.
