### ISSUE TITLE
13.6.2 - rendering of hyperlink to 13.7 Rich media is corrupt

### ISSUE THREAD

**Issue by tballison** [pdf-association/pdf-issues#142]
**Describe the bug**
13.6.2

Rendering of the link is broken.  The rendered text is garbled and has an interleaved newline. 

`see 0 "\n\nRich  media" `should be something like `see "13.7 Rich media"`.

**Additional context**
I saw this behavior in both Adobe Reader DC and Foxit.
<img width="501" alt="Screen Shot 2022-01-20 at 9 47 28 AM" src="https://user-images.githubusercontent.com/6739646/150362330-e46bf6df-ad81-4957-ad63-8b609329cd29.png">

**Comment by petervwyatt** [comment]
Thank you! Purely a typo/formatting artifact so will fix soon without PDF TWG review.

**Comment by petervwyatt** [comment]
PDF TWG agree
