### ISSUE TITLE
Table 335 - default value of the View Entry. 

### ISSUE THREAD

**Issue by datalogics-pgallot** [pdf-association/pdf-issues#145]
The description is slightly mangled:
"Default value: The first element in the Views array of the annotation specified in the RichMediaContent dictionary."

The Annotation does not have a Views array, the RichMediaContent does, but it does not specify an Annotation.
So, I believe this sentence was intended to say:

"Default value: The first element in the Views array of the RichMediaContent dictionary specified in the annotation."

**Comment by petervwyatt** [comment]
PDF TWG agree
