### ISSUE TITLE
Clarification on xref sub-section line syntax (clause 7.5.4)

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#147]
In the case where an incremental update ONLY updates a direct trailer entry (e.g. `/ID`) what, if any, are the requirements for the object number in the xref sub-section line (that consists of just 2 integers)?
 * is `xref 0 0` valid or does the first 'object number' need to be strictly greater than zero (i.e. a valid PDF object number, and never the special "start of freelist" object zero)?
* Or is it a "don't care" because the second value is a zero and thus the supposed object number is not relevant? Would that mean `xref -1 0` is then acceptable?

The ISO TC 171 SC 2 WG 8 "Securing PDF" discussion group has discussed this and recommends that both the integers in all xref sub-section lines be specified as non-negative integers. The following changes (in bold) are proposed in clause 7.5.4 Cross-reference table:

> The subsection shall begin with a line containing only two **non-negative** integers separated by a SPACE (20h) and terminated by an end-of-line marker (see 7.2.3, "Character set").

- Delete the last sentence of NOTE 3: "_This also means that cross reference subsections of incremental updates can never have an object number of zero_.", since an incremental update that changes only the trailer dictionary can be like this with no objects added or freed.

**Comment by MatthiasValvekens** [comment]
Good catch on note 3... As a side note: the example in 7.5.8.4 contains an update section with `xref<LF>0 0` in it, which would contradict the note. There's no contradiction in the normative text, so it's not that big of a deal, but still.

**Comment by petervwyatt** [comment]
PDF TWG agree
