### ISSUE TITLE
Table 15 Trailer Size entry definition is described inaccurately/ambiguously

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#149]
Referring to Table 15 Trailer, `Size` entry: "_The total number of entries in the PDF file’s cross-reference table, as defined by the combination of the original section and all update sections. Equivalently, this value shall be 1 greater than the highest object number defined in the PDF file_.":

* the term _entry_ (as in "The total number of entries...") is the terminology used in clause 7.5.4 for each 20-byte line in cross reference tables. But because xref sub-section lines in incremental updates can start object numbering anywhere, there is no guarantee that the "_The total number of entries ..._" is the same as the highest object number.

Thus "_Equivalently_" is technically incorrect because these two sentences are not necessarily equivalent until things are more precisely defined:

* It would be nice to more formally define "_defined by the combination of the original section and all update sections_" and/or "_defined in the PDF file._" - so if the last _N_ objects in a PDF are in the free list does this count or not? What if they are just in the xrefs and there are no actual objects with those numbers in the body of the PDF (is that what makes them "defined in the PDF file"?

* It should be made clear whether the `Size` value needs to be: 
    - 1 bigger than all object numbers defined in any update, or 
    - 1 bigger than all object numbers in the final/combined xref table.

Note also from clause 7.5.4: "_The cross-reference table (comprising the original cross-reference section and all update sections) shall contain one entry for each object number from 0 to the maximum object number defined in the PDF file, even if one or more of the object numbers in this range do not actually occur in the PDF file._"

This was discussed in the ISO TC 171 SC 2 WG 8 "Securing PDF" discussion group where it was agreed that a clearer definition would be helpful as `Size` can be used for memory allocation by some processors, and it also influences when an object might be considered undefined (as per Table 15: "_Any object in a cross-reference section whose number is greater than this value shall be ignored and defined to be missing by a PDF reader._" and clause 7.3.10 statement: "_An indirect reference to an undefined object shall not be considered an error by a PDF processor; it shall be treated as a reference to the **null** object._")

So what is a more formal, accurate but nice and succinct definition for `Size`?

**Comment by MatthiasValvekens** [comment]
Leaving aside the broader question as to what it means to "define" an object for now, I would posit that `Size` needs to be 1 bigger than _any_ object number used in any update. That seems to be the least error-prone option (IMO), and it implies that `Size` can only go up as incremental updates are added (which is a nice sanity check).

**Comment by petervwyatt** [comment]
@MatthiasValvekens what is the formal definition you would state for "used in any update"? There is an object `_x y_ obj ... endobj`? There is an xref entry (20 byte line) which is either free or in-use? There is an xref sub-section that mentions the object number? (Yes, I'm being picky)

**Comment by MatthiasValvekens** [comment]
Good point. I'd consider any xref entry that refers to an object number as a "use". This would cover explicitly freed object IDs in addition to the "regular" `n` (plus variations used in xref streams---we really need a term of art to refer to whatever the opposite of "free" is!).

I don't think empty xref subsections should count.

**Comment by petervwyatt** [comment]
I believe the term of art is "in use" - from 7.5.4 "_There are two kinds of cross-reference entries: one for objects that are in use and another for objects that have been deleted and therefore are free._"

**Comment by MatthiasValvekens** [comment]
Right, then I think we can pin it down as follows:

The value of `Size` shall be one more than any object number in allocated in any preceding cross-reference section. An object number is considered allocated in a given cross-reference section if it appears in a cross-reference entry marking the object number as in use, or as free.

Some wordsmithing will undoubtedly be needed, but does that sound more or less workable?

**Comment by petervwyatt** [comment]
So do you agree with the `Size` in this highly synthetic PDF
[LargeSizePDF.pdf](https://github.com/pdf-association/pdf-issues/files/7965726/LargeSizePDF.pdf)
?

**Comment by MatthiasValvekens** [comment]
For the purposes of defining the `Size` value: I'd say 'yes'. That said, maybe we also need language to deal with skipped objects in incremental updates:

 - Either assume that all "skipped" object numbers are free.
 - Require object numbers to be allocated consecutively (where I'm using "allocate" in the sense defined in my previous comment).

Purely from a backwards compatibility PoV, the first option is probably the only viable choice we have, if we're going to add anything. It's probably also the closest to what processors already assume in the wild.

Thoughts?

**Comment by petervwyatt** [comment]
We need to also consider validators (as well as PDF writers) as `Size` influences which objects are valid or null so I think your option 1 is the only choice. So trying to reword:

> The value of **Size** shall be one more than the largest object number allocated within the current and all preceding cross-reference sections. All in-use and free object numbers are considered allocated.

**Comment by mkl-public** [comment]
In section 7.5.4 I read

>The cross-reference table (comprising the original cross-reference section and all update sections)
shall contain one entry for each object number from 0 to the maximum object number defined in the
PDF file, even if one or more of the object numbers in this range do not actually occur in the PDF file.

Thus, the cross references of LargeSizePDF.pdf are incorrect as there are gaps.

Also this allows an interpretation of the phrase from which this issue started

>The total number of entries in the PDF file’s cross-reference table, as defined by the combination of the original section and all update sections. Equivalently, this value shall be 1 greater than the highest object number defined in the PDF file.

that is correct: If you "combine" all sections by taking the newest entry for each object number, you have at most one entry for each object number; due to the requirement quoted at the top you at the same time do have at least one entry. Thus, exactly one entry for each object number up to the highest object number defined.

Nonetheless, such an entry should have a single definition, any equivalence might be stated in a note and not as an alternative definition. Thus, a bit of tinkering would indeed be appropriate.

**Comment by MatthiasValvekens** [comment]
Ah, I missed that sentence about the gaps. Good catch!

I guess the intended interpretation of "cross-reference table" was indeed the combined representation of all cross-references, taking into account all updated sections, as opposed to any "physical" table viewed strictly as a region in the file data. Perhaps we can do more to disambiguate those usages in the text.

**Comment by petervwyatt** [comment]
The issue is that the common colloquial use of "cross-reference table" doesn't match what the spec _actually_ says:

> The table comprises one or more cross-reference sections. Initially, the entire table consists of a single section (or two sections if the file is linearized; see Annex F, "Linearized PDF" and Annex G, "Linearized PDF access strategies"). One additional section shall be added each time the file is incrementally updated.

So the (singular!) _cross-reference table_ of a PDF file comprises multiple _sections_, which can have _sub-sections_. The common colloquial use of "cross reference table" often refers to data below the **xref** keyword and we should really be saying "cross-reference section"! 

Such important terms should be in the T&Ds.

Somewhat confusingly there are processor requirements stated in the 2nd sentence of the 1st para of 7.5.4: "_The table shall contain a one-line entry for each indirect object, specifying the byte offset of that object within the body of the PDF file._". I don't think this should be a processor requirement but more a statement about what the table comprises - i.e.:

> The table comprises an entry for each indirect object, specifying the byte offset of that object within the body of the PDF file.

So circling back to the original issue: I now think the wording in Table 15, **Size** entry is actually technically correct in light of these "official" terms that are not used, but rewording to make the testable/validatable condition that uses well-understood terminology the dominant statement and making the equivalence informative would be helpful :

> this value shall be 1 greater than the highest object number defined in the PDF file. 
NOTE 1: this is equivalent to the total number of entries in the PDF file’s cross-reference table, as defined by the combination of the original section and all update sections (see 7.5.4 "Cross-reference table").
...

**Comment by vasekp** [comment]
I think the line "Any object in a cross-reference section whose number is greater than this value shall be ignored and defined to be missing by a PDF reader." should read "greater *or equal to*".

**Comment by petervwyatt** [comment]
This is what Table 15 now states albeit using different words: https://pdf-issues.pdfa.org/32000-2-2020/clause07.html#Table15

**Comment by vasekp** [comment]
I don't understand, the line I'm quoting appears verbatim in the link and I'm suggesting it may be faulty in this wording.

The way I'm understanding the text is that if a cross-reference section appears to describe an object with number strictly greater than Size, like:
```pdf
xref
...
100 3
0011223344 00000 n
0011223355 00000 n
0011223366 00000 n
trailer
<< /Root 1 0 R /Size 101 >>
startxref
...
```
then such object is supposed to be a mistake and ignored, in this case the last line (102). But if Size is, by definition, meant to be strictly greater than the highest number of any object in existence, then `number == Size` (the line 0011223355 in this example) should be treated as an error as well. So I'm proposing:

"Any object in a cross-reference section whose number is greater than *or equal to* this value shall be ignored and defined to be missing by a PDF reader."

Or am I misunderstanding the intention behind this?
