### ISSUE TITLE
Table 315: "NA is meaningful only if NR is present" has no sense

### ISSUE THREAD

**Issue by bdoubrov** [pdf-association/pdf-issues#150]
Table 315, **NA** entry says: _meaningful only if NR is present_.

This is related to #6 where the term "meaningful" is considered in general. 

But in this particular case the whole phase "meaningful only if **NR** is present" should be removed, as **NR** entry has the default value _false_, even if it is not present. And the description of **NR** clearly specifies how to interpret **NA** entry for both **NR** being _true_ or _false_. So, **NA** always makes sense.

**Comment by petervwyatt** [comment]
PDF TWG agree
