### ISSUE TITLE
Address whether it is permissible to role map in the classic PDF 1.7 manner within the default standard structure namespace

### ISSUE THREAD

**Issue by mrbhardy** [pdf-association/pdf-issues#151]
**Describe the bug**

The issue is described here (https://github.com/pdf-association/WTPDF/issues/7) and this issue will be resolved in the PDF Reuse TWG and PDF/UA TWG, with this issue being updated with our resolution and details of the issue.

**Comment by faceless2** [comment]
```pdf
13 0 obj
<<
 /Type /StructTreeRoot
 /RoleMap << 
    /Foo /Bar
    /Bar /P
  >>
>>

14 0 obj
<<
  /Type /StructElem
  /S /Foo
  /P 16 0 R
>>
endobj
```
NOTE: In this example, the "Foo" element type is role-mapped transitively through "Bar" to a final element type of "P".

---
After rereading the proposed text above I think it's pretty clear, on reflection. But you can never have too many examples so hopefully that's useful.

**Comment by mrbhardy** [comment]
```
13 0 obj
<<
    /Type /StructTreeRoot
    /RoleMap <<                    % The "Global" role map is applied only to elements in an undefined namespace.
        /Foo /Bar                      % The element type "Foo" in an undefined namespace maps to "Bar".
        /Bar /P                          % The "Bar" element in an undefined namespace maps to P, which is defined in the
                                             % default standard structure namespace.  This means that elements of type "Foo" transitively
                                             % map to "P" through the "Bar" element type.
     >>
>>
endobj

14 0 obj
<<
    /Type /StructElem           % Structure Element with no defined namespace.
    /S /Foo                              % The "Foo" element has an undefined namespace and 
    /P 16 0 R                           % isn't defined in either the PDF 1.7 or PDF 2.0 namespaces.
>>
endobj
```

**Comment by mrbhardy** [comment]
The PDF TWG agrees to this change, but request precise wording, insertion points and example for inclusion in errata.  Matthew to provide...

**Comment by petervwyatt** [comment]
7 April 2022 PDF TWG - @mrbhardy to write up the precise errata fix and submit to Betsy prior to May ISO TC 171 SC 2 meetings so this can be discussed in the context of ISO 32005. If ISO agrees then those words will become the final solution for this errata

**Comment by petervwyatt** [comment]
Here is the doc from @mrbhardy that was submitted to WG8 and discussed recently:
[Errata relating to role mapping in Tagged PDF.pdf](https://github.com/pdf-association/pdf-issues/files/8704059/Errata.relating.to.role.mapping.in.Tagged.PDF.pdf)

**Comment by petervwyatt** [comment]
PDF TWG and ISO WG agree with the proposal
