### ISSUE TITLE
Consider changing several dictionary entry types from unnecessary `number` to `integer`

### ISSUE THREAD

**Issue by crlf0710** [pdf-association/pdf-issues#152]
**Describe the bug**

In `Table 120 — Entries common to all font descriptors`, consider changing entry `FontWeight`'s type from number to integer, since its only possible values are `100, 200, 300, 400, 500, 600, 700, 800, or 900`.

In `Table 257 — Entries in the DocMDP transform parameters dictionary`, consider changing entry `P`'s type from number to integer, since its only possible values are `1, 2, 3`.

In `Table 380 — Standard layout attributes specific to inline-level structure elements`, consider changing entry `GlyphOrientationVertical`'s type from `number or name` to `integer or name`, since all the `number` form's possible values are integers.

These will help pdf generators avoid using corresponding real form (`1.0`, `100.00` etc) accidentally.

**Additional context**

**Comment by petervwyatt** [comment]
There are a lot of legacy extant PDFs that have a `FontWeight` value that is NOT one of the pre-defined "multiples of 100" (typically they are a multiple of 50 so land in between 2 of the predefined values). AFAICT all PDF processors seem to handle this OK...

**Comment by petervwyatt** [comment]
@MatthiasValvekens - care to comment on DocMDP?
@mrbhardy - care to comment on `GlyphOrientationVertical`?

**Comment by MatthiasValvekens** [comment]
DocMDP is indeed always an integer, fractional values just wouldn't make any sense.

Incidentally, the provisions around `GlyphOrientationVertical` specify that numeric values shall be given as multiples of 90, which in particular means that they're always integral.

**Comment by MPBailey** [comment]
> There are a lot of legacy extant PDFs that have a `FontWeight` value that is NOT one of the pre-defined "multiples of 100" (typically they are a multiple of 50 so land in between 2 of the predefined values). AFAICT all PDF processors seem to handle this OK...

Is that something that we should recognise and enable with a change in Table 120?

**Comment by petervwyatt** [comment]
I would not be opposed to that since Font Weight is really a continuum, with keeping the current list as a set of recommended values.

**Comment by petervwyatt** [comment]
PDF TWG agree to change the 3 Tables to integer.
A new issue will be created to discussed FontWeight as a continuum / values other than 100s.
