### ISSUE TITLE
Need clarification on `Linearized` entry in Table F.1 

### ISSUE THREAD

**Issue by crlf0710** [pdf-association/pdf-issues#153]
**Describe the bug**
The spec says nothing much about the `Linearized` entry within `Table F.1`. It is the version identification for **the linearized format**(i think this refers to the whole `Annex F` description), but didn't clarify what may/shall be used here.

From the examples, it seems at least `1.0` is supported, and since the entry has type number, i guess `1` is supported as well. It would be nice if some clarifications be given here.

**Additional context**
The arlington pdf model has `[1.0]` as PossibleValues field value here.

**Comment by petervwyatt** [comment]
In a quick look over almost 1M diverse PDFs they all seem to have `1.0` or `1` so `number` is definitely the appropriate type.

The Adobe PDF 1.2 spec that introduced Linearization (see https://www.pdfa.org/resource/pdf-specification-index/) stated:
> Linearized format version identification. As usual, a change in the integer part indicates an incompatible change in the linearized format. A change in the fractional part indicates an upward-compatible change. The current version is 1.0.

but this information was lost in the conversion to ISO 32000-1:2008 AFAICT. Restoring these words would help!

**Comment by petervwyatt** [comment]
PDF TWG agree
