### ISSUE TITLE
Need clarification on the valid range of miter limit parameter

### ISSUE THREAD

**Issue by crlf0710** [pdf-association/pdf-issues#154]
**Describe the bug**
Currently the spec is not very clear about the valid range of the miter limit parameter. There's text "Parameters that are numeric values, such as the current color, line width, and miter limit, are forced into valid range" in PDFReference17, so i think this is kind of useful. I ran into this today, wondering what's the exact possible range, and whether zero is a valid miter limit value.

On the other hand, there's prior art that PostScript has defined its valid miter limit parameter range to "a number greater than or equal to 1"(`setmiterlimit` in PostScript language reference manual).

It would be nice if some clarificiation be give in the `8.4.3.5 Miter limit` chapter and/or `Table 57 — Entries in a graphics state parameter dictionary`.

**Additional context**

**Comment by petervwyatt** [comment]
Since PDF is based on PostScript then the PostScript definition seems appropriate as the proposed solution

**Comment by MPBailey** [comment]
I don't understand why the minimum value should be limited to 1. If "miter length / line width" exceeds the limit then the join will be painted with a bevel. If the two lines meet at a very sharp angle a bevel join will project only a very short distance beyond the line join. So setting a minimum value of 1 would appear to preclude some effects. If we really need to have a lower limit I'd suggest 0 instead. But even a negative number will still work on the calculations; it would just mean that a bevel join is always used.

At the other end of the scale, see the note in 8.4.3.5: "Very large miter lengths are allowed", which implies very large values of miter limit. And yes, we've seen files set to paint miters multiple metres long. They're a real pain, but ...

So the only change I'd recommend would be to take miter limit out of the 2nd bullet in 8.4.1.

**Comment by crlf0710** [comment]
@MPBailey AFAICT the formula is in 8.4.3.5:
(The ratio of miter length to line width) = (miterLimit / lineWidth) = 1 / sin(j/2)
where j is the angle between the segments. `j` is not meaningful if it's negative, and when j = 180 degree, the function value reaches its positive minimum value, which is 1.0.

**Comment by MPBailey** [comment]
My apologies Charles, you are correct. I had not revisited figure 15 and I had the miter length wrong. So yes, a minimum of 1 does make sense.

**Comment by MatthiasValvekens** [comment]
Yep, Charles is right. For those of us who prefer visuals: the graph nicely illustrates that the ratio explodes for small angles, but otherwise stays above 1: https://www.desmos.com/calculator/jylks9vrp3.

(I also rederived the formula in 8.4.3.5 to double-check. The trig checks out.)

**Comment by petervwyatt** [comment]
PDF TWG agree to copy the words from PS: "... a number greater than or equal to 1"
