### ISSUE TITLE
DigestMethod seed value makes too many assumptions on the signing algorithm

### ISSUE THREAD

**Issue by MatthiasValvekens** [pdf-association/pdf-issues#158]
**Describe the bug**

Table 237 (Entries in a digital signature seed value dictionary) contains the following text in the row defining the **DigestMethod** entry:

> This property is only applicable if the digital credential signing contains
> RSA public/private keys. If it contains DSA public/ private keys, the digest
> algorithm is always SHA-1 and this attribute shall be ignored.

ECDSA also allows the user to specify a digest, so **DigestMethod** should presumably also apply to ECDSA.  On the other hand, with EdDSA (for which we add support in ISO 32002) the choice of digest function is baked into the signing algorithm, which means that **DigestMethod** should not apply at all.

(EDIT: I'm of course making the tacit assumption here that we generally want the digest function used in the signing algorithm to be the same as the one used to digest the document.)

For the record, I also wasn't able to find any other language in the standard restricting the use of DSA to SHA-1. So at the very least, that provision isn't in the right place here. If anything, it should be somewhere in or around Table 260. Granted, the corresponding key size recommendations to make good use of anything "bigger" than SHA-256 with DSA get a bit ridiculous, but there's no real technical reason to stick to SHA-1.

Proposed solution:

Strike the cited portion of Table 237, and replace it with the following text:

> Some signature mechanisms require a specific digest function to be used. In such cases, the value of this entry shall be ignored.

If this change is agreed to, I'm happy to have the discussion on what to do with DSA in another issue. If we end up saying anything about digest algorithms for use with DSA in another subclause, we could of course still add a reference in Table 237.

**Comment by petervwyatt** [comment]
@lrosenthol to investigate

**Comment by lrosenthol** [comment]
In reviewing the proposal, we agree that it is the right one.  Thanks @MatthiasValvekens

**Comment by petervwyatt** [comment]
As per OP, here is the proposed solution: strike the cited portion of Table 237 **DigestMethod**, and replace it with the following text:

> Some signature mechanisms require a specific digest function to be used. In such cases, the value of this entry shall be ignored.

**Comment by petervwyatt** [comment]
PDF TWG agree to the above change
