### ISSUE TITLE
Are Crypt filter Recipient strings always byte strings?

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#16]
"Table 27 — Additional crypt filter dictionary entries for public-key security handlers" **Recipients** key is described as being of type "string or array". 

The array case is then clearly defined to be a byte string: "If the crypt filter is referenced from StmF or StrF in the encryption dictionary, this entry shall be an array of byte strings, where each string shall be a binary-encoded CMS object that shall ...".
An improvement would be to change "where each string ..." to "where each **byte** string ..."

However for the string case, it just says "... this entry shall be a string that shall be a binary-encoded CMS object that shall contain a list of all recipients ..."

Question: is this also required to be a byte string or is just string OK?

**Comment by lrosenthol** [comment]
Recommend that it should be byte string to match

**Comment by petervwyatt** [comment]
Proposed solutions:

1. "If the crypt filter is referenced from **StmF** or **StrF** in the encryption dictionary, this entry shall be an array of byte strings, where each _byte_ string shall be a binary-encoded CMS object that shall ..."
2. change the Type column to say "_byte_ string or array"
3. "... this entry shall be a _byte_ string that shall be a binary-encoded CMS object that shall contain a list of all recipients ..."
