### ISSUE TITLE
Incorrect character identification in 7.9.2.2.1

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#161]
Note 4 in 7.9.2.2.1 says 

> This mechanism precludes beginning a string using PDFDocEncoding with the three characters **dieresis**, guillemotright, questiondown, which is unlikely to be a meaningful beginning of a word or phrase.

But 238 decimal, 0xEF, octal 357 in PDFDocEncoding is idieresis, not dieresis.

**Comment by petervwyatt** [comment]
Probably an MSWord auto-correct!

**Comment by petervwyatt** [comment]
PDF TWG
