### ISSUE TITLE
Are RichMediaSettings dictionaries mandated to be "unique to each annotation" (clause 13.7.2.1)?

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#163]
Clause 13.7.2.1 RichMedia annotations / General, paragraph 1 makes this factual statement:

> The _RichMediaSettings dictionary_ is unique to each annotation, while the _RichMediaContent dictionary_ can be shared across rich-media annotations.

Table 333 "Additional entries specific to a RichMedia annotation" **RichMediaSettings** has no stated requirements regarding uniqueness.

AFAICT there is also nothing technical (like a required indirect reference to something) that makes this a necessary requirement.

So is this a statement an actual enforceable "shall" requirement or purely descriptive/informative (e.g. "Typically ...")?
I believe it is the latter.

**Comment by datalogics-pgallot** [comment]
I think I would substitute the word "specific" for "unique".

**Comment by petervwyatt** [comment]
I would say it is "usually specific" as there is nothing that forces it to be specific that I can see. It is entirely possible that a  RichMediaSettings dict is shared between multiple RichMedia annots (e.g. if they all shared the same Activation / Deactivation Condition behaviours).

**Comment by lrosenthol** [comment]
I believe that it should be a *shall* based on the situation that settings can be changed during execution and if the implementation is using the actual object (instead of an in-memory structure) it would have impact on all other 3D objects.

**Comment by petervwyatt** [comment]
Based on @lrosenthol feedback, will look at all necessary wording changes to make everything a "shall".

**Comment by petervwyatt** [comment]
Clause 13.7.2.1 RichMedia annotations / General, reword paragraph 1 as follows:
> The _RichMediaSettings dictionary_, **if present, shall be unique to each annotation,** while the _RichMediaContent dictionary_ can be shared across rich-media annotations.

Modify Table 333 — Additional entries specific to a RichMedia annotation, RichMediaSettings:
> (_Optional; PDF 2.0_) A RichMediaSettings dictionary that **shall be unique to each annotation and** stores conditions and responses that determine when the annotation should be activated and deactivated by an interactive PDF processor and the initial state of artwork in those states. See "Table 334 — Entries in a RichMediaSettings dictionary".
- Additional question: is the above statement in Table 333 really a "should" or a "shall"?

Clause 13.7.2.2.1 RichMediaSettings dictionary / General, reword paragraph 1 as follows:
> The _RichMediaSettings dictionary_ has a purpose similar to that of the 3D activation dictionary ("Table 310 — Entries in a 3D activation dictionary") with the 3D Annotation described in 13.6.2, "3D Annotations". The RichMediaSettings dictionary stores the conditions and responses that occur in response to certain events, such as activation and deactivation of the annotation, and contains two dictionaries. **It shall be unique to each annotation**. "Table 334 — Entries in a RichMediaSettings dictionary" gives the details of the content of this dictionary.

**Comment by petervwyatt** [comment]
PDF TWG agree to above corrections

**Comment by petervwyatt** [comment]
In answer to the additional question in Table 333 - keep as a "should" because this is a processor requirement and processors may want to prevent triggering actions without the user's explicit consent.
