### ISSUE TITLE
Misleading text in 9.4.3 Text showing operators

### ISSUE THREAD

**Issue by dbuenzli** [pdf-association/pdf-issues#165]
In section *9.4.3 Text showing operators* we can read about the string argument (bold emphasis is mine)

> The strings shall conform to the syntax for string objects. When a string is written by enclosing the data in parentheses, bytes whose values are equal to those of the ASCII characters LEFT PARENTHESIS (28h), RIGHT PARENTHESIS (29h), and REVERSE SOLIDUS (5Ch) (backslash) shall be preceded by a REVERSE SOLIDUS character. **All other byte values between 0 and 255 may be used in a string object**. These rules apply to each individual byte in a string object, whether the string is interpreted by the text-showing operators as single-byte or multiple-byte character codes.

While this is true it is very misleading because in *7.3.4.2 String Literals* we can read (bold emphasis is mine) 

> An end-of-line marker appearing within a literal string without a preceding REVERSE SOLIDUS **shall be treated as a byte value of (0Ah)**, irrespective of whether the end-of-line marker was a CARRIAGE RETURN (0Dh), a LINE FEED (0Ah), or both.

This effectively mean that an `0Dh` byte value in the argument of a text showing operator will be interpreted as `0Ah` byte which is unlikely to be what you want :–) 

I suggest changing the text of 9.4.3 to mandate backslash escaping of `CARRIAGE RETURN (0Dh)` aswell.

**Comment by petervwyatt** [comment]
PDF TWG agree

**Comment by dbuenzli** [comment]
Thanks !
