### ISSUE TITLE
Inconsistences in the data model of the RichMedia annotation

### ISSUE THREAD

**Issue by bdoubrov** [pdf-association/pdf-issues#166]
This bug lists a number of inconsistencies on the optional / required state of some of the objects within the **RichMedia** annotation, as well as the minimal array lengths for some of the cases.

If needed, I can split these issues into individual GitHub issues. I also attach a diagram visualizing the relationship between various object types used within RichMedia annotations: [RichMedia annotation.pdf](https://github.com/pdf-association/pdf-issues/files/8285843/RichMedia.annotation.pdf)

1.  **Assets** entry in the **RichMediaContent** dictionary (Table 341) is currently optional. But it is difficult to imagine a **RichMedia** annotation without a single asset. Having no assets makes also problematic the definition of **RichMediaInstance** type (Table 343), which has **Asset** as a required entry pointing to one of the **RichMedia** assets.

Suggestion: change optional to required.

2. **RichMediaActivation** and **RichMediaDeactivation** entries in the Rich Media Settings dictionary are both optional, with no defualt value specified. On the other hand, both **RichMediaActivation** dictionary (Table 335) and **RichMediaDeactivation** dictionary (Table 336) have all entries optional with well-defined default values. It should also be noted that both **RichMediaActivation** and **RichMediaDeactivation** entries are important for the consistent behavior of RichMedia annotations across different implementations, as they specify when exactly the Rich Media should be activated / deactivated (e.g, upon an explicit user action such as mouse click or when the page with this RichMedia becomes visible). 

Suggestion: define default values for both  **RichMediaActivation** and **RichMediaDeactivation** entries as empty dictionaries except for the correctly specified Type value.

3. Same as above for **Animation** and **Presentation** entries  in the  **RichMediaActivation** dictionary (Table 335). Both **RichMediaAnimation** dictionary (Table 337) and **RichMediaPresentation** dictionary (Table 338) have all entries marked as optional and all having well-defined default values.

Suggestion: define default values for both  **Animation** and **Presentation** entries as empty dictionaries except for the correctly specified Type value.

4. **Configuration** entry in the **RichMediaActivation** dictionary (Table 335) specifies its default value as the first element in the **Configurations** array of the **RichMediaContent** dictionary (Table 341). But this entry is marked as optional in Table 341. So, it is not clear how the processor should behave if there is no **Configurations** entry in the  **RichMediaContent** dictionary or if it is present, but is an empty array.

Suggestion: make **Configurations** entry in the  **RichMediaContent** dictionary required and non-empty.

Alternatively, one can define a default configuration for the **RichMedia** annotation as an array of Instances wrapping all assets (=embedded files with 3D, Sound or Video content) within a given **RichMedia** annotation. But this probably needs to be double checked with the existing implementations.

**Comment by petervwyatt** [comment]
There is a RichMedia TWG today chaired by @datalogics-pgallot - are you able to join to discuss?

**Comment by petervwyatt** [comment]
And noting that there is a similar diagram (mindmap) in https://github.com/pdf-association/PDF-RichMedia-Annotations

**Comment by petervwyatt** [comment]
This issue was discussed during the RichMedia TWG on 18 March:

For (1): this has already been resolved by #58 and is published at https://pdf-issues.pdfa.org/32000-2-2020/clause13.html#Table343. No further fixes are necessary.

For (2) and (3): there was agreement that additional wording is required stating that when certain entries are not present that the defaults as specified in other tables applied. Precise wording and location for new wording is TBD.

For (4): further investigation by vendors is needed before a decision is made. This will be discussed in the next PDF TWG and RichMedia TWG meetings.

**Comment by petervwyatt** [comment]
Proposed wording for resolving (2) and (3) in Table 334 for **Activation** (and **Deactivation** appropriately tweaked):
> Default value: a RichMediaActivation dictionary containing all default entries as defined in "Table 335 - Entries in a RichMediaActivation dictionary".

**Comment by petervwyatt** [comment]
PDF TWG agree:
Table 341 **Configurations** (array) is required and non-empty.
Table 335 **Configuration** (dict) is optional with default value so there is always a sensible value known - no change required here.
