### ISSUE TITLE
Separations All and None are exempt from ColorSpace requirements?

### ISSUE THREAD

**Issue by bdoubrov** [pdf-association/pdf-issues#168]
This is the mirror of the issue https://github.com/pdf-association/pdfa-twg/issues/7 discussed and resolved at the PDF/A TWG.

The question is: are the **All** and **None** separations exempt from the requirements that their ColorSpace/Transforms should be consistent throughout the document (as specified in ISO 19005-4, 6.2.4.4);

> All **Separation** arrays within a single conforming PDF/A-4 file (including those in **Colorants**
dictionaries) that have the same name shall have the same _tintTransform_ and _alternateSpace_. In
evaluating equivalence, the PDF objects shall be compared, rather than the computational result of the
use of those PDF objects. Compression and whether or not an object is direct or indirect shall be ignored.

I believe they are, and the justification for this is this paragraph from ISO32000-2 (clause 8.6.6.4, the text below NOTE 6)

> A PDF reader shall support Separation colour spaces with the colourant names **All** and **None** on all
devices, even if the devices are not capable of supporting any others. When processing Separation
spaces with either of these colourant names PDF readers shall ignore the _alternateSpace_ and
_tintTransform_ parameters (discussed below), although valid values shall still be provided.

The proposed resolution: add a NOTE 4 right after NOTE 3 in 6.2.4.4 saying that **All** and **None** Separation names are not subject to the above requirement on _tintTransform_ and _alternateSpace_.

**Comment by petervwyatt** [comment]
PDF/X-6 also has identical wording in subclause 6.6.3.4, but the existing PDF/A-4 NOTE 3 is NOTE 1 with a slightly extended explanation. So the addition of the new note in PDF/X-6 will be the exact same NOTE 2 as PDF/A-4, added below NOTE 1.

**Comment by lrosenthol** [comment]
The recommendation is incorrect, based on an incorrect belief.  None and All *DO* have to comply to the tintTransform and altSpace rules.

**Comment by petervwyatt** [comment]
As reported during PDF TWG, this wording was originally from PDF/X-4(?) and is intended to support color repurposing. It is intentional in print-centric workflows.

This PDF issue will be closed and the PDF/A issue can be reopened for further discussion in PDF/A.
