### ISSUE TITLE
Lack of clarity in BS entry for link annotations

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#17]
In Table 176 the BS entry specifies "the line width and dash pattern that shall be used in drawing the annotation’s border". It's pretty obvious what that means when only Rect is present. But what does it mean if QuadPoints is in use? Should the outline of every rectangle be painted?

**Comment by lrosenthol** [comment]
I would actually go further to say that the bigger picture here is that the algorithm for generation of an annotation's appearance is undocumented/implementation specific.  There is guidance given in some cases, such as this example, but many of the keys are not (fully) specified as to how to use them.  This is especially true for anything related to text & fonts.

Whether we wish to attempt to tackle this holistically is worthy of some discussion...

**Comment by petervwyatt** [comment]
"Table 176 — Additional entries specific to a link annotation" clearly states that **QuadPoints** is only about _activation_, not _appearance_: "An array of 8×𝑛 numbers specifying the coordinates of n quadrilaterals in default user space that comprise the region in which the link should be activated" and "If this entry is not present, or the PDF processor does not recognise it, or if any coordinates in the **QuadPoints** array lie outside the region specified by **Rect** then the activation region for the link annotation shall be defined by its **Rect** entry."

Furthermore below "Table 166 — Entries common to all annotation dictionaries" is the normative statement:
"A PDF reader shall render the appearance dictionary without regard to any other keys and values in the annotation dictionary and shall ignore the values of the **C, IC, Border, BS, BE, BM, CA, ca, H, DA, Q, DS, LE, LL, LLE,** and **Sy** keys."

Considering also the description of **Border** in Table 166, it's clearly the definition of a visual appearance of a rounded rectangle that's included in the appearance stream whereas **QuadPoints** in Table 176 is about activation areas. 

So a key question from all this: is the annotation border the same as the link activation area?  
Definitely not when **QuadPoints** is used. But if **QuadPoints** is not present, then **Rect** gets used instead and the answer just so happens to be yes. But I think that is just coincidental...
 
I thus think there is an unstated assumption in your question that **QuadPoints** relates to the visual appearance. I don't believe that's correct as it clearly states activation multiple times. And, yes, that makes it very difficult to regenerate appearance streams (especially if the activation area is desired to have a visible stroked outline as the activation path will not be the same as the centre path of the stroke by half the stroke width!).

**Comment by lrosenthol** [comment]
And let's not forget that we have the "NonRectangular Links" document in review that will now add `Path` - though that is only valid on a Link annotation (which can have an AP).

**Comment by petervwyatt** [comment]
Without attempting to solve the very large issue of appearance stream regeneration, but trying to address @MPBailey's original question...

Proposed solution: add the following note (informative, stated as factual) to both the **QuadPoints** and **Border** cells in Table 176:

Note: When **QuadPoints** is used, the activation area and the visual appearance (including border) of the link annotation are not required to be the same. This is because **Border** always uses the annotation **Rect** entry.

**Comment by petervwyatt** [comment]
PDF TWG - concern that Border description in Note is not aligned with wording in Table 166.
Pending

**Comment by petervwyatt** [comment]
Further research about the definition of annotation borders: clause 12.5.4 Border styles only says "_An annotation may optionally be surrounded by a border when displayed or printed. If present, the border shall be drawn completely inside the annotation rectangle_". This definition also supports the additional behaviour described in Tables 177 and 180 which can use a different rectangle for drawing borders (the **RD** key).

Easiest solution is to remove the offending sentence from the proposed note:

Note: When **QuadPoints** is used, the activation area and the visual appearance (including border) of the link annotation are not required to be the same.

**Comment by petervwyatt** [comment]
Approved by PDF TWG.
