### ISSUE TITLE
Radio button form field appearance name for the off state 

### ISSUE THREAD

**Issue by Lonzak** [pdf-association/pdf-issues#170]
For a check boxes the standard defines the following:

> The appearance for the off state is optional but, if present, shall be stored in the appearance dictionary under the name Off.

But for radio buttons this sentence is missing which could indicate that other names for the `Off` state are possible. 

There is a mentioning of the `Off` state in the context of the radio button  `V` dictionary:

> The parent field’s V entry holds a name object corresponding to the appearance state of whichever child field is currently in the on state; the default value for this entry is Off.

But still I would like to suggest that this is clarified by adding the same sentence from the check box also to the radio button chapter ...

**Comment by lrosenthol** [comment]
No objection to proposed addition/clarification

**Comment by petervwyatt** [comment]
PDF TWG to make both places the same
