### ISSUE TITLE
Table 246 unclear what is deprecated with EmbeddedFDFs / possibly inconsistent with other deprecated keys in PDF 2.0

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#173]
Table 246 **EmbeddedFDFs** text is inconsistent with all other deprecated keys in PDF 2.0 - although mentioned as deprecated in the para below Table 246, not everyone reads or notices such text 😁

Need to add "(_Optional; PDF 1.4; Deprecated in PDF 2.0_)" at the start of the description cell in Table 246. Minor.

**Comment by MatthiasValvekens** [comment]
The paragraph below Table 246 is somewhat confusingly worded IMO:

> Although deprecated in PDF 2.0, embedded FDF files specified in the FDF dictionary’s EmbeddedFDFs entry may be encrypted. Besides the usual entries for an embedded file stream, the stream dictionary.

One could read that as saying that _encryption_ of embedded FDF files is deprecated. That would be consistent with the bullet list of deprecated features in 0.3.
Then again, I'm not sure what the point of nesting FDF files would be if encryption is off the table. Compression, maybe?

I guess what I'm saying is that regardless of which it is, that paragraph needs to be clarified as well :)

**Comment by petervwyatt** [comment]
Ahh! Different reading == different understand / good point!
Will remove "proposed solution" label and see if someone can clarify what precisely is deprecated!

**Comment by lrosenthol** [comment]
I have **no** recollection of why we deprecated that feature.  And I can't see a reason to do so.

FYI: The feature was added in PDF 1.4/Acrobat 5 as a backwards compatible way to support having multiple FDF files contained in a single `.fdf`.   This was used by services that served back FDFs to browser-embedded viewers (aka Acrobat/Reader's browser plugin) to provide customers will filled in PDFs w/o having to have a server-side PDF processing component.

**Comment by MatthiasValvekens** [comment]
Thanks! I see. I think that historical context supports my reading of the clause. FDF encryption is deprecated, but nested FDFs aren't. In other words, the paragraph below Table 246 is confusing and needs rewording.

How about replacing this sentence

> Although deprecated in PDF 2.0, embedded FDF files specified in the FDF dictionary’s EmbeddedFDFs entry may be encrypted. 

with 

> Although FDF file encryption is deprecated in PDF 2.0, embedded FDF files specified in the FDF dictionary’s EmbeddedFDFs entry may be encrypted.

Thoughts?

**Comment by lrosenthol** [comment]
I am fine with @MatthiasValvekens 's suggestion above

**Comment by petervwyatt** [comment]
PDF TWG to suggestion from Matthias
