### ISSUE TITLE
Clarification concerning internal fields in ResetForm actions

### ISSUE THREAD

**Issue by sebras** [pdf-association/pdf-issues#174]
In Table 242 — Flag for reset-form actions, the meaning of the
Include/Exclude flag for internal fields is not evident (emphasis is mine):

> **If clear**, the Fields array (see "Table 241 — Additional
> entries specific to a reset-form action") specifies which fields
> to reset. (_All descendants of the specified fields in the field
> hierarchy are reset as well._) **If set**, the Fields array indicates
> which fields to exclude from resetting; that is, all fields in the
> document’s interactive form shall be reset except those listed
> in the Fields array. 

For internal fields it is obvious that when the flag is clear the
parenthesized text applies and all descendant fields will be reset.

But if the flag is **set**, despite the phrase after the semicolon,
it is not obvious what happens to descendant fields. My own
interpretation is that, symmetrically, all descendant fields will
also be exempt from being reset. If PDF TWG agrees, may I
suggest an additional clarification:

> If clear, the Fields array (see "Table 241 — Additional
> entries specific to a reset-form action") specifies which fields
> to reset. (All descendants of the specified fields in the field
> hierarchy are reset as well.) If set, the Fields array indicates
> which fields to exclude from resetting; that is, all fields in the
> document’s interactive form shall be reset except those listed
> in the Fields array. **_(All descendants of the specified fields
> in the field hierarchy are also exempt from being reset.)_**

---

In the unlikely event that PDF TWG does not agree with me, I
would _still_ like to see an addition clarifying the case of
internal fields, perhaps something like this:

> If set, the Fields array indicates which fields to exclude from
> resetting; that is, all fields in the document’s interactive form
> shall be reset except those listed in the Fields array.
> **_(If the flag is set, only terminal fields may be specified in the
> Fields array and those will be exempt from being reset. Any
> internal fields are ignored and their descendants will still be reset.)_**

**Comment by petervwyatt** [comment]
I would agree that clarifying, either way, is for the benefit of everyone. Thanks for your contribution!

**Comment by petervwyatt** [comment]
PDF TWG agree with the exempt solution as being the correct resolution.
