### ISSUE TITLE
Unclear how to set fill color of line ending for free text annotations with callout

### ISSUE THREAD

**Issue by sebras** [pdf-association/pdf-issues#177]
There is a problem in how to draw line endings for free text annotations.

First consider Table 179 - Line ending styles
 * It shows example appearances of line ending types, e.g. Square.
 * Some types use the interior colour to fill an enclosed area, if the interior colour is present.

If the interiour color is not present, the line endings should not be filled in.
Currently this behaviour is implied, but not explicitly stated (which would be better).

This applies to line annotations in Table 178 - Additional entries specific to a line annotation:
 * LE is used to specify the line ending type for the annotations.
 * IC specifies the interior color that applies to the line endings.

It is unclear how it applies to free text annotations in Table 177 - Additional entries specific to a free text annotation
 * Assume that IT is FreeTextCallout and that CL has an array of six numbers.
 * Assume further more that LE has the value Square.
 * There is no IC key specifying the interior color of the line ending.
 * This implies that the interior color of the line ending can not be set.

Does this mean that the line endings of callouts will never be filled?

Figure 79 shows a yellow freetext box with a callout with an OpenArrow line ending.
How would this be rendered if the line ending was Square?

My expectation is that free text annotations work similar to square 
annotations in that C is used to specify the border color and that 
IC is used to specify the interior colour of both the box itself, 
and (in the case of free text annotations also) the line ending fill color.
Thus I propose the following addition to Table 177 (similar to the IC key in Table 178):

| Key  | Type | Value |
| ------------- | ------------- | ------------- |
| **IC**  | array  | (Optional; meaningful only if CL is present; PDF 1.6) An array of numbers in the range 0.0 to 1.0 specifying the interior colour that shall be used to fill both the annotation’s rectangle and line ending (see "Table 179 — Line ending styles"). The number of array elements shall determine the colour space in which the colour is defined: 0 — No colour; transparent, 1 — DeviceGray, 3 — DeviceRGB, 4 — DeviceCMYK 

For reference, if I render a similar example in Adobe Acrobat Reader it uses
the color given in C (see Table 166) to fill in both the box itself and the
line ending (any specified IC is ignored). This contradicts interior colour 
being used for filling line endings in Table 179.

**Comment by petervwyatt** [comment]
Thank you for your contribution - could you attach the sample PDF please?

**Comment by sebras** [comment]
Sure, here is my example: [works.pdf](https://github.com/pdf-association/pdf-issues/files/8578748/works.pdf)

In this file I believe that object 5 specifies that **IC** is a blue color, **C** a bright green, **DA** a red fill color and a purple stroke color and finally **DS** some kind of orange for styling.

From this I expect the freetext annotation rectangle to be filled with blue, its border be bright green, and the callout line would be equally bright green and have a square line end filled with blue.

That is not what I'm seeing in Acrobat Reader. If the specification was clear and this was any old reader I would wager that it is a simple PDF-viewer specific bug and I would not report it here. But the specification _is_ less than clear and Acrobat Reader's implementation decision weigh more than most other viewers.

Perhaps there is also a question about the precedence of  the colors specified in **IC** and **C** versus the operators in **DA** and **DS**.

**Comment by MPBailey** [comment]
I can see why you’re asking the question, but I’m afraid that this is not the right place to ask it. This repository is specifically for errata in ISO 32000-2 (PDF 2.0) and its subset standards. 

Under 32000-2 your sample is invalid because the annotation is of Subtype FreeText and the Rect array has not got zero-sized dimensions. That means that AP (an appearance stream) is required and it’s not present.

So a reader processing the file as if it were PDF 2.0 is effectively free to do whatever it thinks is appropriate because it’s a non-conforming file. Acrobat has a tendency to not report errors because that would often not be a good fit for its business case.

But it would be more appropriate to treat this file as PDF 1.7, given that it claims to be 1.7.

Going back to the latest PDF 1.7 (ISO 32000-1), AP is optional. But a FreeText annotation can only use the keys listed in Table 164 (entries common to all annotation dictionaries) and table 174 (additional entries applicable to a free text annotation). IC is not present in either location. I agree that this is bizarre, when LE _is_ present, and this would be a good catch for an errata if we were developing errata for PDF 1.7.

**Comment by sebras** [comment]
> I can see why you’re asking the question, but I’m afraid that this is not the right place to ask it. This repository is specifically for errata in ISO 32000-2 (PDF 2.0) and its subset standards.

I know, I have contributed errata before. I wrote this becuase I think there might be an omission/inconsistentcy/errata in ISO 32000-2.

> Under 32000-2 your sample is invalid because the annotation is of Subtype FreeText and the Rect array has not got zero-sized dimensions. That means that AP (an appearance stream) is required and it’s not present.

I was unware of this AP difference between ISO 32000-1 and -2. I agree with you that my sample does not conform to -2 and thus that the renderer is free to do whatever it thinks is reasonable with this particular file.

Please remember that my original issue wasn't really with this sample file in a particular renderer, but rather the inconsistency between the descriptions of LE and IC.

> Going back to the latest PDF 1.7 (ISO 32000-1), AP is optional. But a FreeText annotation can only use the keys listed in Table 164 (entries common to all annotation dictionaries) and table 174 (additional entries applicable to a free text annotation). IC is not present in either location. I agree that this is bizarre, when LE _is_ present, and this would be a good catch for an errata if we were developing errata for PDF 1.7.

So you are saying that IC missing from Table 174 was an issue in PDF 1.7 (ISO 32000-1) because an AP is not required in Table 164, while in PDF 2.0 (ISO 32000-2) since and AP is required in Table 166, then IC being missing from Table 177 is not an issue?

For a static PDF renderer, I can see how simply depending on AP for the FreeText annotation appearance allows the document to be accurately rendered. For a program that allows editing of PDF annotations I still think IC missing from Table 177 in ISO 32000-2 is a problem because it is difficult to know what the interior color of the line ending is (even if present in AP) and so cannot be easily adjusted causing a new AP to be generated and saved into a new PDF file.

**Comment by lrosenthol** [comment]
Generation of Annotation Appearances from the values present in the annotation has been determined to be "out of scope" for ISO 32000.  That is one of the reasons why appearances are now required in 32K-2.

An editor may choose to use those values - or any other pieces of information - as it sees fit to create new appearances.

**Comment by sebras** [comment]
> Generation of Annotation Appearances from the values present in the annotation has been determined to be "out of scope" for ISO 32000. That is one of the reasons why appearances are now required in 32K-2.

Aha, then I can see that the *IC* key and the others are more or less deprecated and there is not incentive to do anything about them.

Thank you for everyone patiently explaining the situation to me. I appreciate it. :)
