### ISSUE TITLE
Font Descriptor FontWeight should reflect extant data not using the set of predefined integer values

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#178]
See also Issue #152 Consider changing several dictionary entry types from unnecessary number to integer.

Table 120 — Entries common to all font descriptors: there are a lot of legacy extant PDFs that have a **FontWeight** value that is NOT one of the pre-defined "multiples of 100" (typically they are a multiple of 50 so land in between 2 of the predefined values). AFAICT all PDF processors seem to handle this OK.

Proposal is to permit any integer value between 100 and 900 (the current lower and upper bounds), with a recommendation for multiples of 100 (i.e. as per the existing spec).

**Comment by crlf0710** [comment]
If changing this, i think aligning to Opentype standard would be better. In ISO 14496-22:2019, 5.2.8.3 usWeightClass, the wording is this:
```text
Format: uint16
Title: Weight class.
Description: Indicates the visual weight (degree of blackness or thickness of strokes) of the characters in the
font. Values from 1 to 1000 are valid.
```
So i think integer value from 1 to 1000 will work better here.

**Comment by petervwyatt** [comment]
PDF TWG agree not to make any changes as the PDF spec aligns with CSS. Will mark this issue as Parked for future. Will add informative note re CSS.
