### ISSUE TITLE
Clarify ColorSpace for 3D Data Streams

### ISSUE THREAD

**Issue by lrosenthol** [pdf-association/pdf-issues#18]
Table 311, entry **ColorSpace**
> The RGB colour space in which the 3D artwork’s colour values are encoded. Valid values are the name DeviceRGB, an array specifying a valid CalRGB color space (see 8.6.5.3 "CalRGB colour spaces"), or an array specifying a valid RGB-based ICCBased color space (see 8.6.5.5 "ICCBased colour spaces"). If this key is not present, the colour space for the 3D artwork colour values are considered undefined and a PDF processor may choose any appropriate RGB-based colour space, such as sRGB.

It is not clear from other parts of the text whether a **DefaultRGB** present on the page where the Annotation referencing the stream is used, should be used "in place" of the _DeviceRGB_ (as would be the case for other uses of _DeviceRGB_).  I believe that it should.

**Comment by petervwyatt** [comment]
Proposed solution: add a new 2nd sentence:

If the name is **DeviceRGB** and the page where the annotation referencing the 3D stream is used has a **DefaultRGB** color space, then the **DefaultRGB** color space shall be used (see 8.6.5.6 Default colour spaces).

**Comment by petervwyatt** [comment]
PDF TWG also identified typo "If this key is not present, the colour space for the 3D artwork colour values are considered undefined..." --> "... is considered..."

**Comment by lrosenthol** [comment]
This is also related to #34
