### ISSUE TITLE
Recommendations or informative notes on using Extensions Dictionaries?

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#183]
With the move to need/use Extensions Dictionaries more widely (and thus also Developer Extension Dictionaries) with all the various new ISO TS documents, should we make recommendations about certain objects being indirect references so that incremental updates can more easily "patch" and maintain these objects? (e.g. when an incremental update adds or deletes a TS feature)

Or maybe this is better as a new PDF Association Technical Note on best practices about this kind of thing...?

**Comment by MPBailey** [comment]
The first para of 7.12.1 says:

> The extensions dictionary, all developer extensions dictionaries, as well as their entries, shall be direct objects (i.e., this information shall be nested directly within the catalog dictionary with no indirect objects used).

And then the rows in Table 48 and Table 49 all say "shall be a direct object".

That does seem almost designed to make it difficult to update a document, although all it means is that the processor must read and rewrite the Extensions dictionary, which is unlikely to be excessively complex, especially if Table 49 is taken as an exclusive list of possible entries in a developer extensions dictionary.

I'm trying to remember why we built it like that.

**Comment by petervwyatt** [comment]
@MPBailey thanks for noting that "shall be direct" requirement in 7.12.1 - I completely missed that. 

@MatthiasValvekens - I agree it wouldn't necessarily make things simpler but in the future, with so many ISO TS extensions in the pipe, it will be far more important to have and maintain correct data in the Extensions Dictionaries than it is today (effectively you can ignore them which is what it appears most OSS (at least) is doing).

So this issue can be closed "no fix" for my original question as the spec is entirely explicit for what PDF processors (writers/updaters) need to do in terms of managing/re-writing Extensions Dictionaries.
