### ISSUE TITLE
In ISO 21757, the ECMAScript version for use with PDF 2.0 is not specified or constrained

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#185]
ISO 21757-1:2020 (ECMAScript for PDF 2.0) normatively references (as a **DATED** reference): "_ISO/IEC 22275:2018, Information technology — Programming languages, their environments, and system software interfaces — ECMAScript® Specification Suite_".

ISO/IEC 22275:2018 (https://www.iso.org/standard/73002.html) is freely available from https://standards.iso.org/ittf/PubliclyAvailableStandards/index.html as https://standards.iso.org/ittf/PubliclyAvailableStandards/c073002_ISO_IEC_22275_2018.zip

ISO/IEC 22275:2018 is a VERY short ISO/IEC standard which just normative references ECMA-262 and ECMA-402 using **UNDATED** references. As all ISO standards state: "_For undated references, the latest edition of the referenced document (including any amendments) applies_."

"_ECMA-262, ECMAScript® Language Specification_" is available from https://www.ecma-international.org/publications-and-standards/standards/ecma-262/ with the latest version being ECMAScript 2021. All older ECMAScript specification editions are still available from this URL.

I believe the root cause of this issue is probably ISO insisting that ISO specs are always used in preference to supposedly equivalent standards from other SDOs - but in this case the ISO standard is clearly NOT technically equivalent to a specific version of JS! 

Referring back to ISO 32000-1:2008 (PDF 1.7) which normatively referenced "_Client-Side JavaScript Reference, (May 1999), Mozilla Foundation_.".  I cannot locate this but I suspect was supposed to be ECMA-262 4th edition however this was never released by ECMA. This theory would also align with the previous support for E4X (now agreed deprecated for PDF 2.0).

The latest Adobe documentation for "_Acrobat JavaScript API Reference_" from https://opensource.adobe.com/dc-acrobat-sdk-docs/acrobatsdk/ provides this information on p.33:

![image](https://user-images.githubusercontent.com/26521615/173211534-bac9d9d1-60a8-4dcf-9d64-5e4b4eb1b2f1.png)

This is also confusing as I cannot find references to JavaScript versions as "1.x" but only "ESx" with "ES5" being ECMAScript 5 (2009) and I'm not sure what JavaScript "1.8" is in terms of ECMAScript editions since after ES6 the year is the version...

I do not believe PDF should allow a moving target for JS language support. So the question is: what version(s) of ECMAScript can be used with PDF 2.0, and what are the correct normative references for that fixed version(s)?

**Comment by lrosenthol** [comment]
I have no objection to PDF 2.0, via 21757, specifying a specific version of JS to target.  I would recommend ES2020.

Adobe's implementation was not tied to a specific standard but instead to an implementation (for better or worse).

**Comment by petervwyatt** [comment]
PDF TWG to update 21757 to refer to ES2020 via appropriate ECMA-262 edition.

**Comment by petervwyatt** [comment]
WG7 approved in Prague
