### ISSUE TITLE
Table 273 in section 12.11.1: S entry description points to wrong table for defined values.

### ISSUE THREAD

**Issue by datalogics-pgallot** [pdf-association/pdf-issues#187]
In the S entry of table 273, the description is:  (Required) The type of requirement that this dictionary describes. See "Table 276 — Entries in a requirement handler dictionary" for valid values.

Instead of pointing to table 276 in section 12.11.5 (Requirement Handlers), it should instead point to table 275 in section 12.11.2 (Requirement types).

Note that  table 273 is immediately followed by:
There are two additional keys that may appear in a requirements dictionary that are specific to certain types of requirements (i.e., value of the S key). These are described in "Table 274 — Entries for specific types of requirements".

And the two S key values mentioned in table 274 (Encryption, DigSig) are found in table 275, not in table 276.

**Comment by petervwyatt** [comment]
I agree with the correction of **S** in Table 273. I think in this case too the **S** key is being used as an abbreviated subtype key as described in 7.3.7 (para below note 2).

But I think the text that follows Table 273 is ambiguous - it should be restated more along the lines of the following with Table 274 also renamed:
> In addition to the keys in Table 273, there are two additional keys that may appear in a requirements dictionary that are specific to certain types of requirements as specified by the value of the **S** key. These are described in "Table 274 — Additional entries for specific types of requirements".

**Comment by petervwyatt** [comment]
PDF TWG agree
