### ISSUE TITLE
Placement attribute default in Table 378 unclear for structure elements that can be either block or inline

### ISSUE THREAD

**Issue by willkil** [pdf-association/pdf-issues#188]
The **Placement** attribute is defined in 14.8.5.4.2 General layout attributes, Table 378 — Standard layout attributes common to all standard structure types. The definition says:

> Default value: _Block_ for BLSEs, _Inline_ for ILSEs.

Some structure elements can be either a BLSE or an ILSE, for example **Figure** and **Formula**. It's unclear at this point in the text whether such a structure element is a BLSE or an ILSE. The default value of **Placement** is thus also unclear. The BLSE vs ILSE determination is specified in 14.8.4.1, "General", about 20 pages back.

This issue was discussed in today's meeting of the Reuse TWG of the PDF Association. One expert explained how BLSE vs ILSE could be determined from context. Several other experts in the meeting found that explanation extremely helpful in clarifying the default value of **Placement** for those elements. The meeting participants developed that explanation into an informative note and two examples. I've modified the note slightly. The suggestion is to add this note and those examples after **Placement**'s default value text, so the text would read:

> Default value: _Block_ for BLSEs, _Inline_ for ILSEs.
> NOTE The default value depends on the context in which the structure element is used (see 14.8.4.1, "General").
> EXAMPLE 1 A **Figure** structure element occurring within a **P** structure element is an ILSE, and therefore has a default value of _Inline_. 
> EXAMPLE 2 A **Figure** structure element occurring within a **Sect** structure element is an BLSE, and therefore has a default value of _Block_.

**Comment by petervwyatt** [comment]
PDF TWG agree
