### ISSUE TITLE
Missing back-reference from Placement, WritingMode attribute definitions in 14.8.5.4.2 to 14.8.3.3

### ISSUE THREAD

**Issue by willkil** [pdf-association/pdf-issues#189]
The **Placement** and **WritingMode** attributes are defined in 14.8.5.4.2 General layout attributes, Table 378 — Standard layout attributes common to all standard structure types. Each of these attributes relates strongly to the 14.8.3.3, "Progression direction" clause, but there is no back reference to that clause in either definition. Such back references would be helpful given that the two sections are separated by about 20 pages. Here are the suggested edits:

Change text in Table 378 from:

| Key             | Type | Value |
| --------------- | ---- | ----- |
| **Placement**   | name | _(Optional; not inheritable)_ The positioning of the element with respect to the enclosing reference area and other content. The value shall be one of the following: |
| ... (and) ...
| **WritingMode** | name | _(Optional; inheritable)_ Indicates the directions of layout progression inside Block Level Structure Elements (BLSEs) (inline progression) and regarding the sequence of BLSEs (block progression). **WritingMode** may be used as an attribute for any structure element. |

to

| Key             | Type | Value |
| --------------- | ---- | ----- |
| **Placement**   | name | _(Optional; not inheritable)_ The positioning of the element with respect to the enclosing reference area and other content` (see 14.8.3.3, "Progression direction")`. The value shall be one of the following: |
| ... (and) ...
| **WritingMode** | name | _(Optional; inheritable)_ Indicates the directions of layout progression inside Block Level Structure Elements (BLSEs) (inline progression) and regarding the sequence of BLSEs (block progression)` (see 14.8.3.3, "Progression direction")`. **WritingMode** may be used as an attribute for any structure element. |

**Comment by petervwyatt** [comment]
From PDF Reuse TWG - PDF TWG agree.
