### ISSUE TITLE
Minor nitpick on PDF representation as text

### ISSUE THREAD

**Issue by MatthiasValvekens** [pdf-association/pdf-issues#193]
**Describe the bug**

Clause 7.2.2 contains the following text:

> A non-encrypted PDF file can be entirely represented using byte values corresponding to the visible printable subset of the ASCII character set defined in INCITS 4-1986 (R2017), plus white-space characters. However, a PDF file is not restricted to the ASCII character set; it may contain arbitrary bytes, subject to the following considerations: 
> - [...]
> - A PDF file containing binary data shall be transported as a binary file rather than as a text file to ensure that all bytes of the file are faithfully preserved.

Clearly, _all_ PDF files, not just the ones that happen to contain invisible/non-printable ASCII characters, should be saved and transported as binary files. For example, platform differences in line ending conventions can mess up byte offsets in the cross-reference table of _any_ PDF file if the file is transported as text, even if it doesn't contain any "exotic" characters.

**Proposed solution**

Strike the words "containing binary data" from that last bullet point:

> A PDF file shall be transported as a binary file rather than as a text file to ensure that all bytes of the file are faithfully preserved.

**Comment by petervwyatt** [comment]
PDF TWG agree to proposal as well as deleting first sentence and the "However" from the lead-in paragraphs. PDFs are binary.

**Comment by mkl-public** [comment]
For this we should first determine what the difference of transport as a binary vs. transport as a text file means.

If transport as a text file merely means not allowing certain byte sequences in the output, it would be a special case of a binary transport. In this case the whole list item could be dropped.

If transport as a text file also means replacing any kind of line breaks by a single type (e.g. in SMTP CRLF) or expanding TABs by a number of spaces, this kind of "transport as text file" has to be forbidden for PDFs as it invalidates cross references and byte range offsets!
