### ISSUE TITLE
Document Requirements are processor hints, not file format requirements, for U3D and PRC

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#195]
This issue and proposed solution arose from the PDF/A TWG discussion on July 11 related to https://github.com/pdf-association/pdfa-twg/issues/19.

ISO 32000-2, Table 275 declares requirement type PRC (and similarly for U3D) with the following wording:

> PRC - Requires support for 3D data streams conforming to the PRC specification. This shall apply to the use of PRC in either 3D (13.6.3, "3D streams") or RichMedia annotations (13.7.2.2, "RichMediaSettings dictionary"). This also includes support for associated ECMAScripts.

The "_shall_" statement here for U3D and PRC are not correct as this would imply that Document Requirements would be needed for all PDF/A-4e (for example). ISO 32000-2 describes Doc Requirements not as file format requirements, but as hints to a processor. The best way to avoid confusion is to modify the wording to reword as a factual statement (applies to both U3D and PRC cells in Table 275) as is done with the ECMAScript statement:

> PRC - Requires support for 3D data streams conforming to the PRC specification. **This applies to the use of PRC** in either 3D (13.6.3, "3D streams") or RichMedia annotations (13.7.2.2, "RichMediaSettings dictionary"). This also includes support for associated ECMAScripts.

**Comment by lrosenthol** [comment]
+1 - works for me!

**Comment by petervwyatt** [comment]
PDF TWG agree
