### ISSUE TITLE
Public-key encryption permission explanation has lost its context (editorial)

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#196]
Clause 7.6.5.2 "Public-key encrypt dictionary" paragraph 1 states that it is made up of Table 20 + Table 23. Yet Table 24 talks about permissions, but neither Table 20 or Table 23 have a permissions key anymore as it was removed (as per the NOTE below Table 23). This means all the text below the NOTE below Table 23 about permissions is now contextless and confusing... 

The correct linkage is to the 2nd bullet in 7.6.5.3 "Public-key encryption algorithms".

Rather than move lots of text around I suggest the following purely-editorial correction:
* insert a new subclause heading as 7.6.5.2 "Public-key encryption permissions" directly below the NOTE below Table 23. This new heading is a referencing point for all the current text (incl. Table 24) on permissions
* consequently renumber the current 7.6.5.3 to 7.6.5.4 "Public-key encryption algorithms"
* in the 2nd bullet in the newly numbered 7.6.5.4 "Public-key encryption algorithms" add a back-reference to our new subclause: (see 7.6.5.2 "Public-key encryption permissions").
* as a consequence of the renumber, fix-up Table 27 Recipients description. There are no other cross-references to 7.6.5.x subclauses in ISO 32000-2:2020.

So the final heading structure will be:
* 7.6.5 Public-key security handlers
    - 7.6.5.1 General
    - 7.6.5.2 Public-key encryption dictionary
    - 7.6.5.3 Public-key encryption permissions (**new**)
    - 7.6.5.4 Public-key encryption algorithms

**Comment by MatthiasValvekens** [comment]
Minor typo: in your bullet list of changes, replace `7.6.5.2 "Public-key encryption permissions"` with `7.6.5.3 "Public-key encryption permissions"` in the first and third bullet point. It's already listed correctly in the overview below.

**Comment by petervwyatt** [comment]
PDF TWG agree
