### ISSUE TITLE
Possible typo: missing space after a period

### ISSUE THREAD

**Issue by TonalidadeHidrica** [pdf-association/pdf-issues#203]
First of all: this is a typo I found in PDF 1.7 spec.   I don't know this issue persists in 2.0 spec, because unfortunately the document is not for free, but I am point this out just in case because the paragraph in 1.7 spec may be reused in 2.0.

**Describe the bug**
In 8.4.1 "General", after Table 52 "Device-Independent Graphics State Parameters", we have the following part:
> ... for later use when interpreting the painting operators.However, some parameters ...

Here, a space after the period is missing.

**Comment by TonalidadeHidrica** [comment]
And right after the paragraph, we have

> Most parameters shall be of the correct type or have values that fall within a certain range.

whose font size is a bit smaller than the succeeding items.

**Comment by petervwyatt** [comment]
Both are fixed in ISO 32000-2:2020 - thanks anyway!
![image](https://user-images.githubusercontent.com/26521615/183035390-35da5be9-8dc2-495a-b3b4-0b29192e384a.png)
