### ISSUE TITLE
[Found in 1.7] Operator TJ should be boldface

### ISSUE THREAD

**Issue by TonalidadeHidrica** [pdf-association/pdf-issues#204]
Fonud a typo in PDF 1.7 spec (ISO 32000-1:2008).  It may have been corrected in the latest PDF 2.0 spec (ISO 32000-2:2020 = PDF 2.0), which I cannot check.

**Describe the bug**
9.2.4 Glyph Positioning and Metrics, NOTE 3"

> For example, the TJ operator enables the text position ...

The "TJ" should be boldface ~and Tj instead~.

**Comment by zauguin** [comment]
It should be boldface (and it is in the current version) but it should *not* be `Tj`. `Tj` and `TJ` are different operators and this NOTE specifically discusses the additional functionality of `TJ` which is not available with `Tj`.

**Comment by TonalidadeHidrica** [comment]
Oh my bad.  Thanks for pointnig it out.

**Comment by petervwyatt** [comment]
Note 3 is now Note 4 and was fixed. Thanks.

We appreciate your contributions but please realise that ISO 32000-2:2020 has had over 12 years of input and review in the vendor-neutral consensus-based ISO working groups by many subject matter experts so many of these issues are corrected. You will also learn a great deal and have a far better interoperable implementation if you can use the updated specification.
