### ISSUE TITLE
[Found in 1.7] Missnig reference for later table

### ISSUE THREAD

**Issue by TonalidadeHidrica** [pdf-association/pdf-issues#205]
**Describe the bug**
Fonud a typo in PDF 1.7 spec (ISO 32000-1:2008).  It may have been corrected in the latest PDF 2.0 spec (ISO 32000-2:2020 = PDF 2.0), which I cannot check.

8.2 Graphics Objects, Table 51 – Operator Categories:  The third column in the "table state" is missing.  This should refer to "Table 105 – Text state operators" in "9.3.1 General".

**Comment by petervwyatt** [comment]
We appreciate your contributions but please realise that ISO 32000-2:2020 has had over 12 years of input and review in the vendor-neutral consensus-based ISO working groups by many subject matter experts so many of these issues are corrected. You will also learn a great deal and have a far better interoperable implementation if you can use the updated specification. This specific issue was fixed.
