### ISSUE TITLE
[Found in 1.7] Inconsistent table headings

### ISSUE THREAD

**Issue by TonalidadeHidrica** [pdf-association/pdf-issues#206]
**Describe the bug**
Fonud this inconsistency in PDF 1.7 spec (ISO 32000-1:2008).  It may have been corrected in the latest PDF 2.0 spec (ISO 32000-2:2020 = PDF 2.0), which I cannot check.

The following tables describing operators are inconsistent in capitalization rules.

These captions are in Title Case:
> Table 57 – Graphics State Operators
> Table 59 – Path Construction Operators
> Table 60 – Path-Painting Operators

while for these, only the initial letter is capitalized:
> Table 107 – Text object operators
> Table 108 – Text-positioning operators
> Table 109 – Text-showing operators

I have not checked other tables for operators yet.  I'm also not sure if the capitalization rule should be consistency throughout the whole document.

**Comment by petervwyatt** [comment]
We appreciate your contributions but please realise that ISO 32000-2:2020 has had over 12 years of input and review in the vendor-neutral consensus-based ISO working groups by many subject matter experts so issues such as these are corrected. You will also learn a great deal and have a far better interoperable implementation if you can use the updated specification. These issues were all fixed.
