### ISSUE TITLE
StateEvent initialization less than fully described in ISO 21757

### ISSUE THREAD

**Issue by datalogics-pgallot** [pdf-association/pdf-issues#210]
ISO 32000-2 has a section 13.7.2.3.6.3 (Loading state data) that says that "For 3D content, an ECMAScript StateEvent is invoked with the type property set to the value load and the data property set to the value stored for Data.". However, this information is not found in the ISO 21757 (ECMAScript for PDF) specification, where it might also be relevant.

The most reasonable location for this information in ISO21757 would probably be section 12.35.1 [StateEvent] General, after "A StateEvent object is created when state data must be stored or loaded for the scene, such as when a new comment view is created or invoked for the annotation." 

A sentence along the lines of "The state data is to be pulled/stored from the Data entry of the View Params dictionary described in Table 345 of the ISO 32000-2 specification." might be appropriate.

**Comment by petervwyatt** [comment]
PDF TWG agree to new sentence as an informative NOTE as a citation ("is" --> "could").
