### ISSUE TITLE
Conditions when Contents key in Signature dictionary is unencrypted?

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#211]
Clause 7.6.2 has a list of strings that are never encrypted:
> * The values for the ID entry in the trailer
> * Any strings in an Encrypt dictionary
> * Any strings that are inside streams such as content streams and compressed object streams, which themselves are encrypted
> * Any hexadecimal strings representing the value of the **Contents** key in a Signature dictionary

The last bullet is worded in a very roundabout way... 

Table 255 — Entries in a signature dictionary defines **Contents** as:
> (_Required_) The signature value. When **ByteRange** is present, the value shall be a hexadecimal string (see 7.3.4.3, "Hexadecimal strings") representing the value of the byte range digest. For public-key signatures, Contents should be either a DER-encoded PKCS # 1 binary data object, a DER-encoded CMS binary data object or a DER-encoded CMS SignedData binary data object.
For document timestamp signatures, Contents shall be the TimeStampToken as specified in _Internet RFC 3161_ as updated by Internet RFC 5816. The value of the **messageImprint** field within the TimeStampToken shall be a hash of the bytes of the document indicated by the **ByteRange** and the **ByteRange** shall specify the complete PDF file contents (excepting the Contents value).
Space for the Contents value shall be allocated before the message digest is computed (see 7.3.4, "String objects").

So is it correct that the **Contents** is now only ever a hex string in PDF 2.0?
If so then the 7.6.2 last bullet should just be "The value of the **Contents** key in a Signature dictionary (see Table 255)"?

**Comment by MatthiasValvekens** [comment]
First, the addition of that bullet point is new in PDF 2.0, but reflects the reality of how most implementations already worked before.

> When ByteRange is present, the value shall be a hexadecimal string

This implies that (at least historically) there were at some point signatures that didn't involve **ByteRange**. My guess was that that had something to do with object-based signatures, and  the PDF 1.5 reference seems to back this up (emphasis mine):

> The signature value. When ByteRange is specified, the value is a hexadecimal string (see “Hexadecimal Strings” on page 32) representing the value of the byte range digest. **If ByteRange is not specified, the value is an object digest of the signature dictionary, excluding the Contents entry**.


Allow me to speculate a little (trusting @lrosenthol to correct me where I got the history wrong):

Object digests were never a thing in ISO-standardised PDF (not even ISO 32000-1) for interop reasons. From what I remember (and I might be wrong), object digests were intended to only apply to part of the object graph, so I think it's theoretically possible to upgrade an old document with such an object-based signature to PDF 2.0 without breaking anything. I suppose the non-ISO keys would simply be treated as class 3 names.


Is this a far-fetched objection? Absolutely. I certainly haven't come across anything like this myself. But I imagine the wording with "hexadecimal" was chosen for a reason, so I would hold off on changing the normative text until we know why the "hexadecimal string" condition is there. Nonetheless, I agree that the bullet point could use some clarification either way, so I'll propose an informative note in the meantime, to be inserted below the bullet list in 7.6.2:

> NOTE 1: For the signature types defined in this document, the value of the **Contents** entry is always a hexadecimal string.

PS: bookkeeping remark: there's another note all the way down in subclause 7.6.2 that now needs a number.

**Comment by lrosenthol** [comment]
Object-based signatures never went to ISO because we never got them to work properly and so we removed them from the ISO version.  It's one of the two or three things we didn't bring over for similar reasons.

As for the issue at hand, I don't see any reason to change this - the text is correct as is.

**Comment by MatthiasValvekens** [comment]
I totally agree that the text is correct in a normative sense. However, read outside of its historical context, the standard as written _does_ kind of suggest that there are situations where the Contents entry is not a hex string. It just so happens that those situations never arise if one sticks to the features defined in ISO 32000-x when creating signatures.

If that confuses those of us who aren't already familiar with the way PDF signing works, I don't think a note would hurt.

**Comment by petervwyatt** [comment]
I'll admit to being confused as the words implied a nuance I simply couldn't see elsewhere in 32K. But now I understand why.
A minor reword with a historical (non-detailed) informative note would help.

**Comment by petervwyatt** [comment]
To summarize a proposed solution:

* change the last bullet in 7.6.2 to follow the structure of the earlier bullets:
> the value of the **Contents** key in a Signature dictionary

* add an informative NOTE after this bullet (not exactly sure what to say! My choice of words below is trying to infer that this also applied to 32K-1:2008):
> NOTE ISO 32000 has always required that the value of the **Contents** key in a Signature dictionary is a hexadecimal string (see Table 255).

**Comment by MatthiasValvekens** [comment]
That's the thing, I don't believe this is correct as written:

>  ISO 32000 has always required that the value of the Contents key in a Signature dictionary is a hexadecimal string (see Table 255).

While it's true that **Contents** must be a hex string if you use any signature mechanism _defined within ISO 32000-x_, the wording in the standard has always left the door open for other choices. Presumably that's for historical reasons (object-based signatures), but in principle a developer extension could use the **Contents** key in its own signature scheme that didn't involve **ByteRange**s and have it not be a hex string without violating 32k. Sure, the vast majority of implementations will never see anything other than **ByteRange**-based signatures, and will make assumptions along those lines, but I personally don't feel the need to change the spec to reflect that.

(Technical side note: with ByteRange-based digests there are pragmatic reasons why hex strings are preferable, the main one being that you don't have to put escapes in them so their length is more predictable. That reasoning doesn't apply to non-ByteRange-based signatures like the object-based ones that got removed way back when.)


-----

Alternative suggestion: leave the bullet point as-is, and have the note say something like

> NOTE For the signature schemes enumerated in ISO 32000-1 and in this document, the value of the Contents key in a Signature dictionary is always a hexadecimal string (see Table 255).

Thoughts?

**Comment by lrosenthol** [comment]
I am fine with the proposed note above.

**Comment by petervwyatt** [comment]
PDF TWG agree with informative note only to be added below bullet in question
