### ISSUE TITLE
Multiple Form Field Arrays inside one PDF

### ISSUE THREAD

**Issue by Lonzak** [pdf-association/pdf-issues#212]
Recently I got several PDF Documents which contained several Field Arrays. So as a compliant reader how should I deal with this? Take the first one or last one and ignore the rest? Merge both? I would says that this violates the spec but it is not explicitly forbidden. Current definition:

> Fields | array | (Required) An array of references to the document’s root fields (those with no ancestors in the field hierarchy).

Proposed improvement:

> Fields | array | (Required) An array of references to the document’s root fields (those with no ancestors in the field hierarchy). A Fields array should occur only once inside a PDF file.
(inspired by the `Title` block)

OR

> Fields | array | (Required) An array of references to the document’s root fields (those with no ancestors in the field hierarchy). If a Fields array is present more than once, only the last shall be used.
(inspired by the `NA` array)

**Comment by MatthiasValvekens** [comment]
> Recently I got several PDF Documents which contained several Field Arrays.

Sorry if this is a silly question, but I'm not sure I fully understand what you mean by "several". The key **Fields** occurring multiple times in the same AcroForm dictionary? Because that would be invalid under the no duplicate keys rule. If that's not it, can you describe what your example documents contained in a little more detail?

**Comment by Lonzak** [comment]
Yeah sure, n.p.  - the root dict looks like that:

1500 0 obj
<</Type/Catalog/AcroForm 1 0 R/Pages 1000 0 R>>
endobj

Then there are two 1 0 obj inside the PDF (For better visibility I shortened some places with ...):

1 0 obj
<</Fields[...]/DR<</Font<</EF1 111 0 R>>>>>>
endobj
...
1 0 obj
<</SigFlags 3/Fields[...]/DA(... )/DR<</Font<<...>>/Encoding<</PDFDocEncoding 150 0 R>>>>>>

Can you point me in the spec - where can I find the "no duplicate keys" rule?

**Comment by petervwyatt** [comment]
So it sounds as though the PDF file might have at least one incremental update - which object 1 does the cross-reference data point to (by byte offset)?

(The no duplicate keys refers to keys within dictionaries: subclause 7.3.7 "_Multiple entries in the same dictionary shall not have the same key_.")

**Comment by MatthiasValvekens** [comment]
Yeah, sounds like this is either a file with a "dead object" (i.e. an object that doesn't have a corresponding xref entry anywhere), or a file that's been incrementally updated, with the incremental update modifying the **Fields** array.

The former would be odd (and probably the result of a bug) but not invalid per se. The latter, however, is really nothing out of the ordinary. Example: in a digital signing workflow, creating new signature fields through incremental updates is a very common thing to do.

**Comment by lrosenthol** [comment]
>Just theoretically: what if it would have been referenced as well?
>
Couldn't have been - you can't have two objects with the same ID since the index of the entry in the xref table is the ID

**Comment by Lonzak** [comment]
Ah thanks Leonard - so basically 

0000000000 65535 f 
0002469267 00000 n -> 1 0 obj
0000547815 00000 n -> 2 0 obj
0000000015 00000 n -> 3 0 obj
0000547686 00000 n -> 4 0 obj
0000003518 00000 n -> 5 0 obj

I haven't seen this in the wild but what about IDs with `1 1 obj`?

**Comment by lrosenthol** [comment]
`1 1 obj` replaces `1 0 obj` - it's a new "generation" of that object - and it can only appear in an update table (see 7.3.10 of 32K)

**Comment by Lonzak** [comment]
Ok so everything seems to be covered - this issue can be closed then :-)
