### ISSUE TITLE
Table 255 Signature dictionary SubFilter minor corrections

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#219]
ISO 32000-2:2020 Table 255 **SubFilter** cell has an italic "(PDF 1.6)" indicator for the list of values in the 2nd para. ISO 32000-1:2008 is the same, presumably because Adobe PDF 1.7 said "_PDF 1.6 defines the following values for public-key cryptographic signatures: adbe.x509.rsa_sha1, adbe.pkcs7.detached, and adbe.pkcs7.sha1_" . Adobe PDF 1.3 and PDF 1.4 fail to mention any values for **SubFilter** (even searching for just "x509" returns zero results) - Adobe PDF 1.3 Table 7.53 and Adobe PDF 1.4 Table 8.60 do not list any values. Adobe PDF 1.5 Table 8.93 was the first PDF reference that explicitly mentioned the 3 values. So from a specification-centric PoV the first doco for values _adbe.x509.rsa_sha1_, _adbe.pkcs7.detached_, _adbe.pkcs7.sha1_ should be PDF 1.5, not PDF 1.6. So it should be:

> The following values for public-key cryptographic signatures should be used: _adbe.x509.rsa_sha1_ (_PDF 1.5_), _adbe.pkcs7.detached_ (_PDF 1.5_), _adbe.pkcs7.sha1_ (_PDF 1.5_), _ETSI.CAdES.detached_ (_PDF 2.0_) and _ETSI.RFC3161_ (_PDF 2.0_).

I also note that the sentence starting "Other values may be ..." in the 3rd para should really start a new paragraph in ISO 32000-2:2020 as the "Other values ..." is not only applicable for PDF 2.0.

**Comment by petervwyatt** [comment]
@lrosenthol - could you please provide insight?
Will re-review at next PDF TWG

**Comment by lrosenthol** [comment]
If you look at the `Signature Fields` section in both 1.3 and 1.4, you will find the following:

>Note: The specification for public-key digital signature authentication is available in
the Adobe document PDF Public-Key Digital Signature and Encryption Specification
(see the Bibliography).

Meaning that there are details present concerning the implementation in a separate document.

I have located copies of those documents and verified that for PDF 1.3 (Acrobat 4) the following values were defined for signatures
- adbe.pkcs7.detached
- adbe.x509.rsa_sha1

And for PubKey Encryption:
- adbe.pkcs7.s3

For PDF 1.4 (Acrobat 5), the following value was added
- adbe.pkcs7.sha1

And for PubKey Encryption:
- adbe.pkcs7.s4

**Comment by petervwyatt** [comment]
PDF TWG agree but update text with Acrobat version numbers from comment above. Also do PubKey.
