### ISSUE TITLE
Clarify requirement for AP in annotation dictionaries

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#22]
The Value cell for AP in table 166 explicitly says "_(Optional; PDF 1.2)_", but then goes on to say that "Every annotation [...], except for the two cases listed below, **_shall_** have at least one appearance dictionary."

I recommend changing the initial parenthetical text to something that make people realise that AP is not simply optional and that they need to read the full text; perhaps "_(Usually required; PDF 1.2)_".

**Comment by petervwyatt** [comment]
PDF TWG request wording change to: "_(Required except for conditions listed below...)_"

(PDF TWG would like more specific information instead of just "usually"...)
