### ISSUE TITLE
Null Entries in dictionaries are described differently in 7.3.7 and 7.3.9

### ISSUE THREAD

**Issue by michaeldemey** [pdf-association/pdf-issues#220]
**Describe the bug**
```
7.3.7 Dictionary Objects (Paragraph 1)
[ ... ] A dictionary entry whose value is null (see 7.3.9, "Null object") 
shall be treated the same as if the entry does not exist. [ ... ]

7.3.9 Null Objects
[ ... ]	Specifying the null object as the value of a dictionary entry (7.3.7, "Dictionary objects") 
shall be equivalent to omitting the entry entirely.
```

The same expected behavior: ignoring entries in dictionaries with value `null` is described in two distinct manners. It may be the interpretation of a non-native speaker, but I feel there is a nuance between the two phrasings. 

I would suggest to use the same definition and phrasing for both to make sure the actual behavior is consistent. Ideally, the definition used in 7.3.7 would be used as it feels the most conclusive to me and doesn't depend on "treating".

**Comment by petervwyatt** [comment]
I would interpret 7.3.7 as an explicit processor requirement ("_treated as)"), whereas 7.3.9 is a file format requirement ("_specifying_"). And the processor requirement also kicks in for "implicit" nulls triggered by the other 7.3.9 processor requirement "_An indirect object reference (see 7.3.10, "Indirect objects") to a nonexistent object shall be treated the same as a null object._".

So you need to read it like a lawyer :-)

**Comment by michaeldemey** [comment]
I did not study computer sciences to be a lawyer! :)
