### ISSUE TITLE
Clarify row headers in table 377

### ISSUE THREAD

**Issue by DuffJohnson** [pdf-association/pdf-issues#223]
ISO 32000-2:2020, 14.8.5.4.1, Table 377

The "Vertical text" and "Ruby text" row headers do not reflect the column header ("Structure elements") or the prevailing usage in the other rows of the table.

Correction:

- Replace the row header "Vertical text" with "Any structure element containing vertical text".
- Replace the row header "Ruby text" with "RB RT, EP".

**Comment by car222222** [comment]
In fact the phrase "vertical text" does not occur anywhere else.

Thus even this suggested correction is probably not precise enough.

**Comment by DuffJohnson** [comment]
How about (borrowed from the definition of GlyphOrientationVertical):

"Any structure element containing text whose inline-progression direction is top to bottom or bottom to top."

**Comment by car222222** [comment]
Looks much better now!

**Comment by petervwyatt** [comment]
PDF TWG agree
