### ISSUE TITLE
Extend recommendations around CxF in PDF/X-6

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#227]
PDF/X-6 section 6.19 discusses spectral data as embedded CxF/X-4 files inside PDF. It says

> A conforming writer should ensure that the spectral data present in the file is consistent with the values in the Output Intent ICC profile.” 

But the output intent describes process colorants and CxF is mostly used to describe spots. I recommend that sentence be extended to say

> A conforming writer should ensure that the spectral data present in the file is consistent with the values in the Output Intent ICC profile and with alternate colour spaces and DeviceN colour space attributes dictionaries.

That requirement is not present in PDF/A-4, and is probably not appropriate for adding into 32000-2 itself.

**Comment by petervwyatt** [comment]
@MPBailey Why also alternate colour spaces since they're not allowed to be processed in PDF/X6 conforming mode?

PS. Noting for the record that this was raised as a direct result of TC 130 WG 2 discussions.

**Comment by MPBailey** [comment]
> Why also alternate colour spaces since they're not allowed to be processed in PDF/X6 conforming mode?

But alternates _are_ used for spot colours; see 6.6.3.4 "Separation and DeviceN (including NChannel) colour spaces"

And in any case, requiring consistency between various representations of what is supposed to be the same spot colour is good practice, especially when most spots are emulated on most digital presses. A DFE may choose to use the CxF or the alternate (or the Colorants dictionry)

**Comment by petervwyatt** [comment]
Given that PDF/X-6 clause 6.6.3.4 2nd paragraph states:
> "_A PDF/X-6 conforming processor shall treat process separations, specified using either a **Separation** colour space or as values within the names array of a **DeviceN** colour space, as having been prepared for the characterized printing condition identified in the currently active PDF/X output intent object._", 

doesn't this already mean the CxF/X must already be "... _prepared for the characterized printing condition identified in the currently active PDF/X output intent object._"?

**Comment by MPBailey** [comment]
That clause is specifically about process separations. CxF is primarily (but not exclusively) used for spot separations, which aren't addressed by the output intent.

**Comment by lrosenthol** [comment]
Changed based on agreement of Aligning X/A TWG.
