### ISSUE TITLE
iccMAX profiles embedded within v4 profiles in PDF

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#228]
It is possible to embed an iccMAX profile inside an ICC v4 profile. The v4 profile can then be embedded into a PDF file. Neither 32000-2 itself nor any of other subset standards say anything about this situation, although it could conceivably lead to very different visual appearances from different products.

In many ways this is similar to embedding CxF/X-4 data in PDF, which can also lead to different products producing different output. 32000-2 itself says:
> This document intentionally does not specify how a PDF processor may make use of the data provided in the SpectralData dictionary, and a PDF processor may ignore such data altogether.

And PDF/X recommends that the CxF data should be consistent with output intents (see [issue #227](https://github.com/pdf-association/pdf-issues/issues/227)).

So, should there be a comment about the potential of varying output if a v4 profile includes an iccMax profile, either in 32000-2 itself, or just in PDF/X-6 (together with the CxF recommendation)?

**Comment by petervwyatt** [comment]
Noting for the record that this was raised as a direct result of TC 130 WG 2 discussions.

As noted during WG2 discussions, a number of vendors also use private tags inside ICCs for their own colour conversion "secret sauce". We should cover that off too, since it is fundamentally how "v5 inside v4" has been done for the last 4-5 years (documented via an ICC whitepaper but not formally part of the ICC.1 v4 spec). The difference now with ICC.1:2022 is that the tag is now officially documented.

**Comment by petervwyatt** [comment]
Also need to consider impact on PDF/A-4.

**Comment by MPBailey** [comment]
This issue will need changes in the same area as those from [issue 31](https://github.com/pdf-association/pdf-issues/issues/31), which will completely rework Table 66 and make changes to wording just above or below that table. The proposal here will need to be merged with that.

Add an additional note below the bullet list below Table 66:

> NOTE 2  ICC profiles can contain private tags and/or an embedded profile conforming to ISO 20677 (iccMAX, [nn]). A PDF processor can ignore such data altogether. This means that the colour resulting from transforms through the profile can vary depending on whether a PDF processor makes use of such tags.

That needs a new entry in the bibliography:

> [nn] _ISO 20677, Image technology colour management — Extensions to architecture, profile format and data structure_

TC130/WG2 may wish to consider a more robust statement in the event of any update to PDF/X.

**Comment by petervwyatt** [comment]
PDF TWG to NOTE 2 but delete "and/or an embedded profile conforming to ISO 20677 (iccMAX, [nn]" so it applies generically to all private tags.
