### ISSUE TITLE
Annex E.2 list of places where 2nd class names are explicitly not required is incomplete

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#229]
Annex E.2, 2nd bullet under "Second class" states ".. _except keys added to a document information dictionary (see 14.3.3, "Document information dictionary") or a thread information dictionary (in the **I** entry of a thread dictionary; see 12.4.3, "Articles")._". This is an incomplete list of officially allowed places in PDF where developers may legally add their own custom names that do **not** have to be 2nd-class names.

A list of other places with either explicit or implied wording (in no specific order) - there may well be others:

* Encrypted Payload dictionary, Table 28, **Subtype** key
* 12.6.4.12 Named actions, 1st para "... _further names may be added in the future_".
* Optional Content Usage dict, Table 100, **CreatorInfo** entry: "_Suggested values include but shall not be limited to_ ..."
* Navigators, **Layout** entry, para about Table 160: "_This mechanism is inherently extensible and allows inclusion of custom named layouts ..._"
* Rubber stamp annot, Table 184, **Name** entry: "_Additional names may be supported as well._"
* File attachment annot, Table 187, **Name** entry: "_Additional names may be supported as well_"
* Printer's Mark annot, Table 398, **MN** entry: "_An arbitrary name identifying the type of printer’s mark, ..._"
* Structure Attribute Owner, Table 360, **O** entry: see Errata #226 
* Structure Attribute attribute key names: see Errata #226 
* Marked Content tag operands, Table 352

**Comment by michaeldemey** [comment]
The names of resources are also not explicitly allowed to be custom names without the need for second class names.

7.8.3 Resource dictionaries

The paragraph just before Table 34 - Entries in a resource dictionary

"
The corresponding values shall be as follows:
	• For all resource types, the value shall be a subdictionary. Each key in the subdictionary shall be the name of a specific resource, and the corresponding value shall be a PDF object associated with the name.
"
Doesn't mention that you can use a custom name.


It is implicitly talked about and shown in Example 2 following Table 34:

"
EXAMPLE 2 The following shows a resource dictionary containing fonts, and external objects. The fonts are specified with a subdictionary associating the names F5, F6, F7, and F8 with objects 6, 8, 10, and 12, respectively. Likewise, the XObject subdictionary associates the names Im1 and Im2 with objects 13 and 15, respectively.
"

But never really outspoken or defined that it is allowed. Unless I'm overlooking a clause somewhere.

**Comment by petervwyatt** [comment]
PDF TWG agree to the Annex E change.
Other changes to be done as new errata.
