### ISSUE TITLE
Messy processor requirements for deprecated 'F' operator in PDF/X-6

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#232]
ISO 32000-2:2020 3.15 says:

> deprecated
> a part of ISO 32000 that should not be written into a PDF 2.0 document, and should be ignored by a PDF processor (3.49)
> Note 1 to entry: In some cases variations on these restrictions on continued use of a deprecated feature are explicitly stated in this document.

ISO 15930-9:2020 (PDF/X-6) says:

> Any feature in ISO 32000-2 that is marked as deprecated should not appear in a PDF/X-6 file, but a conforming processor shall process the file as if the features were not present.

I was trawling 32000-2 to find any specific deprecated features that might cause problems as a result of that shall requirement.

32000-2 says in Table 59 that the operator ‘F’ is “Equivalent to f; deprecated in PDF 2.0 and included only for compatibility. Although PDF readers shall be able to accept this operator, PDF writers should use f instead.”

In the context of 32000-2, with the ‘should’ in 3.15, that works fine. But it’s a bit messy for PDF/X-6 with its ‘shall’ requirement and no statement that the description of a deprecated feature may provide specific processor behaviour.

I recommend that, if we should ever do an amendment or dated revision for 15930-9, an explicit prohibition of the ‘F’ operator be added, probably in 6.7.1.

**Comment by petervwyatt** [comment]
Since this is a request for a PDF/X-6 future change, I will flag as "Parked"

**Comment by DietrichSeggern** [comment]
This is also relevant for PDF/A-4. My understanding is that we are in agreement to rather remove the statement, that no deprecated features shall be used altogether. This is a good example why that statement is problematic.

**Comment by lrosenthol** [comment]
This should be resolved as part of the X/6->A/4 alignment

**Comment by petervwyatt** [comment]
Labelling as "proposed solution" so on radar for the next PDF TWG meeting. No changes necessary in ISO 32000-2 so could close as "no fix" as dated revisions handle what is required.

**Comment by MPBailey** [comment]
I'd be happier to close these off here if an issue were opened for X/A alignment first, and a link to that issue were added here.

**Comment by petervwyatt** [comment]
PDF TWG awaiting changes in PDF/X-6 dated revision

**Comment by lrosenthol** [comment]
Aligning X/A TWG agrees to:
Add an explicit prohibition of the ‘F’ operator.

This work was done interactively and the change applied in the DR for both.
