### ISSUE TITLE
Mention of AES-256 in ECB mode

### ISSUE THREAD

**Issue by MatthiasValvekens** [pdf-association/pdf-issues#24]
Clauses 7.6.4.3.3 and 7.6.4.4.9 state that the `Perms` entry shall be computed using AES-256 in ECB mode. More precisely:

> [...] Encrypt the 16-byte block using AES-256 in ECB mode with an initialization vector of zero, using the file encryption key as the key.

I believe this is a typo, since initialisation vectors don't make sense for block ciphers operating in ECB mode, and the specification consistently uses CBC mode elsewhere. This includes cases where the initialisation vector is mandated to be zero.

Note: for encrypting a single block, ECB mode is equivalent to CBC mode with an IV of zero, so this issue is unlikely to lead to errors in implementation. Nonetheless, it's a little confusing.

Proposed solution: either strike the words "with an initialization vector of zero", or replace "ECB" with "CBC" in both instances.

In the former case, explaining that both produce the same result in a note might also be useful, since some cryptographic libraries don't expose ECB on account of its obvious issues with repeating patterns (see [here](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Electronic_codebook_(ECB)) for an example).

**Comment by lrosenthol** [comment]
This is *NOT* a typo - it is indeed ECB mode in this instance.

**Comment by MatthiasValvekens** [comment]
Right, I'm not disagreeing with that per se. To the best of my knowledge, the concept of an "initialization vector" simply doesn't apply to block ciphers in ECB mode, since all blocks are encrypted independently anyhow. Shouldn't the words "with an initialization vector of zero" be removed, then?

I'm aware that the distinction between CBC and EBC doesn't affect the output in this particular case; my question is purely about the nomenclature. :)

**Comment by lrosenthol** [comment]
>"there's no point mentioning IV for ECB" 

Right, that is correct...

**Comment by petervwyatt** [comment]
Proposed solution (as merely as an editor): strike " with an initialization vector of zero," from sentence

**Comment by petervwyatt** [comment]
@MatthiasValvekens what about clause 7.6.4.4.12 Algorithm 13: Validating the permissions (Security handlers of revision 6)?

It also says "Decrypt the 16 byte Perms string using AES-256 in ECB mode with an initialization vector of zero and the file encryption key as the key. ..." (so that would then be 3 places where we would strike " with an initialization vector of zero," from sentences.
Thanks.

**Comment by MatthiasValvekens** [comment]
@petervwyatt Yes, you're absolutely right. I missed that third instance. Thanks for the double-check!
