### ISSUE TITLE
DigestMethod in seed value dictionary and ECDSA

### ISSUE THREAD

**Issue by a20dev** [pdf-association/pdf-issues#240]
After applying the changes of ISO 32001 and ISO 32002 to ISO 32000:2020, the DigestMethod entry of a signature field seed value dictionary is still to be ignored for ECDSA signatures as Table 237 still says about DigestMethod: "This property is only applicable if the digital credential signing contains RSA public/private keys." In particular, the new SHA3 values defined by ISO 32001 for DigestMethod won't apply to ECDSA signatures.

**Comment by MatthiasValvekens** [comment]
This came up during the drafting/review process, and was addressed as an erratum in ISO 32000-2 in #158, if I'm not mistaken.

**Comment by a20dev** [comment]
Thanks! Somehow I missed #158.

**Comment by petervwyatt** [comment]
Closing - see https://pdf-issues.pdfa.org/32000-2-2020/clause12.html#Table237 from Errata #158
