### ISSUE TITLE
Extensions dictionary is required to be direct, but Table 29 does not say so

### ISSUE THREAD

**Issue by MatthiasValvekens** [pdf-association/pdf-issues#242]
**Describe the bug**

Table 29 (Entries in the catalog dictionary) makes no mention of the fact that the value of the **Extensions** entry is required to be a direct object. However, 7.12.1 contains this text:

> The extensions dictionary, all developer extensions dictionaries, as well as their entries, shall be direct objects (i.e., this information shall be nested directly within the catalog dictionary with no indirect objects used.

Recommended fix: add the usual "shall be a direct object" qualifier to the table entry for **Extensions** in Table 29.

**Comment by car222222** [comment]
Should that qualifier read as follows: "must *not* be an indirect reference", or something equivalent?

**Comment by MatthiasValvekens** [comment]
Yeah, I made a typo and sneakily fixed it a few minutes ago... 😅 That's what I get for filing errata before having my coffee.

**Comment by car222222** [comment]
Yes,I see.  I very often need to resort to such edits, even after coffee! It would be good if Github (or whatever) sent notification emails for such edits.
