### ISSUE TITLE
PDF/A-4 normative reference link is dead

### ISSUE THREAD

**Issue by datalogics-pgallot** [pdf-association/pdf-issues#244]
Section 2 of ISO 19005-4:2020 contains as its last entry:
"XMP Specification Part 2: Additional Properties – Adobe Systems – https:// www .adobe .com/ content/ dam/ acom/ en/ devnet/ xmp/ pdfs/ XMPSDKReleasecc -2020/ XMPSpecificationPart2 .pdf"

There is a Link Annotation for the URL: https://www.adobe.com/content/dam/acom/en/devnet/xmp/pdfs/XMPSDKReleasecc-2020/XMPSpecificationPart2.pdf
but it leads to a 404 error page.

Googling for the filename leads to https://developer.adobe.com/xmp/docs/XMPSpecifications/
which in turn has a link to https://github.com/adobe/XMP-Toolkit-SDK/blob/main/docs/XMPSpecificationPart2.pdf

**Comment by petervwyatt** [comment]
Side note: AFAICT the only reason the Adobe XMP Part 2 is a normative reference is because of T&D 3.2 "extension schema". And this phrase is used just the once in subclause 6.7.4 paragraph 1, second last sentence.

**Comment by MatthiasValvekens** [comment]
Not that it matters for @datalogics-pgallot's original question, but I thought documents only used to reference T&Ds had to go into the bibliography?

**Comment by bdoubrov** [comment]
Adobe XMP Part 2 is implicitly used as a normative reference in: 
- 6.7.2.2 where we have Table 1 mentioning predefined XMP schemas from Adobe XMP Part 2
- 6.7.4 and 6.7.5, where some predefined properties from these schemas are mentioned 

So, I would suggest to add an explicit reference to Adobe XMP Part 2 in 6.7.2.2 and 6.7.4 and, of course, fix the URL.

**Comment by bdoubrov** [comment]
PDF/A TWG discussion: the link needs to be fixed as indicated in https://github.com/pdf-association/pdf-issues/issues/244#issue-1458685885 . 

The reference should stay normative, as it is needed for predefined schemas in 6.7 as per previous comment.

**Comment by lrosenthol** [comment]
TWG addressed this in DR
