### ISSUE TITLE
ISO 19005-2:2011 and SubFilter adbe.x509.rsa_sha1

### ISSUE THREAD

**Issue by a20dev** [pdf-association/pdf-issues#245]
ISO 32000-1:2008 allows a SubFilter of adbe.x509.rsa_sha1 in a signature dictionary. If SubFilter is adbe.x509.rsa_sha1, then the Contents entry is not a PKCS #7 message.

B.1 of ISO 19005-2:2011 says: "The PDF Signature (a DER-encoded PKCS#7 binary data object) shall be placed into the Contents entry of the signature dictionary."

This forbids usage of adbe.x509.rsa_sha1 for SubFilter. Is this consequence correct?

NOTE 3 tries to override that requirement, but I don't think that can be done this way.

Ditto for B.1 of ISO 19005-3:2012.

**Comment by bdoubrov** [comment]
I read this paragraph from ISO 19005-2, Annex B (normative):

> The PDF Signature (a DER-encoded PKCS#7 binary data object) shall be placed into the Contents entry of the signature dictionary. The PKCS#7 object shall conform to the PKCS#7 specification in RFC 2315. At minimum, it shall include the signer's X.509 signing certificate and there shall only be a single signer (e.g. a single "SignerInfo" structure) in the PDF Signature.

as a requirement that that only PDF/A-2(3) compliant value of the /Contents entry in the signature dictionary is a PKCS#7 container that includes a signer's X.509 signing certificate and contains exactly one "SignerInfo" structure. 

Note that as adbe.x509.rsa_sha1 and PKCS#1 are deprecated in ISO 32000-2, this question is not applicable to either PDF 2.0 or PDF/A-4.

As a historical note, I think the wording for Annex B in PDF/A-2(3) is largely based on the PDF Association's [TechNote 0006](https://www.pdfa.org/wp-content/uploads/2011/08/tn0006_digital_signatures_in_pdfa-1_2008-03-141.pdf). This TechNote does provides a strong recommendation for using only PKCS#7 containers:

>3.4 Cryptographic Message Syntax
>Only a DER-encoded PKCS#7 binary data object, conforming to RFC 3852, should be used as the value of the signature dictionary’s Contents entry thus making the PKCS#1 binary data object and the X.509 certificate chain stored in the Cert entry obsolete

**Comment by a20dev** [comment]
The paragraph before NOTE 3 is pretty clear. Then comes NOTE 3. As per ISO principles and rules, NOTEs shall state facts. NOTE 3 says "that format is not recommended". I cannot find such a reocmmendation in ISO 32000-1, therefore that recommendation seems to be one made by ISO 19005-2 (violating ISO principles and rules). That recommendation makes only sense if PKCS #1 (adbe.x509.rsa_sha1) *is* allowed.

So, what is NOTE 3 trying to say?

I guess "is not recommended" is a typo for "is not allowed".

**Comment by lrosenthol** [comment]
Notes are *INFORMATIVE*.  You can ignore every note in a document and still be good to implement it.

**Comment by a20dev** [comment]
ISO forbids usage of "shall" in "notes in the text". NOTE 3 of B.1 contains "shall".

**Comment by MatthiasValvekens** [comment]
I suggest striking NOTE 3 at the next opportunity. I can't speak to the historical necessity of that remark, but these days `adbe.x509.rsa_sha1` is all but totally irrelevant, so IMHO the note needlessly muddies the waters.


For completeness, this is what it says:

> NOTE 3 Although ISO 32000-1 also allows the value of the Contents entry of the signature dictionary to be a DER-encoded PKCS#1 binary data object, that format is not recommended.

**Comment by lrosenthol** [comment]
@bdoubrov Add this to the agenda for TWG meeting in Japan

**Comment by lrosenthol** [comment]
WG 5 says that they aren't touching A-2 or A-3, and this does not impact A-4.

@lrosenthol recommends we close this issue!
