### ISSUE TITLE
File encryption key derivation for public key encryption: EncryptMetadata flag

### ISSUE THREAD

**Issue by MatthiasValvekens** [pdf-association/pdf-issues#25]
Clause 7.6.5.3 describes the key derivation procedure for PubKey handlers as follows:

> These operations digest the following data, in order:
> a) The 20 bytes of seed.
> b) The bytes of each item in the Recipients array of CMS objects in the order in which they appear in the array.
> c) 4 bytes with the value 0xFF if the key being generated is intended for use in document-level encryption and the document metadata is being left as plaintext.
> d) The first n/8 bytes of the resulting digest shall be used as the file encryption key, where n is the bit length of the file encryption key.

The step I'm confused about is (c).

 * Does the language "for use in document-level encryption" mean that this step would _not_ apply if the procedure is run by a crypt filter that is only used to encrypt embedded files? More generally: is this step supposed to be skipped if invoked from a crypt filter that isn't used as as a value for `StrF` or `StmF` in the document-wide encryption settings?
 * When using encryption handlers with `SubFilter` set to `adbe.pkcs7.s4` or `adbe.pkcs7.s3`, crypt filters are not supported. In that case, how do we know whether metadata is supposed to be encrypted?  The `EncryptMetadata` entry in the document-wide encryption dictionary is only defined for the standard security handler, after all. Is this an oversight? If not, should we assume that `EncryptMetadata` is `true` for the purposes of key derivation unless a crypt filter dictionary says otherwise?

**Comment by lrosenthol** [comment]
From Adobe
>re (ii): Yes, that's correct. For adbe.pkcs7.s4 or adbe.pkcs7.s3 there's no way to leave meta-data un-encrypted i.e. for these SubFilters, meta-data remains encrypted and therefore this step (c) is skipped (edited)

**Comment by MatthiasValvekens** [comment]
Alright, that makes sense. Do you think this warrants a clarification in the text or in a note, or can we leave it as-is?

**Comment by petervwyatt** [comment]
I'd suggest some notes as they are informative in nature and don't change any normative requirements.

@MatthiasValvekens - would you care to draft some words?

**Comment by MatthiasValvekens** [comment]
OK, here's an initial draft for two notes (to be inserted at the end of clause 7.6.5.3).


NOTE 1: This means that step c) only applies when both of the following conditions are met: 

* the key is being generated for the crypt filter named **DefaultCryptFilter** (i.e. the crypt filter used as the value for **StmF** in the encryption dictionary);
* the **EncryptMetadata** entry of the associated crypt filter dictionary is set to *false*.

NOTE 2: Since crypt filters are not supported when **SubFilter** is set to *adbe.pkcs7.s3* or *adbe.pkcs7.s4* in the encryption dictionary, there is no way to specify that metadata is to be left unencrypted in these cases. In particular, step c) is always skipped for these **SubFilter** values.

**Comment by petervwyatt** [comment]
PDF TWG agreed
