### ISSUE TITLE
pdfaid:​rev of ISO 19005-4:2020

### ISSUE THREAD

**Issue by a20dev** [pdf-association/pdf-issues#253]
6.7.3 says:

`  If the file conforms to a version of ISO 19005 that is defined by a dated revision to a part, then the value of pdfaid:​rev shall be the four digit year of that revision.
`

What value shall pdfaid:rev have if the file conforms to a version of ISO 19005 that is *not* defined by a dated revision to a part? Note that pdfaid:rev is required.

If all revisions to a part are dated, then why that if clause?

**Comment by lrosenthol** [comment]
Then it doesn't have a value - aka it's not present (which is why it is optional).

Since, at this time, there are no dated revisions to 19005-4, you don't need add this.   This is consistent with all other PDF subsets and their identification metadata.

**Comment by a20dev** [comment]
pdfaid:rev is **required** in ISO 19005-4:2020!

**Comment by a20dev** [comment]
That doesn't explain the if clause in the sentence I quoted above. Why is it there? If the if clause always evaluates to true, it should be removed. If it does not always evaluates to true, what shall be the value of pdfaid:rev if it evaluates to false?

**Comment by a20dev** [comment]
Translated to, say, C, 6.7.3 looks like this:

```
if (some_condition)
  pdfaid_rev = some_specified_value;
else
  pdfaid_rev = required_but_unspecified;

```
Either **required_but_unspecified** should be specified or, if the condition turns out to be always true, said condition should be removed:

`    pdfaid_rev = some_specified_value;
`

**Comment by petervwyatt** [comment]
The current wording across Table 2 and the sentence you quote is clear that (a) the entry is always required; and (b) the value is the year of the "the publication **OR** revision" so the only current valid value is "2020" (year of publication of ISO 19005-4). The sentence you quote is conditional as it starts "_If the file conforms..._" and since there is no dated revision then that requirement is not relevant.

**Comment by a20dev** [comment]
I think I now understand what my mistake was. I read

> If the file conforms to a version of ISO 19005 that is defined by a **dated** revision to a part, then the value of pdfaid:​rev shall be the four digit year of that revision.


instead of

> If the file conforms to a version of ISO 19005 that is defined by a **dated revision to a part**, then the value of pdfaid:​rev shall be the four digit year of that revision.


That is, I thought the condition was dated vs. non-dated revision rather than revision vs. publication. Thanks for putting me on the right track!

Quite a convoluted way to say "2020" (and "2023" or whatever in that future revision).

**Comment by MatthiasValvekens** [comment]
I also initially read it the same way @a20dev did. Maybe this slightly tweaked wording would help to remove the ambiguity?

> If the file conforms to a version of ISO 19005 that is defined by a dated revision to a part, then the value of pdfaid:​rev shall be the four digit year of that revision, not the original year of publication.

**Comment by petervwyatt** [comment]
I can now also see that ambiguity in the expression so we should aim to clarify...

Because it is PDF/A I'd suggest an informative-only fix using a NOTE in the short term. Longer-term we change the normative language if ISO TC 171 SC 2 WG 5 wishes. Passing to PDF/A TWG and assigning to @bdoubrov for their discussion.

**Comment by bdoubrov** [comment]
PDF/A TWG reconfirms that this property is required and should be "2020" for now.

**Comment by lrosenthol** [comment]
Text rewritten as:
>The value of *pdfaid:rev* shall be the four digit publication year of that specific revision of this document.
