### ISSUE TITLE
Do Structure Element classes require an entry in the ClassMap?

### ISSUE THREAD

**Issue by faceless2** [pdf-association/pdf-issues#254]
This comes from an ongoing discussion on the PDF/UA mailing list.

In question is a document that contains a `Structure Element` (table 355) with a `C` entry - either a string or array - which identifies one or more _classes_. However there is no corresponding entry in the `ClassMap` value of the `Structure Tree Root` (table 354).

The spec describes the lookup process like so:

ISO 32000-2:2020, 14.8.5.1

> The class name is in turn looked up in the class map, a dictionary identified by the ClassMap entry in the structure tree root, yielding an attribute object or array of objects corresponding to the class.

ISO 32000-2:2020, 14.7.6.1

> An attribute object shall be a dictionary or stream that [...]

So the argument is that, as specified, a missing entry is invalid - it is not an "attribute object".

---

I'm of the opinion that this is an unnecessarily strict requirement. There is a long, long history in PDF of missing items being used to represent missing data. It seems crazy that if an element specifies one or more classes that intentionally have no attributes, that tools then have to defined an empty attribute holder just to represent this. It's brittle, verbose and adds no semantic value.

I would propose changing the text so something like:

> The class name is in turn looked up in the class map, a dictionary identified by the ClassMap entry in the structure tree root. **If present, it yields** <strike>yielding</strike> an attribute object or array of objects corresponding to the class.

I'd also like to note that:

1. There are semantic reasons to add a class with no attributes.
2. I'm not aware of any tools that currently create an empty attribute map when they do this, so there are many PDFs in existence with classes that have no attributes - the vast, vast majority do note create an empty map. So this adjustment would be moving the spec to reflect reality

Other opinions exist of course, I'm sure they will be summarised in replies to this issue.

**Comment by petervwyatt** [comment]
@mrbhardy - care to answer?

**Comment by car222222** [comment]
Many thanks to @faceless2 for raising this in the correct forum.

In the discussion we also considered whether it is valid to have an _empty_ array as a value in the ClassMap dictionary.  The current wording does not explicitly exclude the use of such empty arrays.
It would be good to clarify this point.

**Comment by car222222** [comment]
As @faceless wrote:
There are semantic reasons to add a class with no attributes.

But at this stage we are just trying to clarify what is valid.

**Comment by a20dev** [comment]
If you want to add a class with no attributes, add a class with no attributes (empty array in a ClassMap entry), not a C entry with a class name that does not exist in ClassMap.

**Comment by faceless2** [comment]
> What's the point of adding a C entry that uses a class name that is not defined in ClassMap?

That presumes the only reason to give an element a class is to assign attributes; it's not. For example when converting HTML to PDF, the PDF class model can't represent the HTML class model - so attributes may be set directly on the element. However we shouldn't then be forced to discard the classes from the element - it may still have semantic value.

> If you want to add a class with no attributes, add a class with no attributes (empty array in a ClassMap entry), not a C entry with a class name that does not exist in ClassMap.

For what purpose?

**Comment by a20dev** [comment]
We are talking about **attribute** classes here, not about classes of structure elements. C and ClassMap are about attributes. Nothing else. You are trying to assign semantic value to something that is not designed by PDF to carry semantic value. If you need to add your own data to structure elements, use a different key, say, X.Class.

**Comment by faceless2** [comment]
Well, the spec does say "attribute class" so that's a reasonable statement in itself, but I don't see any reason why C can't have semantic value nor any statement of its design purpose.  But I feel your proposal is the tail wagging the dog:
* with `/C` stripped of _all_ semantics it requires the creation of some sort of non-standard "X-Class" attribute. This introduces different _classes of classes_!
* it requires adding empty arrays to the file, which you're going to presumably expect processors to validate. What if they're missing - is the valid invalid for PDF/UA? What about PDF/A-3a?
* and in terms of benefit we have, quite literally, added nothing. There's no additional semantic meaning in the file.

Pleae don't take me the wrong way - I do think this is a useful exercise, and I'm glad for the discussion and you've helped me understand your position much better, so thank you. Your point about **attribute** classes is a good one and if this text is revised we should revise that term too - perhaps "classes that can be used for attributes", or something less clumsy.

**Comment by romantoda** [comment]
We used class name that doesn't exist in ClassMap in our sample. Check https://normex.github.io/PDF-Derivation/ the file BMIBAI_form_css 
ClassMap is empty, though elements contain C entry which references CSS classes defined in associated css file. I'm not saying that's the best approach, bt there'd be not other way to directly adopt css as an attachment

The other question is what means if we define class and we'd provide an empty dictionary in the ClassMap - considering attribute inheritance - would that mean we are setting values back to default? I'd expect so

**Comment by petervwyatt** [comment]
Cf. to Resource inheritance: an explicitly empty **Resources** entry stops inheritance because it is "present".

**Comment by lrosenthol** [comment]
IMO, there is no requirement that an entry be present in the ClassMap for any specific class provided on an element.  

1 - The spec hasn't required it for the last 20+ years, so no reason to add it now.
2 - As mentioned previously, there are valid use cases for such a scenario.
3 - There are post-creation workflows that could cause such a file to be created, by design.

**Comment by MatthiasValvekens** [comment]
> if a key is not present in a dictionary (here: ClassMap), the value of the entry shall be taken as null

IMHO that's kind of backwards, though. 32k says that `null` dictionary entries shall be treated the same way as missing entries. That's a low-level requirement on PDF dictionary deserialisation, and I don't think it follows that undefined class names correspond to a `null` attribute value. You could equally well interpret the text in 14.7.6.2 para 2 to say that there are no "corresponding attribute objects" if there's no value (or a null entry) in the **ClassMap**.

I agree that the text could be more explicit as to what is and isn't allowed, but I have a hard time interpreting the current words as (implicitly or explicitly) requiring **ClassMap** entries.

**Comment by lrosenthol** [comment]
I agree with @MatthiasValvekens - you are reading this backwards.

And if the PDF/UA committee would like to make such a thing mandatory *just for their spec* they can do so...

**Comment by petervwyatt** [comment]
PDF TWG agree to add an informative note (it is not required). @mrbhardy to draft.

**Comment by a20dev** [comment]
Oops, yes, I confused missing dictionary entries with missing indirect objects.

**Comment by a20dev** [comment]
I still think that only the existence of a name as key in ClassMap makes that name a class name and usage in C does not.

Also, "For each class named in the C entry, the corresponding attribute object or objects shall be considered to be attached to the given structure element, along with those identified in the element’s A entry." seems to require the existience of the corresponding attribute object or objects, ie, an entry in ClassMap. Otherwise, what is/are the corresponding attribute object or objects for a missing entry in ClassMap?

**Comment by a20dev** [comment]
14.8.5.1: The C entry in the structure element dictionary gives the name of an attribute class or an array of such
names. The class name is in turn looked up in the class map, a dictionary identified by the ClassMap
entry in the structure tree root, **yielding an attribute object or array of objects** corresponding to the
class.

A non-existing entry in ClassMap does not yield an attribute object or array of objects.

**Comment by a20dev** [comment]
In short, I think adding a note to the effect that class names do not need to be defined in ClassMap isn't enough.

**Comment by car222222** [comment]
@MatthiasValvekens wrote: I agree that the text could be more explicit as to what is and isn't allowed 

So when is this improvement to the text due to appear?  Or even be drafted?

**Comment by petervwyatt** [comment]
@mrbhardy - can you please progress for our next PDF TWG Meeting?

**Comment by mrbhardy** [comment]
I would suggest we simply add a note to 14.7.6.2:

> NOTE If a class identified through the **C** entry is not present in the **ClassMap**, it is an empty class, which defines no additional attributes.

**Comment by petervwyatt** [comment]
PDF TWG agree
