### ISSUE TITLE
URI dictionary Base requirements are unstated leading to different behaviour

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#256]
"Table 211 - Entries in a URI dictionary" only generically specifies the **Base** key as an ASCII string without being explicit about any requirements of a base URI. It appears from experimentation with multiple popular implementations that a trailing `/` is required for a **Base** URI or otherwise only the host portion gets used (and any path portion is dropped). For interoperability it would be better to be more precise about whether processing is expected/required or whether simple concatenation of **URI** to **Base** is expected to work (file format requirement). Or otherwise an informative note saying behaviour is implementation dependent...

Using https://pdfa.org/community/pdf-technical-working-group as an example: the **Base** settings used were:
* https://pdfa.org/community
* https://pdfa.org/community/

with the relative **URI** in URI action (Table 210) being:
* pdf-technical-working-group
* pdf-technical-working-group/
* ./pdf-technical-working-group
* ./pdf-technical-working-group/
* ../community/pdf-technical-working-group
* ../community/pdf-technical-working-group/

Wrong behaviours included https://pdfa.org/pdf-technical-working-group and https://pdfa.org/communitypdf-technical-working-group which led me to this conclusion.

PS. Note that the URL https://pdfa.org/pdf-technical-working-group will work but only because there is a redirect to https://pdfa.org/community/pdf-technical-working-group, but is technically an incorrect URL for the above **Base** and **URI** combinations.

My experiments led to me think the correct answer is that **Base** (only) needs to end with a trailing `/` and that simple concatenation of **Base** and **URI** is all that is expected (so fundamentally a file format requirement that the two parts are then defined compatibly).

**Comment by lrosenthol** [comment]
The **Base** feature in PDF was designed to match the same functionality present in HTML, or at least HTML at the time (1995) when this was introduced into the spec.   Check out the description for **Base** in the PDF Reference 1.2 (as well as 1.3 and 1.4), where it specifically references the early HTML 2 spec.   In PDF 1.5, the reference is updated to HTML 4.0.1, and it remains in 1.6 and 1.7, as well as 32000-1 and 32000-2.  (See Table 211 in 32K-2).  The specific section is https://www.w3.org/TR/html401/struct/links.html#h-12.4

Looking at a well known implementation, we follow the rules of RFC 1808 ("Relative URLs"), as described in the HTML 4 spec, in combining the **Base** with each URI/URL when determining the final URL be used for processing.

A reminder, as discussed at a recent PDF TWG, that there are MANY places where URL/URIs exist in PDF - and the **Base** is to be applied to all of them, not just to the URI actions.  However, in reading the text in 32K-2 (which is pretty much unchanged since 1.1!) I can see the confusion that it mentions URI actions only.

**Comment by petervwyatt** [comment]
Thanks for that! Very helpful... but it widens the issues with this errata:

* we should be clear about which other PDF entries utilize **Base** - currently ISO 32000-2:2020 states above Table 211: "_To support URI actions, a PDF document’s catalog dictionary (see 7.7.2, "Document catalog dictionary") may include a **URI** entry whose value is a URI dictionary._" which is why I thought it only applied to Actions. This statement goes all the way back to the Adobe PDF specs.

* in Table 211 the wording "_The use of this entry is parallel to that of the body element <BASE>, as described in the HTML 4.01 Specification." is a bit wishy-washy if the intention is that PDF's behaviour _exactly_ mimics HTML 4.01 - there should be a "shall" in there somewhere.

* the HTML 4.01 spec link you provide clearly explains that this is a processor requirement ("user agent ...") to support the various kinds of Base and relative URIs - so this means several mainstream PDF processors have implementation issues.

**Comment by petervwyatt** [comment]
Building on a list previously prepared by @lrosenthol for WG8 back circa 2010 as to all locations in PDF 2.0 that might have a URI/URL (and also checking their specified data type: _what kind of string_?):

- **/URI** dictionary entry in Catalog (Table 29) – indirectly to URI action (12.6.4.8)
- Navigator **/UUID** from Adobe Extensions – text string - **WAS NOT BROUGHT INTO ISO 32000-2**
- Link Annotation (Table 176) **/PA** (from Web Capture) – indirectly to URI action
- URI action Dictionary (Table 210), **/URI** entry in the URI Dictionary – ASCII string
- URI dictionary (Table 211), **/Base** - ASCII string
- RichText link – XHTML string/stream
- OutputIntent **/RegistryName** (Table 401) – text string, 

In addition, there are few places in the PDF spec that refers to URLs instead of URIs and specifically references RFC 1738 and 7-bit ASCII (except where noted below):

- **/FS /URL** specifications in a FileSpec dictionary Table 43. This is a widely referenced data structure!:
    -  **/F** – ASCII string (or PDDocEncoding is allowed), 
    -  **/UF** - text string, 
    - /EF dict also has (**/F,/UF**) as does RF dict (**/F,/UF**)
- any stream via **/F** (Table 5) - via generic file spec dictionary
- **/URL** entry in Developer Extension dictionary – text string - Table 49
- **/URL** entry in signature field seed value dict Timestamp sub-dict  – ASCII string - Table 237
- **/URL** entry in Certificate seed value dict – ASCII string - Table 238
- **/Caption** entry in PaperMetaData dictionary from Adobe Extensions – text string - WAS NOT BROUGHT INTO ISO 32000-2!
- Submit action – URL-based file specification (so indirectly) - Table 239
- **/BU** entry for MediaClips MH/BE dicts – ASCII string - Table 287
- **/U** key in Software Identifier (for Media) – ASCII string - Table 303 - custom scheme `vnd.adobe.swname:`
- **/URL** Strings in WebCapture content sets (14.10) – ASCII strings
- **/AU** entry in source information dictionary – ASCII string - Table 391
- **/U** and **/C** (array) entries in URL Alias dictionary – ASCII string - Table 392
- **/URL** entry in Web Capture command dictionary – ASCII string - Table 393
- **/URLs** array entry in OutputIntent DestOutputProfileRef dictionary – URL-based file specification - Table 402
- RichMedia **/Assets** name tree entries (via File Spec dictionaries with very specific rules: text string, no NULL, 1-255, excl. 6 chars - see 13.7.2.3.2)
- **/NS** entry in Logical structure Namespace dictionary (14.7.4.2) - Table 356, text string
- Fragment identifiers obviously - Annex O
- **/URLS** in name dictionary (Table 32) for web capture content sets
- Associated Files (AF), 14.13 - via generic file spec dict
- **/PronunciationLexicon** in Table 354 - via generic file spec dict
- Inside JS code (ECMAscript)

Would not apply to URI/URLs inside XML data streams: XMP Metadata streams, MathML , CxF/X. ???

Are there any others??

**Comment by petervwyatt** [comment]
PDF TWG agree that Base should apply to all relative URL/URI/IRIs as per the HTML 4 spec quoted above.
Need to invent a method to have this explanation clearer for all uses.

**Comment by petervwyatt** [comment]
Proposed rewording and restructure:

* Update Table 29 (Document Catalog) URI entry to say "A URI dictionary containing document-level
information for URI (uniform resource identifiers)." (i.e. delete "actions (see 12.6.4.8, "URI actions").". Replace this reference with an updated link to a new section - TBD.

* Move the para of text below EXAMPLE 2 in 12.6.4.8 URI actions along with Table 211 and the following NOTE to a new subclause TBD, with subclause title "Document URI dictionary". Note the addition of "Document" to clearly indicate this is document-wide...

* Add HTML 4.01 as a Normative Reference https://www.w3.org/TR/html401/. RFC 1808 is obsoleted and the replacement RFC 3986 is already a normative reference.

* Change the 1st sentence of the para below EXAMPLE 2 to start "To support relative URIs, ..." (i.e. generalize "URI actions" to cover all kinds of URIs in a PDF)

* Add a new sentence to the end of the para below EXAMPLE 2 to make it crystal clear that things apply to _every_ relative URI/IRI/URL in a PDF: "The document URI dictionary applies to all IRIs, URIs and URLs defined by PDF."  This wording is subtle as I am writing to exclude URIs defined in other specs such as MathML, CxF/X, XMP, ECMAscript, etc. - is there a better way of stating this??

* Replace the last sentence in Table 211 to make things explicit requirements: "Partial URIs, base URIs, and resolving relative URIs shall be defined according to the HTML 4.01 specification, section 12.4 Path information: the BASE element.". Note that this sentence construct combines 2 file format requirements (partial, base) and a processor requirement (resolving things) but I think that is OK as it clearly points to a combined single reference for everything.

* For each place in the PDF spec that can be an IRI/URI/URL, add a "See also x.x.x Document URI dictionary."

* Suggested location for the new subclause is 7.13 (i.e. end of clause 7), since it is document wide.

PS. This is rather big surgery for an errata!

**Comment by petervwyatt** [comment]
PDF TWG agree that this is too big for an errata. Instead add an informative note stating the intended change and linking to this issue. Note will be reviewed by PDF TWG next time.

**Comment by petervwyatt** [comment]
Proposed new informative NOTE to be added below EXAMPLE 2 (which is the start of the discussion about **Base**):

NOTE  The following text (including Table 211 and NOTE) apply to all relative URIs in a PDF document and are not limited to only URI actions as is currently implied. A future edition of ISO 32000 will move this text and update many other locations so this is clear throughout the PDF specification as described in Errata #256 (link added).

For review by PDF TWG at the next meeting.

**Comment by petervwyatt** [comment]
PDF TWG agree

**Comment by seehuhn** [comment]
The new note shown at https://pdf-issues.pdfa.org/32000-2-2020/clause12.html#H12.6.4.8 uses an incorrect section number.  The note currently reads

> The remaining text in subclause 12.6.4.16 ...

I believe 12.6.4.16 should be replaced with 12.6.4.8.

**Comment by petervwyatt** [comment]
Correct. Thanks for spotting!
