### ISSUE TITLE
Media Clip Data dictionary should comply with RFC 2045 - why not shall?

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#257]
In "Table 285 — Additional entries in a media clip data dictionary", the **CT** entry states:

> The string should conform to the content type specification described in Internet RFC 2045.

All other references to RFC 2045 in ISO 32000-2 mandate ("_shall_") compliance with RFC 2045 (i.e. text in 12.7.5.3 Text fields and Web Capture **CT** entries in Tables 388 and 393).

Why is this a "_should_" and not a "_shall_"? How does PDF interoperability work if it is something else?

**Comment by petervwyatt** [comment]
@lrosenthol - any comments?

**Comment by lrosenthol** [comment]
Should be an ISO `shall`.

The should goes all the way back to the original proposal and no one caught that it should be a shall till now.

**Comment by petervwyatt** [comment]
PDF TWG agree
