### ISSUE TITLE
Table 205 Target P entry does not support all methods for named destination

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#258]
"Table 205 — Entries specific to a target dictionary" defines the **P** entry to be either an integer or byte string. The description then states "_... If the value is a string, it specifies a named destination in the current document that provides the page number of the file attachment annotation._"

But named destinations are supported in 2 ways:
* (_since PDF 1.1_) via PDF name objects, via the Doc Catalog **Dests** entry, where the destination name is directly the key in this dictionary
* (_since PDF 1.2_) via PDF string objects, via the Doc Catalog **Names** dictionary and then the **Dests** name-tree as specified in Table 32. And of course noting that name trees actually use strings as their index...!

Both methods are clearly described in 12.3.2.4 Named Destinations.

So I think the Target dictionary **P** entry should also include "name" as a type to support all forms of named destination.

PS. This seems to be the only place in PDF where a named destination is constrained.

**Comment by petervwyatt** [comment]
Yes to files in the real-world which is what made me question things (Arlington errors)... and the original method is not marked as deprecated nor is it prohibited in other parts of the PDF spec that use named destinations. AFAICT this is the odd one out.

**Comment by petervwyatt** [comment]
History research: Adobe PDF 1.6 introduced Embedded Go-To actions thus the target dictionary (Table 205 in ISO 32000-2:2020, Table 8.48 in Adobe PDF 1.6). Adobe PDF 1.6 was originally specified as just "integer or string" (no "or name") so this limitation is how it has always been spec'd.

**Comment by lrosenthol** [comment]
The reason that you *cannot* use Name objects for a `P` value in a `GoToE` action, is that you can't refer to objects in other PDFs.   The Name object would need to be an object *in the embedded PDF* - not in the current/containing PDF.

So the text is correct - integers and strings.

**Comment by petervwyatt** [comment]
PDF TWG agree to informative to highlight that this is not a mistake but intentional.

**Comment by petervwyatt** [comment]
I just tried to apply the PDF TWG recommendation and had an issue on closer review:

When **R** is _C_, **P** must effectively point to a file attachment annotation in the "current document" (quoting Table 205):
> If the value is an integer, it specifies the page number (zero-based) in the current document containing the file attachment annotation. If the value is a string, it specifies a named destination in the current document that provides the page number of the file attachment annotation.

so a named destination of the target is to the _current_ document, not the child document. And this is possible using a PDF 1.1 named destination name object as it has the identical set of possible values as the PDF 1.2 string form. This is explicitly stated in 12.3.2.4 Named destinations in the para after NOTE 2 where it says "_The destination value associated with a key in the name tree may be either an array or a dictionary, as described in the preceding paragraph._" - the preceding paragraph is the PDF 1.1 name object description.

This means the name form of the named destination would be described as:
> If the value is a name, it specifies a named destination in the current document that provides the page number of the file attachment annotation.

So I think the stated reasoning for prohibiting the name form of Named Destinations for target dictionaries is flawed... but there might be other reasons??? @lrosenthol ???

**Comment by petervwyatt** [comment]
@lrosenthol to research some more after PDF TWG Discussion.

**Comment by lrosenthol** [comment]
I see what you are getting at @petervwyatt .  

As best I can tell, when embedded destinations were designed, only the Names tree (>= PDF 1.2) was considered since the original 1.1 model had been superseded (though not officially deprecated, since we didn't have that concept in Adobe specs).  In today's world, I would consider it such - read but don't write - so no reason to support.

**Comment by petervwyatt** [comment]
OK - understanding more what was intended...

Proposed solution is to add "_name (deprecated)_" to **Type** column implying that it may be encountered in old PDFs, along with "_If the value is a name (deprecated), it specifies a named destination in the current document that provides the page number of the file attachment annotation._"

**Comment by petervwyatt** [comment]
@lrosenthol - could you please draft so PDF TWG can review? Thanks

**Comment by lrosenthol** [comment]
In a review of the history of this feature's design & implementation, it was determined that the reason for not including support for a Name was two fold.

1 - Adobe's creation tools at the time would not write the old version and so there was no reason to include it as a possible value.

2 - The use of the other methods, was determined to improve support for page rearrangement without losing the association between documents.

Given that, I propose the following note in the `P` description

>NOTE: Although normally named destinations can also be specified by the use of a name object, that particular usage of them is not provided for in this case.

**Comment by petervwyatt** [comment]
PDF TWG agree
