### ISSUE TITLE
Should we use British or US spelling of mitre?

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#259]
This was triggered by noticing that the current WG8 doc on the next cycle of errata uses the UK 'mitre' spelling for the title of 8.4.3.5 and the body of that clause uses the US 'miter'. In fact 32000-2 uses 'miter' throughout (the writer of the errata doc must have been tripped up by not being American!)

I can't find anywhere that the word is used in constructing a PDF file; it's always abbreviated to something like 'ML' for mitre limit. But the back-reference to PostScript in table A.1 does note the use of 'setmiterlimit' there.

In general we follow the ISO guidance on using British English spelling except where that would invalidate PDF files conforming to pre-ISO specifications. Not sure this one is worth changing, but figured I should ask.

**Comment by petervwyatt** [comment]
Similar to the use of "colour" in prose, but "color" for the technical key names and values, etc.

Maybe can resolve now with a generic editor note as a reminder for fixing in the future, or just leave alone (park) as I'm sure there are other similar issues...

**Comment by petervwyatt** [comment]
Only technical wording is the PS "setmiterlimit" - everywhere else (27!) is descriptive. `ML` is the key.

PDF TWG agree
