### ISSUE TITLE
Figure 5 does not show Document Parts

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#261]
Figure 5 was not updated for PDF 2.0 and thus does not show Document Parts (subclause 14.12).
It should be represented in a similar manner to the existing "Page tree", "Outline hierarchy" and "Structure Tree".

Is there anything else significant as the document level that got added in PDF 2.0 that should also be added while we are at it?

**Comment by petervwyatt** [comment]
Updated figure (trying to keep proportions roughly similar):

![figure5-document-structure](https://user-images.githubusercontent.com/26521615/220785864-05366a75-fda1-438d-89dd-5960ab91278d.svg)

**Comment by lrosenthol** [comment]
There are LOTS of other things in a PDF that aren't in that diagram.  Why update it for DParts and not everything else?

**Comment by MPBailey** [comment]
I agree with Leonard. 

Three choices:
a) Make it complete enough to not be misleading (which won't be easy if you start adding things like Resources and optional content)
b) Leave it as is, possibly with a note to confirm that not every element of a PDF file structure is represented
c) Cut it.

On balance I'd go with b.

**Comment by petervwyatt** [comment]
Move Figure 5 into 7.7.1 above the note that refers to it. This brings everything together.
Figure 5 itself: remove "DParts" from fig and make same as Collection. Remove horizontal line from "Interactive Form".
PDF TWG agree.

**Comment by petervwyatt** [comment]
New Figure 5, updated and simplified as agreed by PDF TWG
![figure5-document-structure](https://user-images.githubusercontent.com/26521615/224580513-4f829db7-cfd4-4995-93b0-54824471987d.svg)
