### ISSUE TITLE
Potentially conflicting entries for initial visibility of OCGs (layers), but no priorities defined

### ISSUE THREAD

**Issue by DietrichSeggern** [pdf-association/pdf-issues#262]
There are parameters in the D(efault) OCCD, that are used by the most commonly used viewers: **BaseState**, **ON** and **OFF**. In addition to these there is the **View** dictionary in the **Usage** dictionary in the OCG itself.

It is not clear in the spec what happens when an OCG is in the **ON** array in the **D** OCCD and at the same time has an **Usage** dictionary with a **View** dictionary with **ViewState** set to **OFF**. It is neither said that there must not be any such conflicts.

Afaics there are no applications that create or use the **ViewState**. We may:
- deprecate **View** and **ViewState** in the **Usage** dictionary or
- give priority to one of the two parameters

In the latter case we should also specify the default for **ViewState** if the parameter is missing, which should probably be **ON**.

**Comment by DietrichSeggern** [comment]
Sorry, I now dug deeper and now think I found the provision in "Determining the state of optional content groups" where it says that the **D** OCCD is used for initialization and then overwritten by **ViewState**, so the latter has higher priority. I therefore close this.

**Comment by petervwyatt** [comment]
In some future rewrite, it might be good to add forward references to 8.11.4.5 "Determining the state of optional content groups" from Table 99 and elsewhere.
