### ISSUE TITLE
ISO 21757-1:2020 section 12.40.2 either misnamed or mispositioned.

### ISSUE THREAD

**Issue by datalogics-pgallot** [pdf-association/pdf-issues#267]
Section 12.40.2 is named 12.40.2 ToolEventHandler properties
however, section 12.40 is 12.40 ToolEvent and section 12.41 is ToolEventHandler
which implies that 12.40.2 should be ToolEvent properties

or, alternately, it should be moved to 12.41.2.

**Comment by petervwyatt** [comment]
Table 130 matches the table on p.105 of "JavaScript™ for Acrobat® 3D Annotations API Reference". The Adobe 3D spec says:
> An object that is passed as an argument to the onEvent method of the ToolEventHandler object.

and this is the same text as under 12.40.1.

I suggest re-titling clause 12.40.2 as ToolEvent properties

**Comment by petervwyatt** [comment]
PDF TWG agree
