### ISSUE TITLE
Is it permissible to use SubFilter adbe7.pkcs.s4 with a security handler of version 5?

### ISSUE THREAD

**Issue by MatthiasValvekens** [pdf-association/pdf-issues#27]
There is language in clause 7.6.5.2 indicating that adbe7.pkcs.s5 shall be used when crypt filters are used in a public key security handler. Clause 7.6.4.1 also states that when a security handler of version 4 or 5 is specified, the _standard_ reader shall _support_ crypt filters.

A literal reading of this requirement doesn't appear to forbid using `adbe7.pkcs.s4` as the `SubFilter` entry for a V5 public key security handler (e.g. in case you'd want to encrypt a document using AES-256 without bothering with crypt filters). Nonetheless, apparently Acrobat refuses to decrypt such files.

Was the intention here to make crypt filters effectively mandatory for version 4 and 5? In V4 they'd be effectively required anyway (to distinguish between RC4 and AES-128), but that doesn't apply to V5. If V4 and V5 require crypt filters to be used, adding a sentence to clause 7.6.5.2 to that effect could be helpful.

I've attached a couple of example files testing different combinations of security handler versions and subfilter values. As indicated in the specification, the `S5` files use crypt filters, while the `S4` files do not. Acrobat opens all of them except the `V5-S4` one.

[aes-tests-V2-S5.pdf](https://github.com/pdf-association/pdf-issues/files/5841191/aes-tests-V2-S5.pdf)
[aes-tests-V5-S5.pdf](https://github.com/pdf-association/pdf-issues/files/5841193/aes-tests-V5-S5.pdf)
[aes-tests-V2-S4.pdf](https://github.com/pdf-association/pdf-issues/files/5841194/aes-tests-V2-S4.pdf)
[aes-tests-V5-S4.pdf](https://github.com/pdf-association/pdf-issues/files/5841192/aes-tests-V5-S4.pdf)

GitHub won't allow me to attach it, but the key material can be found here: https://github.com/MatthiasValvekens/pyHanko/tree/master/pyhanko_tests/data/crypto (the relevant files are named `selfsigned.*`; you can either grab them in PKCS#12 format or as a straight PEM dump of the certificate + key)

**Comment by lrosenthol** [comment]
From Adobe:
>Table 23 in section 7.6.5.2 clearly states that Crypt Filter is to be used for SubFilter is adbe.pkcs7.s5, and not for adbe.pkcs7.s4 or adbe.pkcs7.s3.
Section 7.6.4.1 and Table 20 in Section 7.6.2 clearly states that for V4 and V5, Crypt Filter (CF, StmF, and StrF) is mandatory.
This clearly implies adbe7.pkcs.s4 and V5 are incompatible and "not supported" or forbidden.

**Comment by MatthiasValvekens** [comment]
Right, that makes sense. Thanks for clarifying!
