### ISSUE TITLE
Issues with minimal PDF file example

### ISSUE THREAD

**Issue by LegionMammal978** [pdf-association/pdf-issues#271]
**Describe the bug**
H.2 contains a PDF file that "is almost the minimum acceptable PDF file". However, even though the file identifies itself as a PDF 2.0 file, it does not contain an `/ID` entry in its trailer, which is required by 7.5.5, Table 15.

Also, the text mentions:

> It is not strictly the minimum acceptable because it contains a page content stream (**Contents** in the page object), and a metadata stream.

However, it does not mention that the page object is also optional. 7.7.3 does not prohibit empty page trees, even though many PDF readers in practice refuse to accept PDF files with no pages.

**Comment by petervwyatt** [comment]
Ideally every example would also be downloadable as a fully valid and functional PDF...

**Comment by lrosenthol** [comment]
@LegionMammal978 according to ISO 32000-2 there must be at least one page - but the reasoning is ambiguous.

Table 29, the `Pages` entry is required in the `Catalog` and it points to the root of Pages tree.
Table 30, the `Kids` entry is required in a Pages tree node. The `Kids` entry is defined as an array of indirect references (to page objects or other kids nodes), which means that it *cannot* be an empty array and must consist of at least one indirect reference.

**Comment by LegionMammal978** [comment]
> Table 30, the `Kids` entry is required in a Pages tree node. The `Kids` entry is defined as an array of indirect references (to page objects or other kids nodes), which means that it _cannot_ be an empty array and must consist of at least one indirect reference.

I find that reading somewhat self-contradictory, since 3.2 gives an array object as a

> one-dimensional collection of *objects* (3.44) arranged sequentially and implicitly numbered starting at 0

Since an empty array has no objects, would it not be an array object?

Regardless, "an array of *X*" is commonly clarified to be explicitly inclusive of an empty array, depending on the particular context. Table 97 gives **OCGs** as

> A dictionary or array of dictionaries specifying the optional content
groups [...] If this entry is not present, is an empty array, or contains references only to **null** or deleted objects, [...]

Table 99 gives **Locked** as

> An array of optional content groups [...] Default value: an empty array.

Table 273 gives **RH** as

> An alternative requirement handler dictionary or an array of such dictionaries. [...] Default value: an empty array.

Table 279 gives **V** as

> An array of software identifier objects [...] If this entry is present and non-empty, [...]

and **L** as

> An array of *language identifiers* [...] If this entry is present and non-empty, [...]

Table 283 gives **R** as

> An array of rendition objects. [...] An empty array is valid.

Table 301 gives **MU** as

> An array of media player info dictionaries [...] If **MU** is also present and non-empty, **A** shall be ignored.

And so on.

If an empty array is meant to be excluded, then the standard usually calls it "an array of/specifying/consisting of one or more *X*", or it otherwise places constraints on the array that imply it is non-empty.

**Comment by car222222** [comment]
As @LegionMammal978 explains, normally an array can be empty unless explicitly des uber as a non-empty array.  In 32000-2 there certainly appears to be an implicit assumption that any array can be empty, except where this is explicitly not allowed.

But maybe this was unintended and so this assumption of non-emptiness should be made explicit, together with explicit positive statements added in all those cases when an empty array is permitted.

**Comment by petervwyatt** [comment]
I agree that PDF should always be explicitly clear about the semantics of arrays and array elements: whether an explicit empty array is valid; whether an implicitly empty array (`[ null ... ]`) is valid; whether an array with an excessive number of elements is valid; etc. See also #157. 

But I would be **very** hesitant to add any generic statement about whether arrays can or cannot be explicitly/implicitly empty until _after_ every array object in PDF is explicitly checked and confirmed. I have started down this path for the Arlington PDF Model as I note at the bottom of the (INTERNAL_GRAMMAR.md file](https://github.com/pdf-association/arlington-pdf-model/blob/master/INTERNAL_GRAMMAR.md#checks-still-needing-to-be-completed-in-iso-32000-22020)

A short-term fix would be to add a note for the specific case of the page tree, but a general fix requires a lot more work.

**Comment by MPBailey** [comment]
Peter, I don't see why "[ null ]" should be regarded as an implicitly empty array. The statement about a null value being treated as if it does not exist is specific to dictionary entries:
> A dictionary entry whose value is null (see 7.3.9, "Null object") shall be treated the same as if the entry does not exist.

I can't find any other references to null (either explicit or replacing a reference to a non-existent object) being ignored.
To pick up on one of the specific examples from this thread, the Kids entry in a pages dictionary says:
> An array of indirect references to the immediate children of this node. The children shall only be page objects or other page tree nodes.

My reading would be that an array item referencing a non-existent object should be treated as null, and is therefore invalid in the context of that array.

**Comment by petervwyatt** [comment]
I wasn't asserting that it is an empty array - I was questioning how `[ null ]` should be handled (which I arbitrarily named an "implicitly empty array") and whether this is the same as `[ ]` or not. I agree it is not mentioned anywhere. I think we'd all agree that this is an array of length = 1 (i.e. `null` array elements are definitely not "ignored") - but the issue is about the wording/phrasing we choose around array values since relying on just a length may not account for `null` elements. It will be case by case I think.

**Comment by petervwyatt** [comment]
Summarizing the concrete issue raised here that is addressable via an errata:

* Table 30, **Kids** entry - can this be an empty array `[]`? Are `null` entries permitted? 
   Depending on the answer, may have to maintain H.2

The bigger issue of handling empty arrays `[]` and arrays with `null` elements needs to be addressed on a case-by-case basis - please raise new issues for anything that is confusing.

**Comment by petervwyatt** [comment]
PDF TWG agree that **Kids** cannot be empty and cannot have `null` entries. 
State Count has to be > 0.

**Comment by LegionMammal978** [comment]
Has the PDF file in H.2 been updated to include an `/ID` entry in its trailer? That's the other part of this issue.

**Comment by petervwyatt** [comment]
There is other work afoot to address the refreshing of informative Annex H (more so than errata around the edges)... that should appear in coming months. 
Stay tuned 😁
