### ISSUE TITLE
UseAttachments missing from NonFullScreenPageMode

### ISSUE THREAD

**Issue by johnwhitington** [pdf-association/pdf-issues#275]
In 7.7.2, there are six page modes possible in the /PageMode of a document catalog: /UseNone, /UseOutlines, /UseThumbs, /FullScreen, /UseOC, and /UseAttachments.

In 12.2, Viewer Preferences, for /NonFullScreenPageMode, we would expect every value except /FullScreen to be available.

However, /UseAttachments is missing.

**Comment by petervwyatt** [comment]
If you check the old Adobe PDF specifications, this is the way it has always been specified. 
I don't know why it was never specified to be the same... @lrosenthol?

Marking this as an enhancement.

**Comment by johnwhitington** [comment]
Thanks. Here is an example file, for reference:

[out.pdf](https://github.com/pdf-association/pdf-issues/files/11260962/out.pdf)

In a Well Known PDF Reader, it behaves as expected, showing the attachments pane when not in full screen mode.

**Comment by lrosenthol** [comment]
AFAICT, it seems to be something that was just missed or added in one place but not another.

As noted, "well known implementation" doesn't care.

**Comment by petervwyatt** [comment]
If it is common behavior then let's document it.

**Comment by petervwyatt** [comment]
PDF TWG agree
