### ISSUE TITLE
Is a byte string always written in hexadecimal form?

### ISSUE THREAD

**Issue by gettalong** [pdf-association/pdf-issues#276]
In section 7.9.2.4 "Byte string type" of the PDF 2.0 spec it is stated:

>The byte string type shall be used for binary data that shall be represented as a series of bytes, where
each byte may be any value representable in 8 bits. Byte string type is a subtype of string type. For
example, byte strings are used to define a file identifier (see 14.4, "File identifiers") that is specified in
ID entry of PDF file trailer (see "Table 15 — Entries in the file trailer dictionary"). In such case byte
string is written in hexadecimal form (see 7.3.4.3, "Hexadecimal strings") and looks like

> \<B6FB54F3F8554D478DC874F11DAD0F11>

Apart from (probably) some small typos in the last two sentence ("...in *the* ID entry of *the* PDF...", "In such *a* case *a* byte string...") this description is greatly expanded from the PDF 1.7 version which only contains the first two sentences.

What is not clear to me now is whether the given example means that byte strings should now always be in hexadecimal form and may not use the literal string form anymore.

It is my understanding that the description of a dictionary entry contains information on whether a (byte) string should be encoded specially, i.e. either in hexadecimal form or literal string form. See e.g. the description of key `/Contents` in table 255 in section 12.8.1 where it says that `/Contents` should be encoded in hexadecimal form. The key `/ID` mentioned in the example has no such wording in its description.

If my understanding is correct, i.e. if byte strings can be written in both forms except where one of the forms is explicitly requested, I would propose removing the last sentence ("In such case...").

**Comment by MatthiasValvekens** [comment]
I agree that it's odd & confusing. Also, there are plenty of processors that use the "regular" parentheses notation for what is ostensibly binary data in certain circumstances, so...

@petervwyatt do you happen to remember the context in which this was added?

Either way, this piece of text looks like it was never intended to be normative, so I think we can make it work if we clean up the language and put it in an `EXAMPLE`.

**Comment by petervwyatt** [comment]
No, there is no general requirement that all byte strings are always hexadecimal strings - they can be hex or literals. However, there are specific instances where a requirement to be a hex string is specifically stated (like **ID** in the trailer and **Contents** as you state).

**Comment by petervwyatt** [comment]
I'd also suggest moving the example text as an official EXAMPLE, as in ISO-ese examples are only informative and not normative.

**Comment by gettalong** [comment]
> No, there is no general requirement that all byte strings are always hexadecimal strings - they can be hex or literals. However, there are specific instances where a requirement to be a hex string is specifically stated (like **ID** in the trailer and **Contents** as you state).

Could you please clarify where it says that the **ID** in the trailer has to be in hexadecimal format? Table 15 in section 7.5.5 "File trailer" says nothing about **ID** being in hexadecimal form. The referenced section 14.4 "File identifiers" also says nothing about them being hexadecimal.

Then I searched through the PDF 2.0 spec for the string "hexadecimal" and the only instance where it mentions that the encoding of a byte string must be in hexadecimal format is for the **Contents** entry of a digital signature dictionary.

**Comment by petervwyatt** [comment]
You are 100% correct! Trailer **ID** strings do not have to be hex strings altho they typically are done this way by producers. Only the **Contents** key of Signatures are explicitly required to be hex strings. It is a bad choice for the example... 

PS. I should have checked what I encoded into the Arlington PDF Model with the `fn:IsHexString` predicate, rather than trust the paragraph you quoted.

**Comment by gettalong** [comment]
Thanks for confirming, @petervwyatt!

I'm currently investigating a problem with a PDF that is falsely parsed by the Adobe Acrobat chrome extension (https://github.com/gettalong/hexapdf/issues/243) and thought that this might be the problem.

**Comment by mkl-public** [comment]
>Only the Contents key of Signatures are explicitly required to be hex strings.

Even that only _when **ByteRange** is present_.

(OK, that's true for at least 99.9% of all signatures, but nonetheless...)

**Comment by petervwyatt** [comment]
@mkl-public Correct. That was why I very carefully worded things as "_can be_" rather than "_is_"! 😁

**Comment by petervwyatt** [comment]
PDF TWG would like to analyze the file...

**Comment by lrosenthol** [comment]
@gettalong can you please provide a file that you believe is correct but is not processed correctly?

**Comment by gettalong** [comment]
@lrosenthol I'm sorry but I don't have a file for this. I was investigating a problem with a PDF created by HexaPDF which didn't work correctly in one viewer and narrowed it down to two possibilities, either the need for writing strings in hexadecimal form or adding the `/Length` key to the encryption dictionary with a `/V` of 4 - it was the latter, see https://github.com/gettalong/hexapdf/issues/243#issuecomment-1513333493 for details.

**Comment by petervwyatt** [comment]
@gettalong - thanks. The PDF TWG misunderstood and was concerned that there might be other issues with major implementations.

Since this is not the case, the PDF TWG agreed with the proposal above.
