### ISSUE TITLE
Clarification request regarding `bfrange` operators in ToUnicode cmaps

### ISSUE THREAD

**Issue by gettalong** [pdf-association/pdf-issues#277]
Section 9.10.3 says the following about the `dstString` of the `bfrange` operator on page 359:

> In this case, the last byte of the string shall be incremented for each consecutive code in the source code range.
> 
> When defining ranges of this type, the value of the last byte in the string shall be less than or equal to 255 - (srcCode2 - srcCode1). This ensures that the last byte of the string shall not be incremented past 255; otherwise, the result of mapping is undefined.

While the [Adobe Technical Note #5411 "ToUnicode Mapping File Tutorial"](http://www.audentia-gestion.fr/ADOBE/5411.ToUnicode.pdf) is not on the [list of normative references](https://pdfa.org/iso-32000-normative-references/), it doesn't say anything about this restriction. On the contrary, it includes the following example on page 37:

~~~
<1379> <137B> <90FE>
~~~

This would map <1379> to <90FE>, <137A> to <90FF> and <137B> to <9100>, if I understand correctly. So in this case the last byte of the string *would* be incremented past 255.

Furthermore, TN#5411 mentions in section 1.4.1: *"Also, when using “bfrange” operators, care must be taken not to cross first-byte boundaries for the CID values in a single mapping line."* This restriction bears resemblance to the one mentioned in the PDF spec, although for a different part (the `srcCode1 srcCode2` part).

The question for me is now whether the restriction in 9.10.3 is an additional restriction just for ToUnicode CMaps in PDF or if this is an error.

**Comment by petervwyatt** [comment]
@lrosenthol - would you care to comment?

**Comment by gettalong** [comment]
Thanks for clarifying!

I'm not sure if other developers had concerns about this part of the spec but it would have helped if there was a note saying that this requirement is specific to ToUnicode CMaps in PDF (so that it is clear that there *is* a difference to standard ToUnicode CMaps).

In your opinions - would it make sense to add such a note?

**Comment by petervwyatt** [comment]
Yes, I think an informative note will also help others. Being informative means the referenced TechNote gets added to the Bibliography and not the NormRefs (which is a good thing).

Proposed Note:
NOTE: the above requirements are specific to PDF and are not described in Adobe Technical Note #5411 "ToUnicode Mapping File Tutorial".
