### ISSUE TITLE
Typo in section "9.7.5.2 Predefined CMaps"

### ISSUE THREAD

**Issue by smuehlst** [pdf-association/pdf-issues#278]
In section "9.7.5.2 Predefined CMaps" after "Table 117 — Character collections for predefined CMaps, by PDF version" there is the following text:

> A PDF processor shall support Adobe-CNS1-7, Adobe-GB1-5, Adobe-Japan1-7 and Adobe-KR-9 character collections. ". Adobe-Japan2-0 and Adobe-Korea1-2 are deprecated in this document (2020).

Between the two sentences there's a stray '".' that should be removed.

Suggestion for correction:

> A PDF processor shall support Adobe-CNS1-7, Adobe-GB1-5, Adobe-Japan1-7 and Adobe-KR-9 character collections. Adobe-Japan2-0 and Adobe-Korea1-2 are deprecated in this document (2020).

**Additional context**
This report refers to the most recent free version of ISO 32000-2:2020.

**Comment by petervwyatt** [comment]
Thank you!
Editorial correction as per OP.

**Comment by petervwyatt** [comment]
PDF TWG agree
