### ISSUE TITLE
ECB mode doesn't use an Initialisation Vector

### ISSUE THREAD

**Issue by johnwhitington** [pdf-association/pdf-issues#279]
In 7.6.4.4.9 f):

"Encrypt the 16-byte block using AES-256 in ECB mode with an initialization vector of zero, using the file encryption key as the key"

should read

"Encrypt the 16-byte block using AES-256 in ECB mode using the file encryption key as the key"

A similar correction is needed to 7.6.4.4.12.

(ECB mode doesn't use initialization vectors, however some encryption libraries do use an IV of zero to put the library into ECB mode - that's just an API implementation choice, though, and not relevant in a spec like this one).

Example of someone being confused by this, and some discussion:

https://stackoverflow.com/questions/76118349/iv-for-aes-in-ecb-mode-algorithm-2-a-in-the-pdf-2-0-spec/

**Comment by MatthiasValvekens** [comment]
This is one of the corrections that will be included in the upcoming amendment. See #24.

**Comment by petervwyatt** [comment]
And if you happen to get your own no-cost version via https://pdfa.org/sponsored-standards/, you will find all the amendment errata including this one as comments (annotations)!
