### ISSUE TITLE
Table 226, T key stated as Required but should be Optional?

### ISSUE THREAD

**Issue by lrosenthol** [pdf-association/pdf-issues#28]
ISO 32000-1:2008, Table 220, has the `T` key identified as Optional.  However, ISO 32000-2:2020, Table 226, shows the same `T` key as being required.  However, in 12.7.4.2, it says:

>A field dictionary that does not have a partial field name (T entry) of its own shall not be considered a field but simply a Widget annotation.

Which clearly implies that a field dictionary need not have a `T`.   

I don't know how the Optional->Required, but I consider it a typo and we need to put it back.

**Comment by petervwyatt** [comment]
This was also the case in ISO 32000-2:2017... and as far back as the "ISO/DIS 32000-2.4" DIS ballot document in Sept 2016! But it was correct (optional) in the previous CD version of 32K-2 (published as N0670). 
I also tried looking for any official ISO comment doc resulting in this change but couldn't find any such comment (but searching for "T" is not productive).

**Comment by petervwyatt** [comment]
Proposed solution: Table 226, T key change from Required to Optional to match ISO 32000-1:2007

**Comment by lrosenthol** [comment]
Change request in from ADDS and was resolved in WG8_N0680

![image](https://user-images.githubusercontent.com/5074741/105785477-fc4b2800-5f48-11eb-91bd-b78ca2e29843.png)

However, the resolution also adds the text above that makes it optional as well!   I think the meeting was in Edinburgh...

**Comment by petervwyatt** [comment]
"ADDS" indicates a PDFa member who was involved in the Edinburgh meetings - either in person or virtually.
If you recognize this as your comment could you please comment and provide some guidance/history.

Otherwise consensus so far is to revert this change.

**Comment by MatthiasValvekens** [comment]
I obviously wasn't there so I can't say for sure, but perhaps the intention was to make `T` required for _form field_ dictionaries only. Defining dictionaries in the field tree that _lack_  the `T` entry as "mere" widget annotations (as opposed to full-fledged form fields) then eliminates the apparent contradiction.

This may be a bit of a reach, but it would explain why both appear in the same change request. Nevertheless, even if my guess is correct, the status quo is unclear at best.

**Comment by petervwyatt** [comment]
Actually ISO WG8 doc N0680 is from the Pretoria, South Africa meeting and is dated June 2014. Not Edinburgh.
I will ask if the PDF Association (@DuffJohnson) has any records of the submitter of comment ADDS081 back in early 2014.

@MatthiasValvekens I definitely agree that something needs to be corrected for the `T` key...

**Comment by MatthiasValvekens** [comment]
Just noticed this while scrolling down the list of issues, but the issue title has it backwards, right? Shouldn't the words "Required" and "Optional" be switched?

**Comment by petervwyatt** [comment]
Yes - thanks. Fixed.

**Comment by petervwyatt** [comment]
There has been no further comments so shifting to a "proposed solution" state for discussion in the PDF TWG.

**Comment by petervwyatt** [comment]
Although this issue is currently labelled as "Proposed Solution" for discussion at the next PDF Association PDF TWG, the original issue raised in the ADDS-081 comment from June 2014 will remain unaddressed AFAICT: 
"_there is no robust way to find the terminal fields in a form field tree_".

**Comment by petervwyatt** [comment]
Approved by PDF TWG
