### ISSUE TITLE
/Pattern is not permitted as a value in ColorSpace subdictionary of  resource dictionary (Table 34) 

### ISSUE THREAD

**Issue by bdoubrov** [pdf-association/pdf-issues#280]
Current definition of ColorSpace subdictionary in resource dictionary (Table 34) says:

> A dictionary that maps each resource name to either **the name of a device-dependent colour space** or an array describing a colour space (see 8.6, "Colour spaces")

However, apart from "the name of a device-dependent colour space" the resource name can also be mapped to **/Pattern** name object. 

This is also explicitly stated in the description of the operands for **CS/cs** operators in 8.6.3 (2nd paragraph after Table 61) and a similar text in Table 73 - Colour operators:

> Within a content stream, the **CS** or **cs** operator establishes the current colour space parameter in the graphics state. The operand shall always be name object, which either identifies one of the colour spaces that need no additional parameters (**DeviceGray**, **DeviceRGB**, **DeviceCMYK**, or some cases of **Pattern**) or shall be used as a key in the **ColorSpace** subdictionary of the current resource dictionary (see 7.8.3, "Resource dictionaries"). In the latter case, the value of the dictionary entry in turn shall be a colour space array or name. A colour space array shall never be inline within a content stream.

I would suggest modifying the description of ColorSpace entry in Table 34 as:

> A dictionary that maps each resource name to either the name of a colour space with no additional parameters (**DeviceGray**, **DeviceRGB**, **DeviceCMYK**, or **Pattern**), or an array describing a colour space (see 8.6, "Colour spaces").

**Comment by petervwyatt** [comment]
PDF TWG agree
