### ISSUE TITLE
Link Structure Element restrictions in 14.8.4.7.2 are slightly nonsensical

### ISSUE THREAD

**Issue by faceless2** [pdf-association/pdf-issues#281]
In the description of the `Link` element, final few paragraphs if 14.8.4.7.2 on p764, we have this:

> The following items may be children of a link element:
> * One or more content items or other ILSEs (except other links) if `A`, `Dest` and `PA` keys of all of them have identical values
> * One object reference (see 14.7.5.3, "PDF objects as content items") to one link annotation associated with the content

A _content item_ is defined to mean a) a marked-content sequence, or b) an object reference. And _ILSE_ means another Structure Element (accurate enough definition for this discussion)

So there are lots of problems here;

1. The first point says I can include "one or more content items", which includes OBJR to link annotations, and the second point says I can only include one. If the bullet points are to be joined with "and", it's contradictory. If joined with "or", the second is redundant. And the paragraph preceding the list gives no hint as to which applies.
2. The `A`, `Dest` and `PA` keys are prohibited on all content in the first point, which includes ILSEs - on which the `A` key defines attributes! We don't want that. The intent is that all _link annotations_ within the Link element have the same values for these keys, but that's not what's written.

and lastly, all of this is wrapped in a "may contain" rather than should/shall, which means this specific-but-incorrect rule is just a hint. Which I don't think is the intent either.

I'll suggest some options for alternative wording, in the full knowledge that Matthew will jump on it and improve it. I've specifically used "should" for the restriction that all links point to the same thing.

Option 1, replace that text with this

> The following items may be children of a link element:
> * One or more content items or other ILSEs (except other links)
>
> If a link element contains object references (see 14.7.5.3, "PDF objects as content items") to more than one link annotation, all should have identical values for the `A`, `Dest` and `PA` keys

Option 2 is to remove everything from after Note 1 at the bottom of Table 368 to the point just before 14.8..4.7.3, and instead put this in the Description for the Link element in table 368, where it most definitely belongs. Suggested replacement text for the Description:

> An association between content enclosed by the **Link** structure element and a corresponding link annotation (see 12.5.6.5, "Link annotations"). In tagged PDF, **Link** provides functionality comparable to HTML hypertext links. A **Link** structure element may have one or more content items or other ILSEs (except other links) as children.
>
> If more than one link annotation is referenced in a **Link** structure element, they should all have identical values for the `A`, `Dest` and `PA` keys

This way it's aligned to the way Annot and Form are described.

----

Edit: I'm aware this is largely a copy/paste from 32000-1, which had a note - "use of the Link structure element to enclose multiple link annotations is deprecated". That note has now been removed, which goes some way to explaining how the text got into this state.

**Comment by mrbhardy** [comment]
Hi.  They are nonsensical and we fixed it in the following: https://github.com/pdf-association/pdf-issues/issues/133

**Comment by mrbhardy** [comment]
I believe this is in the official amendment and, along with a fix to Tables in P, were one of the reasons I pushed so hard to get 32005 and 14289-2 based off of that amendment...

**Comment by petervwyatt** [comment]
See https://pdf-issues.pdfa.org/32000-2-2020/clause14.html#Table368

But, no, as indicated by "gray ISO" logos errata #133 was **after** Amd1 was prepared and submitted, and thus is not included - only the "blue ISO" logos made it into Amd1 (i.e. those labelled as "ISO approved" here in GitHub). However #133 has been officially approved by ISO TC 171 SC 2 WG 8 in a later round of technical reviews (labelled "ISO submitted"). 

Note that this can also be confirmed by downloading the no-cost ISO 32000-2 as this includes the Amd1 XFDF file (as comments).

PS. As soon as Amd1 is officially published by ISO I will update labels.
