### ISSUE TITLE
Go-To-3D-View actions section omits information on usage with 3D RichMedia

### ISSUE THREAD

**Issue by datalogics-pgallot** [pdf-association/pdf-issues#282]
Clause 12.6.4.16 "Go-To-3D-View actions" is described solely in terms of 3D annotations, but should cover both 3D annotations and RichMedia annotations with 3D content.

That implies that the first sentence of this clause should be changed to:
A go-to-3D-view action (PDF 1.6) identifies a 3D _or RichMedia_ annotation and specifies a view for the annotation to use (see 13.6, "3D Artwork").

it also implies some tweaks to the 'V' Value text in Table 220:
* An integer specifying an index into either the VA array in the 3D stream (see "Table 311 — Entries in a 3D stream dictionary"), _or the Views array of the RichMediaContent dictionary (see "Table 341 — Entries in a RichMediaContent dictionary), as appropriate for the specified Annotation._
* A text string matching the IN entry in one of the views in either the VA array (see "Table 315 — Entries in a 3D view dictionary") or _the Views array of the RichMediaContent dictionary (see "Table 341 — Entries in a RichMediaContent dictionary), as appropriate for the specified Annotation._
* A name that indicates the first (F), last (L), next (N), previous (P), or default (D) entries in the VA array _or Views array._

There are four more mentions of the VA array in the remaining text following the table that should likewise be similarly expanded .

**Comment by petervwyatt** [comment]
PDF TWG agree
