### ISSUE TITLE
S entry of Table 331 references wrong clause.

### ISSUE THREAD

**Issue by datalogics-pgallot** [pdf-association/pdf-issues#283]
The S entry of Table 331 has the following text:
"A comment reference is an indirect reference to a projection annotation that may be associated with this 3D measurement. See "_Table 341 — Entries in a RichMediaContent dictionary_".

Tables 328,329,and 330 have similar S entries with near identical value descriptions but more appropriately reference clause 13.6.7.4 "3D measurements and projection annotations" instead.

**Comment by petervwyatt** [comment]
PDF TWG agree.
