### ISSUE TITLE
PDFDocEncoding table lists wrong Unicode equivalent for code point 0x16

### ISSUE THREAD

**Issue by kmoon-chromium** [pdf-association/pdf-issues#285]
**Describe the bug**
D.3 PDFDocEncoding character set

PDFDocEncoding code point 22 (0x16) is mapped to U+0017 (SYNCHRONOUS IDLE)
PDFDocEncoding code point 23 (0x17) is mapped to U+0017 (END OF TRANSMISSION BLOCK)

SYNCHRONOUS IDLE is actually U+0016, and code point 22 probably was meant to be mapped to U+0016.

**Comment by petervwyatt** [comment]
PDF TWG agree
