### ISSUE TITLE
Why isn't MathML a standard structure owner for attributes?

### ISSUE THREAD

**Issue by faceless2** [pdf-association/pdf-issues#286]
This isn't a bug exactly, but it does feel like an oversight.

Table 376 lists various standard structure owners for attributes in a tagged PDF. We have owners for various standards - HTML, CSS - but we _don't_ have an owner for MathML, despite it being a first-class namespace in PDF 2.0

As an example, if I have the following MathML:

```html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">...</math>
```

I currently have a choice when turning this into a StructElem: I can use UsersProperties:

```
<<
 /Type /StructElem
 /S /math
 /NS 33 0 R  % the MathML namespace
 /A [
  <<
    /O /UserProperties
    /P [ << /N (display) /V (block) >> ]
  >> ]
>>
```
or I can use the MathML namespace
```
<<
 /Type /StructElem
 /S /math
 /NS 33 0 R  % the MathML namespace
 /A [
  <<
    /O /NSO
    /NS 33 0 R
    /display (block)
  >> ]
>>
```

Neither of these are quite right: the attributes are not defined in the MathML namespace (in the XML sense; they don't need a namespace prefix), and UserProperties loses their semantics.

Is this important? It's certainly going to matter when deriving HTML from PDF or when using well-tagged PDF, and it will impact on accessibility if those attributes are critical to the understanding of the equation - which is the case for (eg) `mathvariant` in MathML4 (see https://www.w3.org/TR/mathml4/#presm_commatt - _"Note that this class is more than styling, it typically conveys semantic intent"_)

Because of this I can't see any place to fix it other than 32000 itself. My proposal would be to add a `MathML` entry to table 376, where it would be "attributes governing MathML structure elements". We already changed `CSS-3.00` to `CSS-3` in the 2020 dated revision, so I hope this isn't too controversial. Failing that, I'd settle for some best-practice guidance.

**Comment by petervwyatt** [comment]
@mrbhardy ?

**Comment by faceless2** [comment]
If that's the intention, that's fine. But I just want to underline my point that this is going to require special handling for anyone processing to or from XML/HTML.

The example you'd given above has attributes with a namespace. So, without any special knowledge that the MathML namespace is different, anyone kconverting an element with those attributes to XML or HTML would give you:

```xml
<m:mathelement xmlns:m="http://www.w3.org/1998/Math/MathML" m:depth="4em" m:width="400px" m:height="5em">
```
which isn't correct - it isn't valid MathML. What we want is
```xml
<m:mathelement xmlns:m="http://www.w3.org/1998/Math/MathML" depth="4em" width="400px" height="5em">
```

It also means going the other way, it's impossible to represent this technically valid, if slightly useless XML structure in PDF

```xml
<m:mathelement xmlns:m="http://www.w3.org/1998/Math/MathML" depth="4em" m:depth="5mm">
```

Finally, this feels a little laboured for what should be a first-class attribute owner in PDF, although I agree neither of these points are show-stoppers.

However we absolutely need to clarify this in the documentation. It's not at all obvious this is how it should work.

**Comment by mrbhardy** [comment]
@faceless2 I'm completely in agreement we should fix the documents, but the output syntax isn't controlled directly by the PDF syntax.  I would argue that you have to understand the target namespace to convert to it and that a processor would have to do that work.  The intent was to make the namespace mechanism the primary mechanism over the longer term...

**Comment by faceless2** [comment]
So long as we have a process that's defined and commonly understood, I'm happy. And on reflection I am taking a very XML centric view of this because a) that's how MathML is defined and b) that's how we present the structure tree in our API.

So as we need some docs, here's my offering:

> Note: The Attribute  owner (as defined by the O key) identifies the semantic owner of the attribute; it does not imply anything about the way that attribute is represented outside of PDF. For example, attributes with an `O` key of `CSS-3` may be represented in a CSS stylesheet; attributes with an `O` key of `HTML-5.00` may be represented as attributes in an HTML document (which does not have the concept of namespaces), and attributes with an `O` key of `NSO` and an `NS` of `http://www.w3.org/1998/Math/MathML` may be represented in XML as attributes with a default namespace in an element belonging to the `http://www.w3.org/1998/Math/MathML` namespace.

Something like that would cover it for me, and I think it reflects the point you're making too - and I appreciate that you don't want to get too prescriptive here. Drop something like that in at the end of 14.7.6.1 and that would cover it.

**Comment by petervwyatt** [comment]
@DuffJohnson @mrbhardy - can you please progress for our next PDF TWG Meeting?

**Comment by mrbhardy** [comment]
@faceless2 I like the direction, but we need to take the normative language (may) out of it.  How about:

> NOTE The attribute owner, defined through the **O** and **NS** entries in the attribute object, define an owner for each attribute, but do not provide information on transformation of those attributes into other formats.  When considering formats such as HTML and MathML, attributes would be transformed to meet the syntactic requirements of those formats.

**Comment by faceless2** [comment]
Works for me, particularly as this issue will remain public for anyone that needs more info.

**Comment by petervwyatt** [comment]
PDF TWG agree

**Comment by faceless2** [comment]
Noting reference to same issue reported previously at https://github.com/pdf-association/pdf-issues/issues/72

**Comment by davidcarlisle** [comment]
@faceless2 thanks for linking to this issue during my presentation on 2025-03-06 (which I missed at the time as I was concentrating on the screen share and not on the chat, sorry). Fortunately the resolution here is compatible with what we ended up with generating from LaTeX. Even though it's a bit odd to use mathml namespace for no-namespace attributes, so long as we all do the same it's certainly workable.
