### ISSUE TITLE
Value of an attribute defined by multiple classes associated with a StructElem is undefined

### ISSUE THREAD

**Issue by faceless2** [pdf-association/pdf-issues#289]
If a StructElem is a member of two classes, and both classes define an attribute value, which takes priority? Earlier classes in the class list, later classes in the class list, or some other priority rule? The spec tells us that directly defined attributes (in the `A` key) take priority over attributes defined in classes, but nothing more is said on priority.

A concrete example: what is the Placement attribute for the `P` element - Block or Inline?

```
1 0 obj
<<
 /Type /StructElem
 /S /P
 /C [ /ClassA /ClassB ]
 ...
>>

2 0 obj
<<
  /Type /StructTreeRoot
  /ClassMap <<
    /ClassA << /O /Layout /Placement /Block >>
    /ClassB << /O /Layout /Placement /Inline >>
  >>
  ...
>>
```

I suspect this one's for you, @mrbhardy. For reference here's the text relating to this from 32000-2:2020 - section 14.7.6.2

> If many structure elements share the same set of attribute values, they may be defined as an attribute class sharing the identical attribute object. Structure elements shall refer to the class by name. The association between class names and attribute objects shall be defined by a dictionary called the class map, that shall be kept in the ClassMap entry of the structure tree root (see "Table 354 — Entries in the structure tree root"). Each key in the class map shall be a name object denoting the name of a class. The corresponding value shall be an attribute object or an array of such objects.

> The C entry in a structure element dictionary (see "Table 355 — Entries in a structure element dictionary") shall contain a class name or an array of class names (typically accompanied by revision numbers as well; see 14.7.6.3, "Attribute revision numbers"). For each class named in the C entry, the corresponding attribute object or objects shall be considered to be attached to the given structure element, along with those identified in the element’s A entry. If both the A and C entries are present and a given attribute is specified by both, the one specified by the A entry shall take precedence.

**Comment by faceless2** [comment]
Re, attributes not in classes, we have this sentence right at the end of 14.7.6.1

> When an array of attribute objects is provided, the value of the O and NS keys may be repeated across attribute objects. If a given attribute is specified more than once, the later (in array order) entry shall take precedence.

That's for attributes directly defined on an element, not classes, but it seems obvious to me the same rule should apply. In which case as a proposed solution, how about something similar inserted before the final sentence at the end of 14.7.6.2

> If a given attribute is specified more than once in a class, the later (in array order) entry shall take precedence. If a given attribute is defined in multiple classes in the `C` array entry, the value from the class that comes later in the array shall take precedence

**Comment by petervwyatt** [comment]
@mrbhardy - can you please progress for our next PDF TWG Meeting?

**Comment by petervwyatt** [comment]
I think you mean 14.7.6.2 😁 but otherwise 👍

**Comment by petervwyatt** [comment]
PDF TWG agree

**Comment by mrbhardy** [comment]
> I think you mean 14.7.6.2 😁 but otherwise 👍

Fixed!
