### ISSUE TITLE
Wording around CIEJab is still unclear

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#29]
I've just had another developer who misunderstood the text in 7.4.9 around using CIEJab for JPXDecode.

It says "Data used in PDF image XObjects shall be limited to the JPX baseline set of features, except for enumerated colour space 19 (CIEJab)." My understanding, supported by the wording in Adobe v1.7, is that CIEJab is not in the baseline set, but is allowed. 

That's immediately followed by "In addition, enumerated colour space 12 (CMYK), which is part of JPX but not JPX baseline, shall be supported in a PDF file." I think the difference in the way that CIEJab and CMYK are described contributes to the confusion.

I suggest something like: "Data used in PDF image XObjects shall be limited to the JPX baseline set of features. In addition, enumerated colour spaces 12 (CMYK) and ### (CIEJab), which are part of JPX but not JPX baseline, shall be supported in a PDF file."

**Comment by petervwyatt** [comment]
I don't believe this is correct... CIEJab is permitted in JPX Baseline according to ISO/IEC 15444-2:2004 (whereas CMYK is not):

Referring to ISO/IEC 15444-2:2004: 
- Clause "M.6.1.3 Fallback" defines that "... JPX baseline is defined in M.9"
- Clause "M.9.2.4 Colour specification" then goes on to explicitly state that CIEJab can be in JPX Baseline (see bullets 4 and 5). But CMYK is not permitted (alone) by any of the 7 bullets.
- CIEJab (value 19) is defined in "Table M.25 - Additional legal EnumCS values" in subclause M.11.7.3.1. This is the same table that also defines CMYK (value 12). The last sentence of the paragraph before Table M.25 says "Valid EnumCS values are those values defined for the Enumerated method in the JP2 file format and the values defined as follows (Table M.25)".

This is why we changed the words from Adobe - 'cos they were wrong / confusing! :-)

The words in ISO 32000-2:2020 are correct: we need to **exclude** CIEJab from JPX Baseline and **add** CMYK to make the set colour spaces that JPEG 2000 data in PDF can use.

**Comment by MPBailey** [comment]
Thanks Peter, that sounds pretty conclusive. I wonder if we could replace "except for enumerated colour space 19 (CIEJab)." with "excluding for enumerated colour space 19 (CIEJab)."?

**Comment by petervwyatt** [comment]
Proposed solution: "... except for ..." --> "... excluding ..."
