### ISSUE TITLE
PDF version of the IRT entry in Table 172 is not entirely correct

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#297]
PDF version of the **IRT** entry in Table 172 is not entirely correct. See also https://github.com/pdf-association/arlington-pdf-model/pull/82

The Adobe PDF Reference for PDF 1.5 describes **IRT** in section 8.4 Annotation States. However the key **IRT** was only explicitly listed in Table 8.19 for Text Annots. The index in Adobe PDF 1.5 also explicitly stated "IRT entry (text annotation dictionary)" and thus limited it to text annots. The PDF 1.5 errata (8/28/2003) doesn't mention **IRT** either so no help there. The Adobe PDF Reference for PDF 1.6 then has IRT listed in table 8.17 Markup annots with version 1.5 implying that it was actually for all markup annots and not just text annots.

Text should more accurately state:

> _(Required if an **RT** entry is present, otherwise optional; PDF 1.5 for text annotations only, PDF 1.6 for other markup annotations)_ ...

**Comment by lrosenthol** [comment]
I would say that the 1.5 text was an oversight not a technical decision and have it apply to all markups from 1.5 on

**Comment by petervwyatt** [comment]
@lrosenthol - Adobe PDF 1.5 is very clear that IRT only applies to text annots. Do you mean the Adobe implementation actually added IRT to other annots at that time?

**Comment by petervwyatt** [comment]
@lrosenthol - gentle poke please

**Comment by petervwyatt** [comment]
Thanks. PDF TWG agree.
