### ISSUE TITLE
Wrong PDF version of BS key in Link and FreeText annotations

### ISSUE THREAD

**Issue by MaximPlusov** [pdf-association/pdf-issues#299]
Table 176 (Link annotation) and Table 177 (FreeText annotation) contain `(Optional; PDF 1.6)` for BS entries. But these keys for these annotations were actually introduced in PDF 1.3.

See also https://github.com/pdf-association/arlington-pdf-model/pull/86

**Comment by petervwyatt** [comment]
Confirmed in Table 7.9 (p. 400-401) in Adobe PDF 1.3 Reference.

**Comment by petervwyatt** [comment]
PDF TWG agree
