### ISSUE TITLE
Unclear wording in 7.10.3 - Type 2 (exponential interpolation) functions

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#30]
The first sentence of the first para under Table 40 says:
  "Values of Domain shall constrain x in such a way that if N is not an integer, all values of x will be nonnegative,
and if N is negative, no value of x will be zero."

We have a sample file that has opened a debate about whether those are two separate statements, or if the second clause is a follow on from the first.

In other words, which of these is it?

a) "Values of Domain shall constrain x in such a way that:
* if N is not an integer, all values of x will be nonnegative; and
* if N is negative, no value of x will be zero."

b) "Values of Domain shall constrain x in such a way that if N is not an integer, all values of x will be nonnegative,
and if N is a negative integer, no value of x will be zero."

My reading woiuld be a), but a couple of editing applications seem to be happy to retain a negative non-integer value of N in combination with a Domain of [ 0 1 ] when updating files.

Thanks

Martin

**Comment by petervwyatt** [comment]
Are you able to share a test PDF?

**Comment by petervwyatt** [comment]
And I would also agree with your interpretation (a).

**Comment by MPBailey** [comment]
Sorry, this is a customer file that I can't share.

**Comment by MPBailey** [comment]
I managed to obfuscate the file sufficiently that I could upload. The relevant function is object 36.

[DomainN_Interactions.new.pdf](https://github.com/pdf-association/pdf-issues/files/5968742/DomainN_Interactions.new.pdf)

**Comment by petervwyatt** [comment]
Proposed solution (para below Table 40): split out as dual bullet points as formatted above by @MPBailey (so concluding (a) is the correct interpretation)

**Comment by MPBailey** [comment]
I'm happy with that technically, but it does seem to say that some existing PDF files (and creators) are invalid, where you could not say that with certainty before. Are we all OK with that?

**Comment by petervwyatt** [comment]
The whole point of the exercise is to remove ambiguities and get precision of what is and is not valid PDF. Any change to the spec can make existing extant data files technically invalid, but all processors can (and most do!) support malformations of their choice. It is also unknown whether malformations are intentional or an unintentional side effect of insufficiently thought-out code...

**Comment by petervwyatt** [comment]
PDF TWG agreed
