### ISSUE TITLE
Can a PDF integer have leading zeros?

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#300]
Clause 7.3.3 states:

> An integer shall be written as one or more decimal digits optionally preceded by a sign. The value shall be interpreted as a signed decimal integer and shall be converted to an integer object.

Should this really include that a valid PDF integer can have leading zeros?
e.g. `0123` or even `00000123`

And similar wording for numbers permits `00001.23` too.
Is this intended/intentional?

**Comment by lrosenthol** [comment]
Agreed.  Most definitely allowed.

**Comment by petervwyatt** [comment]
And clearly some implementations definitely _don't_ support this (I guess they figure adding spaces is not much harder than adding `0`s 😀 - or maybe they use program language built-in integer parsing which may vary), but I accept the wording has never prohibited.

Suggest we add an informative note (below the 2nd last para about PostScript syntax) and a related example to both EXAMPLE 1 and EXAMPLE 2 clarifying the situation:

* NOTE: PDF permits multiple leading 0 digits in numeric objects,
* EXAMPLE 1 add: -00123
* EXAMPLE 2 add: -001.23

**Comment by petervwyatt** [comment]
PDF TWG agree but only use examples and no NOTE ("permits" does not imply that we want this to happen)

**Comment by a20dev** [comment]
Better example: -00987 (this clarifies that the radix is not 8).
