### ISSUE TITLE
Nesting rules for BX/EX operators with respect to BT/ET and q/Q

### ISSUE THREAD

**Issue by pesco** [pdf-association/pdf-issues#302]
The standard allows the BX/EX compatibility section operators in content streams at both the content stream level and within text objects, according to Figure 9 (section 8.2 Graphics objects) - similar to q/Q (graphics state) and BMC/EMC (marked content). It says that pairs of BX/EX can be nested (7.8.2, last paragraph), but contrary to q/Q (cf. 9.4.1, last paragraph) and BMC/EMC (cf. 14.6.1, last paragraph) , it does not state that nesting must be "balanced" with respect to BT/ET, i.e. whether the following would be legal:

    BX ... BT ... EX ... ET

Is this intentional or an oversight?

The same question _also_ applies to the following combinations:

 - BX/EX vs. q/Q
 - BX/EX vs. BMC/EMC
 - q/Q vs. BMC/EMC

As far as I can see from Figure 9, the four pairs BT/ET, BX/EX, q/Q, and BMC/EMC are those with the relevant nesting behavior. Specifically, all are allowed at both the content stream level and in text objects while the other kinds of objects in the figure (paths, clipping paths, in-line images, external objects, and shading objects) do not seem to have operator overlap.

PS: I have not mentioned BDC, assuming it is equivalent to BMC with regards to this issue.

**Comment by petervwyatt** [comment]
It is an oversight - all paired operators need to be "properly balanced".

Proposed solution:
* add text to the end of the para above Table 33 which describes **BX**/**EX**:
> All pairs of matching operators (marked-content operators **BMC**, **BDC**, and **EMC** (see 14.6 Marked content); text object operators **BT** and **ET** (see 9.4, "Text objects"); the compatibility operators **BX** and **EX** (see Table 33 "Compatibility operators") and the graphics state save and restore operators **q** and **Q** (see Table 56 "Graphics state operators")) shall be properly (separately) nested.

* add text to the para below Table 352 Marked content operators to include mention of **BX**/**EX**:
> When the marked-content operators **BMC**, **BDC**, and **EMC** are combined with the text object operators **BT** and **ET** (see 9.4, "Text objects"); the compatibility operators **BX** and **EX** (see Table 33 "Compatibility operators"); or the graphics state save and restore operators **q** and **Q** (see Table 56 "Graphics state operators") each pair of matching operators (**BMC**…**EMC**, **BDC**…**EMC**, **BT**…**ET**, **BX**...**EX** or **q**...**Q**) shall be properly (separately) nested.

**Comment by petervwyatt** [comment]
PDF TWG agree

**Comment by jhcarl0814** [comment]
(This note is for anyone who is writing parser for pdf format and thinking that content streams can be parsed into a tree structure because of those paired operators.)
The 0th content stream of the 0th page of the pdf specification itself (`ISO_32000-2_sponsored-ec2.pdf`) starts with this:
```
/Artifact<</Type/Page>> BDC
/Span<</Lang (en-US)>> BDC
q
/GS0 gs 0 0 595.25 842 re W* n
BT
/F0 11 Tf 379.9 691.45 Td
( )Tj
ET
EMC
EMC
Q
/Span<</Lang (en-US)/MCID 1>> BDC
...
```
If you maintain a stack of "expected closing operators", it will end up like this:

1. encounter `BDC` instruction: `[EMC]`
2. encounter `BDC` instruction: `[EMC, EMC]`
3. encounter `q` instruction: `[EMC, EMC, Q]`
4. encounter `BT` instruction: `[EMC, EMC, Q, ET]`
5. encounter `ET` instruction: `[EMC, EMC, Q]`
6. encounter `EMC` instruction: `error, not properly nested`

A workaround is to (relax the constraint in the specification and) maintain two stacks: all paired operators except `q` and `Q` use one, `q` and `Q` alone use the other.

**Comment by mkl-public** [comment]
I'm not sure that from the wording alone - _shall be properly (separately) nested_ - I would have understood correctly what is required here.
Furthermore, this clarification, the ISO approved resolution, did not come into being before 2023, and then only has been provided for ISO 32000-2. So many PDF generating tools have been implemented without awareness for it and you have to be prepared to be confronted with PDFs without proper nesting.
Also be aware that `ISO_32000-2_sponsored-ec2.pdf` is only claiming to be PDF-1.7. Thus, it may well have been created by a tool based on ISO 32000-1 alone.

**Comment by jhcarl0814** [comment]
@mkl-public 
Thanks for your tip! Now I know how to parse it.
