### ISSUE TITLE
Apparent contradiction in wording for marked content operators

### ISSUE THREAD

**Issue by pesco** [pdf-association/pdf-issues#303]
14.6.1, Note 1 states:
> This [sequence bracketed by BMC/BDC and EMC] is a sequence not simply of bytes in the content stream but of complete graphics objects.

However, the marked content operators are allowed inside text objects which would seem to imply that in such a case they cover a partial graphics object.

I am assuming that a (complete) text object is what is bracketed by the BT and ET operators based on their description in 9.4.1 (paragraph 3) and Table 105 in 9.4.1, as well as Figure 9 in 8.2 "Graphics objects".

**Comment by petervwyatt** [comment]
I'm not sure what NOTE 1 is trying to state or imply... maybe the simplest solution is to just delete it and remove the confusion.

**Comment by pesco** [comment]
> I'm not sure what NOTE 1 is trying to state or imply...

My reading is that it wants to say that marking content works at the semantic (object) level rather than at the lexical (byte) level. Maybe this was deemed necessary due to the wording in the first paragraph (of 14.6.1) - emphasis mine:

> Marked-content operators (PDF 1.2) may identify **a portion of a PDF content stream** [...]

**Comment by lrosenthol** [comment]
I agree with @petervwyatt - just remove the note!

**Comment by petervwyatt** [comment]
PDF TWG agree
