### ISSUE TITLE
Documentation on sub page navigation seems to be insufficient

### ISSUE THREAD

**Issue by jpakkane** [pdf-association/pdf-issues#304]
I'm trying to create a presentation PDF file that has a heading and a few bullet points and said points should appear when navigating on the page. Basically this is the exact use case described in 12.4.4.2. I have not managed to make this happen as the documentation is quite limited and possibly even misleading.

[The PDF file I managed to create is here](https://github.com/pdf-association/pdf-issues/files/11826184/subpage.pdf).

The basic setup is that the bullets are in optional content groups that are hidden by default. Then there is a subpage navigation setup that should show the bullets one by one (and hide them when going backwards).

What makes debugging this even harder is that most PDF viewers ignore subpage navigation. Okular, Chromium, Firefox and Apple Preview ignore subpage navigation info. The only viewer that does anything with this is Acrobat Reader and even that behaves weirdly. There are also very few if any sample documents with PresSteps defined (that I could find, at least) so one can't even look into existing docs on how things should work. Neither LibreOffice nor Keynote try to create subpage navigation tags. The most common solution seems to be to simulate that by creating multiple pages instead.

12.4.4.2 says the following:

> When a user navigates to a page, if the page dictionary has a PresSteps entry, the node specified by that entry shall become the current node.

and then:

> If the user requests to navigate forward (such as an arrow key press) and there is a current navigation node, the following shall occur

> The sequence of actions specified by NA (if present) shall be executed.

 Just a few paragraphs later in the same chapter it says:

> If the user requests to navigate to another page (regardless of whether there is a current node) and that page’s dictionary contains a PresSteps entry, the following shall occur

> If the navigation request was forward, or if the navigation request was for random access (such as by clicking on a link), the actions specified by NA shall be executed and the node specified by Next shall become the new current node, as described previously.

These two statements seem to be contradictory. The first action either is or is not taken for seemingly the same operation. At least I can't reasonably understand what the difference between the two is (or if it even exists and the latter should always be done).

If you open the document in Acrobat Reader, start presenter mode and navigate to the second page, the first bullet is already visible. This means that the NA action on the first navigation step has been performed. However if you close the document, reopen it, navigate to the second page and then enable presenter mode, the bullet item is also shown. Even though the user comes to the page via "navigation" rather than "requesting to navigate to a new page". This is all very confusing, as these steps are contradictory and seemingly both apply at the same time but in practice the latter seems to always happen.

I have no idea what the underlying issue here is. My doc might well be malformed somehow, but with the current documentation it is really difficult to determine what the correct syntax should be.

**Comment by petervwyatt** [comment]
Extremely minor error and zero to do with the reported issue: but the 2nd line should start with `%` to make it a comment line that then contains the 4-byte binary file marker bytes.

**Comment by jpakkane** [comment]
After fiddling around enough I managed to create a PDF document that works as expected in Adobe Reader:

[subpage_working.pdf](https://github.com/pdf-association/pdf-issues/files/11851487/subpage_working.pdf)

However there is one issue that could be considered either a bug in Adobe Reader or an omission in the standard. If you navigate the document (in presentation mode) and reach the end of the second page, you have to press right twice to get to page three. The same happens if you go backwards from page 3 to 2 and to 1. Only one press should be needed to move to the next page in sequence. However the PDF spec does not specify (in 12.4.4.2 at least) what should happen when the user is on a navigation node that has no `next` entry and navigates forwards (and equivalent for backwards navigation). IMHO the correct behaviour should be that if the `next` entry is missing, the PDF viewer should navigate to the following page.

The PDF creator could possibly create a fake navigation node with a page change action but that is extra works and this is such a common case that it should work out of the box.

**Comment by petervwyatt** [comment]
@lrosenthol - care to comment?

**Comment by sgaither** [comment]
I have done this using internal creation tools that do work as expected both going forward and backward. That said, there is indeed an Acrobat viewer bug where it does not do the right thing if you get to the very last bullet and try to go back (it will take you to the prior page instead); similarly, if you go all the way back to before the first bullet and hit forward it will jump to the next slide.  So as you have noted, there is (so far as I know) bo way to get the behavior exactly correct.  
[bullet-live.pdf](https://github.com/pdf-association/pdf-issues/files/14181389/bullet-live.pdf)

**Comment by petervwyatt** [comment]
Thanks @sgaither for confirming a vendor issue.
 
Fom @jpakkane: 
> However the PDF spec does not specify (in 12.4.4.2 at least) what should happen when the user is on a navigation node that has no next entry and navigates forwards (and equivalent for backwards navigation). IMHO the correct behaviour should be that if the next entry is missing, the PDF viewer should navigate to the following page.

This seems to me to be the remaining issue from a spec PoV, as we don't address implementation issues here.

**Comment by petervwyatt** [comment]
Proposing a solution in 12.4.4.2:

* For the first bulleted list (covering the navigate forward case AND having a current navigation node), append to bullet **b)**: "_If there is no node specified by **Next** then navigate to the next page. If the current page is the last page, then the current navigation node remains unchanged._"

* For the second bulleted list (covering the navigate backward case AND having a current navigation node), append to bullet **d)**: "_If there is no node specified by **Prev** then navigate to the previous page. If the current page is the first page, then the current navigation node remains unchanged._"

**Comment by sgaither** [comment]
Thank you Peter!  This does seem like a very reasonable modification.  I have not yet been able to work with the Acrobat viewer team at Adobe to validate the bug.
