### ISSUE TITLE
Attribute revision numbers are deprecated in PDF 2.0

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#305]
The first sentence in the last para of subclause 14.7.6.1 states:
> The **C** entry in a structure element dictionary (see "Table 355 — Entries in a structure element dictionary") shall contain a class name or an array of class names (typically accompanied by revision numbers as well; see 14.7.6.3, "Attribute revision numbers").

Attribute revision numbers are deprecated in PDF 2.0 so there is no "typically" any more. We also note deprecation whenever a topic is mentioned, rather than relying on a user to follow links. So a better sentence construction would be:
> The **C** entry in a structure element dictionary (see "Table 355 — Entries in a structure element dictionary") shall contain a class name or an array of class names (possibly accompanied by revision numbers (_deprecated in PDF 2.0_); see 14.7.6.3, "Attribute revision numbers").

**Comment by DuffJohnson** [comment]
Concur. No need for PDF/UA TWG review on this, IMO.

**Comment by mrbhardy** [comment]
@DuffJohnson @petervwyatt agreed, let's consider this approved.

**Comment by petervwyatt** [comment]
PDF TWG agree

**Comment by petervwyatt** [comment]
Clause number was incorrect - should be 14.7.6.2
