### ISSUE TITLE
Table 91: slightly confusing "uppercase I"

### ISSUE THREAD

**Issue by pesco** [pdf-association/pdf-issues#306]
Table 91 (Entries in an inline image object) in 8.9.7 (Inline images) lists the abbreviation for Interpolate as

> I (uppercase I)

which is logically unambiguous with respect to mistaking it for a lowercase L, but less useful than "uppercase i". The latter is also used in Table 92 below, with "Indexed".

**Comment by petervwyatt** [comment]
PDF TWG agree
