### ISSUE TITLE
Name- and number-tree handling of Name and Num array "keys" which are null

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#307]
See https://github.com/veraPDF/veraPDF-library/issues/1355 and https://github.com/pdf-association/arlington-pdf-model/issues/90.

One of the issues in https://github.com/veraPDF/veraPDF-library/issues/1355 is that the _key_ in the `name-tree` is `null` and name tree keys are defined as "_where each keyi shall be a string_" and "_The keys shall be sorted in lexical order_". `number-tree` use slightly different wording for the key type ("_each keyi is an integer_" - "is" vs "shall") but the same wording for the sorting requirement ("_The keys shall be sorted in numerical order_").

So `name-tree`/`number-tree` keys cannot be `null` (fails "shall be a string"/"is an integer") and no allowance is made in either the lexical or numeric sorting algorithms for `null` keys - for example, whether they need to come first, last, or are skipped over entirely. And what would it mean if you had a `null` key but a non-`null` value??? Is that meaningful? (I note in https://github.com/veraPDF/veraPDF-library/issues/1355 that both the key and value are both `null`).

So referring to Tables 36 and 37:
* can name-tree and number-trees have keys that are `null`? 

~~I think the answer is yes (it's relatively common as @bdoubrov points out) so we need to allow `null` as an explicit key type for both. And name and number trees should both use the same "shall"-style wording for consistency.~~

* what are the requirements (if any) for the lexical and numeric sorting for keys that are `null`?

~~I think the answer is that keys that are `null` can appear anywhere but are ignored (not involved/skipped over) when considering lexical or numeric sorting. Not sure how to best phrase this - either we can say that only keys that are string/integer are sorted, or we say something about keys that are `null`...~~

* does a `null` key with a non-`null` value mean anything special?

~~I think no. It's syntactically valid but stupid as the value is "inaccessible" via a name/number tree lookup - so no real difference to a key and value both being `null`. This is probably worth a short informative NOTE.~~

**Comment by petervwyatt** [comment]
My misunderstanding about https://github.com/veraPDF/veraPDF-library/issues/1355 and https://github.com/pdf-association/arlington-pdf-model/issues/90. That is not related.

But my questions are still valid - can name-/number-trees have keys (even array elements 0, 2, 4, ...) that are `null` in **Names** and **Nums** arrays?

**Comment by bdoubrov** [comment]
I'd say no, same as for dictionaries: 

- The keys in `name-tree` are always of `string` type
- The keys in `number-tree` are always of `integer` type

**Comment by petervwyatt** [comment]
And makes it very easy to then state "... and shall not be null".

**Comment by petervwyatt** [comment]
PDF TWG agree
