### ISSUE TITLE
Clarify prohibition of None in NChannel colour spaces

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#309]
32000-2 prohibits the use of the name None for a component in an NChannel colour space, but that is only stated in a rather convoluted way that is separate from the clearer statement that None may be used in a DeviceN colour space.

Section 8.6.6.5, two paragraphs above Note 4 says 

> "The component names shall all be different from one another, except for the name None, which may be repeated as described later in this subclause. The special name All, used by Separation colour spaces, shall not be used. "

The paragraph below note 6 says:

> "The colour component name None, which may be present only for DeviceN colour spaces that do not have the NChannel subtype, indicates ..."

I suggest extending the first of these paragraphs with the italic text as below:

> "The component names shall all be different from one another, except for the name None, which may be repeated as described later in this subclause. _The special name None shall not be used in DeviceN colour spaces that have the NChannel subtype._ The special name All, used by Separation colour spaces, shall not be used. The names Cyan, Magenta, Yellow and Black are reserved to name the subtractive  process colourants of a CMYK device."

The second paragraph may then be simplified by deleting the parenthetical "which may be present only for DeviceN colour spaces that do not have the NChannel subtype" to avoid duplication.

**Comment by MPBailey** [comment]
Extend the para in section 8.6.6.5, two paragraphs above Note 4 with the italic text as below:

> The component names shall all be different from one another, except for the name None, which may be repeated as described later in this subclause. _The special name None shall not be used in DeviceN colour spaces that have the NChannel subtype._ The special name All, used by Separation colour spaces, shall not be used. The names Cyan, Magenta, Yellow and Black are reserved to name the subtractive process colourants of a CMYK device.

Remove the parenthetical text flagged as italic in the paragraph below note 6 to avoid duplication:

> The colour component name None _, which may be present only for DeviceN colour spaces that do not have the NChannel subtype,_ indicates indicates that the corresponding colour component shall never be painted on the page, as in a Separation colour space for the None colourant. ...

**Comment by petervwyatt** [comment]
PDF TWG agree
