### ISSUE TITLE
Text in "10.6.5.6 Type 5 halftones" is not clear

### ISSUE THREAD

**Issue by DietrichSeggern** [pdf-association/pdf-issues#311]
This should be discussed AFTER #310

The first para after the two bullets says:
'When a halftone dictionary of some other Type appears as the value of an entry in a Type 5 halftone dictionary, it shall apply only to the single colourant or colour component named by that entry’s key.'
That makes totally sense since Type 5 halftone dictionaries use different "sub halftone dictionaries" for all colourants.
The text goes on:
'This is in contrast to such a dictionary’s being used as the current halftone parameter in the graphics state, which shall apply to all colour components.'
It should say "dictionary" instead of "dictionary's".
It then goes on:
'If nonprimary colourants are requested when the current halftone is defined by any means other than a Type 5 halftone dictionary, the gray halftone screen and transfer function shall be used for all such colourants.'
It is not clear what this should say in a chapter that specifies Type 5 halftone dictionaries?

**Comment by johnwhitington** [comment]
>'This is in contrast to such a dictionary’s being used as the current halftone parameter in the graphics state, which shall apply to all colour components.'
> It should say "dictionary" instead of "dictionary's".

Sadly, despite being a native speaker, I can't explain this in grammatical terms: but either is correct.

Arguably "dictionary" is more modern though.

**Comment by MPBailey** [comment]
@lrosenthol were you involved in the hand-over of PDF 1.3 from Adobe internal to Addison Wesley? Can you shed any light on the reference to "the gray halftone screen"?

**Comment by lrosenthol** [comment]
I can verify the change happening between those two versions Adobe -> AW, but I cannot find anything that documents why at this time.  Will keep looking.

**Comment by lrosenthol** [comment]
OH WOW!   Figured out what happened...

The paragraphs that were added between Adobe 1.3 -> AW were taken verbatim(!!!) from the PLRM 3rd edition.
<img width="547" alt="image" src="https://github.com/pdf-association/pdf-issues/assets/5074741/07471c09-7d57-4134-a699-be5a35ad4410">

The concept of a "gray halftone screen" is mentioned in the "Graphics State Operators" section of the PLRM v3 (`setscreen`). As noted, none of this makes sense in the PDF context.  Ugh!

**Comment by petervwyatt** [comment]
Proposed Solution - delete the mistake!

**Comment by petervwyatt** [comment]
PDF TWG agree to delete last sentence in highlighted text above.
