### ISSUE TITLE
Table 226 AA entry points to wrong sub-clause.

### ISSUE THREAD

**Issue by datalogics-pgallot** [pdf-association/pdf-issues#313]
The AA entry in Table 226"Entries common to all field dictionaries"
has the following description:
"(Optional; PDF 1.2) An additional-actions dictionary defining the field’s behaviour in response to various trigger events (see 12.6.3, "Trigger events"). _This entry has exactly the same meaning as the AA entry in an annotation dictionary (see 12.5.2, "Annotation dictionaries")._"

The last sentence seems to be incorrect because clause 12.5.2 does not contain any mention of an 'AA' key.

The last sentence could be corrected with:
"This entry has exactly the same meaning as the AA entry in _a Widget_ annotation dictionary (see _12.5.6.19, "Widget Annotations"_)."

Note that the only other Annotation with an AA entry seems to be the Screen Annotation.

**Comment by petervwyatt** [comment]
PDF TWG agree for first change proposed (to clause).
