### ISSUE TITLE
DA entry: string vs. byte string (ISO 32000-2:2020)

### ISSUE THREAD

**Issue by a20dev** [pdf-association/pdf-issues#318]
In table 177  (Free text annotations), table 224 (Interactive form dictionary), and table 228 (fields containing variable text) the DA entry is specified as a string, in table 195 (Redaction annotations), DA is specified as a byte string. For all four instances, DA is a default appearance string and all four instances should use the same object type.

**Comment by petervwyatt** [comment]
Well noticed (and I also confirmed using the Arlington PDF Model: `grep "^DA" *`).
Given that a byte-string is a subset of string (as per Figure 7), I think Table 195 for Redactions just needs the word "byte" deleted.

**Comment by MatthiasValvekens** [comment]
...and given that **DA** contains (partial) content stream data, which doesn't really have a well-defined encoding anyway, my vote also goes to aligning on "byte string".

**Comment by petervwyatt** [comment]
Maybe the disadvantage of generalizing to "string" is that implies it can also be a text string which includes Unicode with BoMs and BCP-47 markers - and that doesn't make sense. So maybe the more technically correct solution (but larger edit!) is to change Tables 177, 224 and 228 to "byte string" and leave Table 195 alone.

**Comment by MatthiasValvekens** [comment]
Yes. I also don't think there's any way one could convincingly argue that the content of **DA** is somehow textual. It's not, and it's encoding is undefined, so "byte string" is the only reasonable option.

I guess you could in principle even have string literals or embedded images as tokens in the **DA** payload...

**Comment by mkl-public** [comment]
>I guess you could in principle even have string literals or embedded images as tokens in the DA payload...

Strictly speaking, _only operators that are allowed within text objects shall occur in this string_ (12.7.4.3 Variable text) which makes sense as it is used inside a text object. Furthermore, it _contains any graphics state or text state operators needed to establish the graphics state parameters, such as text size and colour, for displaying the field’s variable text._ So string literals are highly questionable and embedded images are clearly forbidden.

Nonetheless, byte string is the only option that makes sense here.

**Comment by MatthiasValvekens** [comment]
Fair enough, I was maybe overselling the point a bit there 😅

**Comment by datalogics-pgallot** [comment]
The second bullet of section 3.10 seems applicable here:
"The contents (data) of a string or stream object (3.63) in some contexts are interpreted as character codes in the PDFDocEncoding, UTF-8 or UTF-16BE character set."
 
Also, I don't recall ever seeing a DA string that couldn't be encoded in 7bit ASCII (where PDDocEncoding and UTF-8 overlap), so I don't see why it needs to be a "byte" string.

**Comment by datalogics-pgallot** [comment]
Eh.  Put another way, clause 7.3.4 differentiates between Literal strings and Hexadecimal strings. To me, indicating that a string is a "byte string" strongly implies the use of a Hexadecimal string for storing that data. I see no case for using anything but a Literal string for the sort of data that goes into a DA entry.

**Comment by stechio** [comment]
> The second bullet of section 3.10 seems applicable here: "The contents (data) of a string or stream object (3.63) in some contexts are interpreted as character codes in the PDFDocEncoding, UTF-8 or UTF-16BE character set."

"*in some contexts*" — as explained, this is NOT the case.

> Also, I don't recall ever seeing a DA string that couldn't be encoded in 7bit ASCII (where PDDocEncoding and UTF-8 overlap), so I don't see why it needs to be a "byte" string.

`byte string` is about the **interpretation** (ie, semantics) of a string; even if its **representation** (syntax) overlaps other subtypes (like in ASCII-encodeable data), *its interpretation doesn't change — and should command over syntax:* in a `byte string` entry (like `DA`) whose assigned value is a literal string starting, ad absurdum, with UTF-16BE BOM (FE FF), the BOM bytes should be interpreted, according to its semantics (a series of bytes whose encoding is unknown (7.9.2.4)), simply as bytes[0] (FE) and bytes[1] (FF) in the series, without special meaning (ie, it is NOT a `text string` even if it *looks like* that!).

> Eh. Put another way, clause 7.3.4 differentiates between Literal strings and Hexadecimal strings. To me, indicating that a string is a "byte string" strongly implies the use of a Hexadecimal string for storing that data. I see no case for using anything but a Literal string for the sort of data that goes into a DA entry.

As @mkl-public stated, "string literals are highly questionable", as `DA` entries are serialized content stream chunks which by their very nature are `byte string`s (even if they use only ASCII characters, their context (content stream) implies both ASCII PDF tokens *and* arbitrary bytes (in particular, glyph selectors mapping to font-specific encodings)).

Unfortunately, to my understanding, PDF leaves too much leeway in this respect (literal/hexadecimal forms are essentially at developer's discretion): IMHO, associating syntax and semantics in unambiguous ways (literal form for `text string` (and `ASCII string`), hexadecimal form for `byte string`) would have been much cleaner.

**Comment by MatthiasValvekens** [comment]
> To me, indicating that a string is a "byte string" strongly implies the use of a Hexadecimal string for storing that data.

I beg to differ here. For better or worse, both the Literal and hex forms can be used (and are used!) to represent all manner of binary data unambiguously. Whether said binary data is to be decoded/interpreted as text is a separate issue, and context-dependent.

In fact, I'd go as far as to say that we probably shouldn't have _any_ string usages in the spec that aren't explicitly classified as binary or textual. The fact that this isn't the case is a bug IMHO 😉

Sure, this state of affairs is awkward, but it's sort of par for the course for pre-Unicode technologies that are still in use today, I 'spose...

At the end of the day, **DA** represents data that will be spliced into a binary stream as-is, so it should be binary. There are quite a few other string usages classified as "byte string" where the hex form is nonetheless not the most popular representation used in the wild.

(Side note: @stechio I don't necessarily disagree with your broader point, but I believe @mkl-public was referring to string literals being used as tokens inside the **DA**, as opposed to the preferred representation for the **DA** string itself.)

**Comment by a20dev** [comment]
The Contents entry of a signature dictionary must be binary and hexadecimal.

**Comment by datalogics-pgallot** [comment]
@stechio if you want to argue that the second bullet point from clause 3.10 does not apply *in this context*, fair enough. I think we can also agree that the third choice does not fit the context, which leaves us with just the first choice:  

"A PDF file is represented as a sequence of 8-bit bytes (3.7), some of which are interpreted as character codes in the ASCII (3.3) character set and some of which are treated as arbitrary binary data (3.5) depending upon the context."

And again, we are not dealing with arbitrary binary data, but a subset of PDF operators and their operands so we must be dealing with ASCII characters, right ?

@MatthiasValvekens  My own prior use of DA strings did not involve splicing the DA string straight into a content stream but rather parsing it for hints as to how to initialize the graphic/text state of the content I was generating.  I think if one were splicing DA string directly into a content stream, then that code is possibly not correctly handling the potential presence of auto-size value for the DA string's required tf operator.

**Comment by a20dev** [comment]
Good point about "/Helv 0 Tf", maybe this warrants another issue here.

**Comment by petervwyatt** [comment]
Byte strings do NOT "recommend" nor require hex strings. We already made the spec very clear on that: https://pdf-issues.pdfa.org/32000-2-2020/clause07.html#H7.9.2.4.

> ... subset of PDF operators and their operands so we must be dealing with ASCII characters, right ?
No. Content streams do not have to be 7-bit only. "Byte string" allows string operands for text painting operators to have 8-bit bytes in literal strings: 7.9.2.4 "_The byte string type shall be used for binary data that shall be represented as a series of bytes, where each byte may be any value representable in 8 bits_". Using "ASCII string" would always require hex strings or octal escape codes to keep everything to strictly 7-bit.

Also because it is a string (of whatever kind), it will always need to be parsed to remove possible escape sequences before being "pasted" into a content stream.

**Comment by mkl-public** [comment]
@datalogics-pgallot 

>And again, we are not dealing with arbitrary binary data, but a subset of PDF operators and their operands so we must be dealing with ASCII characters, right ?

No. While operators indeed are represented using the ASCII encoding of certain letters or letter tuples, their operands often are not. This is most visible in the string operands of text showing operators (which admittedly I have already called questionable in a *DA* value) but can also become relevant in name operands (for example the font names).

Representations of names can contain any non-NULL, non-whitespace bytes (escaping bytes outside the 0x21..0x7e range merely is recommended and only necessary for whitespace bytes).

(Arg, I just re-read the specification of Names... what a dance, talking about "characters" while at the same time trying to make clear that one shouldn't make more assumptions than for arbitrary non-null bytes...)

> To me, indicating that a string is a "byte string" strongly implies the use of a Hexadecimal string for storing that data.

Oh well, I remember I also used to mix up those two concepts. Working in particular with the crypto aspects, one learns not to do that.

**Comment by datalogics-pgallot** [comment]
@mkl-public 
I concede the point about name operands potentially being non-ASCII though resource names are commonly (almost always?) ASCII-compatible, there's no requirement to that effect, it's just convention.  

So I withdraw my objection against using "byte string" instead of "string" and agree that it makes more sense in this context.

**Comment by petervwyatt** [comment]
PDF TWG agree "byte string" is correct.

**Comment by petervwyatt** [comment]
Also clarified some normative paragraph text to be "byte string"
