### ISSUE TITLE
Articles (12.4.3): Wrong thread beads order

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#320]
ISSUE

`B` entry in Table 31 in 7.7.3.3 ("Page objects") states:
"The beads shall be listed in the array in *natural reading order*." [emphasis is mine]

whilst body text in 12.4.3 ("Articles") prescribes the beads in that array to be "in drawing order":
"for each page on which article beads appear, the page object (see 7.7.3, "Page tree") shall contain a B entry whose value is an array of indirect references to the beads on the page, *in drawing order*." [emphasis is mine]

CORRECTION

Considering that article threads are specifically intended to convey logical relations over physical discontiguity, "in drawing order" should be replaced with "in natural reading order".

**Comment by petervwyatt** [comment]
Well spotted! The "drawing order" text is all the way back from PDF 1.1, although the "natural reading order" text wasn't added until PDF 1.3.

**Comment by petervwyatt** [comment]
@lrosenthol to research some more.

**Comment by petervwyatt** [comment]
@lrosenthol ?

**Comment by petervwyatt** [comment]
PDF TWG agree that articles use "reading order", not "drawing order" (and "natural reading order" is heavily adopted by Tagged PDF/Logical Structure so we should avoid that specific term).

**Comment by stechio** [comment]
Recapping, both the two above-mentioned sentences need to be fixed with the new term ("reading order"):
- `B` entry in Table 31 in 7.7.3.3 ("Page objects") 
- body text in 12.4.3 ("Articles")
