### ISSUE TITLE
Geographic coordinate system dictionary (12.10.3): Entry constraint (normative) and EPSG url (informative)

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#321]
ISSUE 1 - Entry constraint (normative)

The body text in 12.10.3 states:
"The geographic coordinate system shall be described in either *or both* of two well-established standards" [emphasis is mine]

whilst entries within Table 270 (Entries in a geographic coordinate system dictionary) imply that the two standards are mutually exclusive (cannot be "both"):
- `EPSG` entry states:
"Shall not be present if WKT is present."
- `WKT` entry states:
"Shall not be present if EPSG is present."

CORRECTION

If the entry descriptions in Table 270 are correct, the chunk "or both" in the body text of 12.10.3 should be deleted, thus:
"The geographic coordinate system shall be described in either of two well-established standards"

----

ISSUE 2 - EPSG url (informative)

The body text in 12.10.3 references:
http://www.epsg.org/

which is obviously obsolete (web clients like Firefox display a warning because of switching from unsecure HTTP protocol to HTTPS).

CORRECTION

should be updated to:
https://epsg.org/

**Comment by petervwyatt** [comment]
Thank you.

Maybe the "_or both_" was meaning that a PDF file could have 2 or more instances of a geographic coordinate system dictionary and there is no requirement that they all use the same system in a single PDF (could be completely different maps on different pages). This would be better stated as an informative note if it is worth stating at all.

**Comment by stechio** [comment]
> Maybe the "_or both_" was meaning that a PDF file could have 2 or more instances of a geographic coordinate system dictionary and there is no requirement that they all use the same system in a single PDF (could be completely different maps on different pages). This would be better stated as an informative note if it is worth stating at all.

I understand your point; IMO, that statement could be more clearly reformulated like this:
`The geographic coordinate systems shall be described in any of two well-established [...]`

Using the plural "systems" (instead of the original "system") should give spec readers a hint at *instances* (rather than single dictionary); for the same reason, ''any of" would avoid the restrictive interpretations suggested by "either or both of".

**Comment by petervwyatt** [comment]
PDF TWG Agree
