### ISSUE TITLE
PDF data types (Table 35, 7.9.1): Inconsistent entry descriptions

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#322]
ISSUE

The descriptions of several entries in Table 35 ("PDF data types") of 7.9.1 ("General" - "Common data structures") lack terminological uniformity: some entries correctly reference their base object type (eg, `array` is described as "Array object") or base data structure (eg, `name tree` is described as "Name tree (dictionary)"), whilst other entries do not (eg, boolean, numbers and string data types). Furthermore, the description of `date` entry ("Date (ASCII string)") is plain wrong (dates are `text string` (see 7.9.4, "Dates")).

CORRECTION

The descriptions of the following entries in Table 35 ("PDF data types") should be amended as indicated:
- ASCII string:
`String object whose bytes contain ASCII characters`
- boolean:
`Boolean object`
- byte string:
`String object whose series of bytes shall represent [...]`
- date:
`Date (text string)`
- integer:
`Integer numeric object`
- number:
`Numeric object (integer or real)`
- PDFDocEncoded string:
`String object whose bytes contain PDFDocEncoding characters`
- string:
`String object that is not a text string. Beginning [...]`
- text string:
`String object whose bytes shall represent characters [...]`
- text stream:
`Text stream (stream)`

**Comment by petervwyatt** [comment]
I agree with your intentions as this table is very old and not at all "ISO-ish", however a few corrections to your suggestions:

* Dates are always ASCII strings, never "text strings", so as never to be Unicode with BOMs or BCP-47 escapes- see Figure 7. Dates can however be either in literal (with or without `#` hex codes) or hex forms as NOTE 1 in 7.9.4 describes.

* a "string" can be any type of string as illustrated in Figure 7. A "text string" is a specialised subset of "string". Anything defined as a "string" can be a "text string", but not vice-versa.

* a better description for "text string" would be to reiterate the words from 7.9.2.2 "_... shall be used for character strings that contain information intended to be human-readable_"

* "PDFDocEncoded string" should be clarified to be a kind of "A text string whose bytes ...". Just FYI: this term is used only once in Table 246 (FDF, **Status** key).

**Comment by stechio** [comment]
> * Dates are always ASCII strings, never "text strings", so as never to be Unicode with BOMs or BCP-47 escapes- see Figure 7.

THAT was *precisely* my thought! I always assumed dates were `ASCII string` (it had been so for a long time, anyway), until I stumbled upon real-world PDF files containing dates formatted as `text string`s [sic]... perplexed, I re-read the specification and discovered, to my bewilderment, that the "Dates" section had changed the definition of its base type:
- PDF 1.6, 3.8.3, "Dates":
`A date is a string of the form`
- PDF 1.7, 7.9.4, "Dates":
`A date shall be a text string of the form`
- PDF 2.0, 7.9.4, "Dates":
`A date shall be a text string value containing no white-space, of the form`

I double-checked the specs because it looked (and still does!) REALLY strange (after all, dates are *naturally* `ASCII string`, as they convey specially-formatted data, NOT informal human-readable content), but I had to accept that, if it was specifically reformulated and vetted by a standards commission, it should have been definitely authoritative...

BTW, here it is a sample (allegedly created by Adobe InDesign 15.0 for Windows and published on the UN website) containing UTF-16BE-encoded dates as values of `LastModified` entries of page-piece data dictionaries: https://sustainabledevelopment.un.org/content/documents/26261VNR_Report_Finland_2020.pdf
This is the decoded dictionary associated to its first page:
```
3 0 obj
<<
    /Type /Page
    /PieceInfo <<
        /InDesign <<
            /LastModified (D:20200529092447Z)
            /NumberofPages 1
            /OriginalDocumentID (xmp.did:0a6a5a8b-8ff9-4f40-83cd-096168779463)
            /DocumentID (xmp.did:570b4e15-239e-e241-9856-7675d6e127ad)
            /PageWidthList << 0 595.276 >>
            /PageUIDList << 0 20155 >>
            >>
        >>
    [...]
>>
```
where `D:20200529092447Z` was encoded this way (the hexadecimal representation here is just for our convenience):
`FEFF0044003A00320030003200300030003500320039003000390032003400340037005A`

NOTE: this sample declares itself as PDF 1.6, so it is non-conformant per-se (BTW, its page-piece data dictionaries are malformed too, missing their `Private` entries), nonetheless *the definition of dates as `text string` in the ISO PDF  specs needs to be fixed.*

> * a "string" can be any type of string as illustrated in Figure 7. A "text string" is a specialised subset of "string". Anything defined as a "string" can be a "text string", but not vice-versa.

Again, THAT was *precisely* my thought! I always assumed `string` data type was just string object (it had been so for a long time, anyway), so I re-read the specification and discovered, to my bewilderment, that the `string` entry in Table 35 had changed the definition of its base type:
- PDF 1.6, TABLE 3.31 (PDF data types), 3.8, "Common Data Structures":
`String object`
- PDF 2.0 (1.7), Table 35 (34) (PDF data types), 7.9.1, "General" - "Common Data Structures":
`Any string that is not a text string.`

Terminologically, `string` should be *any* type of string (as you argued), yet the way it is referenced in dictionary entries throughout the spec seems more appropriate to the restrictive acceptation stated in PDF 2.0 ("Any string that is not a text string"). For example, `CheckSum` in Table 45 (Entries in an embedded file parameter dictionary), 7.11.4.1 (General - Embedded file streams): it is declared as `string` (thus, according to your statement, it could legitimately be a `text string`)... how can a checksum be meaningfully considered a `text string`? IMHO, your statement ("Anything defined as a `string` can be a `text string`") doesn't apply to such cases.

All the above considered:
- `string` should retain its pre-ISO (PDF 1.6) description (`String object`), which implies your statement ("a `string` can be any type of string")
- a new data type (eg, `binary string`) should be defined inside Table 35 (PDF data types), corresponding to the current ISO (PDF 1.7, 2.0) description of `string` ("Any string that is not a text string."), and all the `string`-typed dictionary entries conforming to this restrictive definition (such as `CheckSum` in Table 45) should be revised accordingly with the new data type. Such `binary string` type would also fit elegantly in the considerations of @MatthiasValvekens (see https://github.com/pdf-association/pdf-issues/issues/318#issuecomment-1672116519)

Therefore:
1. the descriptions of the following entries in Table 35 ("PDF data types") should be amended as indicated:
   - string:
   `String object`
   - binary string:
   `String object that is not a text string. Beginning [...]`

2. all the `string`-typed dictionary entries conforming to `binary string` (such as `CheckSum` in Table 45) should be revised accordingly, eg:
    Table 45 — Entries in an embedded file parameter dictionary
    |Key|Type|Value|
    |-----|------|--------|
    |CheckSum|binary string|(Optional) A 16-byte string that is the checksum of the bytes of the uncompressed embedded file. [...]|

> * a better description for "text string" would be to reiterate the words from 7.9.2.2 "_... shall be used for character strings that contain information intended to be human-readable_"

Sounds good!

> * "PDFDocEncoded string" should be clarified to be a kind of "A text string whose bytes ...". Just FYI: this term is used only once in Table 246 (FDF, **Status** key).

Sounds good!

**Comment by petervwyatt** [comment]
I do note the example PDF you cite is under `/PieceInfo` so it is very clearly vendor-specific private data vendor - but you cannot assume it is a normal PDF date. The vendor will have their own definitions (and potential variations) for this data... if you need to read over it, then the object is just a string of some unknown kind.

Changing Figure 7 and propagating changes throughout the spec is **major document surgery** and well beyond what we would address via an errata. That is not to say it is a bad thing, just a very big thing.  And I'm not a fan of the term "binary string" but that is minor...

I will look up to see if I can find discussions around Date strings in ISO documents - we have discussed this several times before but I don't recall all the details. Thanks for your contributions!

**Comment by stechio** [comment]
> I do note the example PDF you cite is under `/PieceInfo` so it is very clearly vendor-specific private data vendor - but you cannot assume it is a normal PDF date.

*The `LastModified` entry in the page-piece data dictionary is clearly required by the PDF spec to be of `date` type* (see Table 351 (Entries in a data dictionary), 14.5 (Page-piece dictionaries)); that entry must be conformant also because it is involved in the comparison algorithm described just below that table: "The **LastModified** entry indicates when a PDF processor last altered the content of the document, page or form. If the page-piece dictionary contains several data dictionaries, their modification dates can be compared with those in the corresponding entry of the page object or form dictionary [...]"
Why cannot I assume it is a normal PDF date?

> Changing Figure 7 and propagating changes throughout the spec is **major document surgery** and well beyond what we would address via an errata. That is not to say it is a bad thing, just a very big thing.

I understand. Nonetheless, the relevant inconsistencies I spotted deserve to be addressed, in particular:
-  *`date` type is wrongly defined as text string* (see 7.9.4, "Dates": "A date shall be a text string value containing no white-space [...]")
- `string` type is wrongly defined as "Any string that is not a text string" (see Table 35 (PDF data types), 7.9.1 ("General" - "Common Data Structures"))

> And I'm not a fan of the term "binary string" but that is minor...

No problem, it was just an example/placeholder name (I am nobody, it is up to the people in charge).

> I will look up to see if I can find discussions around Date strings in ISO documents - we have discussed this several times before but I don't recall all the details. Thanks for your contributions!

Thank you for your dedication!

**Comment by petervwyatt** [comment]
My mistake - you are correct that the `LastModified` date in this case is covered by ISO 32000. I mistakenly thought it was one level deeper. That is then clearly out-of-spec.

**Comment by stechio** [comment]
> My mistake - you are correct that the `LastModified` date in this case is covered by ISO 32000. I mistakenly thought it was one level deeper. That is then clearly out-of-spec.

That page-piece data dictionary was actually quite a mess :sweat_smile: (I had to wrap my mind around it because I couldn't believe an industry-standard application like InDesign could have generated such a bad structure!)

**Comment by petervwyatt** [comment]
PDF TWG want to see precise wording for all Table 35 corrections

**Comment by stechio** [comment]
Please, let me know if you want my recap of all Table 35 corrections as resulting from our interaction, thanks.

**Comment by petervwyatt** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<h1><a name="7.9 Common data structures"></a><a name="7.9.1 General"></a><a
name="_bookmark0"></a><a name="_bookmark1"></a>Table 35 — PDF data types
(informative)<o:p></o:p></h1>



Type | Description | Subclauses
-- | -- | --
ASCII   string | A string   object containing bytes encoded as ASCII characters. | 7.3.4 <br/>  7.9.2
array | An array   object. | 7.3.6
boolean | A Boolean object. | 7.3.2
byte   string | A string   object containing bytes where the encoding is determined by the context. | 7.3.4 <br/>  7.9.2  <br/> 7.9.2.4
date | A string   object that represents a date. | 7.3.4 <br/>  7.9.2 <br/>  7.9.4
dictionary | A dictionary   object. | 7.3.7
file   specification | A file specification (dictionary or string) | 7.11
function | A function   object (dictionary or stream) that represents a parameterised function,   including mathematical formulas or sampled representations with arbitrary   resolution. | 7.10
integer | An integer   number object | 7.3.3
name | A name   object | 7.3.5
name   tree | A name   tree data structure (dictionary) | 7.9.6
null | The null   object | 7.3.9
number | A numeric   object (integer or real) | 7.3.3
number   tree | A number   tree data structure (dictionary) | 7.9.7
</b>PDFDocEncoded</b> string | A type   of text string containing information intended to be human-readable that is encoded   using the single-byte PDFDocEncoding. | 7.9.2   7.9.2.2
rectangle | A rectangle   (array with 4 numeric elements) | 7.9.5
stream | A stream   object | 7.3.8
string | A string   object that may be further qualified    as either a text string, an ASCII string, or a byte string. | 7.3.4 <br/>  7.9.2
text   string | A type   of string object containing information that is intended to be human-readable,   and that is encoded as either PDFDocEncoding, UTF-16BE, or UTF-8 (<i>PDF 2.0</i>) | 7.9.2 <br/>  7.9.2.2



<p class=MsoNormal style='margin-bottom:0cm;line-height:normal;mso-layout-grid-align:
none;punctuation-wrap:simple;text-autospace:none;mso-line-break-override:restrictions'><span
style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin'>
Note: unless otherwise stated in this specification, all string objects may be written
as either a literal string or a hexadecimal string as described in 7.3.4.
</span></p>

</body>

</html>

**Comment by petervwyatt** [comment]
PDF TWG agree but also wish to add an informative note to the "number" row stating that the "real" is also used and means the same as number. Will also create a new errata to check usage of the word "real" throughout ISO 32000-2.
