### ISSUE TITLE
Wrong cross reference in table 119

### ISSUE THREAD

**Issue by seehuhn** [pdf-association/pdf-issues#324]
The last row of table 119 (Entries in a Type 0 font dictionary) explains the `ToUnicode` field as follows: "(Optional) A stream containing a CMap file that maps character codes to Unicode values (see 9.9.2, "Font subsets")."  Since the `ToUnicode` field has little to do with font subsets, I believe the "(see 9.9.2, "Font subsets")." must be a typo.  The text should say "(see 9.10.3, "ToUnicode CMaps")." instead, or maybe link to section 9.10.

In the PDF 1.7 spec the corresponding clause read "(see 9.10, "Extraction of Text Content")."

**Comment by petervwyatt** [comment]
ISO 32000-1:2008 had a link to 9.10, "Extraction of Text Content" so ISO 32000-2 should be corrected back the same.

**Comment by petervwyatt** [comment]
PDF TWG agree

**Comment by petervwyatt** [comment]
Commit message had typo - said 234, should have been 324!
