### ISSUE TITLE
PDF fails to fully describe how adjacent numbers need to be delimited (i.e. separated).

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#327]
Together "7.2 Lexical conventions" and "7.3.3 Numeric objects" fail to fully describe (or is at least very obtuse) how adjacent numbers need to be delimited (i.e. separated). For example, do `+`, `-` or even `.` some of the time, delimit the start of a new number from a previous number, or is a whitespace character always required (nothing states this that I can see!)? 

e.g. `0.12-34-5.6.7` - does this validly represent the four numbers: 0.12, -34, -5.6 and 0.7? Or just 0.12 and a syntax error? Or ...?

The specification is very clear when a number object is preceded by or followed by an object that needs one of the explicit delimiter characters from Table 2. But it is unclear what the requirements are for adjacent numbers...  and implementations do vary a lot!! 

"7.3.3 Numeric objects" states "_An integer shall be written as one or more decimal digits optionally preceded by a sign._" and "_A real value shall be written as one or more decimal digits with an optional sign and a leading, trailing, or embedded PERIOD (2Eh) (decimal point)._" which implies the above is valid as 4 numbers, but it would be good to clarify for consistency between implementations.

**Comment by petervwyatt** [comment]
https://github.com/mozilla/pdf.js/blob/master/src/core/parser.js#L955

**Comment by mkl-public** [comment]
You need delimiters between numbers. Otherwise non-trivial numbers would fall apart: you could parse  `1.3` as `1` and `.3` or as `1.` and `3`; and you could parse `123` as `1`, `2`, and `3`, or `12` and `3`, or ...
Also your example `0.12-34-5.6.7` could be parsed as *eight* numbers, not merely four, e.g. `0`, `.1`, `2`, `-3`, `4`, `-5.`, `6.`, and `7`.

The only exception could be that the `-` and `+` might be considered to have delimiting properties to the left side. 

Strictly speaking, by the way, section 7.3.3 does not require the (optional) sign to be in front for real numbers while for integers it says that the sign must precede the digits. Thus, `3-.` can be interpreted to represent the `-3` as real number...

**Comment by petervwyatt** [comment]
OMG! You are right! On a re-read it doesn't actually say that the sign has to be _before_ the digits! That is truly awful and I can't imagine that we want to allow that in valid PDF!

And thanks for finding that wording at the end of 7.2.3 as that states that a whitespace is needed to separate adjacent number tokens. It wouldn't hurt to note this in 7.3.3... once we work out what a valid numeric token looks like.

I think an EBNF "railroad" diagram would help - is this correct for numbers?:
![image](https://github.com/pdf-association/pdf-issues/assets/26521615/c5c8be6c-20b9-4071-9a74-5f5079020613)

**Comment by mkl-public** [comment]
> I think an EBNF "railroad" diagram would help - is this correct for numbers?:

Looks good to me.

**Comment by car222222** [comment]
The EBNF looks good to me too.

**Comment by petervwyatt** [comment]
Proposed solution:

1. reword how an integer is defined from:
> An integer shall be written as one or more decimal digits optionally preceded by a sign.  ...

to:

> An integer shall be written as an optional PLUS SIGN (U+002B) (`+`) or HYPHEN-MINUS (U+002D) (`-`) followed by one or more decimal digits.  ...

2. reword how a real is defined from:
> A real value shall be written as one or more decimal digits with an optional sign and a leading, trailing, or embedded PERIOD (2Eh) (decimal point). ...

to:

> A real value shall be written as as an optional PLUS SIGN (U+002B) (`+`) or HYPHEN-MINUS (U+002D) (`-`) followed by one or more decimal digits with a PERIOD (2Eh) (decimal point). ...

3. Add a new informative NOTE below Example 2:
> NOTE: as described in "7.2.2 - Representation", a PDF white-space character is needed to separate numbers that represent separate syntactic constructs from each other since PLUS SIGN (U+002B) (`+`), HYPHEN-MINUS (U+002D) (`-`) and PERIOD (2Eh) are not PDF delimiter characters.

4. add the EBNF railroad diagrams above as informative figures below the new NOTE below Example 2. A picture says a 1,000 words...

**Comment by mkl-public** [comment]
> followed by one or more decimal digits with a PERIOD (2Eh) (decimal point).

I'm not sure about this 'with' formulation, some people could understand this to mean "decimal digits with a PERIOD _each_".

But I currently also don't have a clearer alternative that doesn't sound too abstract or abstruse.

**Comment by petervwyatt** [comment]
@mkl-public  - I agree: "with", "including", "or" are all wrong under various interpretations, even if we augment the PERIOD to say "single PERIOD", etc.

Which is why I also think the EBNF railroad diagrams are critical... the words cannot be clear 100% of the time for 100% of readers who may or may not have strong English skills.

**Comment by MPBailey** [comment]
If we were to add an EBNF diagram then it would be the first one in the doc. That suggests that you'd probably want to add a bibliography reference to an appropriate specification of EBNF.

**Comment by petervwyatt** [comment]
PDF TWG agree to add EBNF diagrams (and EBNF source).
