### ISSUE TITLE
FieldMDP Table 259 - full or partial field names

### ISSUE THREAD

**Issue by lrosenthol** [pdf-association/pdf-issues#33]
Minor issue in 12.8.2.4 on the Fields value:

>(Required if Action is Include or Exclude) An array of text strings containing field names.

Should say "fully qualified field names"

**Comment by petervwyatt** [comment]
Proposed solution for Table 259: "... text strings containing fully qualified field names (see 12.7.4.2, "Field names")".

I added the cross-ref as that to be consistent with other places that use the phrase "fully qualified field names", as clause 12.7.4.2 gives the definition of what "fully qualified" is.
