### ISSUE TITLE
Language identifiers (14.9.2.2): Lang entries type

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#330]
Subclause 14.9.2.2 states that
> Certain language-related dictionary entries [(`Lang` entries)] are text strings that specify language identifiers

and that a language identifier is
> a Language-Tag as defined in [IETF] BCP 47

AFAIK, *the standards behind that specification* (in particular, ISO 639-* and ISO 3166) *describe codes within the ASCII charset, making it compatible with `ASCII string` type* (sure, `Lang` entries definition pre-dates `ASCII string` type, yet at the time it could be assigned `string` type instead...).

Why are language identifiers defined as `text string` (ie, "character strings that contain information intended to be human-readable" (see 7.9.2.2.1)) instead of `ASCII string`?

**Comment by petervwyatt** [comment]
@mrbhardy ?

**Comment by DuffJohnson** [comment]
Concur. I see no reason not to make this "ASCII string".

**Comment by petervwyatt** [comment]
Only that it might invalidate existing PDFs that unnecessarily used Unicode strings. (I haven't looked across my corpus). Note also that this is completely orthogonal to being a literal or hex string.

**Comment by mrbhardy** [comment]
It probably could, but since it does pre-date ASCII string (as stated above), do we need to "fix" this?

**Comment by petervwyatt** [comment]
Only for communicating to implementers that a text string includes Unicode-encoded strings as per Figure 7, so incorrect assumptions about ASCII-ness and literal strings is not continued.

Like @mrbhardy, I am very hesitant to mandate a formal data type change in PDF 2.0 for historical and extant data reasons, but PDF/UA, WTPDF or other subsets can always mandate a narrowing to **PDFDocEncoded** text strings (which is close enough to ASCII string for the purposes of language codes) for **Lang** strings, if they so wish.

So I think an acceptable proposed solution is to add a new informative note to 14.9.2.2 below the last bullet:
> NOTE: **Lang** entries are defined as text strings which include Unicode-encoded strings as shown in "Figure 7 - Relationship between string types". **Lang** entry text strings may be represented as either literal strings or hexadecimal strings (see 7.3.4, "String objects").

**Comment by petervwyatt** [comment]
/may/can/ --> "may" not in a Note!
PDF TWG agree
