### ISSUE TITLE
Wrong cross reference in section 8.9.6.2

### ISSUE THREAD

**Issue by seehuhn** [pdf-association/pdf-issues#333]
The note near the end of section 8.9.6.2 states
> For reasons discussed in 9.6.5.3, "Encodings for Type 3 fonts", an image mask, rather than an image, need almost always be used to paint glyph bitmaps.

I can't spot anything relevant to image masks in section 9.6.5.3.  Instead, I believe that this is attempting to refer to one of the following locations:
- the discussion in section 8.6.8, after table 73, or
- the description for the "d1" entry in table 111, or maybe
- note 2 inside the description for the "d0" entry in table 111.

The reference "9.6.5.3, "Encodings for Type 3 fonts"" should be replaced with a reference to a more relevant section.

**Comment by petervwyatt** [comment]
Thank you for reporting this.

I think a reference to "9.6.4 Type 3 fonts" seems appropriate as it then covers both the description of painting above Table 111 and Table 111 with the **d0**/**d1** operators. I don't think we can be more specific as then related information might be missed.

**Comment by seehuhn** [comment]
Great.  While changes are made in this paragrapg, maybe the grammar could be fixed at the same time?  To my (non-native speaker) eyes, "need almost always be used" -> "needs almost always to be used" would be an improvement.

**Comment by car222222** [comment]
Or "is almost always needed"?

**Comment by petervwyatt** [comment]
PDF TWG agree to both reference correction and grammar "... is normally used to paint glyph bitmaps".
