### ISSUE TITLE
tags for marked-content operators

### ISSUE THREAD

**Issue by seehuhn** [pdf-association/pdf-issues#334]
Section 14.6.1 claims

> All marked-content operators except EMC shall take a tag operand indicating the role or significance of the marked-content element to the PDF processor. All such tags should have second-class names registered with ISO ...

I believe that the intention here is to also allow first-class names, defined in the specification itself.  For example, example 1 in section 14.8.2.2.2 (Specification of Artifacts) suggests that artifacts could be marked using `/Artifact BMC`, and `/Artifact` is not a second-class name.

**Comment by petervwyatt** [comment]
Thank you. Totally agree... it would also be very helpful if all the 1st class names for tags defined in ISO 32000-2 were also centrally defined somewhere! I can find `Artifact`, `ReversedChars`, `OC`, `AF` in addition to a should recommendation in 14.7.5.2: "_Although the tag associated with a marked-content sequence is not directly related to the document’s logical structure, it should be the same as the structure type of the associated structure element._" 

I also note that the EXAMPLE below Table 228 and the last para in 12.7.4.3, and the example below Table 232, all refer to a tag `/Tx` which is neither second class nor formally defined anywhere I can see.

**Comment by DuffJohnson** [comment]
AFAIK, these tags mean nothing (and should mean nothing) except to the authoring processor and/or a closed workflow. I agree that 1st class names should be allowed in addition to 2nd class... but 3rd class names should also be permitted. Curious to know @mrbhardy's view...

**Comment by petervwyatt** [comment]
Well, 14.8.2.2.2 Specification of Artifacts, 14.8.2.5.3 Reverse-order show strings, 14.9.4 Replacement Text, and 14.9.5 Expansion of abbreviations and acronyms all clearly state that those features can be done using marked content sequences _or_ tagging.

I also noticed `Span` is explicitly mentioned in both 14.9.4 Replacement text, and 14.9.5 Expansion of abbreviations and acronyms.
And that the mandated `ActualText` and `E` entries for the associated property list dicts do not get their own Table like other property list dictionaries do. For consistency and clarity (since these mentions are buried in the dense text) we should add such tables.

**Comment by petervwyatt** [comment]
@mrbhardy ?

**Comment by mrbhardy** [comment]
Yes, definitely a mistake.  I wouldn't try to solve anything additional in this thread though (such as gathering up names here, though an Annex for that could be useful).

I think it should read:

> **For tags not defined elsewhere in this document,** all such tags should have second-class names registered with ISO (see Annex E, "Extending PDF") to avoid conflicts between different applications marking the same content stream.

That would fix the issue and leave it open to use marked content for any purpose we later choose.

**Comment by car222222** [comment]
Agree with @petervwyatt that such a table would be extremely useful.

**Comment by car222222** [comment]
Maybe add to the table somehow the information that "Span" and "Artifact" are (also) structure types?

**Comment by petervwyatt** [comment]
14.6.1, NOTE 3: "_The tag operand of marked-content operators have no relationship to Tagged PDF (see 14.8 "Tagged PDF") and thus is not role-mapped._"

14.7.5.2, 1st bullet, 2nd sentence: "_Although the tag associated with a marked-content sequence is not directly related to the document’s logical structure, it should be the same as the structure type of the associated structure element._"

**Comment by car222222** [comment]
So are you stating that when used as in your table, these are only coincidentally the names of structure types.  

If so, to avoid any such misunderstanding, maybe there needs to be note explaining that the use of these names is a mere coincidence?

**Comment by petervwyatt** [comment]
I think that is the discussion for tomorrow's F2F PDF TWG 😁 - just highlighting some related text in the spec.

**Comment by car222222** [comment]
OK!  Makes sense now, thanks.

**Comment by mrbhardy** [comment]
It is correct that there’s no connection between Span and Artifact MCS and the tags.  It would be improper for a Span MCS used for Alt text to have an MCID, for example. I would also argue MCID is only a reserved entry in to property list if Tagging is active. 

There’s a reason Marked Content pre-dates logical structure and logical structure pre-dates Tagged PDF. We try hard to make sure we don’t overload them early with too much future understanding of specific use cases.

**Comment by u-fischer** [comment]
> It would be improper for a Span MCS used for Alt text to have an MCID, for example.

sorry but "improper" is not really a sensible category in a technical spec ;-).

All the special rules mentioned in this issue make implementing the PDF spec and tagging more difficult, slower and error prone and *they need therefore a proper justification*.  Useless rules only led to more PDF's in the wild not following the rules and processors that work around such faults. 

If as @DuffJohnson  says *these tags mean nothing* then why should an implementor spent time and resources to follow all the rules mentioned here? What exactly is the problem with

~~~~
/mytag <</MCID 0 /ActualText (Duck) >> BDC
...
EMC
~~~~

that the rules ask to convert that into this:

~~~~
/P <</MCID 0 >> BDC
 /Span <</ActualText (Duck) >> BDC
...
 EMC
EMC
~~~~

?

**Comment by willkil** [comment]
I searched for marked-content sequence tags in PDF 1.7 and PDF 2.0 awhile back and here are the results I found:

PDF 1.7 marked-content specified tags
/Span
/OC
/Tx
/Clip
	/Pgf
/Artifact
/TagSuspect
/ReversedChars
tags that match structure type when MCID is present.

PDF 2.0 marked-content specified tags
/AF
