### ISSUE TITLE
Sub (2.0 structure type) should be added as an allowed child of Code (1.7 structure type)

### ISSUE THREAD

**Issue by car222222** [pdf-association/pdf-issues#336]
Since the Code structure type appears only in the “1.7 namespace”, this 
addition does not require any change to ISO 32000-2:2020.
It only requires a change to the relevant entries in Table 5 (Section 7.2) 
of ISO/DTS:32005.

The major justification for this change is that ISO 32000-2 (in Table 367 in 14.4.8.6) 
explicitly gives “a line of source code” as an example of the use of the Sub 
structure type.   Note also that @mrbhardy has stated that 
the failure to include this in the table in ISO/DTS:32005 was an oversight 
that should now be corrected. 

Following discussion at the LaTeX LWG, this suggestion was brought to the 
attention of the PDF/UA TWG by @DuffJohnson  and that body approved the change.

**Comment by petervwyatt** [comment]
@DuffJohnson @car222222 - can someone from the PDF/UA TWG please provide me with the _exact_ markup necessary and/or a spreadsheet/CSV?

**Comment by DuffJohnson** [comment]
There is no change to ISO 32000-2:2020; the requested change is to ISO TS 32005.
 
@mrbhardy (the PL for ISO TS 32005) needs to make the change there, both in the megatable (the intersect of Code (parent) and Sub (child) should be changed to "0..n"), and in the "paginated" version of the same data in the TS itself.

**Comment by car222222** [comment]
Thanks, @DuffJohnson, for the clarifications.

**Comment by car222222** [comment]
Thanks, @DuffJohnson, for the clarifications.

**Comment by car222222** [comment]
Please can either @mrbhardy or @DuffJohnson explain here the decision of PDF/UA concerning exactly how such future updates to ISO TS 32005 are to be documented and progressed. Thanks!

**Comment by mrbhardy** [comment]
There are two parts to the documentation.  

### 1. Industry Documentation

We've identified that we want to have a place in our PDF Association hosted material (specifically the Excel spreadsheet that represents the mega table compactly) and we need a means of calling out this as a recommended change, while acknowledging it isn't officially part of a standard yet that things like 14289 and 32005 rely on. We should also document the workarounds that exist to help authors (people/software) who do need to be fully compliant to be compliant.

### 2. Updating 32005

We need to update 32005 with this change.  However, the PDF/UA committee is not fully aligned that right now we have had sufficient time to gather other issues that we might want to fix in a dated revision, so we want to allow some small amount of time to pass to get to that point.  Once it is there, the industry documentation would be updated...

**Comment by mrbhardy** [comment]
I'll add, we do believe the workaround proposed (namely, to include a **Span** inside the **Code**, since **Sub** is permitted inside **Span**) would be robust even after fixes to 32005.

**Comment by petervwyatt** [comment]
PDF TWG support PDF/UA TWG decisions above:
1. update "megatable" in PDF 2.0 errata
2. add a ISO/TS 32005 errata with an editor note seeking feedback which will be addressed in ISO in a future meeting for a possible dated revision on ISO/TS 32005.
