### ISSUE TITLE
Do the symbolic/non-symbolic flags apply to the whole font or to the embedded subset?

### ISSUE THREAD

**Issue by seehuhn** [pdf-association/pdf-issues#337]
Table 121 (Font Flags) explains the `Symbolic` flag as follows:

> Font contains glyphs outside the Standard Latin character set. 

From the description it is not clear whether this applies to the original font, or to the subset embedded in the PDF file.  It would be nice if the description in the table could be updated to clarify this (and similarly for the `Nonsymbolic` entry).

**Comment by petervwyatt** [comment]
@lrosenthol - please research

**Comment by lrosenthol** [comment]
FontFlags are part of a font descriptor.   A font descriptor is connected to a specific instance of a font - which itself may be either embedded or referenced.  But the descriptor is to THAT INSTANCE.

So if the descriptor is for an embedded font, then the flags (and all the other fields of the descriptor) are for that specific embedded (full or subset) font program.  If it is for a referenced (non-embedded) font, then it applies to the source material found by the PDF Writer at the time of PDF creation.

**Comment by petervwyatt** [comment]
Proposed solution to clarify that it is instance-specific (i.e. a font object):

*  9.8.1, 3rd para first, sentence: "_A font descriptor is a dictionary whose entries specify various font attributes._" --> "_A font descriptor is a dictionary whose entries specify various font attributes specific to an instance of a font._" 

* 9.8.2, 1st para, 1st sentence: "_The value of the **Flags** entry in a font descriptor shall be an unsigned 32-bit integer containing flags specifying various characteristics of the font_." --> "_The value of the **Flags** entry in a font descriptor shall be an unsigned 32-bit integer containing flags specifying various characteristics of the instance of the font_." 

And/or we could do informatively via a NOTE such as at the very end of 9.8.1 - something like (thanks @lrosenthol!):

* NOTE: if the font descriptor is for an embedded font, then all fields of the descriptor are for that specific embedded (full or subset) font program. If it is for a referenced (non-embedded) font, then it applies to the source material found by the PDF Writer at the time of PDF creation.

**Comment by petervwyatt** [comment]
PDF TWG request just note and check common usage of "PDF Writer" term.

**Comment by petervwyatt** [comment]
Confirming that "PDF writer" is definitely still defined (in 6.3.1) and used throughout ISO 32000-2:2020 (49 occurrences).
I think what we changed was from "conforming PDF Writer"...

**Comment by seehuhn** [comment]
Just to check my understanding of the resolution: If the font used by a PDF writer contains some glyphs outside the Standard Latin character set, but the document only uses glyphs contained in the Standard Latin character set then there are two cases:
1. If the font is not embedded, the writer has to mark the font as `Symbolic`.
2. If the font is subsetted and embedded, the writer has to mark the font as `Nonsymbolic`.

Is this what the clarified text says?

**Comment by petervwyatt** [comment]
I don't think it reduces to this simplicity. Since not embedding fonts is a very **VERY** high-risk activity (and not permitted for PDF 2.0 files "_At most, only one of the FontFile, FontFile2, and FontFile3 entries shall be present_") it's up to the author to think about the consequences of getting a symbolic or non-symbolic font substitution for the content using the missing font - so it is all about the specific content and very much a big gamble on the part of the author.

**Comment by seehuhn** [comment]
Great, thank you, I think I understand.

In the case where the font data is embedded, what is the intended purpose of the font flags?

As an aside: I think the text you quoted, *"At most, only one of the FontFile, FontFile2, and FontFile3 entries shall be present"*, does not require inclusion of font data, but instead forbids to include two different font programs for the same font.  (I agree that not embedding fonts is not advisable.)
