### ISSUE TITLE
pdf version of /AF and /AFRelationship

### ISSUE THREAD

**Issue by u-fischer** [pdf-association/pdf-issues#338]
*Table 29 — Entries in the catalog dictionary*  describes `/AF` as *(Optional; PDF 2.0)* and
*Table 43 — Entries in a file specification dictionary describes* `/AFRelationship`  as *(Optional; PDF 2.0)* too. 

But one gets error if a PDF 1.7 file trying to follow the A-3u standard is missing these keys, and the rule from verapdf refers to ISO 19005-3:2012: https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Parts-2-and-3-rules#rule-68-3

I don't own ISO 19005-3:2012 or ISO 32000-1 so I can't check, but can it be that both keys are actually already PDF 1.7?

**Comment by MatthiasValvekens** [comment]
Perhaps someone with a first-hand understanding will correct me, but AFAIK this is how it works:

Associated files are defined in Annex E of ISO 19005-3:2012, and IIRC that's where they historically first appeared. They were rolled into "core" PDF starting from 2.0, so in that sense I think the version number is correct.

**Comment by u-fischer** [comment]
@MatthiasValvekens  yes it boils down to the question what these version designations mean. But 5 Version designations says that the notation indicates *at which point in the sequence of versions a feature was introduced* and imho an introduction in 2012 can't be something that has been introduced for PDF 2.0.

**Comment by petervwyatt** [comment]
@MatthiasValvekens is correct: the AF/AFRelationship entries are _not_ in ISO 32000-1:2008 (PDF 1.7), but only in ISO 19005-3:2012 Annex E (PDF/A-3). They were later adopted into ISO 32000-2:2017 (PDF 2.0). So these keys only have _meaning_ in PDF/A-3 files with a file header version of 1.x as per clause 6.1.2 of PDF/A-3.  Outside of PDF/A-3, these keys would be considered "private data" and implementations are then free to do whatever they want - such as supporting Associated Files.

PS. This is one case where our informal term "ISO subset" is not a subset of ISO 32000, but actually a superset 😁

There is no issue with the standards/specifications. Other issues may lie with veraPDF's implementation so please report any further issues to them via https://github.com/veraPDF/veraPDF-library/issues
