### ISSUE TITLE
Structure content (14.7.5): Pg entry inconsistency

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#339]
`Pg` entries of Marked-content reference and Object reference dictionaries are defined in divergent ways:

- for Marked-content sequences as content items (14.7.5.2), Table 357 (Entries in a marked-content reference dictionary):
> [...] This entry overrides any **Pg** entry in the structure element containing the marked-content reference; it shall be required if the structure element has no such entry.

- for PDF objects as content items (14.7.5.3), Table 358 (Entries in an object reference dictionary):
> [...] This entry overrides any **Pg** entry in the structure element containing the object reference; it shall be used if the structure element has no such entry.

IMO, the latter definition is unnecessarily loose: it states that object-reference-specific `Pg` entry "shall be *used* if the structure element has no such entry", opting for the semantically weaker term *"used"* instead of the much more precise term *"required"* employed by the marked-content reference counterpart.

It seems clear that the description of `Pg` entry in Table 358 needs to be amended this way:
`This entry overrides any Pg entry in the structure element containing the object reference; it shall be required if the structure element has no such entry.`

**Comment by MatthiasValvekens** [comment]
Note that certain verbs have specific technical meanings within ISO-ese that is sometimes different from the way they're used colloquially in English.

In this instance, the verb "shall" is already defined in the ISO directives as expressing a normative requirement. In other words, the current text already means exactly what you want it to say.

IMHO the text is clear and unambiguous as-is.

**Comment by stechio** [comment]
I understand your point, yet, as a user, *that difference in wording sticks out, since the surrounding text is identical between the two entries*:

- `Pg` entry of Table 357 (Entries in a marked-content reference dictionary) says (emphasis is mine):
> it shall be *required* if the structure element has no such entry.

- while the equivalent `Pg` entry of Table 358 (Entries in an object reference dictionary) says:
> it shall be *used* if the structure element has no such entry.

Someone could legitimately think: if a single word is *purposely* different ("used" vs "required"), it may actually imply a subtle difference between the two entries (especially considering that the meta-attribute `Required` (referenced also by the Arlington model) is extensively and consistently used across all the entry tables in ISO PDF). *According to your interpretation, though, that difference is just accidental/arbitrary* — something I wouldn't expect in a specification!

*If the specification means exactly the same thing in the two definitions, I see no reason in introducing variations in wording*. IMHO, a technical doc should be as terse and predictable as possible: *identical things should be described in exactly the same words* — I think we can all agree that variations and embellishments are stylistically reserved to other literary genres :)

**Comment by car222222** [comment]
@MatthiasValvekens Maybe you missed the point here? -- @stechio was not questioning the use of "shall" but asking about the distinction between  "used" and "required".  Are these two words also defined by the ISO rules?

**Comment by petervwyatt** [comment]
I am speaking generally here - **not** specifically to the wording this issue highlights: ISO doesn't define such things, but in PDF standards we have 2 different types of requirements: "file format" and "processor". 

* "File format" means what has to happen within a file for it to be a valid PDF - if it is not done then the file is _invalid_ and usually falls outside the scope of ISO 32000. Files are just piles of passive bytes - they don't "do" anything.
* "Processor" requirements relate to what (all?) software needs to do. Software is active - it does something when given data accordingly. And verb-like word is always a processor requirement.

Generally speaking, we always try to define **file format** rules ahead of processor rules.

So the word "required" is _normally_ used to indicate a file format rule - e.g. some key or value is required, optional, or has some relationship to other data in the file.
The word "use" would imply a processor requirement as would other verbs ("ignore", "paint", etc.)

Of course this is how we have come to understand things today and not every sentence in all 1,000 pages will have been originally written with that understanding (hence my opening statement) - but does that help at all?

**Comment by car222222** [comment]
Thanks, @petervwyatt , for a very useful and detailed explanation!

**Comment by stechio** [comment]
> So the word "required" is _normally_ used to indicate a file format rule - e.g. some key or value is required, optional, or has some relationship to other data in the file. The word "use" would imply a processor requirement as would other verbs ("ignore", "paint", etc.)

To me, this puts the two terms in the right perspective: even if such distinction emerged pragmatically rather than programmatically, it seems coherent with the formal definition of the format, indeed. My entry normalization proposal follows suit.

**Comment by petervwyatt** [comment]
So I would agree that both statements across Tables 357 and 358 are intended to convey _only_ file format requirements. 
Thus I'd also make the terminology used ("... required ...") identical in both.

**Comment by MatthiasValvekens** [comment]
Right, with that perspective I agree that the change makes sense. I still don't think the original sentence was ambiguous in context (it reads as a file format requirement to me either way), but I see the general point :).

**Comment by petervwyatt** [comment]
PDF TWG agree - change "used" to "required" in Table 358.
