### ISSUE TITLE
Default color spaces for annotation C and IC entries 

### ISSUE THREAD

**Issue by bdoubrov** [pdf-association/pdf-issues#34]
Section 8.6.5.6 - Default color spaces defines the following cases when the default color spaces are applicable as:

> A colour space is selected for painting each graphics object. This is either the current colour space parameter in the graphics state or a colour space given as an entry in an image XObject, inline image, or shading dictionary.

On the other hand, we have C entry in the annotation dictionary (Table 166) specifying a number of cases when Device colors are used to define the appearance of the annotation. Currently there is no mechanism available to remap these device colors to any device-independent ones. 

This is not an issue if the annotation has an appearance stream, which is required for most cases in PDF 2.0. But, for example, Link annotations do not require AP entry and yet use the value of C entry to draw the border. Another case is when the annotation is modified and the appearance stream has to be recreated.

One way to resolve this would be to state that default color spaces defined in the page resource dictionary are applicable also to color spaces used in C and IC entries of the annotation dictionaries on that page.

This is especially important for PDF/A and PDF/X standards which forbid the use of Device colors with undefined matching output profile.

**Comment by faceless2** [comment]
> One way to resolve this would be to state that default color spaces defined in the page resource dictionary are applicable also to color spaces used in C and IC entries of the annotation dictionaries on that page.

That's the way we've interpreted it, certainly. The DefaultRGB space determines the colorspace for all device-rgb content on the page, and the annotation is on the page. I agree without this it would make PDF/A compliance very difficult - impossible, if the document OutputIntent was CMYK and the annotation RGB.

**Comment by petervwyatt** [comment]
Other misc comments:

- "Table 145 — Additional entries specific to a transparency group attributes dictionary": 
**CS** key: "Device colour spaces shall be subject to remapping according to the **DefaultGray**, **DefaultRGB**, and **DefaultCMYK** entries in the **ColorSpace** subdictionary of the current resource dictionary (see 8.6.5.6, "Default colour spaces")" and
"For a transparency group XObject used as an annotation appearance (see 12.5.5, "Appearance streams"), _the default colour space shall be inherited from the page on which the annotation appears_." (italics are my emphasis)
This is also reinforced by "Annex P (informative) An algorithm to determine the actual blending colour space of a transparency group"

- And don't forget that we now have a **BM** (blend mode) in every annotation ("Table 166 — Entries common to all annotation dictionaries") that needs advanced color handling when blending an annot onto the page: "_The blend mode that shall be used when painting the annotation onto the page (see 11.3.5, "Blend Mode" and 11.6.3, "Specifying Blending Colour Space and Blend Mode")_."

**Comment by petervwyatt** [comment]
See also some discussions in Issue #17

**Comment by petervwyatt** [comment]
I believe everyone is in alignment that default colour spaces can and do apply to all aspects of rendering annotations (including 3D data streams as per #18). So the question now is where is(are) the best place(s) to define this... is it 12.5 Annotations (12.5.1 General to be more precise) or 8.6.5.6. Default colour spaces? Both?

And since there is no existing normative language to the contrary, this might also be done as a NOTE - or should we go with stronger normative wording?

**Comment by bdoubrov** [comment]
I'd suggest to add this as an additional bullet at the end of 8.6.5.6 Default colour spaces after the words:

> This shall apply to the following colour spaces:
> ...
> - colour spaces used in the entries C, IC, CS of Annotation dictionaries.

 

I don't think we need to add this to the definitions of these entries. For example, item 8.6.6.3 "Indexed colour spaces" does not mention explicitly that the base colour space is subject to the logic of Default colour spaces.

**Comment by petervwyatt** [comment]
As per @bdoubrov proposal above

**Comment by petervwyatt** [comment]
PDF TWG: 
* Bullet list refers to special colour space handling so that is not correct place to add these words.
* also 7.8.3 says "Named resources shall be meaningful only in the context of a content stream" - but also has DefaultXXX

Needs further work

**Comment by petervwyatt** [comment]
Do default color spaces on Page Resource dictionaries affect rendering of annotations in any way?

How are the color values for annotation properties (e.g. C, IC, etc) impacted by output intents in the ISO subsets? (context is PDF/A validation and PDF/X)

Q1 to be raised at ISO WG8.
Q2 goes to PDF/A TWG.

**Comment by faceless2** [comment]
Re question one, we had long presumed it did but changed that presumption fairly recently based on this post from Leonard to the verapdf-tech mailing list on 20160923:

> On the issue of Annotations – there is nothing in 32K (or its predecessors) that states that the rendering of the appearance for an annotation would ever fallback to the page’s resources.

Implying that DefaultRGB set on a page would not affect the DeviceRGB color used in an annotation.

----

On question two, C and IC are not used directly for rendering, but are used when the annotation appearance needs rebuilding for any reason. However, PDF/A-1 still has this requirement in 6.5.3

> An annotation dictionary shall not contain the C array or the IC array unless the colour space of the DestOutputProfile in the PDF/A-1 OutputIntent dictionary, defined in 6.2.2, is RGB.

So _if_ C and IC are present, they must be an array of 3 entries and the OutputIntent must be RGB.

PDF/A-2 and later have no requirements on C/IC, other than that they shall be ignored for rendering.

In either case, if they are used to recreate an annotation and the annotation has device color as a result, that would be affected by the OutputIntent as normal.

Dietrich did some testing on this in February, and I believe this was the conclusion of the group and all the tested vaildators were aligned on this decision (we changed our validation to match; I think the others were already doing this).

**Comment by bdoubrov** [comment]
Comments and test files from Dietrich: attached are three files as discussed at the PDF/A TWG on June 14

[simple PDF with URL in text.pdf](https://github.com/pdf-association/pdf-issues/files/6671304/simple.PDF.with.URL.in.text.pdf)

A very simple file. When you open it in Acrobat it will automatically convert the URL into a clickable link - if in the Preferences->General->Create links from URLs is active.

[simple PDF with URL in text + Link Annotation.pdf](https://github.com/pdf-association/pdf-issues/files/6671303/simple.PDF.with.URL.in.text.%2B.Link.Annotation.pdf)

Is the same file, but now with a link annotation created in Acrobat that uses a BS entry and C defining a brown color. 

[simple PDF with URL in text + Link annotation A2.pdf](https://github.com/pdf-association/pdf-issues/files/6671305/simple.PDF.with.URL.in.text.%2B.Link.annotation.A2.pdf)

The file has then been converted to PDF/A-2 with an appearance as needed. The appearance defines a dark green rectangle slightly inside. Acrobat does still show the border, which is against PDF 2.0 and PDF/A-2, and also the appearance.

In my opinion the issue is not so much Acrobat, but more the text... To be discussed.

In PDF/A-4 we only say, that the rendering behavior as specified in PDF 2.0 should be use. So I think if we fix the text there, then we are good.

**Comment by petervwyatt** [comment]
Discussed PDF TWG on June 18 - draft an informative NOTE below Table 166: "ignoring" is render case, not regen....

Default color spaces do not apply to C and IC entries. 
PDF/A states OutputIntents do apply.

**Comment by petervwyatt** [comment]
Current comment below Table 166 says:

> A PDF reader shall render the appearance dictionary without regard to any other keys and values in the annotation dictionary and shall ignore the values of the C, IC, Border, BS, BE, BM, CA, ca, H, DA, Q, DS, LE, LL, LLE, and Sy keys

Proposed solution for improved wording related only to rendering (so nothing is stated about regeneration which is the general approach taken in ISO 32000-2:

> When rendering, a PDF reader shall ignore the values of the C, IC, Border, BS, BE, CA, ca, H, DA, Q, DS, LE, LL, LLE, and Sy keys in the annotation dictionary, and render the appearance dictionary. 
NOTE: some of these keys are only relevant to certain annotation subtypes as described in subsequent subclasses.

Also note that the BM key is removed from this list, since as I mention above, it needs to get used to blend the annot appearance stream with the page content.

**Comment by petervwyatt** [comment]
PDF TWG: what happens if Link annot does not have AP as allowed by Table 166, AP key (as one of 3 annots that don't have to have AP)?
Improve wording: When rendering the appearance dictionary, a PDF reader shall ignore ...

Add to Table 166, AP cell:
NOTE: When AP is not present, rendered appearance is implementation dependent.

PDF TWG agree
