### ISSUE TITLE
Extending PDF (Annex E): Third-class names

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#340]
**Third-class** paragraph (E.2 (Classes of PDF names)) ends with redundant and ambiguous words:
> [...] Third-class names shall all begin with a specific prefix reserved for private extensions. This prefix, which is XX, shall be used as the first characters in the names of all private data added by the developer. It is not necessary to register third-class names in the PDF Names list.

In my opinion:
- the second sentence is *almost a rewording of the first one*: a prefix is a prefix, no need to specify that it is "the first characters in the names"! Furthermore, it already implicitly stated that third-class names concern private data — if they are "reserved for private extensions", they are necessarily used to define private data, what else?
- the third sentence uses the *misleading expression "not necessary"*, which implies that the registration *may* be possible: to my understanding, this is NOT true (the paragraph earlier states that such names "may be used only in PDF files that are part of an internal process", so it doesn't make sense to expose them to a public registry, otherwise they would overlap second-class names!)

### CORRECTION

This is my reformulation proposal:
`[...] Third-class names shall all begin with a specific prefix, which is XX, reserved for all private data added by the developer. By definition, third-class names cannot be registered in the PDF Names list.`

**Comment by lrosenthol** [comment]
I agree that the current text could use improvement, but the proposed correction is also not correct.

Instead, recommend:

>[...] Third-class names shall all begin with the specific prefix, `XX`, which has been reserved for this purpose. Any keys that are added by a developer for the purpose of adding private data to a PDF, shall begin with this prefix. Third-class names cannot be registered in the PDF Names list.

**Comment by petervwyatt** [comment]
PDF TWG agree to Leonard's wording
