### ISSUE TITLE
Incremental updates (7.5.6): Unnecessary mention of proprietary technology

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#341]
NOTE 1 in subclause 7.5.6 reads:

> The main advantage to updating a PDF file in this way is that small changes to a large document can be saved quickly. There are additional advantages *such as when editing a document across an HTTP connection or using OLE embedding (a Microsoft Windows™ specific technology)*, a PDF processor cannot overwrite the contents of the original PDF file. [...]

The emphasized phrase was introduced in PDF 1.4 (2001). While "editing a document across an HTTP connection" may be a perfect fit as an example, "using OLE embedding" IMHO nowadays lacks relevance to be mentioned inside a universal, cross-platform standard format like ISO PDF — OLE is an... ole proprietary technology, feels a bit arbitrary for it to make its way inside this specification, *especially considering that platform-specific definitions* like those in Launch actions (12.6.4.6) or File specifications (7.11.3) *have been deprecated since PDF 2.0*.

### CORRECTION

This is my reformulation proposal:
`The main advantage to updating a PDF file in this way is that small changes to a large document can be saved quickly. There are additional advantages such as when editing a document across an HTTP connection, a PDF processor cannot overwrite the contents of the original PDF file. [...]`

**Comment by lrosenthol** [comment]
I would instead suggest that we simply remove the entire second sentence - since the point about HTTP is no longer true either (since the introduction of PUT, POST or PATCH).

**Comment by petervwyatt** [comment]
PDF TWG agree to remove entire sentence.
