### ISSUE TITLE
Wording improvements in 11.3.5.1 and Fig 72 and Fig 73

### ISSUE THREAD

**Issue by crlf0710** [pdf-association/pdf-issues#345]
**Describe the bug**
I was staring at the PDF cheat sheets, and the Colors page leads me here. The figure 72 and figure 73 are exhibiting the blending results for one specific kind of RGB colorspace and one specific kind of CMYK colorspace, right? I think this sentence: "
```text
"Figure 72 — RGB blend modes" and "Figure 73 — CMYK blend modes" illustrate the 
resulting visual effects for RGB and CMYK colours, respectively.
```
" is not that precise, and might mislead people into believing otherwise. 

It would be even nicer if the text could provide *which* specific RGB and CMYK color spaces these figures are generated from, though not a must.

**Comment by petervwyatt** [comment]
We don't have the "live" source data for these images anymore - they are just static pre-rendered bitmaps in the ISO publication. I don't know what colorspaces the original data were in, nor how accurately the bitmaps were generated. 

But I take your point - maybe the best solution is to simply note that these images are not intended to be pixel- or color-precise, but just indicative of the style of visual effects generated by the different blend modes in an additive RGB space and subtractive CMYK space respectively.

**Comment by lrosenthol** [comment]
@petervwyatt I believe I have all the original images that were used in 32K-1 if you need them.

**Comment by petervwyatt** [comment]
@lrosenthol  - yes please! Can you please email them or put them on a drive share? Thanks

**Comment by petervwyatt** [comment]
PDF TWG agree to add informative note: "NOTE: these images are not intended to be pixel- or color-precise, but just indicative of the style of visual effects generated by the different blend modes in an additive RGB space and subtractive CMYK space respectively."
