### ISSUE TITLE
Table 382 ContinuedList and ContinuedFrom don't state their inheritability

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#346]
"Table 382 — Standard list attributes" **ContinuedList** and **ContinuedFrom** don't state their inheritability. All other attributes always explicitly state either "_not inheritable_" or "_inheritable_" in the opening parenthesised italics after _Optional_ or _Required_. As a result, it is unclear what the inheritance is for these two new PDF 2.0 attributes.

My guess is "_not inheritable_".

**Comment by MatthiasValvekens** [comment]
> not inheritable

Agree, I don't think the alternative makes sense :)

**Comment by petervwyatt** [comment]
PDF TWG await @mrbhardy

**Comment by mrbhardy** [comment]
@petervwyatt yes, not inheritable.

**Comment by petervwyatt** [comment]
PDF TWG agree
