### ISSUE TITLE
Table 385 Standard artifact attributes don't state their inheritability

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#347]
None of the 3 attributes (**Type,** **BBox**, **Subtype**) in "Table 385 - Standard artifact attributes" state their inheritability. All other attributes always explicitly state either "_not inheritable_" or "_inheritable_" in the opening parenthesised italics after _Optional_ or _Required_. As a result, it is unclear what the inheritance is for these two new PDF 2.0 attributes. 

@DuffJohnson or @mrbhardy - please suggest the correct inheritance for each artifact attribute.

Also, the **Subtype** entry states that it was defined in PDF 1.7 (ISO 32000-1:2008) however this is not correct. ISO 32000-1:2008 only defined "Table 330 – Property list entries for artifacts" in 14.8.2.2.2 (what is now Table 363 in 14.8.2.2.2 in ISO 32000-2:2020), but this is a property list for marked content and **_NOT_** structure element attributes. I believe the "PDF 1.7" is a hangover from a copy and paste of the marked content information. Instead, all 3 entries in "Table 385 - Standard artifact attributes" in ISO 32000-2"2020 should be marked as new in PDF 2.0.

**Comment by petervwyatt** [comment]
I should also mention that **BBox** is also mentioned in "Table 377 — Standard layout attributes" under "Figure, Form, Formula and Table elements" with an inheritance of "No". 

This means Table 377 should also be modified to pull **BBox** into its own new row labelled "Figure, Form, Formula, Table and Artifact elements" (Artifact is added).

**Comment by petervwyatt** [comment]
I will also add that "Table 385 — Standard artifact attributes" is the ONLY PDF dictionary in ISO 32000 that _breaks_ a golden PDF rule that the **/Type** entry "_identifies the type of object the dictionary describes_" as per 7.3.7:

> By convention, the **Type** entry of such a dictionary, if present, identifies the type of object the dictionary describes. In some cases, a **Subtype** entry (sometimes abbreviated **S**) may be used to further identify a specialised subcategory of the general type. The value of the **Type** or **Subtype** entry shall always be a name. For example, in a font dictionary, the value of the **Type** entry shall always be _Font_, whereas that of the **Subtype** entry may be _Type1_, _TrueType_, or one of several other values.

In the case of standard attribute artifact dictionaries, **/Type** (if it was defined) would be something like **_StructAttribute_** akin to **_StructElem_** that is used for structure elements.

**Comment by mrbhardy** [comment]
@petervwyatt agreed on the not inheritable piece.  However, I worry about mismatching the values in the property list versus attributes, even though I completely agree **Type** is usually reserved.  Since there is no **Type** associated with attributes, my feeling is leave it.  However, open to hear other opinions...

**Comment by petervwyatt** [comment]
Thanks for confirming the inheritance.

For **Type**/**Subtype**: maybe just adding an informative Note stating that this is not the norm is sufficient. But happy to hear suggestions from others.

**Comment by petervwyatt** [comment]
PDF TWG agree on inheritability. Also add informative note regarding non-std use of **Type** and **Subtype** key names
