### ISSUE TITLE
Logical structure, Document catalog dictionary (Table 29, 7.7.2): StructTreeRoot entry incomplete

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#348]
This report relates to #106, although in the opposite way (missing mandatory indirect reference requirement).

`StructTreeRoot` entry in Table 29 (Entries in the catalog dictionary) in subclause 7.7.2 (Document catalog dictionary) omits mandatory indirect reference requirement (`P` entry in Table 355 (Entries in a structure element dictionary) in subclause 14.7.2 (Structure hierarchy) *requires structure tree root to be an indirect reference*, obviously).

### CORRECTION

My reformulation proposal replaces:
> (Optional; PDF 1.3) [...]

with:
`(Optional; PDF 1.3; shall be an indirect reference) [...]`

**Comment by petervwyatt** [comment]
Very nicely spotted! Thank you!

**Comment by petervwyatt** [comment]
PDF TWG agree
