### ISSUE TITLE
Logical structure, parent tree (14.7.5.4): PDF version of StructParent entry

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#350]
`StructParent` entry is declared as "PDF 1.3" (see Table 359 (Additional dictionary entries for structure element access)) despite, weirdly, [the edition of PDF 1.3 currently available on Adobe website](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/pdfreference1.3.pdf) defines only `StructParents`, NOT `StructParent` (see TABLE 8.10 (Additional dictionary entry for structure element access) herein; note also that, eg,  image XObject (TABLE 4.35 (Entries in an image dictionary)) contains `StructParents` instead of ISO PDF's `StructParent`).

![PDF 1.3, TABLE 8.10](https://github.com/pdf-association/pdf-issues/assets/10812966/c3bd7bf6-e893-4a3b-a140-e43ea5a5fd35)

Since [PDF 1.4](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/pdfreference1.4.pdf) declares both `StructParent` and `StructParents` as "PDF 1.3" (see TABLE 9.13 (Additional dictionary entry for structure element access) herein), I suppose an erratum was issued between them: can someone please confirm this? If so, for philological reasons Adobe should be notified to replace the edition of PDF 1.3 currently available on their website with the latest one; conversely, if `StructParent` was confirmed as a PDF 1.4 addition, its occurrences in ISO PDF dictionaries should be amended accordingly.

![PDF 1.4, TABLE 9.13](https://github.com/pdf-association/pdf-issues/assets/10812966/757eceee-0f76-491c-a2f0-d5a7ff09b59a)

**Comment by mkl-public** [comment]
See the PDF Reference 1.3 Errata. 

>Page 497, Table 8.10, StructParents entry: Replace this entry
>with the following two entries:
>
>StructParent    integer   (Required for all objects that are structural
>content items; PDF 1.3) The integer key of this object's entry in the
>structural parent tree.
>
>StructParents   integer   (Required for all content streams
>containing marked-content sequences that are structural content items;
>PDF 1.3) The integer key of this object's entry in the structural
>parent tree.

**Comment by stechio** [comment]
Ops, my fault :grimacing: (I assumed that, after so many years, the errata of the first edition were integrated in a published version...), thanks!

**Comment by car222222** [comment]
Glad that this historical detail got sorted so quickly !!

**Comment by mkl-public** [comment]
By the way, there are lots and lots of other StrustParent[s] replacements in the 1.3 Errata, so you're likely to stumble over similar discrepancies if you look up those key words.
