### ISSUE TITLE
Marked content (14.6.1): Marked-content point clarification

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#351]
While the purpose of marked-content sequences is absolutely clear because of their extensive coverage within ISO PDF, ***marked-content points** seem quite obscure*: AFAIK, in the whole spec there is no statement nor example explaining why marked-content points exist and what use they are intended for. Till ISO PDF 1.7 there was a subclause (14.6.3 (Marked Content and Clipping)) which made some sketchy example fleetingly mentioning marked-content points, nothing more.

IMHO, *subclause 14.6.1 (General, Marked content) should clearly state the purpose of marked-content points, along with practical examples* (the same way as marked-content sequences are currently described by ISO PDF). Otherwise, if marked-content points have become neglected and obsolete, that should be stated as well (deprecation?).

**Comment by petervwyatt** [comment]
Like many of the flexible features in "general" PDF, marked content points exist to support extensions by implementers and vendors. Historically you can find extant PDFs with such features from certain vendors for their proprietary technology. You can be assured they have no impact on standardized logical structure as they are not mentioned in ISO 32000 for this purpose. Although we would like to see public-facing documentation from implementers and vendors who extend PDF via such features, this is not a requirement.
