### ISSUE TITLE
Common data structures (7.9): 'date' type contradiction

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#352]
Table 35 (PDF data types) in 7.9.1 (General, Common data structures) declares `date` type as `ASCII string`, *despite its dedicated subclause (7.9.4 (Dates)) defines it as `text string`*.

As [already emerged in a related issue](https://github.com/pdf-association/pdf-issues/issues/322#issuecomment-1674933919), for some obscure reason, that definition has changed over time, inadvertently creating a rift between the ancient declaration in Table 35 (`ASCII string`) and the current definition in subclause 7.9.4 (`text string`). I assume that the ancient declaration was so deeply engrained in everybody's mind that nobody cared about this blatant contradiction.

### CORRECTION

IMHO, subclause 7.9.4 definition should be reverted to `ASCII string`.

**Comment by petervwyatt** [comment]
The vendor-neutral ISO working group previously decided PDF date strings are of definitely type _text string_ as per subclause 7.9.4.  Table 35 is in error as per other errata.

**Comment by stechio** [comment]
Are those WG proceedings publicly available (just to understand how they came to that decision)? thanks

**Comment by petervwyatt** [comment]
All ISO work is done under ISO policy and procedures and is limited to ISO members - but you can join via your national body (https://www.iso.org/get-involved.html) or through any liaison organization for ISO TC 171 SC 2 (https://www.iso.org/committee/53674.html), such as the PDF Association, ETSI, Khronos or IPTC.
