### ISSUE TITLE
Logical structure, attributes (14.7.6): 'O' entry inconsistency

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#354]
Across subclauses 14.7 (Logical structure) and 14.8 (Tagged PDF), `O` entry of attribute object dictionaries (see Table 360 in subclause 14.7.6 (Structure attributes)) is defined in multiple, confusing ways (bolding is mine):

- as "**conforming product** that owns the attribute information" (subclause 14.7.6.1 (General, Structure attributes))
- as "**PDF processor** creating the attribute data" (Table 360 (Entries common to all attribute object dictionaries))
- as "**owner** [...] which determines the interpretation of the attributes defined in the object's dictionary" (subclause 14.8.5.2 (Standard attribute owners))

IMHO, *the last definition is the only accurate one, as "conforming product" and "PDF processor" are misleadingly restrictive* (the Standard attribute owners in subclause 14.8.5.2 have nothing to do with what the rest of the spec calls "PDF processors", yet they are owners as well).

### CORRECTION

My proposal is to harmonize the ways attribute information owners are referred to in ISO PDF:

- subclause 14.7.6.1 (General, Structure attributes): replace "conforming product that owns the attribute information" with "`owner of the attribute information`"
- `O` entry, Table 360 (Entries common to all attribute object dictionaries): replace as follows:
`(Required) The name of the owner of the attribute data. The value shall either be NSO, UserProperties (see "Table 361 — Additional entries in an attribute object dictionary for user properties"), one of the values from 14.8.5, "Standard structure attributes", or the name of the PDF processor conforming to the guidelines described in Annex E, "Extending PDF".`
`[...]`

**Comment by petervwyatt** [comment]
See also #226

**Comment by petervwyatt** [comment]
PDF TWG agree
