### ISSUE TITLE
Clause 9.10 is misnamed; should be "Extraction of characters"

### ISSUE THREAD

**Issue by DuffJohnson** [pdf-association/pdf-issues#355]
Clause 9.10 title is "Extraction of text content", but this is misleading, as the clause pertains ONLY to extraction of information at a character level.

Clause 9.10 should be renamed to "Extraction of characters", or possibly, "Extraction of character content".

Note that the phrase "Extraction of text" does not appear elsewhere in the clause, however, "extraction of character content" does.

**Comment by MatthiasValvekens** [comment]
Just to make sure I understand: is the issue that "text extraction" would also imply things like inferring the correct reading order etc., and that that is out of scope here?

**Comment by DuffJohnson** [comment]
Precisely so.

**Comment by mkl-public** [comment]
If you look at the first paragraph of 9.10.1, though, you read:

>The preceding subclauses describe all the facilities for showing **text** and causing glyphs to be painted on the page. In addition to rendering **text**, PDF processors often need to determine the information content of **text** — that is, its meaning according to some standard character identification as opposed to its rendered appearance. This need arises during operations such as searching, indexing, and exporting of **text** to other file formats.

Furthermore, in the same chapter you have ***text** state parameters and operators*, ***text** objects, ***text** positioning operators*, ***text** showing operators*, ***text** space*, etc. Most of these items also only deal with rendering individual glyphs, not with human-centric details like reading orders and whatnot.

Thus, replacing "text" by something else wherever it only refers to small collections of characters or glyphs, would require a complete rewrite of chapter 9.

**Comment by DuffJohnson** [comment]
I agree that the proposal holds implications beyond the title of the clause. In the context of the paragraph you've quoted, at least, I believe "character" could be readily substituted for "text". 

In general, I'd like to see "character" and "text" properly disambiguated throughout (although I know that's a heavy lift). One approach might be to augment the definitions of character (3.10) and glyph (3.29) in conjunction with (and linked to) a new definition for "text" in clause 3.

**Comment by MatthiasValvekens** [comment]
> in conjunction with (and linked to) a new definition for "text" in clause 3

Hmm, I don't think this is a bad idea per se, but if we're going to redefine what something as basic as "text" means, then I don't think we have a choice: wouldn't that pretty much force us to also revise (or at least thoroughly review) all of clause 8?

Either way, I think we can apply the spot fix in 9.10 without having to do all of that work: even if we take the current vague/broad definition of text, it's arguably just replacing a generic term with a more specific/accurate one.
That's not to say that reviewing clause 8 wouldn't be worth it (I have no strong opinion on that), but I don't think they're inextricably intertwined.

**Comment by DuffJohnson** [comment]
Well... "text" isn't (formally) defined at all in 32k (yet), which is a pity. Best there is (I guess?) is at the opening of clause 9.: "...characters with glyphs from fonts...".

My focus is on "extraction". I agree that spot-fixing 9.10 (beyond the title) is reasonable / possible, and need not imply surgery elsewhere.... but I would certainly understand the argument, should it be made, that such "clarifications" could cause trouble unless they were made holistically, and perhaps, on that basis, aren't worth the effort.

**Comment by petervwyatt** [comment]
Maybe a short-term solution more appropriate for an errata is the addition of an informative NOTE in 9.10 stating that this text extraction algorithm may not extract text in logical reading order...?

**Comment by DuffJohnson** [comment]
IMO, that's an acceptable (if minimal) way to address the proximate issue... but hopefully not at the expense of some future enhancement disambiguating "text", "character" (and "glyph") more generally.

**Comment by car222222** [comment]
I have found, from many decades of trying, that it is extremely difficult to be precise concerning "characters" and "glyphs" and "slots/numbers in an encoding" and, . . . etc. So Good Luck with that! 

As for precisely defining the many similar but distinct uses of the term "text", I would not know where to begin.

**Comment by car222222** [comment]
Maybe a more radical change of title for 9.10 would avoid having any concern there about a definition of either “text” or “characters”. 

Something like the following would, in addition, provide a much better description of the actual practical content of this Clause.

Since the clause in fact describes only this one method for extraction, the title could usefully be:
“Character identification and Unicode values” 
-- as this would give a much more accurate (and hence more useful) description of the actual,
substantive content of the clause.

If this suggestion is too radical, here is another version:
"Extraction of meaning/information using Unicode values"

**Comment by car222222** [comment]
But if it must contain "Extraction", then I vote for "Extraction of character content".

**Comment by petervwyatt** [comment]
PDF TWG will discuss next time when @DuffJohnson (OP) is present
