### ISSUE TITLE
Tagged PDF, Standard structure attribute owners (14.8.5.2): Inaccurate descriptions of 'CSS-*' entries

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#357]
Descriptions of `CSS-*` entries in Table 376 (Standard structure attribute owners) incorrectly qualify CSS formats with "version", while the correct term is "level".

### CORRECTION

<table>
<tr><td>CSS-1</td><td>Additional attributes governing translation to a format using CSS, level 1</td></tr>
<tr><td>CSS-2</td><td>Additional attributes governing translation to a format using CSS, level 2, revision 1</td></tr>
<tr><td>CSS-3</td><td>Additional attributes governing translation to a format using CSS, level 3</td></tr>
</table>

**Comment by mrbhardy** [comment]
Agreed

**Comment by petervwyatt** [comment]
PDF TWG agree
