### ISSUE TITLE
Default values for entries in graphics state parameter dictionaries?

### ISSUE THREAD

**Issue by seehuhn** [pdf-association/pdf-issues#360]
Section 8.4.5 (Graphics state parameter dictionaries) describes how graphics state parameter dictionaries are constructed.  Table 57 lists all possible dictionary keys.  All keys are marked as optional.  The entry for `UseBlackPtComp` states "The default value is: Default".

My understanding was that graphics state parameter dictionaries only change the parameters explicitly mentioned in the dictionary, and leave state corresponding to missing keys unchanged.  If this reading is correct, then giving a default value in table 57 makes no sense.

My suggestions would be:

1.  Remove the statement "The default value is: Default" from table 57.  (Note that table 51 already states that the initial value of the corresponding graphics state parameter is `Default`.)
2. Make it explicit that the `gs` operator does not change graphics state parameters not mentioned in the dictionary.  (I currently can't find anywhere in the spec which says this explicitly.)

**Comment by petervwyatt** [comment]
Correcting Table 57 is the correct solution, as all other entries do not mention their default values.

**Comment by petervwyatt** [comment]
PDF TWG agree
