### ISSUE TITLE
Table 311 Entries in a 3D stream dictionary, Resources entry is under-specified

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#362]
Table 311 Entries in a 3D stream dictionary, **Resources** entry is under-specified. The current wording is:

> A name tree that maps name strings to objects that may be used by applications or scripts to modify the default view of the 3D artwork. The names in this name tree shall be text strings so as to be encoded in a way that will be accessible from ECMAScript. 

This does NOT state that these are file specification strings (clause 7.11.2) or embedded file streams or ...
What can they be?

**Comment by petervwyatt** [comment]
Since the **Resources** relate to the growing list of 3D data formats, theoretically they can be anything but the name tree string must be compatible with ECMAScript (as already stated). Therefore basic objects such as integers, reals, booleans, and strings would all seem to be OK. Streams should also be OK (since it is really the stream data). However arrays and dictionaries are expressed in PDF syntax and that is not necessarily appropriate for the 3D data format, if they even support such data structures - and if they did it would be better if these were encoded as strings using the syntax appropriate for the 3D data format (e.g. adding commas between array elements, using JSON format, etc).

So the question becomes: does the PDF stipulate an allowed set (and thus a prohibited set) like is currently done for DPM; or does it allow any PDF object along with an "implementation dependent" statement? Reliable interoperability across 3D runtimes probably needs the former along with some application/implementation notes for each 3D format.

@datalogics-pgallot ?

**Comment by datalogics-pgallot** [comment]
@petervwyatt I think that the relevant sections of the ISO 21757-1:2020 spec. are 11.1.5 Resource Objects and 12.26 Resource, but see also sections 12.13.3.1 and 12.28.2.2. 
Based on those sections, I expected file specification strings (clause 7.11.2) or embedded file streams...

And maybe that's what they are supposed to be; Unfortunately, I can't tell.  Reviewing what I found in the digital Corpora, I think I only found file 1780126.pdf that attempted to use the Resources nametree, and that file causes conniptions in a well-known implementation with its Image XObjects entries in the Resources nametree.  I found 6 others that had empty Resources nametrees.

**Comment by petervwyatt** [comment]
@datalogics-pgallot - thanks, but public extant data won't necessarily cover all that is feasible - and definitely not what new forms of 3D rich media can support. Hence why I compared to DPM. But if something is a stream how does the 3D runtime engine know what kind of data is in the stream... or we leave this unspecified and make it a 3D runtime engine issue.

**Comment by datalogics-pgallot** [comment]
@petervwyatt Understood; I'm firmly in the camp that having it under-specified is a specification problem that should be rectified. 
Perhaps @lrosenthol  can weigh in on how certain well-known implementation(s) choose to handle this PDF feature.

**Comment by lrosenthol** [comment]
The language here is unchanged since PDF 1.6 (though the reference to the Acrobat 3D Ref is no longer present, for obvious reasons).

Short version - this is a feature that was never fully implemented by well-known implementation and this key should be marked deprecated!

Longer version - the intent was that this key would hold "hot swappable" resources such as images, scripts, etc. that could be referenced from a 3D JS script (via the `Resource` object) and then used to replace parts of the 3D image.  It was never fully realized but the key got left in the spec.

**Comment by petervwyatt** [comment]
PDF TWG agree but Stuart to check.

**Comment by petervwyatt** [comment]
@stuartgalt - please check. You are not a member of the PDF TWG so I cannot assign to you... please join if you wish via your PDFa member area.

**Comment by stuartgalt** [comment]
Stuart checked and agree depreciation is fine.

**Comment by petervwyatt** [comment]
Proposed solution: mark as deprecated.

**Comment by petervwyatt** [comment]
PDF TWG agree to deprecate. Add informative note as to reason for deprecation.
