### ISSUE TITLE
14.9.4 ActualText example of hyphenated "Drucker" is no longer current practice since last century

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#364]
Clause 14.9.4 `ActualText` example of hyphenated "Drucker" is no longer a current practice in the German language since last century (thanks @u-fischer).

Suggest this is noted in the current EXAMPLE lead-in para (so the example is kept), but that some additional examples, such as from https://www.butte.edu/departments/cas/tipsheets/punctuation/hyphen.html, also be added (as EXAMPLE 2, 3, etc).  Examples are informative and thus do not alter anything.

**Comment by petervwyatt** [comment]
@DuffJohnson - please have the PDF/UA TWG develop some appropriate examples and related text.

**Comment by petervwyatt** [comment]
Proposed from TWG:
```
/Span << /ActualText (Missing space) >> BDC
  (Missing) Tj
  44 0 Td
  (space) Tj
EMC
```

**Comment by DuffJohnson** [comment]
I gave you the wrong example, sorry! The recommendation was actually...

```
/Span<<
  /ActualText (Missing )
>>BDC
  (Missing)Tj
EMC
44 0 Td
(space)Tj
```

**Comment by mrbhardy** [comment]
I might go a step further:

```
/Span <</ActualTest (Missing )>> BDC
    (Missing) Tj
EMC
44 0 Td % Simulate space by moving the drawing position
(space) Tj 
```

**Comment by petervwyatt** [comment]
PDF TWG agree - current example to be kept.
