### ISSUE TITLE
Clarify /BitsPerComponent requirements in /DecodeParms

### ISSUE THREAD

**Issue by johnwhitington** [pdf-association/pdf-issues#366]
If, hypothetically, I see this image:

```
BI
/CS/RGB
/W 347
/H 1
/BPC 16
/F/Fl
/DP<</Predictor 15
/Columns 347
/Colors 3>>
ID 
```

Is the /BitsPerComponent for the predictor filter 8 (because that's the default value for /BitsPerComponent in /DecodeParms specified in Table 8) or 16 (because the /BPC entry in the main dictionary says 16 per Table 87)?

From a reading of the various parts of the documentation, it seems that the /BitsPerComponent entry in the /DecodeParms is just there for situations where the /BitsPerComponent entry in the image dictionary is not required, and therefore missing.

Table 87 does also say:

"...and an LZWDecode or FlateDecode filter shall deliver samples of a specified size if a predictor function is used."

Does that imply that the /BitsPerComponent entry in the /DecodeParms, if present, must be equal to the /BitsPerComponent entry in the image dictionary, if present?

Suggested remediation: a clarifying note in the /BitsPerComponent entry in Table 8, pointing out any interaction, or the lack of interaction between that entry and the main /BitsPerComponent entry in the image dictionary.

**Comment by johnwhitington** [comment]
Found a real-world example (Exported by Illustrator CS2) where both are present, and different:

```
20 0 obj
<</Subtype/Image/Length 13821/Filter/FlateDecode/Name/X/SMask 17 0 R
    /BitsPerComponent 8/ColorSpace/DeviceRGB/Width 221
    /DecodeParms<</Columns 221/Predictor 15/BitsPerComponent 4/Colors 3>>
    /Height 173/Type/XObject>>
stream
```

So this is probably a misunderstanding on my part. I shall dive back into the spec...

File on request.

**Comment by robinwatts** [comment]
My understanding of it is that /BitsPerComponent in the image dictionary is unrelated to the /BitsPerComponent field in the DecodeParms.

The /BitsPerComponent in the /DecodeParms is only used to influence the behaviour of the predictor. It can, quite permissibly, be different to the /BitsPerComponent of the image itself.

No implication, either way, can be drawn from the value of one of those to the other one.

**Comment by petervwyatt** [comment]
Possibly worth an informative note?

**Comment by robinwatts** [comment]
It seems that there is at least one person for whom such a note would have saved some head-scratching.

**Comment by johnwhitington** [comment]
Thank-you Robin.

Two suggestions. First, to tweak this paragraph in Table 87 /BitsPerComponent:

"If the image stream uses a filter, the value of BitsPerComponent shall be
consistent with the size of the data samples that the filter delivers. In
particular, a CCITTFaxDecode or JBIG2Decode filter shall always deliver
1-bit samples, a RunLengthDecode or DCTDecode filter shall always
deliver 8-bit samples, and an LZWDecode or FlateDecode filter shall
deliver samples of a specified size if a predictor function is used."

In the case of LZWDecode / FlateDecode does "deliver samples of a specified size" just mean "deliver the correct amount of data"? If the Predictor /BitsPerComponent is unrelated to the image /BitsPerComponent, it can't mean any more than that, surely?

Perhaps replacing "shall deliver samples of a specified size if a predictor function is used." with "shall deliver samples of the specified size." is sufficient here. If there's no formal relation to the /BitsPerComponent in the predictor, there's no need to mention it.

Second, a note could be added to Table 8 to point out that there is not necessarily any relation between the predictor parameters (/Colors, /BitsPerComponent) and identically-named parameters (/Colors, /BitsPerComponent) in an image dictionary.

**Comment by petervwyatt** [comment]
PDF TWG agree
