### ISSUE TITLE
Minor typos in section 9.3.6 (Text rendering mode)

### ISSUE THREAD

**Issue by seehuhn** [pdf-association/pdf-issues#372]
There are two typos near the end of section 9.3.6:

1. I believe that in Note 3, "a zero line with round end caps" should be "a zero-length line with round end caps".
2. Just after Note 3, "The $e$ and $f$ components of **Tm**" should be "The $e$ and $f$ components of $T_m$" (since the operator does not have components, but the parameter does).

(Please let me know if you are interested in cosmetic issues like this.  I'm happy to either report or not report these, whatever is best for you.)

**Comment by petervwyatt** [comment]
Always interested in all issues - you never know how others might interpret what are seemingly small errors.
Thanks!

**Comment by petervwyatt** [comment]
PDF TWG agree
