### ISSUE TITLE
possible typo in table 106 (Text-positioning operators)

### ISSUE THREAD

**Issue by seehuhn** [pdf-association/pdf-issues#373]
Table 106 states that **T*** has has the same effect as "0 $-T_l$ **TD**".  I believe that in this explanation, **TD** should be replaced with **Td**, since it seems redundant and unnecessarily confusing to set $T_l$ to the value it already has, before adjusting the text matrix.

Note that the PDF 1.7 spec said **Td** here, so my proposed change would undo a 1.7 -> 2.0 change.

**Comment by petervwyatt** [comment]
Looks to be an accidental auto-capitalization by MSWord. Thanks!
