### ISSUE TITLE
Associated Files for marked content violates requirements for property lists

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#374]
Requirements in clause 14.13.5 "Associated files linked to graphics objects" contravene requirements specified in "Table 34 — Entries in a resource dictionary" and clause 14.6.2 "Property Lists"::

Clause 14.1.3.5:
> The property list associated with the marked-content shall specify an array of file specification dictionaries to which the content is associated. The named resource in the _property list_ (see 14.6.2, "Property lists") shall specify an array of file specification dictionaries to which the content is associated. The relationship that the associated files have to the PDF content is supplied by the **AFRelationship** key in each file specification dictionary.

This states the property list is an array.

Table 34, **Properties**:
>(Optional; PDF 1.2) A dictionary that maps resource names to property list dictionaries for marked-content (see 14.6.2, "Property lists").

14.6.2 "Property Lists":
> The _property_ list is a dictionary containing information (either private or of types defined in this document) meaningful to the PDF processor

These both state that the names in **Resources** **Properties** and the inline equivalent can only be dictionaries which is not what 14.13.5 states!

No examples are given, so how does one specify Associated Files via marked content, either using a named property or directly inline? 

```
/Resources << 
    /Properties << /MyFiles1 ??? >> 
>>
...
/AF /MyFiles1 BDC ... EMC
/AF << ??? >> BDC ... EMC
```

Is an extra level of indirection required (e.g. a dictionary with `/AF` key?) so that an array of file spec dictionaries (written as `<<...>>` below) can then be present and still meet requirements for property lists to always be dictionaries? 

```
/Resources << 
    /Properties << 
        /MyFiles1 << /AF [ <<...>> <<...>> ] >> 
    >> 
>>
...
/AF /MyFiles1 BDC ... EMC
/AF << /AF [ <<...>> <<...>> ] >> BDC ... EMC
```

**Comment by sgaither** [comment]
I have not done this, but have been using /AF inside an Image XObject dictionary where its value is indeed an array of dictionaries to allow multiple files with different /AFRelationship values (further we have seen this just recently with different representations of equations via TeX and MathML).  So far as I know, everything in 14.13 does refer to an array of dictionaries, so it is only the Property List definition which does appear to be in conflict (as you do note).  For processors, an array would indeed be expected, but one could argue the same expectation for a Property List being a dictionary; so, I do think PDFA/ISO has painted ourselves into a corner a bit.  It is also interesting to note I think that all entries in a Resource dictionary have dictionaries as their value (except the deprecated ProcSet).  I am quite curious as to how the TeX/MathML effort has tagged equations.

**Comment by u-fischer** [comment]
> I am quite curious as to how the TeX/MathML effort has tagged equations.

Happily we don't have to handle this case here currently, as we are attaching /AF files only to structures (or to the root) and not to marked content ;-). Examples are here https://github.com/latex3/tagging-project/discussions/56

**Comment by petervwyatt** [comment]
PDF TWG agree to move forward with specifying a dictionary with a key to support the array syntax. To be drafted.

**Comment by petervwyatt** [comment]
Proposed edits to 14.13.5 are in the attached PDF: [MarkedContent-AssociatedFiles.pdf](https://github.com/pdf-association/pdf-issues/files/14325116/MarkedContent-AssociatedFiles.pdf)
I choose to use a uniquely named key "**MCAF**" (similar to the naming convention of **MCID**), rather than have 2 keys both called **AF** as above which would likely cause confusion and malformed files.

**Comment by sgaither** [comment]
I think this looks good except for the first two occurrences of “dictionarys” that should be “dictionaries”.
Also, maybe just personal preference, but I would use “/MF1” instead of “/MyFiles” in the example as the latter looks like a readable keyword instead of being merely an identifier.

**Comment by car222222** [comment]
"dictionarys" is just good old Oz spelling, I guess? 😃

**Comment by car222222** [comment]
"MCAF" looks good.

**Comment by petervwyatt** [comment]
PDF TWG agree subject to corrections listed above.
TBD what to do about PDF/A-4 dated revision (include this in Amd1???)

**Comment by petervwyatt** [comment]
* added label to indicate required Amd1 errata for PDF/A-4 dated revision (otherwise AF cannot be used with marked content for PDF/A-4f or PDF/A-4e)

* PDF/A-3 Annex E.5 is also completely incorrect (since this is where the words originated) and also needs correction
