### ISSUE TITLE
Is "horizontal scaling" a percentage?

### ISSUE THREAD

**Issue by seehuhn** [pdf-association/pdf-issues#376]
Section 9.3.4 (Horizontal scaling) specifies the horizontal scaling parameter, $T_h$, to be a percentage:

> Its value shall be specified as a percentage of the normal width of the glyphs, with 100 being the normal width.

This is supported by the examples of $T_h = 100$ and $T_h = 50$ in Figure 58.

In contrast, Table 103 states that the **Tz** operator sets $T_h$ to $\textrm{scale} ÷ 100$, giving the impression that only the argument to **Tz** is a percentage and that $T_h=1$ might correspond to normal width.  This interpretation is supported by the text in section 9.4.4 (Text space details), where dimensions are multiplied with $T_h$ instead of $T_h/100$.

This leaves the question whether $T_h = 100$ or $T_h = 1$ corresponds to normal width.

Suggested fixes (assuming that the parameter value $T_h = 1$ corresponds to normal width, and that the argument to **Tz** is a percentage):

* Remove "Initial value: 100 (normal width)" from the **Tz** row of Table 103.
* Maybe change "(scale ÷ 100)" to "(*scale* ÷ 100)", adding italics?
* In section 9.3.4, replace "Its value shall be specified as a percentage of the normal width of the glyphs, with 100 being the normal width" to "The default value is 1, corresponding to normal width".
* Maybe add a sentence making it explicit what the parameter actually does, something like "... horizontally stretches/shrinks the glyph, so that is width becomes $w_x T_h$, where $w_x$ is ..."?
* Maybe say whether or not $T_h$ is allowed to be zero or negative?
* In Figure 58, replace $T_h = 100$ with $T_h = 1$ and $T_h = 50$ with $T_h = 0.5$.

**Comment by petervwyatt** [comment]
Looking through the old Adobe legacy references $T_h$ has always been specified as a percentage (with 100 == normal) so I think the other formulae that are incorrect...
@lrosenthol ?

**Comment by lrosenthol** [comment]
Agree with @petervwyatt - look like a bug crept in in that formula...

**Comment by petervwyatt** [comment]
The only places I can see $T_h$ used in a formula anywhere are NOTE 2 in 9.4.4 and the formula for $T_x$ just below. Both assume a normalized value of $T_h$ = 1 for 100% so Figure 58 is at fault and needs correction to show 100 **Tz** being $T_h$ = 1 and 50 **Tz** being $T_h$ = 0.5. Table 103 should also be corrected to have scale in italics as per OP's suggestion, but all other mentions of $T_h$ are in a mathematical 1.0 normalized sense, whereas **Tz** is the operator with the numeric percentage as an operand.

Where do we stand on zero and negative values?

**Comment by lrosenthol** [comment]
So well known implementation is fine with 0 (though it does special case it).  And I see nothing that would prefer a negative value either - though I admit to not fully understanding what that would mean in real life

**Comment by petervwyatt** [comment]
[PDF-Horizontal-Scaling.pdf](https://github.com/pdf-association/pdf-issues/files/14174194/PDF-Horizontal-Scaling.pdf)

Simple test PDF for horizontal text that tests 100 (default), 50, 5, 0, -5, -50 and -100 values for **Tz**.
All implementations I tested appear to support both zero and negative percentages, with zero meaning nothing shown and negative values reverse-mirroring the text. Suggest therefore that we note this informatively.

**Comment by petervwyatt** [comment]
PDF TWG agree to make NOTE 2 normative and correct Figure 58

**Comment by seehuhn** [comment]
Possibly the start of section 9.3.4 should also be changed: It currently says

> The horizontal scaling parameter, Th, adjusts the width of glyphs by stretching or compressing them in
> the horizontal direction. Its value shall be specified as a percentage of the normal width of the glyphs,
> with 100 being the normal width.

Should 100 be replaced with 1 here, since $T_h=1$ corresponds to normal width, and $T_h=100$ does not?

**Comment by mkl-public** [comment]
Then I would also change the remaining wording: "Its value shall be specified as ..." can be understood as "Its value shall be specified _in the parameter of the **Tz** operator_ as ...", and in that case the 100 would be correct.

So something along the lines of "A value of 1 represents the normal width of the glyph." Probably followed by "Beware: When setting $T_h$ with the **Tz** operator, the value of the parameter of the operator will be divided by 100 before assignment."

**Comment by petervwyatt** [comment]
Yes - I will wordsmith appropriately. $T_h$ is the scaling factor used in the calculation of text matrices with 1.0 being normal, while the numeric operand to **Tz** is the percentage with 100 (meaning 100%) being normal.
