### ISSUE TITLE
Are object numbers and generation numbers PDF numeric integer objects? 

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#379]
Are object numbers and generation numbers PDF numeric integer objects? 
i.e. can they have an optional `+` sign (but never `-` since they can never be negative), and/or can they have optional leading zeros?

This applies to indirect references and indirect objects (`X Y obj`).

See also Errata #300 and https://pdf-issues.pdfa.org/32000-2-2020/clause07.html#H7.3.3.

e.g.
```
+0123 +0 R

+00456 +0 obj
...
endobj
```

Or are they only permitted to be a sequence of decimal digits `0`-`9` with the first digit being non-zero (`1`-`9`)?

**Comment by mkl-public** [comment]
In the spec I only find the object number to be characterized as a positive integer and the generation number as non-negative integer. In particular I don't find them to be PDF objects in their own right (and I doubt we want them to be that!).

The specification only defines a representation in the special case of cross reference entries as `10-digit object number nnnnnnnnnn` (in **f** entries) and as `5-digit generation number ggggg` (in **f** and **n** entries). Other than that it only hints at the representation by means of examples as sequences of decimal digits.

Thus, in the context of an object identifier the representation is not yet specified. To parallel the specification for cross reference entries I'd suggest it to be "a sequence of decimal digits" without forbidding leading zeros.

**Comment by petervwyatt** [comment]
There are also the 2 integers in each conventional cross-reference subsection marker line.

The 5- and 10-byte cross-reference numbers also date back to a time of fixed line lengths for reading the alleged 😀 20-byte lines.

**Comment by mkl-public** [comment]
> There are also the 2 integers in each conventional cross-reference subsection marker line.

Indeed. Their representation also is undefined (only their separator is defined) and merely hinted at by example.

> The 5- and 10-byte cross-reference numbers also date back to a time of fixed line lengths

Yes, at least in that context it has been made clear that only digits make up those numbers.

**Comment by petervwyatt** [comment]
To try and get in-principle traction on moving this forward - proposed solution (wordsmithing to come later):

* formally define both object numbers and generation numbers as PDF integer objects since I suspect that is the reality of most parsers today. This ensures no PDF file today will get invalidated. Note that `-` is never allowed since both object numbers and generation numbers are always greater than or equal to zero. Potentially add a recommendation ("should not") to not have any leading `+` sign or any unnecessary leading zeros (rather than mandate with a "shall not") for use in direct objects and indirect references.  Future PDF subsets could then mandate no leading `+` sign or zeros if they so wish. The ONLY exception to this rule are the fixed width 10-digit and 5-digit numbers in conventional cross reference entries which can only contain decimal digits (so never any `+` sign, but certainly many leading zeros).

**Comment by mkl-public** [comment]
Have you actually seen a `+` sign used in indirect references or objects? 

I'd have to check to be sure but I think multiple PDF libraries I have to do with will only expect digits there. 

I have the hunch that allowing a `+` there will break more code than disallowing it.

**Comment by stechio** [comment]
> To try and get in-principle traction on moving this forward - proposed solution (wordsmithing to come later):
> 
> * formally define both object numbers and generation numbers as PDF integer objects since I suspect that is the reality of most parsers today. 

Please, DON'T do that: even if PDF integers and object identifier numbers are lexically indistinguishable as tokens, they belong to distinct syntactic definitions. They may _accidentally_ look alike (positive integer number without `+` sign) BUT nonetheless their respective syntactic meanings don't overlap at all.

Despite the representation of object identifiers may be not formally specified yet, IMO there is no ambiguity in its definition (is there any implementer out there who sanely prefixed object identifier numbers with a `+` sign? On the other hand, I don't think any parser may reasonably represent object identifier numbers as PDF integers): object identifiers should be treated as symbols which happen to be made of digits-only numbers — _applying the syntax of PDF integers to them would be an unnecessary (and ungraceful) confusion between lexical and syntactic levels_.

**Comment by stechio** [comment]
I added a BNF representation to [my comment](https://github.com/pdf-association/pdf-issues/issues/379#issuecomment-2057109384) to make my point clearer.

**Comment by petervwyatt** [comment]
PDF TWG agree that object numbers and generations shall **NOT** have leading + or leading zeros.
Reword a full proposed solution for later.

**Comment by petervwyatt** [comment]
Proposed updates to 7.3.10 "Indirect objects" which covers both the definitions for `X Y obj` and `X Y R`:

> A positive (non-zero) decimal integer object number without any leading `+` sign or leading zeros. Indirect objects may be numbered sequentially within a PDF file, but this is not required; object numbers may be assigned in any arbitrary order.

> A non-negative decimal integer generation number without any leading `+` sign or leading zeros. In a newly created file, all indirect objects shall have generation numbers of 0. Non-zero generation numbers may be introduced when the file is later updated; see 7.5.4, "Cross-reference table" and 7.5.6, "Incremental updates".

**Comment by petervwyatt** [comment]
The "_object numbers may be assigned in any arbitrary order_" is old/existing wording. 

However the requirement for contiguous object numbering _only_ applies to original PDF files, not incremental updates:
> For a PDF file that has never been incrementally updated, the cross-reference section shall contain only one subsection, whose object numbering begins at 0.

When adding incremental updates, PDF writers can use cross-reference subsections and start numbering new objects from _wherever they want_! And any PDF consumer that only assumes densely packed object numbers and thus allocates wads of memory is going to be in a whole world of pain when attempting to read the extant malicious PDFs that target such assumptions!

**Comment by mkl-public** [comment]
> However the requirement for contiguous object numbering _only_ applies to original PDF files, not incremental updates:
>...
> When adding incremental updates, PDF writers can use cross-reference subsections and start numbering new objects from _wherever they want_!

Hhmmm, if I read this correctly

>_The cross-reference table (comprising the original cross-reference section and all update sections) shall contain one entry for each object number from 0 to the maximum object number defined in the PDF file, even if one or more of the object numbers in this range do not actually occur in the PDF file._

*(ISO 32000-2:2020, section 7.5.4 Cross-reference table, page 57)*

then sparse cross reference tables are not allowed. For each number from 0 up to excluding **Size** there must be an entry in some section.

> And any PDF consumer that only assumes densely packed object numbers and thus allocates wads of memory is going to be in a whole world of pain when attempting to read the extant malicious PDFs that target such assumptions!

Certainly, you must implement defensively. And then reject PDFs with sparse cross reference tables.

**Comment by petervwyatt** [comment]
It may be what the spec says, but 10,000s of PDFs don't obey that rule anymore (if they ever did!), yet I haven't come across any PDF software that rejects such files... it's probably an area of the spec that should be clarified to better reflect reality (i.e. as implicitly free objects).

**Comment by mkl-public** [comment]
Admittedly, rejecting them is an extreme measure. Nonetheless, when processing them one should fix the issue (if possible) or at least warn.

(By the way, gaps in the cross references, in particular in the initial cross reference section, make Acrobat signature validation fail in multi-signature documents, so if one does want one's PDFs to be signable, one should prevent gaps.)

> it's probably an area of the spec that should be clarified to better reflect reality (i.e. as implicitly free objects).

Hhmmm, that wouldn't be merely a clarification, it would be an actual change.

So this of course can be considered but - if desired - should only be implemented as part of a PDF version change.

**Comment by mkl-public** [comment]
Back to the original topic, the updates defining object and generation numbers; for generation numbers you proposed

> A non-negative decimal integer generation number without any leading `+` sign or leading zeros.

How shall a generation 0 be written if leading zeros are disallowed?

**Comment by petervwyatt** [comment]
"additional leading zeros" or "extraneous leading zeros" - meaning `00` is not OK, but `0` is obviously.

**Comment by mkl-public** [comment]
> "additional leading zeros" or "extraneous leading zeros" - meaning `00` is not OK, but `0` is obviously.

Yes, I assumed you meant something like that. But there's no "obviously" in specs. ;) Just remember how you tried to put it more formally in your initial message here: 

> Or are they only permitted to be a sequence of decimal digits `0`-`9` with the first digit being non-zero (`1`-`9`)?

**Comment by petervwyatt** [comment]
PDF TWG agree with direction. Wording TBD.

**Comment by petervwyatt** [comment]
Picture says a 1,000 words:
![image](https://github.com/pdf-association/pdf-issues/assets/26521615/361171ad-453d-4942-9748-f7cb3e3e76fd)

**Comment by petervwyatt** [comment]
PDF TWG agree with figure. Will try to wordsmith words to match

**Comment by petervwyatt** [comment]
Diagram to be also be included:

> A PDF object number is a positive (non-zero) decimal integer comprised only of digits. It shall not have a leading plus sign (`+`) and shall not start with leading zeros (`0`).

> A PDF generation number is a non-negative decimal integer comprised only of digits. It shall not have a leading sign (`+` or `-`) and shall not have multiple leading zeros (`0`).

**Comment by mkl-public** [comment]
> shall not have multiple leading zeros

That sounds like single leading zeros are allowed, like in `017`, while James Bond would indeed be forbidden... ;) 

I think the most secure way is to write it like it's drawn in the graph, something like "It shall be `0` or a non-empty sequence of digits starting with a non-zero digit."

Ah, stop, the graph is wrong, it does not allow for single non-zero digit results, e.g. `7` is forbidden.

**Comment by car222222** [comment]
Try this:

A PDF generation number is a non-negative decimal integer: its syntax requirements are identical to those of a PDF object number, except that the single digit 0 is also permitted.

**Comment by car222222** [comment]
So both graphs are wrong!

**Comment by petervwyatt** [comment]
And that's why we review things 😀! Here's the fix:
![image](https://github.com/pdf-association/pdf-issues/assets/26521615/43437862-66e6-4926-b614-f719c9bf95b4)
with proposed wording:

> A PDF object number is a positive (non-zero) decimal integer comprised only of digits. It shall not have a leading plus sign (`+`) and shall not start with leading zeros (`0`).
> A PDF generation number is a non-negative decimal integer: its syntax requirements are identical to those of a PDF object number, except that the single digit `0` shall also be permitted.

**Comment by petervwyatt** [comment]
PDF TWG agree
