### ISSUE TITLE
ISO 32005: wrong BibEntry parent-child rules?

### ISSUE THREAD

**Issue by u-fischer** [pdf-association/pdf-issues#383]
PDF/UA-2 and WTPDF mandate the use of `BibEntry` for bibliography entries:

> Content within a document that represents a bibliography entry shall be enclosed in a `BibEntry` structure element. 

There is no example how exactly `BibEntry` should be used (WTPDF itself doesn't use `BibEntry`)

In ISO 32005 (as summarized in the [matrix](https://pdfa.org/wp-content/uploads/2023/09/PDF-Tags-Hierarchical-Inclusion-Rules-as-expressed-in-ISO-TS-32005-with-errata.xlsx)) the parent-child rules allow  the use of `BibEntry` basically only in an inline context: it can't be used directly inside "large" Structures like `Sect` or `FENote` or `BlockQuote` or `L` but it can be used inside `P`, `LBody`, `Em`, `H1`, `Lbl` or `Span`.

As such it is imho not really usable for a full bibliography list. While technically possible it looks semantically wrong to do something like

~~~~
<P><BibEntry><Lbl>..</Lbl> ....</BibEntry></P>
<P><BibEntry><Lbl>..</Lbl> ....</BibEntry></P>
<P><BibEntry><Lbl>..</Lbl> ....</BibEntry></P>
~~~~

even more as some bibliography styles can have more than one paragraph for an entry (e.g. with an additional note or the abstract, see the two examples below). And to force it into the `LBody` of a list looks quite convoluted.

Is is really intended that `BibEntry` can be used only for inline content? And if yes what is the intended use of `BibEntry` for complex bibliography entries as showin the screenshots?

![image](https://github.com/pdf-association/pdf-issues/assets/4047173/4f58bcac-9361-4c06-8a2e-3f5ccbb3e228)

![image](https://github.com/pdf-association/pdf-issues/assets/4047173/bcbc0067-16eb-4cc1-a25e-10b9e96eebb2)

**Comment by u-fischer** [comment]
As discussed in PDF/UA TWG I suggest to allow BibEntry additionally as child of
**Sect**, **Aside**, **BlockQuote** and **FENote** and perhaps **Art** and **Note**. 

**Sect** is the most important one, as it would allow to build a full bibliography list with entries containing paragraphs. The other versions are for cases where a single entry is added in the running text ("fullcites").

**Comment by petervwyatt** [comment]
@DuffJohnson  Is there a concrete recommendation or solution coming from PDF/UA TWG? Or is more discussion needed?
(Just wanting to know if I should label as "proposed solution")

**Comment by u-fischer** [comment]
@petervwyatt  PDF/UA agreed that allowing BibEntry in Sect and perhaps a some more Tags is the way to go. But a concrete list has been decided instead they asked me to make a suggestion.

**Comment by car222222** [comment]
The details of a particular solution have not yet been discussed by PDF/UA.

**Comment by ozross** [comment]
If you look at the way Bibliographies are described by the [Daisy Corporation](http://kb.daisy.org/publishing/docs/html/bibliographies.html) then the nearest corresponding structure in Tagged PDF would be to use a list via `/L' having `/ListNumbering /Description`, but with `/BibEntry` as a direct replacement for `/LI`. Notice that Daisy recommends the DPUB-ARIA `role="doc-bibliography"` on a `<section>` for the Bibliography itself. This can be done in PDF with an ARIA-owned attribute.

While version 1.0 of DPUB-ARIA had a `role="doc-biblioentry"` for the entries themselves, this became deprecated in version 1.1. Instead the requirement is now "at least one list structure" containing the bibliographic entries. Hence the Daisy examples use description lists: `<dl>` with `<dt>` and `<dd>`, though ordered and unordered lists are acceptable also.

From [DPUB-ARIA](https://www.w3.org/TR/dpub-aria/#doc-bibliography):
```
The element carrying the doc-bibliography [role](https://www.w3.org/TR/wai-aria/#dfn-role) MUST contain at least one descendant list containing the bibliography entries (if the entries are subdivided, for example alphabetically, the element would contain more than one list).
```

If `/BibEntry` is to be required with PDF2.0 and PDF/UA-2 then it seems to me that it best replaces `/LI` within the required list structures. Within each `/BibEntry` the `/Lbl` (corresponding to a `<dt>`) would be optional, as it is quite possible to just list the references without any citation key. Clearly `/LBody` would correspond to the `<dd>`, as in any description list. I'd expect that `/LBody` would be a required child of such usage of `/BibEntry`, even if there is no content (yet??).

With `/P` allowed in `/LBody`, then Ulrike's complicated multi-paragraph examples are fully covered. The text of the initial part of the description can be a direct child of the `/LBody`, with extended information occurring in subsequent `/P`s, also as children of the `/LBody`.
For derivation into HTML, the initial part would be tagged `<dd>`, as also would each subsequent `/P` give content with a further `<dd>`. In such a situation there can be expected to be a `<dt>` for the citation label, perhaps naming the (1st) author. 

I think this covers all the standard bibliography/citation styles that I've encountered using LaTeX-based methods.

**Comment by u-fischer** [comment]
@ozross pdf/UA discussed the idea to allow **BibEntry** inside **L* instead of **LI** (I agree that would work well) but the problem is that that would additionally require various changes in the list descriptions in the standards.  So pdf/UA thought that allowing BibEntry below Sect and doing something like

~~~~
/Sect role="doc-bibliography"
 /H2 bibliography
/BibEntry 
  /Lbl     ....
/BibEntry 
  /Lbl     ....
~~~~

would  be easier to achieve.

**Comment by car222222** [comment]
Since this is possibly on the agenda for imminent TWG meeting, it may be helpful to add the following --

As @mrbhardy has explained (but not, so far, in writing, I think), neither of the above suggestions, from @u-fischer and @ozross, concerningBibEntry can appear will be acceptable: due to this type of structure element being strictly categorised as an "inline-only" structure type -- 
It must therefore be contained in a P, or similar, element, such as an LBody.

**Comment by car222222** [comment]
Now edited for grammar/sense etc!

**Comment by mrbhardy** [comment]
Thanks Chris and appreciate your write-up.  I will happily write up the solution, but was waiting for a meeting of UA in-person to talk through this one final time.

We should finalize in UA and Reuse, then communicate our decision, thought what you've written is a great representation of where we've landed.

**Comment by car222222** [comment]
Agreed!  

I was only intending to provide information for PDF TWG on what has been talked about, rather than about anything agreed by the other TWGs.

**Comment by mrbhardy** [comment]
The committee discussed this item further and agreed that, while less than ideal, the current ISO TS 32005 rules are correct.  **BibEntry** is an inline element, so requires this containment.  Suggest we close and re-visit if we get to create a new tagset in the future (e.g. PDF 2.x or PDF 3.0).

**Comment by mrbhardy** [comment]
I believe Chris already articulated this.  There’s no conflict.

**Comment by u-fischer** [comment]
@bdoubrov basically the suggestion was something like `L>LI>LBody>BibEntry` and inside the BibEntry then perhaps more structure like P etc. (It still feels odd to me to hide the semantic (*this is a bibentry*) so deep inside the list, and I would prefer to either replace the LI by BibEntry as suggested by Ross or to simply not use BibEntry, but I understand that this would require many changes ...)

**Comment by ozross** [comment]
With `BibEntry` meant to be inline, then surely the structure for a bibliography section, as a (perhaps nested) list of bibliographic information, has to be slightly more cumbersome. That is, like:
```
<Sect role="doc-bibliography">
 <H2> References </H2>
 <L>
  <LI> 
   <Lbl> (visual) cite-key </Lbl>
   <LBody>
    <BibEntry> 
      ... descriptive text ... 
    </BibEntry>
   </LBody>
  </LI> 
  ... more entries ...
  </L>
 ... more (perhaps nested) lists
 </Sect>
```
The salient point is that the `<Lbl>` structure is not part of the `<BibEntry>` itself. 
It can be viewed as providing a name for it, but is not part of it.
This makes semantic sense as the (visual) cite-key is not so much a property of the bibliographic material itself, but of the way that material is included into the current document. (E.g., ordered, with a numeric key.)
In a different document the visual key is quite likely to be different, even when referencing the same material.
  
Also valid for single items would be:
```
<P><BibEntry><Lbl> key </Lbl> ... descriptive text ... </BibEntry> ... more stuff ... </P>
```
and both
```
<FENote><BibEntry><Lbl> key </Lbl> ... descriptive text ... </BibEntry> ... perhaps more stuff ... </FENote>
```
which has a key that is clearly associated with the bibliographic material; and
```
<FENote><P><Lbl> key </Lbl><BibEntry> ... descriptive text ... </BibEntry> ... perhaps more stuff ... </P></FENote>
```
where the key might be just a footnote number, say.

Or a `<Lbl>` need not be present at all.

Other possibilities could also be valid.

Is this all OK?

**Comment by mrbhardy** [comment]
The PDF/UA TWG recommends closing this as not fix.  However, we also recommend considering this as a candidate to be solved by our future tagset discussions, as well as to capture the great examples and notes from here for future best practice considerations.  One suggestion is to also add to the derivation specification.

**Comment by car222222** [comment]
Please can we have a place to take forward discussion of these ideas?  
Maybe an issue under "Reuse"?

**Comment by petervwyatt** [comment]
Of course! Most [PDF Association TWGs](https://pdfa.org/community/) have one or more own member-only repos to use as they wish. Please create a separate issue in those repos, as this repo is focused on errata against existing standards and specifications. 

@mrbhardy - do you wish to nominate the most appropriate TWG (at this time) for those further discussions you mention?

**Comment by car222222** [comment]
Thanks to @petervwyatt for taking up this idea: over to @mrbhardy !

**Comment by mrbhardy** [comment]
I believe this would be best taken into Reuse and we can identify a repo for that.
