### ISSUE TITLE
9.6.2.2 List of standard 14 fonts is harder to read than necessary

### ISSUE THREAD

**Issue by pgundlach** [pdf-association/pdf-issues#384]
Not really a bug, but a possible (minor) improvment.

9.6.2.2 The list of standard 14 fonts is a bit messed up:

> The PostScript language names of 14 Type 1 fonts, known as the standard 14 fonts, are as follows:
Times-Roman, Helvetica, Courier, Symbol, Times-Bold, Helvetica-Bold, Courier-Bold, ZapfDingbats,
Times-Italic, Helvetica-Oblique, Courier-Oblique, Times-BoldItalic, Helvetica-BoldOblique, Courier-
BoldOblique.

The 1.7 spec had a nice table:

<img width="768" alt="17-fonts" src="https://github.com/pdf-association/pdf-issues/assets/209434/372649e4-50aa-44c0-ab32-f2d8966b8e70">

A solution might be to rephrase the above paragraph with

The PostScript language names of 14 Type 1 fonts, known as the standard 14 fonts, are as follows: 
Courier, Courier-Bold, Courier-BoldOblique, Courier-Oblique, Helvetica, Helvetica-Bold, Helvetica-BoldOblique, Helvetica-Oblique, Symbol, Times-Bold, Times-BoldItalic, Times-Italic, Times-Roman, ZapfDingbats.

Or to re-insert the table.

**Comment by petervwyatt** [comment]
AFAICT ISO Directives won't allow a table like the Adobe specs used to have. Only permitable option is a list - either an inline comma-separated (like now), or a bullet list. A bullet list is probably better.

**Comment by petervwyatt** [comment]
PDF TWG agree

**Comment by pgundlach** [comment]
I have not seen the result, only the commit. It looks to me that this list is still unsorted. If this is the case, we have this sorted:

```
<li>Times-Roman</li>
<li>Times-Bold</li>
<li>Times-Italic</li>
<li>Times-BoldItalic</li>
<li>Helvetica</li>
<li>Helvetica-Bold</li>
<li>Helvetica-Oblique</li>
<li>Helvetica-BoldOblique</li>
<li>Courier</li>
<li>Courier-Bold</li>
<li>Courier-Oblique</li>
<li>Courier-BoldOblique</li>
<li>Symbol</li>
<li>ZapfDingbats</li>
```
?

**Comment by petervwyatt** [comment]
Good call - I had them in the order of the comma-separated list.
https://pdf-issues.pdfa.org/32000-2-2020/clause09.html#H9.6.2.2
