### ISSUE TITLE
ISO 21757-1:2020 Table 113  Access column is empty

### ISSUE THREAD

**Issue by datalogics-pgallot** [pdf-association/pdf-issues#388]
Table 113 of ISO 21757 describing the properties of a Mesh object has a column for Access which would typically indicate if the property were read-only (R) or Read-write (R/W).

Judging by conventions used in other objects, my best guess is that the _material_ property should likely be 'R', 
and the _renderMode_ property should likely be 'R/W' (compare to the gridMode or LightScheme properties in Table 122)

**Comment by DuffJohnson** [comment]
PDF TWG agrees.
