### ISSUE TITLE
Update reference to page number description in Annex F - Linearized PDF

### ISSUE THREAD

**Issue by sebras** [pdf-association/pdf-issues#389]
ISO 32000-2:2020 in Table F.1 — Entries in the linearization parameter dictionary, describes the last entry **P** by:

> (_Optional_) The page number of the first page; see F.3.4, "First-page cross-reference
> table and trailer (Part 3)". Default value: _0_.

Section F.3.4 does not mention **P** at all, instead it is discussed (i.e. what *0* means, and how it relates to **OpenAction**) in section F.3.7 paragraph 1. Historically this has been the same for ISO 32000-2:2017 and PDF 32000-1:2008. In PDF Reference sixth edition 1.7 Nov 2006 in Table F.1 for the last entry **P** the value is described by:

> (_Optional_) The page number of the first page (see Section F.2.6, “First-Page 
> Section (Part 6)”). Default value: 0. 

And section F.2.6, paragraph 2 does indeed discuss the **P** entry. I would therefore like to reference the corresponding section in ISO 32000-2:2020, so if the PDF TWG agrees, may I suggest the following update of the references for the **P** entry in Table F.1:

> (_Optional_) The page number of the first page; see F.3.7, "First-page section
> (Part 6)". Default value: _0_.

**Comment by petervwyatt** [comment]
PDF TWG agree
