### ISSUE TITLE
Does annot dictionary BM key apply to 3D artwork backgrounds?

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#39]
Clause "13.6.4.3 3D background dictionaries" gives no clarity of if/when the **BM** key that is in all annotation dictionaries (see Table 166 — Entries common to all annotation dictionaries) is used. 

3D annots have two situations - when an appearance stream is used (such as when print rendering or in a non-3D-capable processor) and when the 3D artwork is invoked (such as in an interactive viewer that is 3D aware). 13.6.4.3 also states "In effect, the 3D artwork and its background form a transparency group whose flattened results have an opacity of 1 (see 11, "Transparency")." but this does not mention the **BM** key...

Table 166 defines **BM** as "The blend mode that shall be used when painting the annotation onto the page .." so does it also apply when using the 3D artwork???

**Comment by philspreier** [comment]
I think that the blend mode only applies to the case where the appearance stream is used and not to the interactive 3D scene.

**Comment by lrosenthol** [comment]
Agree with @philspreier - we should make it clear that rendering a 3D annot appearance follows all the same rules as all other appearances.  It does not, however, impact the actual rendering of the 3D data in an interactive processor.

**Comment by petervwyatt** [comment]
Proposed solution: added to 13.6.4.3 as a 2nd para (above NOTE):

- PDF processors that render 3D data streams shall do so directly and without regard to keys and values in the annotation dictionary that define appearance streams or how appearance streams would be rendered onto the page. They shall ignore the values of the **C**, **IC**, **Border**, **BS**, **BE**, **BM**, **CA** and **ca** keys from "Table 166 - Entries common to all annotation dictionaries".

This is supposed to mimic the wording from below Table 166 ("PDF reader shall render the appearance dictionary without regard to any other keys and values in the annotation dictionary and shall ignore the values of the C, IC, Border, BS, BE, BM, CA, ca, H, DA, Q, DS, LE, LL, LLE, and Sy keys.")

**Comment by petervwyatt** [comment]
PDF TWG agreed.

(Note BM key change to para below Table 166 needs changing but as a separate issue - TBD issue number)

**Comment by petervwyatt** [comment]
Issue #23 "What happens when there's no AP in an annotation dictionary?" discusses that BM is incorrect in the para below Table 166. That issue will continue to be tracked there,
