### ISSUE TITLE
Last sentence in 12.7.4.3 is messed up/unclear

### ISSUE THREAD

**Issue by lrosenthol** [pdf-association/pdf-issues#393]
>The interactive PDF processor shall then replace the existing contents of the appearance stream from /Tx BMC to the matching EMC with the corresponding new contents as shown in Example 1 in 12.7.5.2.3, "Check boxes", 12.7.5, "Field types" (If the existing appearance stream contains no marked-content with tag Tx, the new contents shall be appended to the end of the original stream.)

**Comment by petervwyatt** [comment]
Adobe PDF 1.5 Reference stated:
> The viewer application should then replace the existing contents of the appearance stream from
/Tx BMC
to the matching
EMC
with the corresponding new contents as shown in Example 8.10. (If the existing appearance stream contains no marked content with tag Tx, the new contents should be appended to the end of the original stream.) Also see implementation note 106 in Appendix H.

Adobe PDF 1.7 Reference stated:
> The viewer application should then replace the existing contents of the appearance stream from /Tx BMC to the matching EMC with the corresponding new contents as shown in Example 8.14. (If the existing appearance stream contains no marked content with tag Tx, the new contents should be appended to the end of the original stream.) Also see implementation note 119 in Appendix H.

ISO 32000-1:2008 (PDF 1.7) had:
> The conforming reader shall then replace the existing contents of the appearance stream from /Tx BMC to the matching EMC with the corresponding new contents as shown in Example 1 in "Check Boxes," 12.7.4, “Field Types.” (If the existing appearance stream contains no marked content with tag Tx, the new contents shall be appended to the end of the original stream.)

ISO 32000-2 (both 2017 and 2020 editions, PDF 2.0) have the quote in the OP above.

Only issue I can see is with the reference to the example. Searching for "/TX" I find "Example" a bit below Table 228 in 12.7.4.3 and "Example" immediately below Table 232 in 12.7.5.3. By checking the Adobe PDF 1.5 Reference it appears that the "Example" a bit below Table 228 in 12.7.4.3 is the same as Example 8.10 and the Example below Table 232 is example 8.14, so the correct reference should be to that.

**Comment by petervwyatt** [comment]
PDF TWG agree

**Comment by petervwyatt** [comment]
End result is it is the "example above" - no need for an explicit subclause reference.
