### ISSUE TITLE
Are all structure element namespaces supposed to be in the StructTreeRoot Namespaces array for general PDF?

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#396]
There doesn't appear to be any explicit normative "shall" statements that all structure element namespaces (Table 355 StructElement/**NS**) have to be listed in the StructTreeRoot/**Namespaces** array. At most there is a descriptive, semi-factual style statement in Table 354 (StructTreeRoot), under **Namespaces**: "_An array of namespaces used within the document._"

Is this intentional for "general PDF", or an oversight in the style of wording? Or did I miss something somewhere?

If this is an oversight, the following suggestions might help:

* For StructTreeRoot/**Namespaces** (and specifically allowing additional namespaces to support edited PDFs): 
     > An array of at least all namespaces used within the document as referenced from structure elements (see Table 355) in the structure hierarchy.

* For StructElement/**NS**: 
    > An indirect reference to a namespace dictionary defining the namespace this element belongs to (see 14.7.4, "Namespaces") that shall also be an element in the structure tree root **Namespaces** array (see Table 354).

**Comment by MaximPlusov** [comment]
- For StructElement/NS:
> An indirect reference to a namespace dictionary defining the namespace this element belongs to (see 14.7.4, "Namespaces") that **shall** also be an element in the structure tree root Namespaces array (see Table 354).

It looks like the explicit normative "shall" statement.

**Comment by petervwyatt** [comment]
@MaximPlusov - yes, that is my proposed new wording. Current wording is just:
> An indirect reference to a namespace dictionary defining the namespace this element belongs to (see 14.7.4, "Namespaces").

**Comment by petervwyatt** [comment]
@mrbhardy - seeking your suggestions please!

**Comment by mrbhardy** [comment]
I don't see how the definition of Namespaces is misaligned with how IDTree and other equivalent structures are defined.  None of them are explicit about shall statements, but covered by intent.  IDTree doesn't say all IDs shall be a part of it, but by saying that you can navigate between them through the IDTree conveys that requirement.

I don't want to open a can of worms here, but this was written with consistency to how the section is generally written.

**Comment by u-fischer** [comment]
> don't see how the definition of Namespaces is misaligned with how IDTree and other equivalent structures are defined. None of them are explicit about shall statements, but covered by intent.

Imho there is a difference between **IDTree** and **Namespaces** here. If a processor encounters an ID, e.g. in a Headers of a table, then it clearly needs the **IDTree** to find the relevant structure (fast). This makes the **IDTree** a technical requirement as soon as there are crossreferenced IDs.  But the **NS** key references the namesspace dictionary directly. There is no need to go through the **Namespaces** array first to find it.  So if *covered by intent* is the criterion I would say that with the current wording content **NamesSpaces** is not more than an optional, non-binding listing of dictionaries that are perhaps used in the tree. If that is what is wanted, then I think a note *Processors should not assume that all dictionaries referenced from **NS** keys are listed in **Namespaces*** would help to avoid misunderstandings.

**Comment by mrbhardy** [comment]
I don't believe this is entirely necessary, but how about we fix the text in Table 354 - "Entries in the structure tree root":

> An array of namespaces used within the document

to 

> An array that shall contain all namespaces used within the document

**Comment by petervwyatt** [comment]
I take it from the proposed wording, that you want the **Namespaces** array to be a full list in every general PDF, which is sort of the opposite to Ulrike's suggestion: "_Note Processors should not assume that all dictionaries referenced from **NS** keys are listed in **Namespaces** would help to avoid misunderstandings._"

Does that wording also permit additional unused namespaces too? (where used means referenced by a structure element in the logical structure tree).

**Comment by mrbhardy** [comment]
The PDF/UA TWG committee agrees with the proposal to create an errata strengthening the language to a shall.
