### ISSUE TITLE
XML namespaces in metadata streams

### ISSUE THREAD

**Issue by seehuhn** [pdf-association/pdf-issues#397]
Table 349, in section 14.3.3 (Document information dictionary), specifies mappings between entries of document information dictionary and XMP properties in the document's metadata stream.  Some examples:

  - "The `dc:title` entry in the document’s metadata stream can be used to represent the document’s title."
  - "The `pdf:Keywords` entry in the document’s metadata stream can be used to represent the keywords for the document."
  - "The `xmp:CreatorTool` entry in the document’s metadata stream can be used to represent the creation tool of the document."

These XMP properties are also referred to in other places, *e.g.* table 147 (Entries in a viewer preferences dictionary) explains that `DisplayDocTitle` species whether "the window’s title bar should display the document title taken from the `dc:title` element of the XMP metadata stream"

The problem is, that the PDF spec does not specify the meaning of the XML namespace prefixes `dc:`, `pdf:` and `xmp:`.

Suggested fixes:

  - It seems clear that `dc:` stands for the Dublin Core namespace `http://purl.org/dc/elements/1.1/`.  The XMP spec states that for this namespace the "preferred namespace prefix is dc."  Probably the PDF spec could simply state that in the PDF spec `dc:` is bound to the URI `http://purl.org/dc/elements/1.1/`, allowing the actual XMP to use a different prefix.  This would match the approach taken by the XMP spec (see the last paragraph of section 6.2 there).
  - Very similarly, it seems clear that `xmp:` should stand for `http://ns.adobe.com/xap/1.0/`.  The fix would be analogous to the one for `dc:`.
  - The prefix `pdf:` is not mentioned in the XMP spec, so this one is less clear.  From the examples in the PDF spec, I guess that this one stands for `http://ns.adobe.com/pdf/1.3/`.  It true, this should probably be made explicit in the spec.  It would also be nice to add a reference to the documentation for this namespace (maybe on [developer.adobe.com](https://developer.adobe.com/xmp/docs/XMPNamespaces/pdf/) ).

**Comment by petervwyatt** [comment]
Add suggestions to 4.2 Established notations:
* the Dublin Core namespace with preferred prefix "dc" is defined in ISO 16684-1:2019, clause 8.3
* the XMP namespace with preferred prefix "xmp" is defined in ISO 16684-1:2019, clause 8.4
* the Adobe PDF namespace with preferred prefix "pdf" is only defined on the Adobe website at https://developer.adobe.com/xmp/docs/XMPNamespaces/pdf/ and not in any ISO standard AFAICT. Is this the best reference?

And ISO 16684-1 is already a normative reference in ISO 32000-2:2020.

**Comment by seehuhn** [comment]
Just in case this got lost in my too long text: my main point is that the spec should clarify whether the prefixes like `dc:` must be exactly as shown in the PDF spec, or whether any prefix will do as long as it points to the correct namespace.

**Comment by seehuhn** [comment]
So when the PDF spec says "The dc:title entry in the document’s metadata stream can be used to represent the document’s title", does "dc:" mean a literal "dc:" (whatever namespace it may be bound to) or does it mean "whatever prefix the metadata stream uses for Dublin Core"?

**Comment by petervwyatt** [comment]
ISO 16684-1 uses the phrase "preferred prefix" which is definitely not a "shall", but more of a "should" if it had been written strictly according to ISO-ese. ISO 19005-4 (PDF/A) explicitly says "should" for certain namespace prefixes `dc`, `pdf`, `xmp` and `xmpMM`, but "shall" for `pdfaid`.

So 32K should also stick with "should" for the XMP standard namespaces (AFAICT `pdfaid` is not used in 32K) with examples using the recommended prefixes. I think just noting the convention of using XMP preferred prefixes in the 32K Notation clause is sufficient.

**Comment by petervwyatt** [comment]
"_In this document and by convention, XMP examples always use the preferred prefixes for XMP standard and specialised namespaces as specified in ISO 16684-1 and at https://developer.adobe.com/xmp/docs/XMPNamespaces._"

**Comment by seehuhn** [comment]
Thank you for the clarification, @petervwyatt .
