### ISSUE TITLE
Corrupted UTF-8 in XMP example code

### ISSUE THREAD

**Issue by seehuhn** [pdf-association/pdf-issues#398]
The example XMP packet in section 14.3.3 (Document information dictionary) uses "Ôªø" to represent the UTF-8 value of U+FEFF.  This should be changed to match the "… UTF-8 value of U+FEFF (efbbbf) …" used in the remaining XMP examples.  See the example in the appendix in section H.2 (Minimal PDF file) for a non-corrupted case.

**Comment by petervwyatt** [comment]
PDF TWG agree
