### ISSUE TITLE
Clarity over which of adbe.x509.rsa_sha1, adbe.pkcs7.sha1 and adbe.pkcs7.detached are deprecated in PDF 2.0

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#4]
Clause 12.7.5.5, Table 237 (under "AddRevInfo") [...] adbe.pkcs7.detached and adbe.pkcs7.sha1 are deprecated in PDF 2.0.
Clause 12.8.3.1, Table 260 [...] values adbe.x509.rsa_sha1 and adbe.pkcs7.sha1 have been deprecated with PDF 2.0.

PeterW: If you search for “adbe.x509.rsa_sha1”, it comes up in:
- clause 0.3 where it is explicitly stated as deprecated;
- Table 237 has NOTE 3 which says “NOTE 3 adbe.pkcs7.detached and adbe.pkcs7.sha1 are deprecated in PDF 2.0.” – **but not adbe.x509.rsa_sha1**;
- Table 255 SubFilter key which has a last para saying it is deprecated;
- Table 255 Cert key – which is described as only valid if SubFilter key is adbe.x509.rsa_sha1 and thus arguably you go on to read the SubFilter key in Table 255 where it explicitly says deprecated
- Table 260 which has table-note (c) which states it is deprecated
-1st para 12.8.3.2 – which admitted neglects to mention deprecated
- 12.8.3.3.1, 2nd last bullet which refers back to Table 260 (where it is explicitly stated as deprecated).

If you search for “adbe.pkcs7.sha1”, it comes up in:
- clause 0.3 where it is explicitly stated as deprecated;
- Table 237 has NOTE 3 which says “NOTE 3 adbe.pkcs7.detached and adbe.pkcs7.sha1 are deprecated in PDF 2.0.”;
- Table 255 SubFilter key which has a last para saying it is deprecated;
- Table 255 Cert key – but this time there is no statement either way…
- Table 260 which has table-note (c) which states it is deprecated – the (c) should be added to the right-most column to reference it correctly…
- 12.8.3.3.1 2nd bullet which explicitly states it is deprecated.

If you search for “adbe.pkcs7.detached”, you get the following:
- It is NOT called out in clause 0.3;
- It IS marked as deprecated in NOTE 3 of Table 237;
- It is NOT marked as deprecated in Table 255 SubFilter key;
- It is NOT marked as deprecated in Table 255 Cert key;
- It is NOT marked as deprecated in Table 260

**Comment by petervwyatt** [comment]
So I think the correct answer is:

- [ ] adbe.x509.rsa_sha1 and adbe.pkcs7.sha1 ARE deprecated;
- [ ] adbe.pkcs7.detached is NOT deprecated;
- [ ] Table 237 NOTE 3 needs to be corrected to remove "adbe.pkcs7.detached" and say “NOTE 3 adbe.x509.rsa_sha1 and adbe.pkcs7.sha1 are deprecated in PDF 2.0.”;
- [ ] Table 260 right-most column header for “adbe.x509.rsa_sha1” needs a “(c)” footnote marker added
- [ ] Add the updated Table 237 Note 3 to Table 255 Cert key.

**Comment by lrosenthol** [comment]
I believe that is correct as well.

**Comment by petervwyatt** [comment]
Proposed solution as per above
