### ISSUE TITLE
handling of soft hyphen in tagged PDF

### ISSUE THREAD

**Issue by u-fischer** [pdf-association/pdf-issues#401]
I currently try to properly implement support for the visible hyphen that is introduced through the incidental division of a word at the end of a line and find some parts of the spec not fully understandable.

In PDF 1.7  (10.7.1Tagged PDF and Page Content, Incidental Artifacts, Page 888) I find

> In Tagged PDF, such an incidental word division **must** be represented by a soft hyphen character, 

In ISO 32000-2:2000 this sentence changed to 

> In tagged PDF, the visible hyphen that is introduced through the incidental division of a word at the end of a line but which would not be present otherwise, **may** be represented as a soft hyphen,

* Why has the **must** be amended to **may**? What are the alternatives to a soft hyphen?

Using the U+00AD char for the soft hyphen works fine if the char exists, but some fonts do not have it. In ISO 32000-2:2000 (and also in PDF 1.7) there is a note about this case (14.8.2.6 Unicode mapping in tagged PDF):

> In some cases a required character may not be available in a given font, for example the soft hyphen character. Such a character may be represented either **by adding it to the font’s encoding or CMap and using ToUnicode to map it to the appropriate Unicode value**, or by using an ActualText entry in the associated structure element to provide substitute characters.

* what does the emphasized part mean? I have a font which has only an hard hyphen, U+002D. How can I generate a visible U+00AD by adding an not existing character to the CMap?

**Comment by lrosenthol** [comment]
Alternatives to soft hyphen are in that quoted section, such as using `ActualText` over a hard hyphen.

> by adding it to the font’s encoding or CMap and using ToUnicode to map it to the appropriate Unicode value
Seems pretty clear.  You can map any glyph to the soft-hyphen.

**Comment by u-fischer** [comment]
> Seems pretty clear. You can map any glyph to the soft-hyphen.

Well yes but how does that help? If I use a hard hyphen and map it to a soft hyphen I no longer can use the hard hyphen as hard hyphen in other places.

> Alternatives to soft hyphen are in that quoted section, such as using `ActualText` over a hard hyphen.

Ah so the  "may" is there to allow this case. As a side remark: ActualText on a MC doesn't work well in our test in one reader it breaks copy and paste and  another reader simply ignore it.

**Comment by petervwyatt** [comment]
I think this issue can be closed as "no fix" since both mechanisms are adequately defined in ISO 32000-2:2020.
Implementations are the responsibility of individual vendors so please report to said vendor(s).
