### ISSUE TITLE
Table 116 — Predefined CJK CMap names contains only deprecated Korean CMaps

### ISSUE THREAD

**Issue by smuehlst** [pdf-association/pdf-issues#41]
Table 116 — Predefined CJK CMap names

Table 116 in the "Korean" section lists only predefined CMaps that belong to the deprecated "Adobe-Korea1-2" character collection. On the other hand the predefined CMaps belonging to the new "Adobe-KR-9" are not listed in the "Korean" section of Table 116.

The predefined CMaps in the "Korean" section belonging to the deprecated "Adobe-Korea1-2" character collection should be removed from Table 116. The new predefined CMaps "UniAKR-UTF8-H", "UniAKR-UTF16-H" and "UniAKR-UTF32-H" should be added to the "Korean" section of Table 116.

See also [The Adobe-KR-9 Character Collection](https://github.com/adobe-type-tools/cmap-resources/blob/master/README.md#the-adobe-kr-9-character-collection) in the README.md file in the Adobe CMap Resources GitHub repository.

**Comment by MPBailey** [comment]
Surely the old names should be marked as deprecated, rather than removed from the list?
But that would then run into the question of what a reader should do if it encounters a file that uses them; what does 'ignoring' them mean in this context?

**Comment by petervwyatt** [comment]
WG8 previously agreed not to copy requirements from external normative referenced documents as that is a maintenance issue (and this particular referenced doc is free too). In this case we are tracking the Adobe stuff...

Re deprecation: remember too our very precise definition in T&D 3.15 is "... should be ignored..."

**Comment by lrosenthol** [comment]
Below Table 117, it already says
>Adobe-Japan2-0 and Adobe-Korea1-2 are deprecated in this document (2020).

So what else is necessary here?

**Comment by petervwyatt** [comment]
Discussed in PDF TWG. No changes to ISO 32000-2:2020 as the wording is clear that deprecation relates to PDF ("... in this document"). TheAdobe CMap Resources apply to other formats beyond PDF.
