### ISSUE TITLE
Formatting in table 238

### ISSUE THREAD

**Issue by pgundlach** [pdf-association/pdf-issues#410]
Clause 12.7.5.5 Signature fields
Table 238 — Entries in a certificate seed value dictionary
Entry: KeyUsage 

<img width="450" alt="238" src="https://github.com/pdf-association/pdf-issues/assets/209434/5fbb4bbe-e1b4-40d8-9527-a34ebc254c56">

The formatting seems to be wrong, IMO it should be as follows

1. digitalSignature
1. non-Repudiation
1. keyEncipherment
1. dataEncipherment
1. keyAgreement
1. keyCertSign
1. cRLSign
1. encipherOnly
1. decipherOnly

**Comment by petervwyatt** [comment]
ISO 32000-1:2008 (PDF 1.7) is correctly formatted - ISO 32000-2 (PDF 2.0) seems to have lost the table-inside-a-table:

![image](https://github.com/pdf-association/pdf-issues/assets/26521615/bdb64678-881c-4638-8487-acfb198919ee)

**Comment by petervwyatt** [comment]
PDF TWG agree

**Comment by crlf0710** [comment]
Just leave a note here that, some National Bodies are not allowing nested tables in their national standards. While the casual two column Enum - Desc can be rearranged in a list like setting. These six columns here involves larger rearrangement.
