### ISSUE TITLE
After "Table 286" perhaps duplicate "An unrecognised value shall be treated as (TEMPNEVER)."

### ISSUE THREAD

**Issue by pgundlach** [pdf-association/pdf-issues#414]
Clause 13.2.4.2 Media clip data
Right below Table 286

Text:
An unrecognised value shall be treated as (TEMPNEVER).

This is already the last line of the table (entry TF), it does not make sense at this point IMO.

**Comment by petervwyatt** [comment]
PDF TWG agree
