### ISSUE TITLE
Figure H.7 missing tags

### ISSUE THREAD

**Issue by pgundlach** [pdf-association/pdf-issues#418]
The upper part of Figure H.7 misses a few tags. These are present in PDF 32000-1:2008

Old (PDF 32000-1:2008):

<img width="914" alt="old-pdf1 7" src="https://github.com/pdf-association/pdf-issues/assets/209434/17da8604-dfc6-40e5-8cf1-b89de7e9cbd6">

This is the new figure. 

<img width="932" alt="new-pdf20" src="https://github.com/pdf-association/pdf-issues/assets/209434/ac2f16d2-687e-44ee-b6cd-539f9af57010">

Below 201, 211, 214, 215, 212, 213 and 216 parts of the structure elements are missing.

**Comment by petervwyatt** [comment]
Thanks for spotting!
Looks to be text wrapping (and text alignment) in the master artwork when it got upgraded... solution is to re-create figure exactly as per ISO 32000-1:2008.

**Comment by petervwyatt** [comment]
PDF TWG agree
