### ISSUE TITLE
Figure H.5 not corresponding to example

### ISSUE THREAD

**Issue by pgundlach** [pdf-association/pdf-issues#419]
A very minor issue

Figure H.5 has no ....... in it, but the example shows the dots.

Old (from 1.7):

<img width="281" alt="figh5" src="https://github.com/pdf-association/pdf-issues/assets/209434/b9deb387-9230-4689-b013-cd0629241411">

New example:

<img width="280" alt="figh5" src="https://github.com/pdf-association/pdf-issues/assets/209434/1fa80cb8-621c-4799-bf0e-8aafe817b82d">

The example after Figure H.7  has:

```
/P         <</MCID 1>>  BDC BT T* (TABLE OF CONTENTS)  Tj ET EMC
/Lbl       <</MCID 11>> BDC BT T* (1. )                Tj ET EMC
/Reference <</MCID 12>> BDC BT    (Chapter One )       Tj ET EMC
/NonStruct <</MCID 13>> BDC BT    (. . . . . . . . . ) Tj ET EMC
/Reference <</MCID 14>> BDC BT    (3 )                 Tj ET EMC
/Lbl       <</MCID 21>> BDC BT T* (1.1 )               Tj ET EMC
/Reference <</MCID 22>> BDC BT    (Section A )         Tj ET EMC
```

and so on

**Comment by petervwyatt** [comment]
Thanks.
Figure H.5 is actually not a figure but in-situ text and the tab stop setting for the page numbers is not correctly set to have PERIOD leaders so it matches Figure H.6 (which is a real figure).

**Comment by petervwyatt** [comment]
PDF TWG agree

**Comment by petervwyatt** [comment]
Also fixing the H2 bullets that are incorrectly numbered and the fact there were 2 "Chapter Twos"!
