### ISSUE TITLE
Table 166: Clarify requirements for annotation appearances

### ISSUE THREAD

**Issue by t-merz** [pdf-association/pdf-issues#42]
Some clarification is required regarding whether or not an annotation requires an appearance stream /AP. The main source is Table 166 "Entries common to all annotation dictionaries" which states that the following don't need any appearance:

* zero-size annotations
* annotations of type Popup, Projection or Link (this somewhat obscures the fact that 12.5.6.14 even disallows /AP for Popups)
  
But there are additional sources:
* 12.5.6.18 "Screen annotations": the clause _If AP is not present,..._ implies that /AP is not required for Screen annotations.
* 12.5.6.24 "Projection annotations":
  _A projection annotation with a Rect entry that has zero height or zero width shall not have an AP dictionary._
  This overlaps with the general exemption per Table 166, but uses _zero height **OR** zero width_ as opposed to **_AND_** in Table 166.
* Table 177 "Additional entries specific to a free text annotation":
  _The annotation dictionary’s AP entry, if present, shall take precedence..._
  This either implies that /AP is not required for FreeText annotations, or is a wrong left-over. I believe it's the latter.

**Suggestions:**
* Change the /AP description in Table 166 from _Optional_ to _Required in some cases; see below_.
  
  (UNCHANGED) _Every annotation (including those whose Subtype value is Widget, as used for form fields), except for the two cases listed below, shall have at least one appearance dictionary._
  * (UNCHANGED) _Annotations where the value of the Rect key consists of an array where the value at index 1 is equal to the value at index 3 and the value at index 2 is equal to the value at index 4._
  * (MODIFIED) _Annotations whose Subtype value is Projection, Screen, or Link._
  
  (NEW) _The AP entry is not allowed in the following cases:_
  * _Annotations whose Subtype value is Popup._
  * _Annotations whose Subtype value is Projection and where the value of the Rect key consists of an array where the value at index 1 is equal to the value at index 3 and the value at index 2 is equal to the value at index 4._

* Table 177: _The annotation dictionary’s AP entry, if present, shall take precedence..._
  Modify as follows:
  _The annotation dictionary’s AP entry shall take precedence..._

* Delete the following phrase in 12.5.6.24 as it duplicates information from Table 166:
  _A projection annotation with a Rect entry that has zero height or zero width shall not have an AP dictionary._

**Comment by petervwyatt** [comment]
See also Issue #23

**Comment by petervwyatt** [comment]
See also #94 and #22 (already agreed and closed).

Summary of proposed solutions 

* Table 166, AP key:
> (_Required except for conditions listed below; PDF 1.2_) An appearance dictionary specifying how the annotation shall be presented visually on the page (see 12.5.5, "Appearance streams"). A PDF writer shall include an appearance dictionary when writing or updating the PDF file except for the two cases listed below.
Every annotation (including those whose **Subtype** value is _Widget_, as used for form fields), except for the two cases listed below, shall have at least one appearance dictionary.
• Annotations where the value of the **Rect** key consists of an array where the value at index 1 is equal to the value at index 3 and the value at index 2 is equal to the value at index 4.
NOTE (2020) The bullet point above was changed from “or” to “and” in this document to match requirements in other published ISO PDF standards (such as PDF/A).
• Annotations whose Subtype value is Popup.

* Table 177: The annotation dictionary’s AP entry, if present, shall take precedence... Modify as follows:
> The annotation dictionary’s **AP** entry shall take precedence...

* Delete the following phrase in 12.5.6.24 as it duplicates and contradicts information from Table 166 (also fixes #94):
> A projection annotation with a **Rect** entry that has zero height or zero width shall not have an AP dictionary.

**Comment by t-merz** [comment]
> Summary of proposed solutions
>     * Table 166, AP key:
> > (_Required except for conditions listed below; PDF 1.2_) An appearance dictionary specifying how the annotation shall be presented visually on the page (see 12.5.5, "Appearance streams"). A PDF writer shall include an appearance dictionary when writing or updating the PDF file except for the two cases listed below.
> > Every annotation (including those whose **Subtype** value is _Widget_, as used for form fields), except for the two cases listed below, shall have at least one appearance dictionary.
> > • Annotations where the value of the **Rect** key consists of an array where the value at index 1 is equal to the value at index 3 and the value at index 2 is equal to the value at index 4.
> > NOTE (2020) The bullet point above was changed from “or” to “and” in this document to match requirements in other published ISO PDF standards (such as PDF/A).
> > • Annotations whose Subtype value is Popup.

In 2020 this reads "...is Popup, Projection or Link", i.e. the suggested phrase would introduce a new incompatible requirement for Link annotations (I guess for Projection annotations this is intended). If the new requirement is really also intended for Link annotations (but I don't think it is). it should be clearly stated as incompatible change.

Similar for Screen annotations: if a new requirement compared to 2020 is introduced it should be clearly marked as incompatible from the PDF producer's point of view.

**Comment by petervwyatt** [comment]
PDF TWG commented that this text is aligned with PDF/A and PDF/X so need to carefully review against those specs.
Changes not approved yet.

**Comment by petervwyatt** [comment]
PDF/A-4 and PDF/X-6 do indeed have identical text in regards to annot appearances:

> For all annotation dictionaries containing an **AP** key, the appearance dictionary that it defines as its value shall contain only the **N** key. If an annotation dictionary’s **Subtype** key has a value of _Widget_ and its **FT** key has a value of _Btn_, the value of the **N** key shall be an appearance sub-dictionary otherwise the value of the **N** key shall be an appearance stream.
NOTE 1 Appearance dictionaries are required to be present in a file and rendered appropriately according to ISO 32000-2:—, 12.5.2, Table 166 and the following paragraph. This ensures the reliable rendering of the annotations.
NOTE 2 In accordance with the requirements of 12.7.5.2.3 and 12.7.5.2.4 of ISO 32000-2:—, a button field will have multiple appearance states, each one associated with the specific values that the button can take.
All graphics content in any appearance dictionary shall conform to all applicable provisions in 6.2.

Both PDF/A-4 and PDF/X-6 do not state any other conditions related to annot appearances w.r.t. AP, Rect, Popup, Screen, Link AFAICT. 

So the final result of all issues reported in the OP are:
* no further changes to Table 166 from those already agreed at https://www.pdfa.org/pdf-issues/ under other issue numbers;
* Table 177 strike "if present" (already done at https://www.pdfa.org/pdf-issues/);
* 12.5.6.24 Projection annotations: minor edits to align with Table 166 (already done at https://www.pdfa.org/pdf-issues/);
* 12.5.6.18 Screen annotations: 2nd bullet below Table 190, last sentence to be deleted ("If **AP** is not present, the screen annotation shall not have a default visual appearance and shall not be printed.") - AP needs to be present for screen annots in PDF 2.0

Only this last point really needs agreement by the PDF TWG at the next meeting.

**Comment by t-merz** [comment]
> AP needs to be present for screen annots in PDF 2.0

Requiring an appearance for Screen annotations gives me some headache. At first glance it looks consistent to require an appearance for (almost) all annotation types, but here we have some specific aspects:

- By definition, "A screen annotation specifies a region of a page upon which media clips may be played". Why does this area have to be visualized if it may only be used later or never for some media rendition?
- A Screen annotation may render all kinds of media including sound. I have no idea how the proper visualization of sound looks like and why one is needed at all.
- It's an incompatible change against ISO 32000-2:2020 which contains the clause "If AP is not present,...".
- Screen annotations don't play any role for real-world PDF/X, but formally this change would also render previously valid PDF/X-6 files invalid.

All this will lead to the inevitable implementation - a dummy appearance which doesn't show anything. This is similar to the situation for invisible signature fields before the requirement was relaxed for annotations with zero area. Does it really make sense to force producers to create an empty appearance only to comply with an incompatible new requirement? Wouldn't it make more sense to formalize the obvious consumer requirement, i.e. display nothing in the absence of /AP?

**Comment by petervwyatt** [comment]
Just use a degenerate Rect (width==height==0) and then you don't need to provide AP. 

I also disagree it's incompatible with ISO 32000-2:2020 or :2017 as Table 166 has always said AP was required under the current set of 2 rules. At worst it was only highly ambiguous and confusing with later clauses 😁

**Comment by t-merz** [comment]
> Just use a degenerate Rect (width==height==0) and then you don't need to provide AP.

This doesn't really help if you want to play a video later in the zero-size area...

**Comment by petervwyatt** [comment]
The last para in 12.5.6.18 says that AP is only used for printing or default display when the clip isn't playing.

So provide a valid Rect (the size of the video clip I would assume) but leave the content of the AP empty so that the underlying page shows through, or make solid black/white box, (with or without transparency and potentially a funky blend mode with the underlying page content as this is PDF 2.0 after all!). Or set the AP to the movie poster that will get printed. When playing the media, the player takes over the rect and AP isn't used.

And I cannot see how this invalidates PDF/X-6 since Table 166 still applies...

**Comment by lrosenthol** [comment]
>The last para in 12.5.6.18 says that AP is only used for printing or default display when the clip isn't playing.

That is correct.  Same is true for any/all annotations where the AP is only used for static/non-interactive rendering.

@t-merz instead of an empty appearance, a producer should create some sort of logical "poster" for the annotation. For example, I believe that Acrobat used to place a music-oriented icon/graphic there when adding Screen annots (back in the day).

**Comment by t-merz** [comment]
> @t-merz instead of an empty appearance, a producer should create some sort of logical "poster" for the annotation. For example, I believe that Acrobat used to place a music-oriented icon/graphic there when adding Screen annots (back in the day).

I get the point... But I guess I'm not old enough to remember Acrobat versions which created Screen annotations. I recall the loudspeaker icon for Sound annotations, and the more common Movie annotations - but Screen? Playing for sure, but creating?

**Comment by petervwyatt** [comment]
PDF TWG discussed again and agreed that the comment above (https://github.com/pdf-association/pdf-issues/issues/42#issuecomment-876938420) listing the resolutions is the way forward, PDF TWG agree to resolve
