### ISSUE TITLE
Example perhaps incorrect data type

### ISSUE THREAD

**Issue by pgundlach** [pdf-association/pdf-issues#423]
Clause 14.7.5.4 Finding structure elements from content items

Last example right before 14.7.6 Structure attributes

```
100 0 obj %Parent tree (accessed from structure tree root)
 <<     /Nums [
              0 101 0 R
              1 102 0 R
              …
              6 [1 0 R] %Entry for page object 2; array element at index 0
                … %points back to parent structure element
          ]
  >>
endobj
```

shouldn't the value for the last entry (6) in the num tree be an object and not an array of object(s)?

It has the same value in the 1.7 spec but in the example before the last example  it is an object reference.

**Comment by petervwyatt** [comment]
No - Table 354 defines **ParentTree** as a number-tree where the node-values (for want of a better term) can be various things:

> _... The form of the associated value shall depend on the nature of the object: For an object that is a content item in its own right, the value shall be an indirect reference to the object’s parent element (the structure element that contains it as a content item). For a page object or content stream containing marked-content sequences that are content items, the value shall be an array of references to the parent elements of those marked-content sequences._

In this case it is an "_array of references to the parent elements of those marked-content sequence_" as described in the paragraph immediately before this EXAMPLE 2:

> _For a content item that is a marked-content sequence, the retrieval method is similar but slightly more complicated. Because a marked-content sequence is not an object in its own right, its parent tree key shall be found in the StructParents entry of the page object or other content stream in which the sequence resides. The value retrieved from the parent tree shall not be a reference to the parent structure element itself but to an array of such references — one for each marked-content sequence contained within that content stream. The parent structure element for the given sequence shall be found by using the sequence’s marked-content identifier as an index into this array (see Example 2)_

**Comment by petervwyatt** [comment]
Closing as EXAMPLE 2 is correct.

**Comment by pgundlach** [comment]
Thank you very much and sorry for the nose, I should _read_ the spec...
