### ISSUE TITLE
Typo in 7.6.6, final example

### ISSUE THREAD

**Issue by robinwatts** [pdf-association/pdf-issues#424]
In ISO 32000-2:2020(E), section 7.6.6, the final example includes:

  8 0 obj
    <</Filter /MySecurityHandlerName
          /V 4
          /CF
            <</MyFilter0
                   <</Type /CryptFilter
                       /CFM V2>>
                   >>

I believe that should be /CFM /V2?

**Comment by petervwyatt** [comment]
PDF TWG agree
