### ISSUE TITLE
Typo in H.8.2, final example

### ISSUE THREAD

**Issue by robinwatts** [pdf-association/pdf-issues#425]
The final object in the example is:

400 0 obj
<</Type /StructElem
/S TOC
/K [201 0 R 211 0 R 301 0 R 214 0 R 215 0 R 302 0 R]
>>
endobj

I believe that should be: /S /TOC

Also, are we not required to have a /P in there too?

**Comment by petervwyatt** [comment]
Yes (`/TOC`) and yes (`/P 400 0 R`). Thanks.

**Comment by petervwyatt** [comment]
PDF TWG agree
