### ISSUE TITLE
Implementation-dependent overlapping tiling patterns should not be allowed in PDF/A-4 and PDF/X-6

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#428]
Overlapping tiling patterns are described as implementation-dependent in the PDF spec (clause 8.7.3.1, end of 2nd para):

> The order in which individual tiles (instances of the cell) are painted is unspecified and unpredictable; figures on adjacent tiles should not overlap.

This unpredictability makes for different results between renderers, but is easy to check or validate by comparing **XStep** and **YStep** to the appropriate **BBox** dimensions.

Propose to remove this implementation-dependent feature in the core ISO subsets by upgrading the "_should not_" in ISO 32000-2:2020 to a "shall not" in 19005-4 (PDF/A-4) and 15930-9 (PDF/X-6) dated revisions.

Here is a hand-crafted test file with overlap: [OverlappingTiles.pdf](https://github.com/pdf-association/pdf-issues/files/15457342/OverlappingTiles.pdf)

**Comment by petervwyatt** [comment]
I checked the spec: searching for "_implementation depend_" (covering "_dependent_" and "_dependency_") occurs 31 times, but "_unpredict_" only occurs 5 times (of which 2 also have "_implementation depend_" in the same sentence). So we should stick with the phrases "_implementation dependent_" or "_implementation dependency_" as the preferred trigger phrase.

Hence I also suggest we tweak the above sentence in ISO 32000-2:2020 to add the trigger term:

> The order in which individual tiles (instances of the cell) are painted is unspecified and unpredictable (i.e., is implementation dependent); figures on adjacent tiles should not overlap.

**Comment by DietrichSeggern** [comment]
Agreed. Side note: The title of this ticket is not fully correct since it would also cover uncoloured tiling patterns (which is good).

**Comment by lrosenthol** [comment]
I would not support this change, without first knowing how many existing PDF/A & PDF/X files would no longer comply...

**Comment by petervwyatt** [comment]
Fair enough - if you think "shall" is too strong for the PDF/A-4 files that exist. PDF/X-6 are very rare...

But adding an informative note stating that overlapping tiles are a device-dependent feature and thus should be avoided would at least wave the red flag in both PDF/A-4 and PDF/X-6 dated revisions.

I personally hadn't realised that this rendering feature was actually device-dependent mainly because it didn't use that specific magic phrase!

**Comment by petervwyatt** [comment]
"Proposed solution" applies to ISO 32000-2 minor edit to add the "implementation dependent" key phrase to the sentence.
Discussion about PDF/A-4 and PDF/X-6 dated revisions is still on-going...

**Comment by DietrichSeggern** [comment]
I have never seen overlapping tiling patterns in any real world PDFs. But I definitely support to make this a recommendation (should).

**Comment by bdoubrov** [comment]
No actions, as the risks are low, and we don't want to introduce new requirements in PDF/A-4 at this stage.

**Comment by petervwyatt** [comment]
Proposed editorial solution for ISO 32000-2 is simply to add the magic "implementation dependent" phrase as a parenthetical ([see my comment above](https://github.com/pdf-association/pdf-issues/issues/428#issuecomment-2153837166))

**Comment by petervwyatt** [comment]
PDF TWG agree
