### ISSUE TITLE
Data type of operands for Type 3 glyph operators d0 and d1 is missing

### ISSUE THREAD

**Issue by t-merz** [pdf-association/pdf-issues#43]
Table 111 "Type 3 font operators" describes the **d0** and **d1** operators which specify metrics of glyphs in a Type 3 font. _wx_ is described as _horizontal displacement in the glyph coordinate system_, but its data type is not specified. Is it integer, real or number (i.e. both)?

The data type for _wx, wy, llx, lly, urx, ury_ should be stated explicitly.

**Comment by petervwyatt** [comment]
I agree ISO 32000 doesn't say anything directly.

However Annex A definition refers **d0** and **d1** operators to **setcharwidth** and **setcachedevice** in PLRM. And the PLRM states: "The operands to **setcachedevice** are all numbers interpreted in the glyph coordinate system (see Section 5.4, “Glyph Metric Information”). _wx_ and _wy_ define the basic width vector for this glyph - in other words, the normal position of the origin of the next glyph relative to origin of this one."

So I think it is fair to state that **d0** and **d1** operands are also all numbers in PDF.

**Comment by petervwyatt** [comment]
Proposed solution: add to rows in Table 111

- **d0** and **d1**: The number _wx_ denotes the horizontal displacement in the glyph coordinate system; it shall be consistent with the corresponding width in the font’s **Widths** array. The number _wy_ shall be 0 (see 9.2.4, "Glyph positioning and metrics").
- **d1** only: The numbers _llx_ and _lly_ denote the coordinates of the lower-left corner, and the numbers _urx_ and _ury_ denote the upper-right corner, of the glyph bounding box. ...

**Comment by petervwyatt** [comment]
PDF TWG agreed
