### ISSUE TITLE
Link, Annot and Form structure element types are poorly and confusingly defined

### ISSUE THREAD

**Issue by DuffJohnson** [pdf-association/pdf-issues#437]
ISO 32000-2:2020, Table 368

The Annot and Form structure element types use the same pattern in their definitions:

> Either an association between the content enclosed by the Annot structure element and one or more corresponding PDF annotations (see 12.5, "Annotations"), or a mechanism to include one or more PDF annotations in the structure tree.

and

> Either an association between content enclosed by the Form structure element and a corresponding widget annotation or a mechanism to include a widget annotation in the structure tree.

### Problems:

1) The definition is presented as "either....or" when in reality it's both.
2) The language doesn't match the pattern appropriately established with other structure element types, e.g., "Encloses content..."
3) The language is clunky.

### Recommendation:

Rewrite the first para of the Annotation structure element type definition to read:

"Encloses one or more PDF annotations and associated content, if any."

Rewrite the first para of the Form structure element type definition to read:

"Encloses a PDF widget annotation and associated content, if any."

**Comment by petervwyatt** [comment]
Maybe discuss first in Reuse or PDF/UA TWGs to get recommended wording?

**Comment by mrbhardy** [comment]
PDF Reuse TWG thinks Duff's proposal is correct and recommends accepting as written.

PDF Reuse TWG agrees with itself.
