### ISSUE TITLE
Glyph name confusion in Type 3 font example

### ISSUE THREAD

**Issue by t-merz** [pdf-association/pdf-issues#44]
The example below Table 111 "Type 3 font operators" and Figure 62 "Output from the example" generates two glyphs which are appropriately named /square and /triangle. However, the EXAMPLE text mentions _character codes a and b_, and the comment within the code similarly talks about _Type 3 font definition encoding two glyphs, 'a' and 'b'._

While the glyphs are placed at positions 97/98 in the Encoding which correspond to a and b in WinAnsiEncoding, there's nothing in the Type 3 font which would imply any relationship of those glyphs to the "glyphs" or "character codes" a and b. It just so happens that they occupy the same slot as a and b in some other encoding which is unrelated to the example.

**Suggestions:**
 * Change _...a filled square and a filled triangle, selected by the character codes a and b._ " to
 ._..a filled square and a filled triangle at positions 97 and 98 of the font's **Encoding**._
  * Change the comment _Type 3 font definition encoding two glyphs, 'a' and 'b'_ to
  _Type 3 font definition encoding the two glyphs square and triangle._

**Comment by petervwyatt** [comment]
Your suggestion is good, but because the Example wording also says "...shows the result of showing the string ( abaabab ) using this font" that we still keep the 'a' and 'b' in parentheses after the 97 and 98 so the explanation of the string makes sense.

So proposed solution, fully expanded:

- Change "...a filled square and a filled triangle, selected by the character codes a and b." to "... a filled square and a filled triangle at positions 97 ('a') and 98 ('b') of the font's Encoding."
- Change the comment "%Type 3 font definition encoding two glyphs, 'a' and 'b'" to "%Type 3 font definition encoding the two glyphs square and triangle".

**Comment by t-merz** [comment]
>     * Change "...a filled square and a filled triangle, selected by the character codes a and b." to "... a filled square and a filled triangle at positions 97 ('a') and 98 ('b') of the font's Encoding."

The 'a' and 'b' seem to fall out of nowhere here. Maybe nit-picking, but it would be more precise to state "...at positions 97 (corresponding to the character 'a' in WinAnsiEncoding)..."

**Comment by petervwyatt** [comment]
The 'a' and 'b' are the bytes in the string operands for the Tj operator, not WinAnsiEncoding. Technically these strings are PDFDocEncoded. We don't use PS-style terminology in PDF so how about: 

"... a filled square and a filled triangle at positions 97 ('a' in the **Tj** string operand) and 98 ('b' in the **Tj** string operand) of the font's Encoding."

**Comment by t-merz** [comment]
> The 'a' and 'b' are the bytes in the string operands for the Tj operator, not WinAnsiEncoding. Technically these strings are PDFDocEncoded. 

I wouldn't agree to this statement. The Tj string contains bytes which are interpreted according to the font's Encoding which happens to place /square and /triangle in these slots. If you happen to look at the TJ string in an editor with WinAnsi or PDFDoc or any other ASCII-based encoding they may look like 'a' and 'b', but the PDF viewer doesn't relate the glyphs to these characters. It just so happens that we conveniently talk about 'a' and 'b' because the raw codes (viewed in ASCII) look like that, but semantically there is nothing to justify that.

Yes, the operators (like Tj) in the content stream are encoded/interpreted in PDFDocEncoding, but this doesn't relate to the contents of show strings which are always interpreted according to the corresponding font encoding.

> "... a filled square and a filled triangle at positions 97 ('a' in the **Tj** string operand) and 98 ('b' in the **Tj** string operand) of the font's Encoding."

Per reasoning above I these characters are not semantically part of the Tj string. A phrase like "corresponding to 'a' and 'b' in PDFDocEncoding (or WinAnsiEncoding)" would describe the situation more accurately in my opinion.

**Comment by MPBailey** [comment]
Rather than 97 and 98, should we not be using 61h and 62h, as described in 7.2.3 Character set?

**Comment by petervwyatt** [comment]
PDF TWG would like @t-merz for discussion to close this issue.

**Comment by petervwyatt** [comment]
@t-merz Please attend the next PDF TWG meeting so this issue can be finalized!

**Comment by MPBailey** [comment]
Trying to collate the discussion above, I think this should work as proposed changes:

•	Replace "a filled square and a filled triangle, selected by the character codes a and b." with "a filled square and a filled triangle at positions 61h and 62h of the font's Encoding (corresponding to 'a' and 'b' in ASCII American Standard Code for Information Interchange) in the Tj string operand".

•	Change the comment "%Type 3 font definition encoding two glyphs, 'a' and 'b'" to "%Type 3 font definition encoding the two glyphs square and triangle".

**Comment by t-merz** [comment]
> • Replace "a filled square and a filled triangle, selected by the character codes a and b." with "a filled square and a filled triangle at positions 61h and 62h of the font's Encoding (corresponding to 'a' and 'b' in ASCII American Standard Code for Information Interchange) in the Tj string operand".
> 
> • Change the comment "%Type 3 font definition encoding two glyphs, 'a' and 'b'" to "%Type 3 font definition encoding the two glyphs square and triangle".

Yes, these are improvements. Regarding "ASCII": wouldn't it be slightly more PDF-native to refer to PDFDocEncoding or WinAnsiEncoding instead of ASCII (PDFDocEncoding can easily be looked up in Annex D.3)? Also, I'm not sure whether hex codes really help here since the code example uses decimal in the font dictionary.

**Comment by petervwyatt** [comment]
I agree PDFDocEncoding is more correct :-). So that would then be:

* Replace "a filled square and a filled triangle, selected by the character codes a and b." with "a filled square and a filled triangle at positions 97 and 98 of the font's **Encoding** (corresponding to 'a' and 'b' in PDFDocEncoding) in the **Tj** string operand".

• Change the comment "%Type 3 font definition encoding two glyphs, 'a' and 'b'" to "%Type 3 font definition encoding the two glyphs square and triangle".

**Comment by petervwyatt** [comment]
PDF TWG agrees
