### ISSUE TITLE
12.5.6.13 (Ink annotations): constraint inconsistency between Vertices and Path entries

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#444]
Polygon and polyline annotations (12.5.6.9) and ink annotations (12.5.6.13) feature a newer (PDF 2.0) optional `Path` entry alongside the older simple vertex array entry (respectively, `Vertices` and `InkList`). Despite this simmetry, the respective constraints oddly diverge:

- for polygon and polyline annotations, `Vertices` is required UNLESS `Path` is present (so they are mutually exclusive)
- for ink annotations, `InkList` is required NO MATTER whether `Path` is present (so they are redundant (?!))

### PROPOSAL

I propose to harmonize the `InkList` entry (Table 185 — Additional entries specific to an ink annotation) to the corresponding `Vertices` entry (Table 181 — Additional entries specific to a polygon or polyline annotation), replacing its constraint ("(Required)") with the following:

```
(Required unless a Path key is present, in which case it shall be ignored)
```

**Comment by stechio** [comment]
@petervwyatt:

> My feeling is that both **InkList** and **Vertices** entries should remain required (as per PDF 1.7) but "_shall be ignored_" whenever the newer PDF 2.0 **Path** entry is present - that both guarantees backward compatibility and makes them the same.

Your interpretation does make sense, actually — it's the "unless" conjunction ("Required *unless* a Path key is present [...]") which causes confusion, wrongly suggesting that the two entries may be mutually exclusive.

So, algorithmically, `InkList` and `Vertices` entries should always be defined, supplemented by `Path` entries in case the extra capabilities of the latter (in particular, `curveto` operations) are needed: in such case, `InkList` and `Vertices` entries will contain a flattened (ie, end points without control points) rendition of the curved path defined in `Path` entries.

**Comment by petervwyatt** [comment]
Proposed solution to change Table 181, **Vertices** and Table 185, **InkList** to both state: 
> "(_Required_) Shall be ignored if **Path** is present."

**Comment by petervwyatt** [comment]
PDF TWG agree
