### ISSUE TITLE
7.10.5.1 Note 1 typo

### ISSUE THREAD

**Issue by datalogics-pgallot** [pdf-association/pdf-issues#446]
the Note in clause 7.10.5.1 (Type 4 (PostScript calculator) functions: General) begins with:

"NOTE 1 Although any function can be sampled (in a Type 4 PDF function) and others can be described with"

I believe that the parenthetical comment is supposed to be: (in a Type 0 PDF function)
referring to the clause 7.10.2 Type 0 (sampled) functions

**Comment by petervwyatt** [comment]
It was correct as per proposed solution in ISO 32000-1:2008 (PDF 1.7) but incorrect in ISO 32000-2:2017.
Clearly an editorial error.

**Comment by petervwyatt** [comment]
PDF TWG agree
