### ISSUE TITLE
13.2.7.2 (Media players dictionary): minor paragraph rearrangement

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#449]
The last paragraph of subclause 13.2.7.2.1 (General), beginning with "Since both media clip data and media play parameters dictionaries [...]", should be moved into the following subclause 13.2.7.2.2 (Algorithm: Media Player), as the latter implicitly references those dictionaries (eg, "The player is found in the `NU` array of *either dictionary*"), causing confusion if read out of context.

**Comment by petervwyatt** [comment]
During ISO-fication of 32K-1, non-heading highlighted words were converted to headings.

**Comment by petervwyatt** [comment]
PDF TWG agree
