### ISSUE TITLE
Clarification for TR structure type

### ISSUE THREAD

**Issue by PaulRayius** [pdf-association/pdf-issues#45]
Section 14.8.4.8.3 - Table 371
Current text reads: "A row of table header cells (TH) or table data cells (TD) in a table."

This could imply that a TR cannot have both TH and TD in it.  

Recommended edit:
"A row of table header cells (TH) and/or table data cells (TD) in a table." (Adding "and".)

**Comment by petervwyatt** [comment]
Proposed solution as above (**TR** row in Table 371)

**Comment by petervwyatt** [comment]
PDF TWG agreed.
Also passed to WG9 for PDF/UA-2

**Comment by petervwyatt** [comment]
The resolution to this issue was replaced by Issue #71.
