### ISSUE TITLE
Incorrect symbol for U+2212 in table D.3

### ISSUE THREAD

**Issue by synercoder** [pdf-association/pdf-issues#461]
**Describe the bug**
In table D.3 PDFDocEncoding character set, entry 138/0x8a/0212/U+2212, the LATIN CAPITAL S WITH CARON is displayed, but should be the MINUS symbol. 

The char symbol in table D.3 for entry 138 should be updated to reflect [U+2212](https://www.compart.com/en/unicode/U+2212): −

**Additional information:**
LATIN CAPITAL S WITH CARON is correctly present in the table D.3; entry 151.

The table D.2 shows MINUS correctly, that the char is octal 212.

**Comment by petervwyatt** [comment]
Thank you. 
This mistake goes all the way back to the Adobe PDF 1.7 reference (pre-dating ISO) where the layout of the Annex was changed. This has then just flowed through ISO-fication. Adobe PDF 1.6 and earlier didn't have a specific table for **PDFDocEncoding**.

**Comment by petervwyatt** [comment]
PDF TWG agree
