### ISSUE TITLE
Heading 12.3.6 Navigators should be demoted to H4 as a subclause of 12.3.5 Collections

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#477]
The H3 heading "12.3.6 Navigators" is currently at the same level in the heading hierarchy as "12.3.5 Collections", yet it is only relevant to Collections. It should be a subclause and thus needs to be demoted to H4 as "12.3.5.3 Navigators" (after the existing "12.3.5.2 Collection hierarchical folders"). It should also be renamed as "Collection navigators" to make it extra clear...

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by petervwyatt** [comment]
PDF TWG agree
