### ISSUE TITLE
Unclear requirements for cross-reference stream object ID and cross-reference data

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#478]
For cross-reference streams in original PDFs (i.e. when there are no revisions and all cross-reference data is in a cross-reference stream), it is unstated if the stream itself (as a valid PDF stream object) needs to be included in its own cross-reference stream data. 

Cross-reference streams are only accessed via file byte offsets (e.g. `startxref` or **Prev** entries for more than one cross-reference stream and incremental updates) and never by indirect references (`X Y R`) so are "outside" the PDF DOM. Thus there is no dependent requirement to know (_or check!_) the object ID when the byte offset to a cross-reference stream is followed, nor will they be detected if the PDF DOM is walked to detect in-use objects (as there are no indirect reference requirements). 

Does this also mean that the object number of the cross-reference stream can be beyond the trailer **Size** entry or a free object?

Is it a requirement that all cross-reference stream objects are listed as in-use objects in the cross-reference data somewhere (i.e. can be included in their own cross-reference stream data)? 

There are real-world extant PDF files with different understandings for such scenarios which cause issues for other PDF software such as when performing edits, incremental updates, optimizing, validating, etc. resulting in even messier PDFs! It would be good to clarify.

PS. This is kinda similar to Linearization parameter dictionaries which are also not detectable by walking the normal PDF DOM that is also not noted AFAICT.

It seems to me that as valid PDF stream objects in their own right they:

1. _DO_ need to be explicitly listed in the cross-reference table data as in-use objects (i.e. they can be included in their own cross-reference data) even though these references are not needed at runtime; and
2. _DO_ need to obey the trailer **Size** constraints for object numbers

and both these points should be explicitly noted informatively.

There is also a minor confusion/circularity with (informative) [NOTE 1 in Table 15 for trailer **Size**](https://pdf-issues.pdfa.org/32000-2-2020/clause07.html#Table15) in that in-use objects are described as those defined to be in the cross-reference data. The easiest editorial correction is to append something like "_... including all cross-reference streams (see XXX) and any Linearization parameter dictionary (see Annex YYY) in the file._" to keep it as a factual statement.

**Comment by mkl-public** [comment]
> For cross-reference streams in original PDFs (i.e. when there are no revisions and all cross-reference data is in a cross-reference stream), it is unstated if the stream itself (as a valid PDF stream object) needs to be included in its own cross-reference stream data.

But in 7.5.8.3 _Cross-reference stream data_  you can read 

> Like any stream, a cross-reference stream shall be an indirect object. Therefore, an entry for it shall exist in either a cross-reference stream (usually itself) or in a cross-reference table (in hybridreference files; see 7.5.8.4, "Compatibility with applications that do not support compressed reference streams").

**Comment by petervwyatt** [comment]
Doh! I completely missed that... not exactly under the correct heading but stated nonetheless.
