### ISSUE TITLE
Invalid reference for IRT entry in section 12.5.6.3

### ISSUE THREAD

**Issue by gettalong** [pdf-association/pdf-issues#479]
Section 12.5.6.3 "Annotation states" references the IRT entry twice with the additional text of "*(see "Table 176 — Additional entries specific to a link annotation")*" following it.

However, that referenced table has no mention of the IRT entry. I think what is meant here instead is "*Table 172 - Additional entries in an annotation dictionary specific to markup annotations*" where the IRT entry is actually defined.

**Comment by petervwyatt** [comment]
Proposed solution as per original post.

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by petervwyatt** [comment]
PDF TWG
