### ISSUE TITLE
Editorial issue with Standard 14 fonts

### ISSUE THREAD

**Issue by t-merz** [pdf-association/pdf-issues#48]
Clause 9.6.2.2 _Standard Type 1 fonts (standard 14 fonts) (PDF 1.0-1.7)_ ends with the following text:

_PDF processors supporting PDF 1.0 to PDF 1.7 files shall have these fonts, or their font metrics and suitable substitution fonts, available.
These fonts, or their font metrics and suitable substitution fonts, shall be available to the PDF processor._

Editorial issue: the second sentence duplicates the first sentence. Suggestion: delete second sentence.

**Comment by petervwyatt** [comment]
Proposed solution as above.

**Comment by michaeldemey** [comment]
I agree with the sentiment of the issue, but the wording in the second sentence isn't identical to the first one. The first one explicitly mentions "supporting PDF 1.0 to PDF 1.7" where the second sentence doesn't, it only references "the PDF processor". 

I'm only raising this as deleting that line might cause an issue with ISO? I mean, you can't word smith a deletion so we need to be careful to not delete stuff based on similar, but not identical text.

But I do agree with the idea of the issue.

**Comment by t-merz** [comment]
> I agree with the sentiment of the issue, but the wording in the second sentence isn't identical to the first one. The first one explicitly mentions "supporting PDF 1.0 to PDF 1.7" where the second sentence doesn't, it only references "the PDF processor".

Keep in mind that the defining property of the standard 14 fonts, i.e. the absence of metrics, is allowed only in PDF 1.0 to PDF 1.7 per text prior to the quote. Therefore availability of the standard fonts (or metrics for these) is not relevant for processing PDF 2.0 documents.

Semantically both sentences are therefore equivalent.

As a side note "... suitable substitution fonts available" is redundant since metrics are sufficient: if the processor has metrics available, it applies whatever method it uses for displaying text in unembedded fonts, i.e. using a substitution font and simulating the metrics. Substituting standard 14 fonts is no different from substituting other non-embedded fonts provided the metrics and FontDescriptor are available.

**Comment by michaeldemey** [comment]
I know, I'm not disagreeing. Just stating that this deletion might get noticed because of the language being used in the sentence :)

**Comment by petervwyatt** [comment]
Resolved in conjunction with Issue #47
