### ISSUE TITLE
Small visual artifact in header row of tables

### ISSUE THREAD

**Issue by gettalong** [pdf-association/pdf-issues#480]
(I'm not sure if this "issue" is one to report here, so feel free to close/delete it.)

All tables have a header row describing the columns. These header rows have a thick black line above and below the row contents. The line above is visually okay but the line below extends a bit outside of the right border:

![image](https://github.com/user-attachments/assets/89d88b01-b93d-44f9-b51f-9c6c7a30d6c4)

I'm not sure whether this is on purpose or not but it does look wrong.

**Comment by petervwyatt** [comment]
Thanks. 
We know about this artifact from when the original PDF specification document was converted to MS-Word. If/when we publish the next edition or part of ISO 32000 this will get fixed (along with other artifacts from the conversion) as our workflow now uses AsciiDoc/Metanorma and thus apply the latest ISO Directives and House Style rules.
