### ISSUE TITLE
Add a `PV` entry in Table 322.

### ISSUE THREAD

**Issue by crlf0710** [pdf-association/pdf-issues#49]
This entry has been undocumented since PDF Reference 1.7 era, but it has always been supported by commercial pdf products like Acrobat and so on. I'd like to propose formalization this entry into the standard for completeness and consistency.

Proposed entry:
**PV**

Proposed description text:

_(Optional)_ A flag indicating the visibility of of the cutting plane. If true, then the cutting plane shall be visible. If false, then the cutting plane shall not be visible.

Default value: _true_

**Comment by lrosenthol** [comment]
I can verify that Adobe's implementation does indeed support a `PV` key that is not currently documented in that table.  I will need to research why it was never documented.

**Comment by petervwyatt** [comment]
Proposed solution as above

**Comment by lrosenthol** [comment]
Actually, given that this is an *ADDITION* to the specification (even though one or more vendors have implemented it), it should be addressed as an "Extension to PDF" (and go through that process) and not an errata.

**Comment by petervwyatt** [comment]
OK - but seems like a lot of overhead for a single key. 
Removed "proposed solution" label and replaced with "documentation" instead

**Comment by crlf0710** [comment]
Since #59 is accepted, maybe it's possible to reconsider adding this directly into the spec? I think they're quite similar in nature.

**Comment by petervwyatt** [comment]
#59 was a little different in that existing text and an example both made mention of something that wasn't specified. 

However I do now note that your proposal above has "Default: _true_" which implies that a very common implementation will _always_ appear differently to every other implementation which doesn't know about this. This is not a good outcome for interoperability and UX of 3D PDF.

Therefore I support your recommendation to consider `PV` as a correction towards aligning the specification to a widely used implementation.

**Comment by petervwyatt** [comment]
PDF TWG: 3 paras below Table 322 in 13.6.4.6 mentions cutting plane. Review text more closely and review next meeting. OP to attend next meeting to discuss.

**Comment by crlf0710** [comment]
@petervwyatt Indeed! I somehow didn't notice that paragraph before! So it seems this is also existing text made mention of something that wasn't specified.

I might not be available for sync discussions because of timezone reasons. Happy to attend any async discussions though.

**Comment by romantoda** [comment]
Our developers that work with Tracker software on PRC implementation indeed confirm PV is missed in the spec. They read it, expecting it to be in the cross section dictionary. The default value is true. Without this entry there are no way to hide a cross section without removing its definition from a PDF file. Even implementations that don't read PV would by default show (or "turn on") the cross section plane so we believe that it's not in fact an extension to 32000 but rather a clarification of existing consensus

**Comment by petervwyatt** [comment]
@romantoda Thanks for the input/insight.
@crlf0710 What is your timezone? 

With this input and after re-reading the entirety of 13.6.4.6, I also now agree that the missing PV entry is an editorial oversight. Updating GH labels appropriately. We will aim to resolve at the next PDF TWG meeting.

**Comment by crlf0710** [comment]
@petervwyatt  I'm in UTC+8. Though i think i don't have a lot more to add here though.

**Comment by petervwyatt** [comment]
PDF TWG agree - and noting that this was an editorial error during original merging of 3D stuff
