### ISSUE TITLE
Correct default value of `IV` entry in Table 322 from `false` to `true`.

### ISSUE THREAD

**Issue by crlf0710** [pdf-association/pdf-issues#50]
In table 322 the default value of `IV` entry is `false`. However in existing commercial products like acrobat, the value of this entry has always been interpreted as `true` if missing. (And it is indeed that `true` as default value is more natural)

I'm not sure whether it's better to just change the specification in this case, or just claim that every existing implementation has been wrong. Personally i feel the former approach is more practical and helpful.

**Comment by lrosenthol** [comment]
I can confirm that the Adobe implementation sets the default value to `true` prior to reading this dictionary, thus leading to that becoming the "default".

**Comment by petervwyatt** [comment]
Proposed solution as above

**Comment by petervwyatt** [comment]
PDF TWG agreed
