### ISSUE TITLE
Link to MathML Namespace

### ISSUE THREAD

**Issue by PaulRayius** [pdf-association/pdf-issues#52]
Two related issues in "Other namespaces" - 14.8.6.3

1. There is no annotation for the URL to the W3C page for the MathML Namespace.
2. With the PDF processor that I'm using, I'm able to click the URL but I get a 404 error when "following the link" (that's not really there) because the quotation marks at the end are being considered as part of the link. 

Recommendation - Add a link annotation with the correct target.  This will resolve both issues mentioned above. 
The target should be:  https://www.w3.org/1998/Math/MathML/

**Comment by petervwyatt** [comment]
Do you mean this URI?

![image](https://user-images.githubusercontent.com/26521615/109238817-51b87480-7828-11eb-900d-8e2fa6b019d0.png)

In which case it is specifically NOT hyperlinked in ISO 32000-2:2020 as it is a namespace URI and, as such, does not have to be a valid URL.  This is officially explained in 14.7.4.2, Note 1.

The issue that includes the trailing quotation mark is an issue with your viewer and not the spec.

**Comment by PaulRayius** [comment]
Thanks Peter.  I stand corrected.
