### ISSUE TITLE
Note 2 in 7.6.4.3.2 unclear

### ISSUE THREAD

**Issue by willkil** [pdf-association/pdf-issues#53]
Note 2 of 7.6.4.3.2 "Algorithm 2: Computing a file encryption key in order to encrypt a document (revision 4 and earlier)" contains the following two excerpts:

> use of the ID in computation of the file encryption key, as required when using 7.6.4.3.3, "Algorithm 2.A: Retrieving the file encryption key from an encrypted document in order to decrypt it (revision 6 and later)Algorithm 2: Computing a file encryption key in order to encrypt a document (revision 4 and earlier)"

and

> This algorithm, when applied to the user password string, produces the file encryption key used to encrypt or decrypt string and stream data according to 7.6.3.2, "Algorithm 1: Encryption of data using the RC4 or AES algorithms".

Surely the first excerpt should read:
> as required when using 7.6.4.3.2, "Algorithm 2: Computing a file encryption key in order to encrypt a document (revision 4 and earlier)"

I believe the second excerpt should read:
> This algorithm, when applied to the user password string, produces the file encryption key used to encrypt or decrypt string and stream data according to 7.6.3.3, "Algorithm 1.A: Encryption of data using the AES algorithms"

Using encryption Algorithm 1 with key Algorithm 2.A seems to imply Encrypt version 4 with standard security handler revision 6, but Table 21 — "Additional encryption dictionary entries for the standard security handler" says use revision 4 "if the document is encrypted with a V value of 4".

**Comment by MatthiasValvekens** [comment]
I agree that the first excerpt is clearly wrong; probably the result of a copy-paste gone awry.

As for the second one, I'm not sure what the intention of that one was, to be honest. It would make sense as-is if it were a _separate_ note. On the other hand, it's also weird to comment on the scope of Algorithm 2.A exclusively in a clause about another algorithm entirely.

I propose adopting @willkil's first correction, in addition to "factoring out" the second excerpt into a separate note with the following text (or some variant thereof), inserted under Note 2 in 7.6.4.3.2:

> NOTE 3: This algorithm, when applied to the user password string, produces the file encryption key used to encrypt or decrypt string and stream data according to 7.6.3.2, "Algorithm 1: Encryption of data using the RC4 or AES algorithms".

Applying the same logic to the V5 security handler, insert the following note at the end of 7.6.4.3.3:

> NOTE: This algorithm, when applied to the user password string, produces the file encryption key used to encrypt or decrypt string and stream data according to 7.6.3.3, "Algorithm 1.A: Encryption of data using the AES algorithms".

I think these three edits would remove all confusion & ambiguity. Any other thoughts?

**Comment by MatthiasValvekens** [comment]
Since nobody has objected to my previous comment, I'll mark it as "proposed solution" for review in the next PDF TWG meeting.

**Comment by willkil** [comment]
@MatthiasValvekens I finally had a chance to review your Jun 13 comment in context and I agree the additional notes clear this up.

**Comment by petervwyatt** [comment]
PDF TWG agree proposed solution.
