### ISSUE TITLE
Clarify status of MK dictionary for widget annotations with AP appearance dictionary

### ISSUE THREAD

**Issue by u-fischer** [pdf-association/pdf-issues#56]
**Describe the bug**
Table 166 — Entries common to all annotation dictionaries says that almost all annotations shall have an AP dictionary. 

Below the table it then says that keys like `C, IC, Border, BS,...` are ignored if AP is present. 

Table 191 — Additional entries specific to a widget annotation then describes the *dynamic appearance stream MK*, but I can find nothing that tells me if MK is ignored too if AP is present.  If yes: are there cases  where MK still makes sense or is basically deprecated in pdf 2.0? If no: how is the relationship between both appearance settings?

**Additional context**

I came across the problem while trying to update the LaTeX code for pushbuttons. I'm unable to decide if it should use AP or MK.

**Comment by petervwyatt** [comment]
Thank you for your contribution! Collecting together various other related tidbits from ISO 32000-2:2020:

* Table 190 - Additional entries specific to a screen annotation: **MK** key: (_Optional_) An appearance characteristics dictionary (see "Table 192 — Entries in an appearance characteristics dictionary"). The **I** entry of this dictionary provides the icon used in generating the appearance referred to by the screen annotation’s **AP** entry.

* Last bullet below Table 190:
> The **AP** entry refers to an appearance dictionary (see "Table 170 — Entries in an appearance dictionary") whose normal appearance provides the visual appearance for a screen annotation that shall be used for printing and default display when a media clip is not being played. If **AP** is not present, the screen annotation shall not have a default visual appearance and shall not be printed.

* Table 191 - Additional entries specific to a widget annotation, **MK** key: (_Optional_) An appearance characteristics dictionary (see "Table 192 — Entries in an appearance characteristics dictionary") that shall be used in constructing a dynamic appearance stream specifying the annotation’s visual presentation on the page. ...

* Para below Table 191:
> The **MK** entry may be used to provide an appearance characteristics dictionary containing additional information for constructing the annotation’s appearance stream. "Table 192 — Entries in an appearance characteristics dictionary" shows the contents of this dictionary.

**Comment by petervwyatt** [comment]
A misc change for the bullet below Table 190 - PDF 2.0 now requires AP appearance streams for screen annotations so the sentence "If **AP** is not present, the screen annotation shall not have a default visual appearance and shall not be printed." is meaningless in PDF 2.0 and can be deleted.

**Comment by petervwyatt** [comment]
Another somewhat relevant statement:

* clause 12.11.6. Note 2: "Other common fallbacks can include presenting a static annotation appearance in place of a dynamic annotation."

**Comment by petervwyatt** [comment]
So I believe the intention of all the words is trying to distinguish between a "static appearance model" defined by **AP** appearance streams in almost all annots and always used by non-interactive processors (such as print RIPs) vs a "dynamic appearance" that might be used by certain interactive processors such as when users are interacting with form widgets. However the dynamic appearance aspects are not standardized or defined as PDF is the definition of a file format, not a software product spec - and vendors/implementors can make their own decisions/innovations. 

Note that the terms "static appearance model" and "dynamic appearance" are not official ISO 32000-2 T&Ds.

Note also that ISO 32000 is silent on how to construct/re-construct appearance streams from all the various dict keys, etc. - again, there is currently no expectation that all PDF processors would construct visually identical appearance streams.

Related discussions are also in Issues #1, #17, #23, #42.

**Comment by petervwyatt** [comment]
So, to summarize for the question actually asked, I therefore think **MK** does **_not_** belong in the list of keys below Table 166 as that list is related to "static appearance" streams.

As a PDF 2.0 writer you must provide AP appearance streams for your annots, and you can optionally provide **MK** to influence interactive processors if/when they allow dynamic user interaction with your widgets.

**Comment by u-fischer** [comment]
> So I believe the intention of all the words is trying to distinguish between a "static appearance model" defined by AP appearance streams in almost all annots and always used by non-interactive processors (such as print RIPs) vs a "dynamic appearance" that might be used by certain interactive processors such as when users are interacting with form widgets.

I can't believe this. The AP appearance stream encodes  various "dynamic" states like rollover and down, /Yes, /Off.  I have code for checkboxes which use on AP for the various states and work fine.

In my opinion the difference is not a difference from user interaction, but how a PDF processor/viewer create the rendering: AP describes the appearance and so the rendering fully by  pointing  to an form Xobject, while MK gives a set of rules (like the text of the caption) and allows the renderer to create something on the fly.

**Comment by petervwyatt** [comment]
I mean that the AP appearance streams are "static" in that a processor just selects the appropriate stream they want (On, Off, Up, Down, etc) and renders it directly without changing it or attempting to reverse engineer how it was constructed to change it. However when a user does data entry into a widget/field, a GUI often needs to be dynamic in the sense that it changes on each keypress and UX designers may want other visual elements to assist/highlight - and this is what the optional MK provides. So I think we are agreeing.

**Comment by petervwyatt** [comment]
Given other proposed solutions in #94 and #42, adding **MK** to the list below Table 166 **as well as** the new wording in those solutions is OK (since the new wording highlights this "ignoring" is only when rendering appearance streams and PDF processors should not intermix keys and appearance streams when rendering). 

Note that the Table 190 description for MK explicitly refers to "... provides the icon used in generating the appearance referred to by the screen annotation’s **AP** entry" - and PDF remains silent on ways and means of regenerating appearance streams. That is a far bigger issue!

**Comment by petervwyatt** [comment]
PDF TWG: OK to ignore MK for Widget. Screen annots require AP therefore OK to ignore.
PDF TWG agree.
