### ISSUE TITLE
Table 341 Assets entry in a RichMediaContent dictionary marked as Optional, should be Required

### ISSUE THREAD

**Issue by datalogics-pgallot** [pdf-association/pdf-issues#58]
In section 13.7.2.3(.1) RichMediaContent dictionary , table 341;
the Assets entry in a RichMediaContent dictionary marked as Optional.

Unless I am missing an alternative way of specifying a Audio/Video/3D asset for playing within a RichMedia Annotation,
it would seem that this Asset entry should be required with at least one entry specified in the NameTree.

**Comment by petervwyatt** [comment]
Table 343 - Entries in a RichMediaInstance dictionary has a key **Asset** which states: "(_Required; PDF 2.0_) A dictionary that shall be an indirect object reference to a file specification dictionary that is also referenced in the **Assets** name tree specified in the **RichMediaContent** dictionary of the annotation."

So Table 343 requires key **Asset** which then (implicitly) requires **Assets** in Table 341 so I would agree with your correction.

**Comment by petervwyatt** [comment]
Proposed solution:

* correct Table 341, **Assets** key : Optional to Required 
* reword Table 343, **Asset** key: "... to a file specification dictionary that shall also be referenced in the **Assets** name tree specified..."

**Comment by petervwyatt** [comment]
PDF TWG: @lrosenthol to investigate

**Comment by petervwyatt** [comment]
Table 343, **Asset**:
(_Required; PDF 2.0_) A dictionary that shall be an indirect object reference to a file specification dictionary that may also be referenced in the Assets name tree specified in the RichMediaContent dictionary of the annotation. 

(Reasoning is that the 3D asset is not referenced by name however the name tree can have other assets)

PDF TWG suggested also adding a note along the lines of:
NOTE: the 3D asset is not referenced by name however the name tree can have other assets
