### ISSUE TITLE
Table 335 missing Scripts entry

### ISSUE THREAD

**Issue by datalogics-pgallot** [pdf-association/pdf-issues#59]
13.7.2.2.2 RichMediaActivation dictionary, the second paragraph, first sentence and table 335:
"The activation dictionary includes a script array."

However, none of the entries in table 335 is of type array.  Was there a Scripts entry unintentionally left off or intentionally removed?

Note that the example under table 337 shows a Scripts entry as part of a RichMediaActivation dictionary.

**Comment by DuffJohnson** [comment]
Ouch.

**Comment by petervwyatt** [comment]
Well discovered @datalogics-pgallot!
 
I can find a **Scripts** key back in the original "Adobe® Supplement to the ISO 32000 BaseVersion: 1.7 ExtensionLevel: 3" document. AFAICT it never got copied into the very early drafts of ISO 32000-2, even as far back as 2012!!!:

**Scripts** 
array
(_Optional; ExtensionLevel 3_) An array of indirect object references to file specification dictionaries, each of which describe a JavaScript file that shall be present in the **Assets** name tree of the **RichMediaContent** dictionary.
Default value: If the array has no elements, no script is executed.

It is also not defined in DVA.

@lrosenthol - do you remember any history here? Can you comment on certain well-known implementations?

**Comment by petervwyatt** [comment]
I managed to find a single PDF with a `/Scripts` key: https://corpora.tika.apache.org/base/docs/bug_trackers/PDFBOX/PDFBOX-4807-0.pdf. This relates to https://issues.apache.org/jira/browse/PDFBOX-4807, but this PDF also has what I think are unrelated issues.
Can anyone else reference a sample PDF?

**Comment by petervwyatt** [comment]
PDF TWG approved

**Comment by t-merz** [comment]
> Can anyone else reference a sample PDF?

The "richmedia_3d" topic in the PDFlib Cookbook creates one; the result is available at
https://www.pdflib.com/fileadmin/cookbooks/PDFlib/results/richmedia_3d.pdf

The code for creating it (https://www.pdflib.com/pdflib-cookbook/multimedia/richmedia_3d/) closely resembles the generated dictionary structure.

**Comment by petervwyatt** [comment]
Required by PDF/A-4 dated revision which has specific requirements around this key for PDF/A-4e
