### ISSUE TITLE
Annex H.8.2 demonstrates deprecated structure elements Reference, TOC and TOCI

### ISSUE THREAD

**Issue by t-merz** [pdf-association/pdf-issues#62]
Annex H.8.2 "Table of Contents" demonstrates the structure element hierarchy for a table of contents, using the Reference, TOC and TOCI elements. However, these elements no longer exist in the standard structure namespace PDF 2.0 per Annex M; they only exist in the standard structure namespace for PDF 1.7. This doesn't make the H.8.2 example wrong, but it's a bit confusing and inconsistent.

Possible solutions:
- Lazy: remove H.8.2
- Unsure: if Reference/TOC/TOCI within a PDF 1.7 namespace is the recommended approach, add a note which explains this.
- Ambitious: redesign the sample code and illustration so that they work without TOC and TOCI (I don't know what the recommended replacements are)

**Comment by mrbhardy** [comment]
@t-merz no tags are deprecated in PDF 2.0.  There are tags that are define in the standard structure namespace for PDF 1.7 (as defined in PDF 2.0) and the standard structure namespace for PDF 2.0.  I see no reason why the examples in PDF 2.0 wouldn't include accurate examples of how to use the elements from the standard structure namespace for PDF 1.7.

PDF 2.0 does not have any preference for whether to use PDF 1.7 elements or PDF 2.0 elements, but the default for PDF 2.0 is still the PDF 1.7 set.  However, the confusion around this shows we might benefit from a note describing this.

**Comment by t-merz** [comment]
> @t-merz no tags are deprecated in PDF 2.0.
I agree that my wording "deprecated" was too aggressive as this is not used in the standard (I changed the title to reflect this). As a matter of fact Reference/TOC/TOCI aren't specified anywhere in ISO 32000-2. They just got kicked out of Table 333 "Standard structure types for grouping elements" (Table 365 in ISO 32000-2).

Sure, I can look them up in ISO 32000-1 to learn their semantics, but this looks like a specification gap to the reader. ISO 32000-2 doesn't define the meaning of all its structure elements.

> @t-merz no tags are deprecated in PDF 2.0.
How would you designate "TagSuspect" in this respect? Silently departed...?

> There are tags that are defined in the standard structure namespace for PDF 1.7 (as defined in PDF 2.0) and the standard structure namespace for PDF 2.0. I see no reason why the examples in PDF 2.0 wouldn't include accurate examples of how to use the elements from the standard structure namespace for PDF 1.7.

See above: because the tags in the example aren't defined in normative language for PDF 2.0.

> PDF 2.0 does not have any preference for whether to use PDF 1.7 elements or PDF 2.0 elements, but the default for PDF 2.0 is still the PDF 1.7 set. However, the confusion around this shows we might benefit from a note describing this.

Much appreciated! I don't know why these useful tags are not included in the PDF 2.0 namespace and why the (perceived) older 1.7 set is default, but we implemented it that way. The harder task is to explain all this to users...

**Comment by DuffJohnson** [comment]
> > @t-merz no tags are deprecated in PDF 2.0.
> > I agree that my wording "deprecated" was too aggressive as this is not used in the standard (I changed the title to reflect this). As a matter of fact Reference/TOC/TOCI aren't specified anywhere in ISO 32000-2. They just got kicked out of Table 333 "Standard structure types for grouping elements" (Table 365 in ISO 32000-2).

Annex M discusses TOC/TOCI... but is only referenced once from the body text; I agree that's an issue.

> Sure, I can look them up in ISO 32000-1 to learn their semantics, but this looks like a specification gap to the reader. ISO 32000-2 doesn't define the meaning of all its structure elements.

This point has been raised elsewhere and is well-taken. 
 
> > @t-merz no tags are deprecated in PDF 2.0.
> > How would you designate "TagSuspect" in this respect? Silently departed...?

TagSuspect was specified in a pretty dubious manner in ISO 32000-1, IMO. That said, the "Suspects" key was deprecated with PDF 2.0 and noted as such in table 353.... but I agree that TagSuspect should have been noted as deprecated as well, even if only in the Introduction (clause 0.3).

> > PDF 2.0 does not have any preference for whether to use PDF 1.7 elements or PDF 2.0 elements, but the default for PDF 2.0 is still the PDF 1.7 set. However, the confusion around this shows we might benefit from a note describing this.

Concur. And perhaps some additional cross-ref links to Annex M...?

> I don't know why these useful tags are not included in the PDF 2.0 namespace and why the (perceived) older 1.7 set is default, but we implemented it that way.

I take this point, however these changes were made well before the 1st edition of PDF 2.0 was published in 2017, and IIRC we did not get many (any?) comments opposing the change.

> The harder task is to explain all this to users...

No argument! 

Perhaps we need to think more expansively about addressing these concerns as we move forwards. This is, in part, the purpose of a Technical Specification effort @mrbhardy is leading right now.

**Comment by mrbhardy** [comment]
> > > @t-merz no tags are deprecated in PDF 2.0.
> > I agree that my wording "deprecated" was too aggressive as this is not used in the standard (I changed the title to reflect this). As a matter of fact Reference/TOC/TOCI aren't specified anywhere in ISO 32000-2. They just got kicked out of Table 333 "Standard structure types for grouping elements" (Table 365 in ISO 32000-2).
> 
> Annex M discusses TOC/TOCI... but is only referenced once from the body text; I agree that's an issue.

@DuffJohnson and @t-merz I guess I'm failing to see the issue.  It is common for standards to refer to other standards for definitions.  We don't describe things that are defined elsewhere and, since ISO 32000-2 is not a replacement for ISO 32000-1, we explicitly call out in 14.8.6.1 that the PDF 1.7 namespace definitions are found in 14.8, ISO 32000-1:2008.  We did go back and forth whether to include them all in an annex and define them there, but felt in the best case, we'd match what we had in 32000-1 and worst case, we'd get it wrong.
 
> > Sure, I can look them up in ISO 32000-1 to learn their semantics, but this looks like a specification gap to the reader. ISO 32000-2 doesn't define the meaning of all its structure elements.
> 
> This point has been raised elsewhere and is well-taken.

I think this is important and correct.  Also, since ISO 32000-1 is freely available, it isn't a huge burden.

> > > @t-merz no tags are deprecated in PDF 2.0.
> > How would you designate "TagSuspect" in this respect? Silently departed...?
> 
> TagSuspect was specified in a pretty dubious manner in ISO 32000-1, IMO. That said, the "Suspects" key was deprecated with PDF 2.0 and noted as such in table 353.... but I agree that TagSuspect should have been noted as deprecated as well, even if only in the Introduction (clause 0.3).

@t-merz I'm not sure I actually follow the point you're making.  I said "no tags are deprecated" and **Suspects** is not a tag, but a document-level property, so I'm not sure of the relevance of your comment.  I think the deprecation of the **Suspects** entry is well-document and is called out in 0.3 already.

> > > PDF 2.0 does not have any preference for whether to use PDF 1.7 elements or PDF 2.0 elements, but the default for PDF 2.0 is still the PDF 1.7 set. However, the confusion around this shows we might benefit from a note describing this.
> 
> Concur. And perhaps some additional cross-ref links to Annex M...?

Isn't this explicitly called out in 14.8.6.1?  We could have a note in Annex M referencing 14.8.6.1 and noting this...

> > I don't know why these useful tags are not included in the PDF 2.0 namespace and why the (perceived) older 1.7 set is default, but we implemented it that way.
> 
> I take this point, however these changes were made well before the 1st edition of PDF 2.0 was published in 2017, and IIRC we did not get many (any?) comments opposing the change.

This is important for upgrading a PDF 1.x to PDF 2.0.  It significantly reduces complexity if someone wants to introduce a structure destination, for example.  This was a strong opinion and not a casual decision.  It is the correct one for compatibility.
 
> > The harder task is to explain all this to users...
> 
> No argument!

See above.

> Perhaps we need to think more expansively about addressing these concerns as we move forwards. This is, in part, the purpose of a Technical Specification effort @mrbhardy is leading right now.

Definitely.

**Comment by petervwyatt** [comment]
Returning to @t-merz original comment - and trying to bring to a resolution for ISO 32000-2:2020. Adding "proposed solution" label for discussion at next PDF TWG.

Suggest we take up @t-merz proposal 2 which is to add an informative note to Annex H.8.2 stating that the example uses Reference, TOC and TOCI elements which are part of standard structure namespace for PDF 1.7 and entirely valid in PDF 2.0.

**Comment by petervwyatt** [comment]
PDF TWG agree to add note
