### ISSUE TITLE
Make statement on which rendering intents are supported normative

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#63]
8.6.5.8 (Rendering Intents) says, in a note a little below Table 69 that "a particular device does not have to support all PDF rendering intents and can support additional ones beyond those listed in the table above."

That would be better as normative text, not in a note.

In the same section, just above the note, it says "If a PDF processor does not recognise the specified name, it shall use the RelativeColorimetric intent by default." and just above Table 69 it says ""Table 69 — Rendering intents" lists the standard rendering intents that shall be recognised". 

So the note says that you don't have to support all of the 4 standard rendering intents, but doesn't say what you should do if you don't, and you attempt to process a file that uses one that you don't support. You shall recognise it, because it's in table 69, so the default to RelativeColorimetric is not mandated.

And what you're supposed to do if you don't support RelativeColorimetric, I have no idea!

My preference would be to require that all of the 4 standard rendering intents must be supported, and that a device may support additional values. Perhaps somebody could explain the benefit of not supporting all four of the standard ones?

This text is the same as 32000-2:2017, by the way, and the meaning was the same in 32000-1.

**Comment by petervwyatt** [comment]
I've also wondered about these words in the past. I'd guess they might relate to early versions of the ICC spec when maybe rendering intents were not well understood and/or widely implemented. ISO 15076-1:2010 still has the following wording:

* clause 0.4: "Two colorimetric rendering intents are specified in this ICC specification, though only one is included fully constructed in the profile."
* clause 0.4: "The colour rendering of the perceptual and saturation rendering intents is vendor specific."

I support your idea of mandating support for all 4 standard rendering intents in PDF 2.0.

**Comment by petervwyatt** [comment]
Noting that NOTEs are informative only (and thus cannot impose or change requirements), the easiest solution is to reword the currently confusing NOTE to remove the comment about not supporting the 4 standard RIs as:

> NOTE The exact set of rendering intents supported can vary from one output device to another; a particular device can support additional ones beyond those listed in the table above.

So the existing normative requirements to support all 4 rendering intents remains (""Table 69 — Rendering intents" lists the standard rendering intents that shall be recognised.") as does "If a PDF processor does not recognise the specified name, it shall use the **RelativeColorimetric** intent by default."

**Comment by petervwyatt** [comment]
PDF TWG approved
