### ISSUE TITLE
Missing an embedded file referenced in Annex L

### ISSUE THREAD

**Issue by DuffJohnson** [pdf-association/pdf-issues#64]
Annex L refers to an XLSX file embedded in the PDF. However, the XLSX is not embedded. :-(

Solution: Embed the XLSX as indicated.

**Comment by petervwyatt** [comment]
Since ISO owns copyright I'm not sure if the PDF Association could host the promised XSLX as a community service.
Labelled as "wont fix" for this reason for now (as we don't have a label called "can't fix").
@DuffJohnson - do you want to ask ISO about this?

**Comment by DuffJohnson** [comment]
I have asked....

**Comment by petervwyatt** [comment]
XLSX file now hosted at pdfa.org - see https://www.pdfa.org/pdf-issues/
