### ISSUE TITLE
NS entry for pdf 2.0 structure elements

### ISSUE THREAD

**Issue by u-fischer** [pdf-association/pdf-issues#65]
section 14.8.6.1 Namespaces for standard structure types and attributes

wites 

> the *default standard structure namespace* shall be "http://iso.org/pdf/ssn". When a namespace is
not explicitly specified for a given structure element or attribute, it shall be assumed to be within this
default standard structure namespace.

Table 355 — Entries in a structure element dictionary 

writes about the `NS` entry

> If not present, the element shall be considered to be in the default standard
structure namespace (see 14.8.6, "Standard structure namespaces").

Does that imply that structure elements that are only defined in the standard structure namespace for PDF 2.0 like `Title` or `Aside` require an `NS` entry  in a pdf 2.0 document?

**Comment by petervwyatt** [comment]
@mrbhardy?

**Comment by mrbhardy** [comment]
@u-fischer yes, all PDF 2.0 elements must have an explicitly declared namespace.  It isn't that much of an impact internally in the file, since the reference from the StructElem is an indirect reference to the corresponding Namespace Dictionary.

**Comment by u-fischer** [comment]
@mrbhardy well the impact is that I have implement it ;-). What do you think is the preferred way for elements which are in both namespaces? Mark them as 2.0 or leave as 1.7? Does it matter?

**Comment by mrbhardy** [comment]
I would say use PDF 2.0 namespace for all PDF 2.0 elements (including those defined in both).  The validation rules are more fleshed out.

**Comment by petervwyatt** [comment]
So is this worthy of a small informative NOTE in our non-official/non-ISO errata?
That way we have captured this for others in the future.

**Comment by u-fischer** [comment]
@mrbhardy  and how should one role map to a 2.0 structure type. E.g. if I want to map `Marginnote` to `Aside`?

The following seems to follow the reference but it looks a bit circular how the /RoleMapNS points to its own parent object:

~~~~
<<  /Type /StructElem /S /Marginnote /NS 9 0 R >>


9 0 obj
<< 
   /Type/Namespace
   /NS(http://iso.org/pdf2/ssn) 
   /RoleMapNS 
     <<
       /Marginnote [/Aside 9 0 R]
     >>
>>
endobj
~~~~


Using the more simple

~~~~
  /RoleMapNS 
     <<
       /Marginnote /Aside
     >>
~~~~

seems to contradict the spec which says, that the simple value is for names "identifying a structure element type in the *default standard structure* [1.7] namespace".

**Comment by mrbhardy** [comment]
@u-fischer sorry for not replying sooner.  It isn't generally considered good practice to define a tag being in namespace that doesn't actually contain it.

Taking your example, I would have suggested:

```
<<
    /Type /StructElem
    /S /Marginnote 
    /NS 8 0 R 
>>

8 0 obj
<<
    /Type /Namespace
    /NS (http://latex.org/v1)
    /RoleMapNS
    <<
        /Marginnote [ /Aside 9 0 R ]
    >>
>>

9 0 obj
<< 
   /Type/Namespace
   /NS(http://iso.org/pdf2/ssn) 
>>
endobj
```

**Comment by petervwyatt** [comment]
Trying to push this towards a proposed solution... 

Sounds to me like adding @mrbhardy's example above to the end of 14.8.6.2 would not go astray as there is a very distinct lack of namespaced examples. What do others think?

**Comment by petervwyatt** [comment]
PDF TWG agrees to add example but changed as follows:
* replace "(data:,"... with "urn:uuid: ..."
* replace /var ... with "..."
