### ISSUE TITLE
Clarification in Table 371 (Table structure types) 

### ISSUE THREAD

**Issue by PaulRayius** [pdf-association/pdf-issues#66]
Comparing Table 370 (14.8.4.8.2 - Standard structure types for Lists) and Table 371 (14.8.4.8.3 - Table structure types)

(Table 370)  LI's "category" is "Internal to L structure elements" and LBody's is "Internal to LI.  That's pretty clear and leaves little room for error.  

However, in  Table 371...
TR's "category" is "Internal to a Table structure".  That seems vague, though, because it could also be internal to THead, TBody, and/or TFoot.  I think we should include that clarification.

Similarly, TH and TD's "categories" are "Internal to a Table structure."  I think we should clarify that TH and TD are "Internal to TR structure elements."  

(If we are as specific as we are with LI and LBody, why do we get more "vague" with TR, TH and TD?)

**Comment by petervwyatt** [comment]
Doesn't Annex L define this precisely? Be best to reference that ...

**Comment by PaulRayius** [comment]
I understand Peter's point and, sure, maybe we should just leave it up to Annex L to specify containment rules, etc.  This could be a better approach because it puts all of that information in just one place instead of two (the "body" of the document as well as Annex L).   But, if we're going to do that, then maybe we should take out all stated (or implied) containment information from the various tables and rely solely on Annex L so that there's not "partial information" here and there in the document.  This would also help to prevent possible conflicting information, too, if containment rules get changed in one place but not in the other.

**Comment by DuffJohnson** [comment]
I don't see the problem. **TR** may indeed by internal to **THEAD**, etc which are elements of table structure, so the text isn't vague, it's appropriately descriptive. Annex L expresses these rules formally. Anyone reading tables 370 and 371 does so in the light of Annex L... so IMO it's ok as-is.
