### ISSUE TITLE
"Category" for Table structure element

### ISSUE THREAD

**Issue by PaulRayius** [pdf-association/pdf-issues#67]
In 14.8.4.8.3 - Table 371, the "Category" for **Table** structure elements is Block.  Meanwhile, **L** (Table 370) and other elements (**Link**, **Annot**, **Form**, etc.) can have a variety of categories including Block, Inline, or even Grouping.  

"Forcing" **Table** to be Block would be inappropriate for situations such as when a paragraph of text, or a list item, or even another table, contains a data table in the middle of it.  

I'd recommend we change its category to Block or Inline. 

Granted, 14.8.4.8.1 says, "There are a number of other structure types... that may be used as grouping level structure elements, as block level structure elements or as inline level structure elements, depending on the context in which they are used."  So we're kind of "covered" there.  However, if that's the case then why does the "category" for List say "Block or Inline" but Table is limited to "Block?"  

If we "clarify" for one structure element then I think we should "clarify" for the others.

**Comment by mrbhardy** [comment]
This is an interesting one.  If you look in Annex L, Table cannot occur inside of most block-level items (i.e. you can't include it in Paragraph).  I'm not sure that this fix is sufficient and would potentially conflict with Annex L. @PaulRayius @DuffJohnson

**Comment by petervwyatt** [comment]
Maybe a better way would be to somehow make more prominent that Annex L is normative and all the detail it contains - such as the long NOTE currently at the end of clause 14.8.4.2.  But I'm not sure how to do that...

And why is that long NOTE a NOTE anyway?

**Comment by DuffJohnson** [comment]
The NOTE is a NOTE that was intended to express in human-readable terms a (hopefully consistent) philosophy as expressed in Annex L... and provide necessary context to understanding Annex L.

I'm not sure I understand what we need to "fix" here... @PaulRayius ? Is your point that you feel that P should be able to include Table?

**Comment by PaulRayius** [comment]
@DuffJohnson, my point was that Table should not be limited to Block.

**Comment by DuffJohnson** [comment]
How about replacing the category for Table with "see Annex L"?

**Comment by car222222** [comment]
Actually, according to Annex L, Table can appear in much the same places as other similar mid/high-level structures.  The two notable exceptions being that Table alone is excluded as a direct child of 'Sub' and 'P'. 

It is not immediately clear why it should differ from, for example, Formula, Figure and List.

**Comment by PaulRayius** [comment]
"It is not immediately clear why it should differ from, for example, Formula, Figure and List."

Agreed.  What if some author puts a table in the middle of their paragraph of text?

**Comment by DuffJohnson** [comment]
> "It is not immediately clear why it should differ from, for example, Formula, Figure and List."
> 
> Agreed. What if some author puts a table in the middle of their paragraph of text?

If this is the issue then the Bug you want to file isn't really about the category of Table but about the rules for Table as stated in Annex L, yes? 

If so then IMO you should close this issue and post a new one along those lines.

**Comment by PaulRayius** [comment]
Closing this, per Duff's last comment.
