### ISSUE TITLE
Cannot represent link semantics for content that spans pages

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#7]
Clause 14.8.4.7.2 General inline level structure types, 2nd bullet below Table 368/Note 1 says:

"One object reference (see 14.7.5.3, "PDF objects as content items") to one link annotation associated with the content"

This restriction (new to PDF 2.0) is too strong; it doesn't allow for multiple link annotations tagged with a single <Link> element as would be necessary to fully represent semantics for content that spans pages.

**Comment by lrosenthol** [comment]
I believe this is correct, in that this is starting from the `Link` element and not the content element.   A content element could have many `Link` children, but a `Link` can only bind back to a single content element.

**Comment by lrosenthol** [comment]
Since annotations are bound to pages, it would be problematic to start thinking about them outside that context.  This is why block level elements that span pages, such as a paragraph are broken into inline elements (eg. Spans) for each page.  And if you needed to duplicate the Link, that would be OK.

**Comment by mrbhardy** [comment]
Actually, this doesn't sound right to me.  There's no reason that a single Link can't have content that spans pages and then OBRJs gathering the related annotations for that link.  This sounds like a mistake when 14.8 was being rewritten.

**Comment by DuffJohnson** [comment]
> Since annotations are bound to pages, it would be problematic to start thinking about them outside that context. This is why block level elements that span pages, such as a paragraph are broken into inline elements (eg. Spans) for each page. And if you needed to duplicate the Link, that would be OK.

To be clear about this, there's no requirement (that I am aware of) for <Span> elements when a <P> includes content that occurs on >1 page, and it's common practice to omit such <Span> elements in this case.

**Comment by mrbhardy** [comment]
@DuffJohnson totally agreed.  Spans can be used to separate them, but certainly aren't in any way required.

**Comment by lrosenthol** [comment]
@mrbhardy @DuffJohnson while I agree that 32K itself has no requirements on the `Span` elements - we should most certainly ensure that it is part of "advanced tagging" work such as PDF/UA or related documents.

**Comment by DuffJohnson** [comment]
I agree that prescriptions for "good tagging", including PDF/UA, should include a requirement for use of a <Span> or similar in these cases (note taken), but the implied need for a <Span> or similar to contain a page-spanning <Link>'s respective OBJRs (as they cannot themselves span pages) is clear enough from the existing text, IMO.
