### ISSUE TITLE
Definition of TR in Table 371 can cause confusion as to whether TD and TH cells can be mixed within a row

### ISSUE THREAD

**Issue by mrbhardy** [pdf-association/pdf-issues#71]
The definition for TR in table 371 currently has the text:

> "A row of table header cells (TH) or table data cells (TD) in a table."

The challenge here is that this can be misread this to imply that there can either be a row of table header cells or a row of table data cells, but not a single row of table header cells and table data cells.  While the sentence above does not actually limit this and Annex L makes no such prohibition on mixing table header and table data cells within a row, we could clear this up.

Proposed alternative:

"A row containing table header cells (TH), table data cells (TD), or both."

**Comment by petervwyatt** [comment]
PDF TWG agree
