### ISSUE TITLE
Missing standard attribute owner for MathML

### ISSUE THREAD

**Issue by bdoubrov** [pdf-association/pdf-issues#72]
**Describe the bug**
Table 376 - Standard structure attribute owners - does not include a standard owner for the tags from the MathML namespace. 

It would be great to have the following owners added to this table:
- MathML-1
- MathML-2
- MathML-3

**Additional context**
MathML does include a number of attributes in its model. A typical example would be a scripted variable:
`<mi mathvariant='script'> L </mi>`

**Comment by petervwyatt** [comment]
I think this is more an extension rather than a bug

**Comment by mrbhardy** [comment]
@bdoubrov why would you want an owner entry versus using the namespace mechanism for attributes?

**Comment by mrbhardy** [comment]
Just to be clear on how this is supposed to be achieved in ISO 32000-2, you would do the following:

```
10 0 Obj
<<
    /Type /Namespace
    /NS (http://www.w3.org/1998/Math/MathML)
>>

11 0 Obj
<<
    /Type /StructElem
    /S /mi
    /NS 10 0 R
    /A 12 0 R
    /K ...
>>

12 0 Obj % Attribute Object
<<
    /O /NSO
    /NS 11 0 R
    /mathvariant (script)
>>
```

**Comment by bdoubrov** [comment]
@mrbhardy Thanks, this is indeed a great example. (I guess `/NS` should point to `10 0 R` in object 12).

I also found this text in 14.8.6.3:
> When including mathematics structured as MathML, the **math** structure element type shall be used and shall have its namespace explicitly defined (see 14.7.4.2, "Namespace dictionary").

I do fully agree that all MathML attributes (as well as all MathML structure types) should always declare a namespace explicitly. If agreed then I propose to change this issue to a different one:

Drop the initial suggestion to add MathML attribute owners and suggest replacing the above citation from 14.8.6.3 to the following
> When including mathematics structured as MathML,  all MathML structure element types and their attributes shall have MathML namespace explicitly defined (see 14.7.4.2, "Namespace dictionary").

**Comment by petervwyatt** [comment]
PDF TWG agree.
