### ISSUE TITLE
Rename 12.4.2 Page labels

### ISSUE THREAD

**Issue by willkil** [pdf-association/pdf-issues#73]
This subclause's heading is currently "12.4.2 Page labels".  This subclause also defines page indices. When referring to 12.4.2 for the purpose of referring to the page indices definition, the reference confusingly says, "see 12.4.2 Page labels".

The proposed renamed heading is "12.4.2 Page labels and indices".

**Comment by petervwyatt** [comment]
PDF TWG agrees
