### ISSUE TITLE
7.6.6 Crypt filters - include v=5 into the text

### ISSUE THREAD

**Issue by romantoda** [pdf-association/pdf-issues#74]
in 7.6.6 Crypt filters bullet 1 we say:

... the value of the V entry shall be 4 to use crypt filters.

the version 5 is missing. please replace with:

... the value of the V entry shall be 4 or 5 to use crypt filters.
or
... the value of the V entry shall be greater than or equal to 4 to use crypt filters.

**Comment by MatthiasValvekens** [comment]
Quick question (and I'm sure it'll come up in the very near future): what are the implications of this for security handlers defined in extensions to the standard?

For example, the current draft of ISO 32003 defines a version 6 security handler, which would theoretically not be covered by this rule, despite using crypt filters just like V4/V5 security handlers. Perhaps this is a good argument in favour of amending ISO 32003 instead, though. Just putting it out there so we don't forget about it.

**Comment by petervwyatt** [comment]
Outcome from discussions at May 2021 virtual WG8 meeting: PDF extension documents (such as ISO 32003) need to highlight whenever they contradict a "shall" requirement from ISO 32000-2 so being strictly precise for this fix is not an issue.

**Comment by petervwyatt** [comment]
PDF TWG agrees
