### ISSUE TITLE
Minor editorial issues

### ISSUE THREAD

**Issue by t-merz** [pdf-association/pdf-issues#75]
I'll collect a few minor editorial topics in a single issue:

(1) Last paragraph in 4.1:
"Characters in text streams, as defined by 7.9.2, "String object types", are identified by their Unicode character name written in uppercase in font followed by a parenthetic four digit hexadecimal character..."

The words "in font" don't make sense. I initially thought this should read "in bold font", but the U+XXXX names are not printed in bold.
Suggestion: delete "in font".

(2) Same clause as in (1): "four digit" is technically wrong as Unicode characters may require up to five hex digits. This is not hypothetical, see "UNICODE HAN CHARACTER ‘U+2003E’" in example 2 in 9.10.3 (should use parentheses instead of single quotes here).
Suggestion: "four or five digit hexadecimal character"

(3) Table A.1, "PDF content stream operators", row c/curveto refers to "Table 60 — Clipping path operators" which doesn't discuss the c operator.
Suggestion: change reference to "Table 58 — Path construction operators" (as in the entries for m, l, re etc.).

(4) 7.9.2.2.1, example 1:
"is represented by the hex code 8B..."
Similar in the last line "hex codes FE, FF, 04,..." of Example 2 just before Note 3.
Suggestion: for consistency this should read "hexadecimal code 8Bh" or "code 8Bh".

(5) 4. 1 uses "upper case" in the para after NOTE 2 and "uppercase" in the last paragraph. In fact, "upper case" appears 5 times in the whole document and "uppercase" 23 times ("lower case"/"lowercase": 1 vs. 20).
Suggestion: consolidate spelling.

And yes, if someone complains that I am nit-picking they are correct.

**Comment by petervwyatt** [comment]
Thank you! No one should complain about such a detailed read...
I agree with all your proposed fixes.

**Comment by petervwyatt** [comment]
PDF TWG agrees

**Comment by petervwyatt** [comment]
Note: " (should use parentheses instead of single quotes here)." is incorrect as Unicode name includes U+xxx value and is not a separate paranthetical

**Comment by petervwyatt** [comment]
Noted the widespread change for consistency for "uppercase" to replace "upper case" everywhere in Clause 4.
