### ISSUE TITLE
Use of Crypt filter with Identity name without document encryption dictionary

### ISSUE THREAD

**Issue by bdoubrov** [pdf-association/pdf-issues#76]
PDF/A-4 allows the use of /Crypt filter with Name=Identity in the decode parameters.  

6.1.6.2 Filters: 
>In addition, the Crypt filter shall not be used unless the value of the Name key in the decode parameters dictionary is Identity.

At the same time it forbids the use of encryption dictionary. 

6.1.3 File trailer: 
> The Encrypt key shall not be present in the trailer dictionary.

However, ISO 32000-2 does not seem to allow the use of Crypt filters without encryption dictionary. 

ISO 32000-2, 7.6.6 Crypt filters: 
> The use of crypt filters involves the following structures: - The encryption dictionary […]

Yet, this text from ISO 32000-2 is a *shell* requirement, merely an explanation how /Crypt filter is supposed to be processed. And clearly encryption dictionary is not required to process the /Crypt filter with Name=Identity. 

If this is correct, I suggest to mention this explicitly in ISO 32000-2, 7.6.6. 

I attach a sample file where the Metadata stream uses such Crypt filter, while there is no encryption dictionary present. But I several applications I tried don’t like this and are not able to extract metadata from the document.
[Crypt-Identity-filter.pdf](https://github.com/pdf-association/pdf-issues/files/6533479/Crypt-Identity-filter.pdf)

I also note that this text on Crypt filters is also present in PDF/A-2 and 3. So, I think this question is relevant for these PDF/A parts as well.

**Comment by MatthiasValvekens** [comment]
Hmm, I'd consider this a bug in PDF/A-{2,3,4} rather than ISO 32k, to be honest. IMO the requirement

> In addition, the Crypt filter shall not be used unless the value of the Name key in the decode parameters dictionary is Identity.

should be amended to

> In addition, the Crypt filter shall not be used.

(without qualifiers). I don't see the point of using **Crypt** at all if encryption is not allowed.

**Comment by MatthiasValvekens** [comment]
Proposed solution as per my previous comment, unless the PDF/A TWG disagrees.

**Comment by petervwyatt** [comment]
@bdoubrov - can you please comment on discussions from PDF/A TWG?

**Comment by bdoubrov** [comment]
Yes, PDF/A acknowledges this resolution, but does not recommend taking any actions towards ISO 19005-4 (as well as 2 and 3) specifications.

**Comment by petervwyatt** [comment]
PDF/A and PDF will not be making any changes at this time. Closing without any changes.
