### ISSUE TITLE
One more clarification on Alternate images with optional content

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#79]
Unfortunately, even after all the work for the 2020 edition, the interactions of optional content and alternate images is still not clear. In particular step c) in the sequence below table 89 is slightly self-contradictory.

If the base image contains an OC entry that specifies that the base image is not visible, then the list of 
alternate image dictionaries specified by the base image Alternates entry shall be examined in order,
and the first entry not containing an OC key, or containing an OC entry specifying that the alternate
image should be visible, shall be selected. **_Further, if this selected alternate image has an OC entry, then
that OC entry shall also be processed to determine if the alternate image shall be rendered or not._** If none
of the alternate image dictionaries have an OC key, **_or_** none of the alternate image dictionaries with an
OC entry specify that that alternate image is visible, then nothing shall be shown. DefaultForPrinting
shall be ignored on all Alternates entries.

I think it would be fine if the 2nd sentence (highlighted above) were removed. It appears to partially contradict the previous sentence, because that already requires the OC entry to have been processed to support the selection process.

Strictly speaking, I also think that the ‘or’ in the 3rd sentence (highlighted above) should be ‘and’.

**Comment by petervwyatt** [comment]
Taking your second comment first: the phrases either side of the "or" are exclusive as the 1st phrase ("If none of the alternate image dictionaries have an OC key...") is mutually exclusive with the second phrase which have OC. So I think it could be either "and" or "or" as the short-circuit boolean evaluation will kick in 😀! But I prefer the "or" there now as it hints at these mutually exclusive alternatives...

**Comment by petervwyatt** [comment]
Looking at your first/main comment: remember that there are 2 locations for OC - in an Image XObject dict (Table 87) and in the alternate image dictionaries (Table 89 OC) which are in the alternate image array. The prior sentence ("... containing an OC entry specifying that the alternate image should be visible, shall be selected." is referring to the alternate image dictionary (NOT the Image XObject) whereas the bold sentence you highlighted is referring to the OC key in the Image XObject itself, which was the value of the Image key in the alternate image dictionary (array element of the alternates image array).

So I don't agree with your suggestion... may be the example shown could be expanded?

**Comment by petervwyatt** [comment]
Or just an informative NOTE stating that the OC key exists in these 2 places.

**Comment by MPBailey** [comment]
Sorry Peter, I disagree.

_If the base image contains an OC entry that specifies that the base image is not visible, then the list of alternate image dictionaries specified by the base image Alternates entry shall be examined in order,_

OK so far; that was talking about the base image having an OC entry, so now we’re stepping through, looking in each of the Alternates in turn.

_and the first entry not containing an OC key, or containing an OC entry specifying that the alternate image should be visible, shall be selected._ 

If we’ve selected this Alternate, it’s because it has no OC, or it does have an OC and that OC specifies that the Alternate should be visible. If it had an OC that didn’t make this Alternate visible then we would not have selected it; we’d have moved on to the next one. And that’s obviously intentional because it allows the optional content mechanisms to guide selection of different alternates. 

_Further, if this selected alternate image has an OC entry, then that OC entry shall also be processed to determine if the alternate image shall be rendered or not._

That’s the confusing/misleading bit, because we must have already done that to reach this point. We must know whether the OC specifies that this Alternate should be visible to have selected it. I still feel that just deleting that sentence would improve the text considerably.

_If none of the alternate image dictionaries have an OC key, or none of the alternate image dictionaries with an OC entry specify that that alternate image is visible, then nothing shall be shown._ 

I still think that should be an ‘and’ because it doesn’t say what should be done if some have an OC that doesn’t specify that that Alternate is visible and some don’t have an OC at all. But I’m not going to fight over that because, if you treat each sentence in this para as a test in turn, and realise that this sentence only applies if you didn’t select an Alternate in the previous ones then you’ll never get to it

_DefaultForPrinting shall be ignored on all Alternates entries._

Yup, that’s good.

Martin

**Comment by petervwyatt** [comment]
I guess this is ambiguous or at the very least unclear 'cos we read the same words and get a different understanding...

_and the first entry not containing an OC key, or containing an OC entry specifying that the alternate image should be visible, shall be selected._

This says "entry" twice so to me this is clearly the **OC** key in the alternate image array. It is not an **OC** key in any Image XObject. So by "selecting this Alternate" you really mean choosing an array element in the alternate image array (we haven't got to the image yet!).

If I was to re-word this, I'd suggest something like:
_and the first alternate image array entry not containing an OC key, or the first alternate image array entry containing an **OC** entry specifying that the alternate image should be visible, shall be selected._

---
_Further, if this selected alternate image has an OC entry, ..._

OK - now it says "selected alternate image" and not "entry" or "element" so we've now dived into the **Image** key in the selected element of the alternate image array. So this is an Image XObject and can have an **OC** key which is what is being described... 
If I was to re-word this, I'd suggest something like:
_Further, if this selected alternate image (as defined by the **Image** key of the selected element of the alternate image array) has an OC entry, ..._

Does that more sense as to how I interpret these words?

**Comment by petervwyatt** [comment]
alternate (image dictionary) vs (alternate image) dictionary 🤣

Could you please edit your previous comment so indenting is retained (using code formatting should retain spaces)? Thanks

**Comment by lrosenthol** [comment]
I am trying to find the original psuedo-code that I presented on this topic at ISO.  Peter, was it recorded a comment sheet?

**Comment by petervwyatt** [comment]
@lrosenthol If it was a formally submitted comment, then yes. If it was long then it would be at the end of one of the comment N-docs. If it was a table comment, or passed around during a meeting then possibly no.

**Comment by lrosenthol** [comment]
Found the comment - it is a in a file called "2019-05-15_PreTorontoComments" and is part of the email thread that @MPBailey started back in March of 2019.

Here is the psuedo-code that I provided in May 2019 based on our implementation:
```
During Parsing
--------------
foreach(Image XObject)
     if HAS_ALTERNATES
           foreach( alternate )
                if BASE_NO_OC
                     if ( DefaultForPrinting == TRUE )
                           Set As DefaultForPrinting
                           AddToAltList
                else BASE_HAS_OC
                     if ALT_HAS_OC
                           AddToAltList


During Rendering (an Image XObject)
-----------------------------------
if BASE_NO_OC
     if AM_PRINTING && HAS_DEFAULT_FOR_PRINTING
           Use DefaultForPrinting
     else 
           Use BaseImage
else BASE_HAS_OC
     if BASE_OC_ON
           Use BaseImage
     else BASE_OC_OFF
           // find first alternate with /OC that is on
           // (and if the image has had an /OC entry of
           // its own it is on too) and use it
           foreach (alternate)
                if ALT_HAS_OC && ALT_OC_ON
                     Use AltImage
                     BREAK_OUT_OF_LOOP
```

**Comment by MPBailey** [comment]
If that's the process that we want to follow, then the 3rd sentence in c) is incomplete: "_If none of the alternate image dictionaries have an OC key, or none of the alternate image dictionaries with an OC entry specify that that alternate image is visible, then nothing shall be shown._"

**Comment by MPBailey** [comment]
I can't see anything in that code which looks at the presence or meaning of an OC key in the stream that forms the value of the Image key in an alternate image dictionary; am I missing something?

Regardless, I'd like to propose this replacement text for step c:

If the base image contains an OC entry that specifies that the base image is not visible, then the list of alternate image dictionaries specified by the base image Alternates entry shall be examined in order.

The first item in the array that forms the value of the Alternates key that meets both of the following criteria shall be rendered:

The alternate image dictionary:
•	does not contain an OC entry; or
•	contains an OC entry that specifies that this alternate image dictionary  should be visible

And the stream that forms the value of the Image key in the alternate image dictionary:
•	does not contain an OC key; or
•	contains an OC key that specifies that this image should be visible

If none of the alternate image dictionaries are rendered using the criteria above then nothing shall be shown. 

DefaultForPrinting shall be ignored on all Alternates entries.

**Comment by lrosenthol** [comment]
>I can't see anything in that code which looks at the presence or meaning of an OC key in the stream that forms the value of the Image key in an alternate image dictionary; am I missing something?

That's a separate issue.  If the image is determined to not be visible in the current state, then none of this matters.  And how you get there is specified in the section on OC and need not be repeated.  (but perhaps a NOTE that references back to that would be OK for me).

>The alternate image dictionary:
>• does not contain an OC entry; or

This would NOT be consistent with the algorithm above.   If there is no OC entry, then the Alt won't appear when the base image is in a non-visible OC state.

>DefaultForPrinting shall be ignored on all Alternates entries.

That would also NOT be consistent with the above algorithm.

**Comment by MPBailey** [comment]
Hi Leonard. You said " If the image is determined to not be visible in the current state, then none of this matters. And how you get there is specified in the section on OC and need not be repeated." 

So you're saying that the process to 'select' an alternate image dictionary does not take account of any OC entry in the image stream. The selection only takes account of OC in the alternate image dictoinaries themselves, and any OC in the image stream is only looked at once once an alternate image dictionary has been selected.

At that point, if there's no OC in the image stream, or the OC specifies visible, that alternate will be rendered; if there's an OC that specifies not visible, nothing will be rendered, regardless of any later alternate image dictionaries in the Alternats array.

Is that correct?

**Comment by lrosenthol** [comment]
>So you're saying that the process to 'select' an alternate image dictionary does not take account of any OC entry in the image stream.

No, I am saying that the process to select an alternate *will never get invoked* for any image that is in an OC that is currently in OFF state.   This is because the `Do` operator doesn't (need to) get invoked.

>if there's no OC in the image stream, or the OC specifies visible, ...

Then the algorithm described above gets invoked to determine WHICH IMAGE (if any) to display...

**Comment by petervwyatt** [comment]
To @lrosenthol point, Table 87 does make this clear under the OC entry: "Before the image is processed by a PDF processor, its visibility shall be determined based on this entry. If it is determined to be invisible, the entire image shall be skipped, as if there were no **Do** operator to invoke it." 

And the algorithm in 8.9.5.4 does loosely indicate that it is logic applied only to alternates: "... may be used to facilitate selection between alternate images."

That said we could still do a lot better, esp. for non-native English speakers and others who don't read the spec like lawyers :-). For this point (only), I suggest we could add a factual NOTE to **OC** in Table 31 which says:

NOTE: Alternate image processing does not occur for invisible base images.

**Comment by petervwyatt** [comment]
@MPBailey - so where do we stand with the algorithm(s) you and @lrosenthol shared?

**Comment by petervwyatt** [comment]
I propose we also do the clarifications I proposed in [this comment](https://github.com/pdf-association/pdf-issues/issues/79#issuecomment-849301401) so others don't fall into the same trap.

**Comment by MPBailey** [comment]
I think Peter's [comment ](https://github.com/pdf-association/pdf-issues/issues/79#issuecomment-860317378) has identified a big hole in this complete structure.
Table 87 (entries in an image dictionary) says that if the base image has an OC entry that indicates that the image is not visible then it's game over, and the image shall not be shown at all. In contrast, step c) of 8.9.5.4 (alternate images) talks about looking through the Alternates array if the base image has an OC entry that makes it invisible.

Just for the sake of discussion, I'm going to be a bit radical ... especially since I think we've spent more time arguing about this than the level of use of alternate images deserves!

**Proposal #1: minimum text changes and greatest consistency with PDF 1.5 - 32000-1:**
* Amend the OC entry in Table 87 to add alternate image handling as an exception to the "as if there were no Do operator to invoke it"
* In Table 4.38 say that DefaultForPrinting is ignored if the base image contained an OC entry
* Restore the simple 2-step description from 32000-1 at the end of 8.9.5.4 (If OC in the base says it's visible, then use the base; if OC in the base says it's not visible then use the first alternate that has an OC entry that says it should be visible).

**Proposal #2: best alignment with Leonard's "well known implementation":**
* remove all references to OC in 8.9.5.4 (Alternate images), just leaving DefaultForPrinting, and adding a statement saying that OC in alternate images is deprecated.

**Comment by MPBailey** [comment]
All of PDF 1.7, 32000-1 & 32000-2:2017 say:
•	If the base image has an explicit OC entry that makes the image visible then the base image shall be shown.
•	If the base image has an explicit OC entry that makes the image invisible then nothing shall be shown.
•	If the base image has no explicit OC entry then the first Alternate that has an explicit OC entry specifying that it would be visible is shown.

I’m talking about explicit OC entries to differentiate from OC not being present and defaulting to visible.
There is no text in any of those documents before 32000-2:2017 to describe what should happen if the Alternate image dictionary has an OC key in it (remember, there are 3 levels of dict here: the base image, the entry in the Alternates array, and the image dictionary that’s referenced by the Image key in an Alternates entry). 32000-2:2017 says it should be ignored, which makes perfect sense to keep this whole thing manageable!

**Proposal:**

_At the end of 8.9.5.4, reinstate the short description of selecting alternates from 32000-2:2017, with the fourth bullet adjusted and an additional bullet added:_

In PDF 1.5, optional content (see 8.11, "Optional content") may be used to facilitate selection between alternate images. The following algorithm shall be used to determine which image, if any, shall be shown:
a) If the base image contains an OC entry that specifies that the content is not visible, then nothing shall be shown.
b) If the base image contains an OC entry that specifies that the base image is visible, then the base image shall be rendered.
c) Otherwise if the PDF is being printed and any of the Alternates entries has DefaultForPrinting set to true, then that alternate image shall be printed.
d) Otherwise, the list of alternates specified by the base image Alternates entry is examined, and the first alternate containing an OC entry specifying that its content should be visible shall be shown **(Alternates that have no OC entry shall not be shown.)** Furthermore if the image dictionary that forms the value of the Image key of the selected alternate contains an OC entry, then that OC in the image dictionary shall not be examined.
**e) If the steps above do not identify an alternate to be rendered then the base image shall be rendered.**

_The 32000-2:2020 last bullet was_ 

d) Otherwise, the list of alternates specified by the base image Alternates entry is examined, and the first alternate _not containing an OC key, or_ containing an OC entry specifying that its content should be visible shall be shown. Furthermore if the image dictionary that forms the value of the Image key of the selected alternate contains an OC entry, then that OC in the image dictionary shall not be examined.

_The NOTE before the bullet list will also need tweaking, perhaps to:_

NOTE (202#) The following algorithm was changed in this document to clarify the relationship between optional content and DefaultForPrinting.

**Comment by petervwyatt** [comment]
PDF TWG would like to consider deprecating alternate images in a future PDF part, as OC achieves the same result without this confusion.

**Comment by MPBailey** [comment]
I'm still happy with the proposal I made on Sept 9th, modulo a minor clarification that I've just made to that (see the italic text in step e).
Can we discuss on the call on Dec 2nd?
The only thing I might add would be a recommendation to use optional content instead of alternate images, perhaps even justified by a note that alternate images may be deprecated in a future version. That needs discussion on a call though.

**Comment by petervwyatt** [comment]
@MPBailey Q: your proposed step (d) says "... that its content should be visible shall be shown ... " - is this really a "should"? Surely OC is fully deterministic and thus is a "shall" (or possibly phrased factually)? If it is truly a should then I think it deserves a note...

**Comment by MPBailey** [comment]
You're right; "should be visible" replaced with "is visible", matching the phraseology of other steps.

**Comment by petervwyatt** [comment]
PDF TWG agree with @MPBailey new / updated wording in the 9 Sept edited commenrt above
