### ISSUE TITLE
Non-namespaced elements are allowed but this is unclear

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#8]
Clause 14.8.6.1 Namespaces for standard structure types and attributes

There is a gap in ISO 32000-2:2020 that allows undefined element types. Need to make it clearer in future editions that we still allow non-namespaced elements. But they need to be roll-mapped to a known type.

**Comment by lrosenthol** [comment]
I would actually disagree with that position.  I believe that any element name that is not in the SST *shall* be in a namespace.

**Comment by mrbhardy** [comment]
@lrosenthol for backwards compatibility with documents being upgraded from PDF 1.7, if an element is in the standard namespace (i.e. no namespace is defined), then it needs to be processed through the global RoleMap (just as it would in 1.7).  So in principle, you can still have an undefined namespace, but it has to meet the requirements of tagged PDF (i.e. be role mapped to something in the standard).  The preference is that all custom tags have a well-defined namespace so they can be used more broadly, but this isn't mandated any more than it was in 1.7.

**Comment by lrosenthol** [comment]
@mrbhardy You are correct about the current state of things - however, I am suggesting that in future "advanced tagging" work that we *require* the namespace.

**Comment by petervwyatt** [comment]
@mrbhardy Is your comment above worthy of an informative note? I think it is. Care to draft one (pretty please)?

**Comment by mrbhardy** [comment]
Proposal is to add a note in 14.8.6.1:

NOTE Namespaces are designed to provide greater interchange of PDFs including logical structure, providing a means to identify the custom namespace for each element, if appropriate.  However, structure elements types in undefined namespaces continue to be permitted.
