### ISSUE TITLE
Shading operator 'sh' is misspelled as 'Sh' in Table 50 - Operator categories, Shading patterns

### ISSUE THREAD

**Issue by bertvankerckhove** [pdf-association/pdf-issues#80]
In 8.2 Graphics objects, Table 50 - Operator categories, Shading patterns:

The shading operator is written as 'Sh', with capital S.  This should be all lower-case 'sh'.

(In 8.7.4.2 Shading operator, Table 76 - Shading operator, 'sh' is spelled correctly.)

**Comment by petervwyatt** [comment]
PDF TWG agrees
