### ISSUE TITLE
Are Page node Resources required even if Contents is not present?

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#81]
Table 31 Page objects defines the leaves of the page tree.
It states that **Resources** is a Required key.
It also states that **Contents** (array or stream) is optional with the explanation "If this entry is absent, the page shall be empty."

So is it intended than an empty page expressed by a non-existent **Contents** key is still required to have **Resources** which should most likely be just an empty dictionary (i.e. `/Resources << >>`) but of course could pointlessly have resources?

Just checking if Resources should really be "Required only when **Contents** key is present"?

**Comment by lrosenthol** [comment]
You might also want/need resources to render annotation appearances.
(granted, you should put them on the appearance stream directly, but that's
not required due to the inheritance model).

**Comment by petervwyatt** [comment]
So validating that Resources is ALWAYS present even if no Contents / Annots is what we really want?
It's what we say so I'm just checking.

Or "Required only when Contents or Annots key are present"?

**Comment by datalogics-pgallot** [comment]
There are edge-case scenarios where you would legitimately not need resources (e.g. pure path, inline images). but the Resources entry also states "Omitting the entry entirely indicates that the resources shall be inherited from an ancestor node in the page tree," so an empty dictionary prevents your PDF application from doing a search up the page tree looking for a Resources dictionary that likely does not exist.

**Comment by lrosenthol** [comment]
I do agree that we could remove the required *BUT* I think, as @datalogics-pgallot points out, we have to work through all the cases when it would be required...and that might make things more complex than just always having it.

**Comment by petervwyatt** [comment]
@datalogics-pgallot: it was one of your RichMedia files which made me look at this in more detail in the first case due to some issues with some PDF parsers not liking no Contents keys 🤣

But Page Resources is Required so inheritance will necessarily stop at each page (leaf node). That's what is said now.

So the descriptive text with explicit requirements is contradictory with the leading required/optional statement:
(_Required; inheritable_) ... Omitting the entry entirely indicates that ... shall be inherited ..., but PDF writers should not use this ...

How can it be both "Required" AND "omitted entirely"? 
Was the "omitted entirely" sentence targeted at how to handle (deprecated?) older wordings from previous specs?

**Comment by datalogics-pgallot** [comment]
@petervwyatt I figured, which is part of why I chimed in :)   Inheritable means it doesn't need to be in that exact page node's dictionary, it can be in a parent node's dictionary.

Although you don't often see this construct, I believe I have seen this scenario before where a file has a resource dictionary at the root of the page tree which are then inherited by all the leaf nodes of the page tree, which then don't need their own resource dictionary.

Doing this, you might get a very slight decrease in the size of the file compared to reusing a reference to the same resource dictionary for each page...at the expense of a slight-ish(?) increase in parsing or rendering time, presumably.

**Comment by MPBailey** [comment]
I'm reading that text to say "It's required somewhere in the pages tree, but doesn't have to be in the leaf node". So I'd agree that the text is slightly confusing, but I'm not seeing the underlying intention of that text as being a bad thing. On the other hand, if it were changed to be optional (as in not needing to be anywhere in the pages tree at all) I don't think we'd need to spell out all of the possible cases where omitting it would be a bad thing. Just say "Required if it would be referenced by page content, annotations or XObjects placed on the page".

**Comment by petervwyatt** [comment]
I am specifically _only_ talking about the situation where the **Contents** key is absent (which is allowed as a short-hand for a blank page) - not about inheritance per-se.

In this case, the current wording REQUIRES a **Resources** dict somewhere in the inheritance hierarchy. In the case of PDF with only blank pages, this Resources dict would therefore be an empty dict (since there are no **Contents** then there are no **Resources** actually required).

If this is the case then I think it is worth an explicit NOTE for the special case of no **Contents** since there are a lot of PDFs out there that fail this simple validation.  I suggest the following informative note (worded as a factual statement) is added to **Contents** key "Value" column in Table 31:

NOTE: if the **Contents** key is not present, a **Resources** dictionary is still required (including through inheritance) in the pages tree.

**Comment by MPBailey** [comment]
I think it would be clearer if "including through inheritance" were replaced with "either directly or through inheritance". Otherwise good.

**Comment by petervwyatt** [comment]
ISO prefer "... would be present" instead of required.
PDF TWG agree.
