### ISSUE TITLE
Strong Structure Element - Example 3

### ISSUE THREAD

**Issue by PaulRayius** [pdf-association/pdf-issues#84]
14.8.4.7.2 - Table 368 - regarding the **Strong** structure element. 

The Example reads, "In this example the **Strong** element is used to denote the content that the user is intended to read first:"  And then it goes on to have a list of 3 items (things to do).  The first item in the list uses the **Strong** structure element.  

Imagine, for example, that, visually, the "strong" text is in bold.  

First question:  Are we saying that the author's intent would be to read the bold text first because it's "marked Strong"?  Or is the author's intent that that item is read first because it's the first item in the list?  If, for example, the second item in the list was in bold text would we then be indicating that, even though the author wrote it as the second "thing" that their intent was that it's read first?  

Second question:  Would the expectation for assistive technology, then, be to read content in a **Strong** structure element first?  For example, again, if the second item in the list was placed in a Strong structure element, as opposed to the first, would the expectation of AT be that it reads the second item and then the first and then the third, and so on?  

Third question:  What if the list had more than one item in a **Strong** structure element.  What should the reading order be in that case (as far as AT is involved)?  Read all of the "strong" list items first and then the "other" items in the list?  What if it's an ordered list?  That could be very confusing for someone using AT who doesn't realize the text is bold and is left wondering why the list is being read in a seemingly illogical order. 

Finally, how should **Strong** be handled when it's used in other scenarios, outside a list? (Or even within a list if all of the text in the **LBody** isn't contained in the **Strong** structure element.)   If the intent is that it's "read first," this is too vague.  "First" in relation to what?  Seeing as **Strong** is an Inline structure element, is the expectation that the content of the **Strong** element is read first, before the other content in a **P** structure element, for example?

**Comment by DuffJohnson** [comment]
The Example's text is unfortunate in that it implies some preference for order of consumption, which isn't appropriate. Also, since it's only a NOTE it doesn't have normative value. We can address the confusion by revising the Example's text to read:

"In this example the **Strong** element is used to denote the most important content:"

**Comment by petervwyatt** [comment]
Strike "the most" in proposal. Change to "more".
PDF TWG agree
