### ISSUE TITLE
Values for DPM metadata disallow names for no good reason - and ISO 21812 specifies the use of names in DPM properties

### ISSUE THREAD

**Issue by DietrichSeggern** [pdf-association/pdf-issues#86]
PDF 2.0:2020 specifies in “14.12.4.2 Document part metadata“ last para:
“The values of keys present in the DPM dictionary, or of any dictionary or array object present in the DPM dictionary, shall only be of type text string, date string, array, dictionary, boolean, integer or real as defined in 7.3, "Objects". Other PDF value types shall not be used.”
 
In 7.3, “Objects” there is chapter on 7.3.5 "Name objects” but “names” is missing in the list of allowed value types.

Many properties in ISO 21812-1 Print Product Metadata, however, use “name” as their “data type”, e.g. CIP4_JobID. Also in the PDF/VT-2 examples (Annex C) values are frequently of type name.

There is no good reason for disallowing names objects in DPM structures.

Request:
Add "name" in “14.12.4.2 Document part metadata“ last para to:
“The values of keys present in the DPM dictionary, or of any dictionary or array object present in the DPM dictionary, shall only be of type text string, date string, name, array, dictionary, boolean, integer or real as defined in 7.3, "Objects". Other PDF value types shall not be used.”

**Comment by MPBailey** [comment]
I'm going to speculate that we left out name objects because they don't have a defined character encoding. There are some recommendations to use UTF-8 (after expansion of # escapes) for user-visible names, but no requirements. So if we were to add names to the list it would make sense to require that they are represented in UTF-8.

**Comment by petervwyatt** [comment]
PDF TWG agree in priniple: also need to require PDF names are UTF-8 in this case.
Wordsmith offline and approve at next TWG Meeting

**Comment by petervwyatt** [comment]
Proposed wording correction which requires names to be UTF-8 compatible (as 7.3.5 Name objects only says "... should be interpreted as UTF-8"). Note also that Annex J.3.4 also does not require UTF-8, just that the comparison happens after "escape expansion". Further, 7.3.5 never uses the term "escape sequences" for the NUMBER SIGN (23h) (#) 2-digit hex codes! "Escape sequences" are only a string thing!:

The values of keys present in the **DPM** dictionary, or of any dictionary or array object present in the **DPM** dictionary, shall only be of type text string, date string, name, array, dictionary, boolean, integer or real as defined in 7.3, "Objects". If the value is a PDF name object, then that name shall be a valid UTF-8 byte sequence after all NUMBER SIGN (23h) (#) 2-digit hexadecimal codes are replaced (see 7.3.5 "Name objects"). Other PDF value types shall not be used.

**Comment by DietrichSeggern** [comment]
Thanks, looks good to me.

**Comment by MPBailey** [comment]
Agreed, looks good.

Martin

**Comment by petervwyatt** [comment]
PDF/X-6 6.5.5 - check wording of #-escape language. Also PDF/A-4.
PDF TWG agree
