### ISSUE TITLE
Wrong Unicode character name

### ISSUE THREAD

**Issue by zauguin** [pdf-association/pdf-issues#87]
**Describe the bug**
ISO32000-2, section 9.10.3 example 2 contains

> [...] is mapped to the Unicode value UNICODE HAN CHARACTER ‘U+2003E’ (U+2003E), which [...]

but according to the Unicode Standard, section 24.2, subsection "CJK Unified Ideographs", "the name of a unified ideograph simply consists of its Unicode code point preceded by `CJK UNIFIED IDEOGRAPH-`." Therefore the name of "U+2003E" is `CJK UNIFIED IDEOGRAPH-2003E` and not `UNICODE HAN CHARACTER ‘U+2003E’`.

Recommendation for correction: Replace `UNICODE HAN CHARACTER ‘U+2003E’` with `CJK UNIFIED IDEOGRAPH-2003E`.

**Comment by petervwyatt** [comment]
You are indeed correct! As a random point of reference: https://www.compart.com/en/unicode/U+2003E
This is also the only instance of "UNICODE" (uppercase) so hopefully no others lurk elsewhere.
Thank you.

Proposed solution as per above.

**Comment by petervwyatt** [comment]
PDF TWG agree
