### ISSUE TITLE
Acknowledge lack of support for SubjectKeyIdentifier to identify the signer's certificate

### ISSUE THREAD

**Issue by MatthiasValvekens** [pdf-association/pdf-issues#88]
**Describe the bug**

This is a really nitpicky one. Clause 12.8.3.3.1 states that signature containers shall conform to CMS as specified in RFC 5652, but most implementations out there don't actually support everything in that RFC. In particular, the `sid` field to identify the signer certificate has the following type in [RFC 5652](https://datatracker.ietf.org/doc/html/rfc5652#section-5.3):

```
SignerIdentifier ::= CHOICE {
        issuerAndSerialNumber IssuerAndSerialNumber,
        subjectKeyIdentifier [0] SubjectKeyIdentifier }
```

In "old school" PKCS#7 (which is presumably what the `adbe.pkcs7.*` formats were originally based on), the type of `sid` was not a union type, but limited to `IssuerAndSerialNumber` only. ASN.1 enthusiasts will note that the tagging choice in the current definition is a relic of that older definition, which can still be found in [RFC 2315](https://datatracker.ietf.org/doc/html/rfc2315#section-9.2).

Anyway, long story short: I believe that the vast majority of implementations out there (especially those that have been around since before PKCS#7 was "reborn" as CMS) only support `IssuerAndSerialNumber`. Is my impression correct, and should we acknowledge that in the specification?

**Proposed solution**

If the answer to both of these questions is "yes", then I propose adding the following informative note at the end of the 3rd paragraph in clause 12.8.3.3.1 (after "This certificate shall be used..."):

> NOTE: For historical reasons and for backwards compatibility with PKCS#7, many implementations only support identifying the signer's certificate using an _IssuerAndSerialNumber_ identifier in a _SignerInfo_ value that is part of a CMS _SignedData_ object.

**Additional context**

There are situations where using `SubjectKeyIdentifier` is useful, mainly because there is no expectation of global uniqueness for those. In theory, a signer might possess more than one certificate issued to the same public key by different CAs, and they might want their signatures to be verifiable using any of those certificates (e.g. because the validators in this story have wildly different trust stores). In such a situation, using `SubjectKeyIdentifier` is the only option: this (theoretically) allows the validator to try multiple signer certificates until they find one they trust.

This example is admittedly a bit contrived, and only relevant in highly specialised private workflows anyway. Regardless, retroactively banning `SubjectKeyIdentifier` altogether seems wrong to me; hence why I went with a note as opposed to a change in the normative text.

**Comment by petervwyatt** [comment]
"Proposed solution" label added as @MatthiasValvekens OP makes a suggestion that no one has objected to. Yet 😁.
Will be discussed in upcoming PDF TWG meeting.

**Comment by lrosenthol** [comment]
This seems like something that would have gone into an "implementation limits" section...if we still had one.

Do we really want to put in a note about "current implementations"?   Seems like this would be better addressed in a tech note from the PDFa

**Comment by MatthiasValvekens** [comment]
That's a fair point; I'm not sure how much precedent there is for this type of note in other areas of the standard.

Perhaps it is better addressed in a more general tech note discussing how RFC 5652 is implemented in PDF in practice, but that feels like a much bigger task. If the PDF TWG prefers that route over adding a note in the standard, I can live with that --- in a way, this thread already serves as public documentation of the status quo. As I said, it's a bit of a nitpick anyway.

**Comment by petervwyatt** [comment]
PDF TWG will not add any note to ISO 32000 but instead pass across to DigSig TWG to consider an implementation note.
