### ISSUE TITLE
Whether page Contents array elements are each a stream in own right or only when combined

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#9]
There is a contradiction between the Contents entry in Table 31, which says that an array value for Contents in a page object is only a single content stream, built from multiple streams.

> "(Optional) A content stream (see 7.8.2, "Content streams") that shall describe the contents of this page. If this entry is absent, the page shall be empty. The value shall be either a single stream or an array of streams. If the value is an array, the effect shall be as if all of the streams in the array were concatenated with at least one white-space character added between the streams’ data, in order, to form a single stream. PDF writers can create image objects and other resources as they occur, even though they interrupt the content stream. The division between streams may occur only at the boundaries between lexical tokens (see 7.2, "Lexical conventions") but shall be unrelated to the page’s logical content or organisation. Applications that consume or produce PDF files need not preserve the existing structure of the **Contents** array. PDF writers shall not create a **Contents** array containing no elements."

And clause 7.8.3 Resource dictionaries, which says that each item in the array is a content stream in its own right:

> "For a content stream that is the value of a page’s **Contents** entry (or is an element of an array that is the value of that entry), ..."

Removing the text in parentheses in clause 7.8.3 would remove this contradiction.

**Comment by MPBailey** [comment]
There are multiple references to a "page's content stream" throughout the text. Removing the parenthetical text would clarify those greatly as well. 

As an example, that would mean that 8.11.3.2 para 1 would clearly say that BMC, the optional content itsent and EMC could appear in up to three separate elements in a Contents array.

**Comment by petervwyatt** [comment]
Proposed solution: removing the text in parentheses in clause 7.8.3
