### ISSUE TITLE
Randomly placed normative statement in 12.5.6.2

### ISSUE THREAD

**Issue by PaulRayius** [pdf-association/pdf-issues#90]
12.5.6.2 - Markup Annotations

Below "Note 1" it says, "When separating text into paragraphs, a CARRIAGE RETURN (0Dh) shall be used and not, for example, a LINE FEED character (0Ah)." 

This seems to me to be out of place.  Or I'm just not understanding Markup Annotations well enough to see how this normative statement is relevant here. 

Note 2, immediately below that, also does not seem to reinforce or explain the statement made above it.  

This might be more appropriately moved to somewhere in section 7.9 - Common Data Structures (?) or section 9 - Text (?).  I'm sure someone in the group knows better than I where it should go but it just seems random where it currently is.

**Comment by car222222** [comment]
I was also puzzled by this statement in this place.

Going further, why is it ever necessary in this standard to specify which Unicode characters should or shall be used at such a low-level to indicate the layout or semantics of some text?

**Comment by petervwyatt** [comment]
To me it looks like that wording is in direct relation to the **/Contents** key which is described just above as "... text that shall be displayed for the annotation or, if the annotation does not display text, an alternative description of the annotation’s contents in human-readable form. In either case, the **Contents** entry is useful when extracting the document’s contents in support of accessibility to users with disabilities or for other purposes".

**/Contents** is a text string (not a content stream) so having an exact 'semantic' definition of how a paragraph break is signified seems useful for on-screen formatting (as the PDF file format does not define how annots might appear in an interactive viewer, such as when side-by-side with PDF pages) - or even a slightly longer pause when being read aloud.

I would also imagine it might be useful for an editing comment (annot) where the commenter is suggesting the insertion of paras of text and thus an advanced processor which applies such comments would need to know this semantic...

**Comment by PaulRayius** [comment]
Thank you, Peter.  That explanation makes sense - this is about the text in the **Contents.** 

We could either mark this as closed, without any changes or possibly add some text so that it reads something like " When providing the **Contents** key, if separating text into paragraphs, a CARRIAGE RETURN (0Dh) shall be used and not, for example, a LINE FEED character (0Ah)."

**Comment by petervwyatt** [comment]
I like this suggestion - clearly indicates what has the "CR-only" requirement. We can see what the PDF TWG think next time.
Marking as proposed solution - and changing from bug to doco.

**Comment by petervwyatt** [comment]
PDF TWG agree
