### ISSUE TITLE
clarify in table 355 if R in a structure element dictionary is deprecated in pdf 2.0.

### ISSUE THREAD

**Issue by u-fischer** [pdf-association/pdf-issues#93]
`Table 355 — Entries in a structure element dictionary` lists  the `R` key and describes it like this:

> (Optional) The current revision number of this structure element (see
14.7.6.3, "Attribute revision numbers"). The value shall be a non-negative
integer. Default value: 0.

If one follows the link to `14.7.6.3 Attribute revision numbers` the section starts with 

> The features described in this subclause are deprecated with PDF 2.0.

If this mean that the key is deprecated and ignored in PDF 2.0 there should imho be a note in table 355.

**Comment by DuffJohnson** [comment]
Agreed; thanks for spotting!

Add a note to the definition of the R key in Table 355: 

NOTE  The use of attribute revision numbers is deprecated in PDF 2.0.

**Comment by lrosenthol** [comment]
@mrbhardy thoughts?

**Comment by petervwyatt** [comment]
PDF TWG agree R is deprecated - will append standard phrasing after "(Optional; deprecated in PDF 2.0)"
