### ISSUE TITLE
Projection annotation requirements conflict with Table 166

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#94]
Clause 12.5.6.24 Projection annotation, last line states:

> A projection annotation with a **Rect** entry that has zero height or zero width shall not have an **AP** dictionary.

yet Table 166 — Entries common to all annotation dictionaries, **AP** entry states:

> Every annotation (including those whose **Subtype** value is _Widget_, as used for form fields), except for the two cases listed below, shall have at least one appearance dictionary.
• Annotations where the value of the **Rect** key consists of an array where the value at index 1 is equal to the value at index 3 and the value at index 2 is equal to the value at index 4.
NOTE (2020) The bullet point above was changed from “or” to “and” in this document to match requirements in other published ISO PDF standards (such as PDF/A).
• Annotations whose **Subtype** value is _Popup_, _Projection_ or _Link_.

This conflicts in that:
* Table 166 states zero height **AND** zero width Rect, whereas 12.5.6.24 says zero height **OR** zero width Rect
* its unclear if Projection annotations (with valid Rect) are required to have "... at least one appearance dictionary" or if the 2nd bullet in Table 166 is a get-out-of-jail card and they are **not** required to have an AP just because they have a certain **Subtype** value

**Comment by petervwyatt** [comment]
Proposed solution for first issue: update clause 12.5.6.24 with "AND" requirement for zero width and zero height as this then is fully aligned with both Table 166 and PDF/A.

Unsure about 2nd issue - is there another reason (besides degenerate Rect) that Projection annots should not have AP appearance streams???

**Comment by petervwyatt** [comment]
See also #42

**Comment by lrosenthol** [comment]
Agree with proposed solution for issue 1.

The description for a projection annotation includes:
>However, a projection annotation is only valid within the context of an associated run-time environment, such as an activated 3D model.

So yes, a projection annotation can have an AP *but* that AP isn't the same as other AP's...

**Comment by petervwyatt** [comment]
Only PDF/A-4e allows 3D and Projection annots only make sense in 3D runtimes, and therefore there is no necessity that AP exists.
FIx - issue 1 as above.  Ensure that optional AP is clear.
