### ISSUE TITLE
Outdated RSA contact information for RC4 licensing

### ISSUE THREAD

**Issue by t-merz** [pdf-association/pdf-issues#95]
7.6.3.1 contains Note 1 with contact information regarding licensing RC4 implementations from RSA Security, Inc.. The provided URL http://www.rsasecurity.com/ redirects to https://www.rsa.com/, so this should probably be updated. I don't know whether it's appropriate to supply a street address here. "RSA has offices in 41 countries" according to their Web site, but the address listed in the Note is not one of RSA's published contact addresses.

Taking into account the availability of free RC4-compatible implementations and the fact that RC4 is deprecated in PDF 2.0 anyway it may make sense to completely drop Note 1.

**Comment by petervwyatt** [comment]
I agree removing the address, but a redirecting URL is not an issue. It's also the very same URL that was in all the Adobe PDF specs so keeping it consistent is good.

**Comment by petervwyatt** [comment]
PDF TWG accepted
