### ISSUE TITLE
Inappropriate reference to C++ type wchar_t

### ISSUE THREAD

**Issue by t-merz** [pdf-association/pdf-issues#96]
Note 5 in 7.9.2.2.1 tries to explain Unicode formats:

"It is important not to confuse UTF-16BE with UCS2 (i.e. wchar_t). UTF-16 is not a fixed width encoding scheme."

I find it a bit strange to reference a programming language (C++) without even mentioning its name for those who are not familiar with its keywords, but this is not my point here.

The problem is that the note is technically wrong since wchar_t in C++ doesn't have fixed size nor interpretation. A wchar on Windows has two bytes and holds UTF-16 code units, while on Linux and macOS it has 4 bytes and holds UTF-32. This defeats its use as a vehicle for explaining UTF-16 vs. UCS2.

Suggestion: delete Note 5 since ample information about Unicode formats is available elsewhere.

A minor issue in Examples 1 and 2 in the same section: these use weird "?" as substitute for some byte values with an explanation "where the character ‘?’ after the ‘text’ is represented by the hex code 8B". Why not use PDF hex string syntax instead? Since this section is not about syntax, but semantics this would improve readability a lot.

**Comment by MatthiasValvekens** [comment]
Coincidentally, I came across that note yesterday as well, and I agree that it's not appropriate. I would be happy just deleting the wchar_t parenthetical, though: I think the rest of the note can stay. Having said that, I also don't object to deleting it outright: people who know what UCS2 is are probably aware of the fact that it's not the same as UTF-16, especially these days.

**Comment by petervwyatt** [comment]
Proposed solutions:

Let's go with deleting the entire NOTE 5 as it is definitely showing its age.

Examples 1 and 2 can also be improved as suggest, but I'd make Example 1 use a single literal string octal escape value so it is still largely human understandable (and adjust the last part of the sentence appropriately). Example 2 can be a full hex string as suggested.

**Comment by petervwyatt** [comment]
PDF TWG accepted
